feat(ONYX-900): remove LotsByFollowedArtistsRail and add RecommendedAuctionLotsRail
artsy/eigen pull request #10120
Opened 2024-04-22 13:47 UTC by tam-kis

This PR resolves [] 

### Description

Removes LotsByFollowedArtistsRail from Auctions page and replaces it with RecommendedAuctionLotsRail.
Refactoring RecommendedAuctionLotsRail to Large and Small rails.

https://github.com/artsy/eigen/assets/17580625/95d95427-e198-4bc1-86b1-3a6c8feb8af3

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes
- replace  LotsByFollowedArtistsRail with RecommendedAuctionLotsRail

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2024-04-22 13:51 UTC, olerichter00 approved these changes
Looks good 🌟

2024-04-22 13:51 UTC, olerichter00 commented on src/app/Scenes/Home/Components/RecommendedAuctionLotsRail.tsx
> +      {size == "large" ? (
To avoid duplicating the props, you could do something like this:

```
const ArtworkRailComponent = size == "large" ? LargeArtworkRail : SmallArtworkRail

<ArtworkRailComponent
          {...trackingProps}
          artworks={artworks as any}
          onPress={handleOnArtworkPress}
          showSaveIcon
          onMorePress={() => {
            trackEvent(tracks.tappedMoreCard())
            navigate("/auctions/lots-for-you-ending-soon")
          }}
          onViewableItemsChanged={onViewableItemsChanged}
          viewabilityConfig={viewabilityConfig}
        />
          
```

2024-04-22 13:54 UTC, tam-kis commented on src/app/Scenes/Home/Components/RecommendedAuctionLotsRail.tsx
> +      {size == "large" ? (
Good idea, other solutions to avoid duplications were throwing a lot of errors, will try this one!

2024-04-22 15:14 UTC, olerichter00 requested changes
Looks good, but we should add a prop to the rail to adjust the tracking `context_screen_owner_type` depending on where the screen is displayed.

2024-04-23 13:52 UTC, MounirDhahri approved these changes
LGTM - just a small comment

2024-04-23 13:52 UTC, MounirDhahri commented on src/app/Scenes/Home/Components/RecommendedAuctionLotsRail.tsx
> +    const tracks = {
**nitpick:** we usually prefer to keep these at the end of the file

2024-04-23 13:52 UTC, MounirDhahri commented on src/app/Scenes/Sales/Sales.tsx
> -          {!!data.me && (
should we maybe bring this back to avoid unnecessary spacing if the rail is not there?

2024-04-23 13:54 UTC, olerichter00 reviewed
Thanks for the tracking update, I've added some suggestions:

2024-04-23 13:54 UTC, olerichter00 commented on src/app/Scenes/Home/Components/RecommendedAuctionLotsRail.tsx
> +      tappedHeader: () => ({
I would leave those out of the component and pass the `contextScreenOwnerType` as a parameter:

`tappedHeader: (contextScreenOwnerType) => ({`

2024-04-23 13:54 UTC, olerichter00 commented on src/app/Scenes/Home/Components/RecommendedAuctionLotsRail.tsx
> +      if (contextScreenOwnerType === OwnerType.home) {
Now the artwork press is only tracked on the home screen. Maybe we should track it in either case and only use the `HomeAnalytics.artworkThumbnailTapEvent()` when it's on the home screen.

2024-04-23 16:53 UTC, olerichter00 commented on src/app/Scenes/Sales/Sales.tsx
> -          {!!data.me && (
Hmm, isn't this only checking whether `me` is `null`? This should only happen if `me` fails to load. If the rail doesn't have any artworks to display, `viewer.artworksForYou` artwork connection would have 0 elements, right?

2024-04-24 09:48 UTC, olerichter00 approved these changes

2024-04-24 11:36 UTC, merged