build(ci): Android specific releases
artsy/eigen pull request #10135
Opened 2024-04-24 11:50 UTC by gkartalis

This PR resolves [] 

### Description

Bringing back the diff of https://github.com/artsy/eigen/pull/7913 

Allow releasing specific past versions on Android.

- On uploading a beta to the playstore we will also upload the signed aab to s3
- On promoting a beta to prod we will allow selection/download from s3 and then upload the selected build to the play store

We will need to test if it works as expected to be able to fetch latest 20 android builds from s3.

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- ci select 20 Android last releases - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2024-04-24 11:51 UTC, gkartalis commented on fastlane/Fastfile
> +desc 'Promote a play store android beta to production'
This is where the changes start, sorry for the verbose diff but added also some linting stuff that my vscode was really persistant in keeping.

2024-04-24 11:51 UTC, gkartalis commented on fastlane/Fastfile
> +  selected_build.scan(/\d+/).first
And this is where the changes end. As mentioned above the rest are just linting changes

2024-04-24 11:53 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (ci select 20 Android last releases - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dedf3863378873b886cb845d192eea46ed5d89d6
</p>

2024-04-24 13:27 UTC, brainbicycle requested changes
Thanks for doing, I don't mind most of the linting changes but don't love this pattern of not passing the var explicitly when it is named the same as the arg.


e.g.:
```
  upload_sentry_artifacts(
     sentry_release_name:,
     dist_version: bundle_version,
     platform: 'ios'
   )
```

vs.

```
 upload_sentry_artifacts(
     sentry_release_name: sentry_release_name,
     dist_version: bundle_version,
     platform: "ios"
   )
```

I don't know if it is valid ruby but it is less readable IMO
Can we revert those?

2024-04-24 14:02 UTC, gkartalis commented on fastlane/Fastfile
> +    beta_app_review_info:,
sounds good to me ;) will do change that back

2024-04-25 16:53 UTC, brainbicycle approved these changes
nice! thanks!

2024-04-25 16:53 UTC, merged