chore: use externalID inside submit artwork flow
artsy/eigen pull request #10636
Opened 2024-08-21 10:05 UTC by MounirDhahri

This PR resolves [] 

### Description

Sorry for the big PR, it wasn't possible to make this smaller.

This PR makes the required changes in order to use `externalId` instead of `internalID` for submissions. This required the following changes:
- A migration to save the `externalID` instead of the `submissionID`.
- Updating `createOrUpdateSubmission` to use the `externaldID` inside `input`
- Updating the routes

https://github.com/user-attachments/assets/3d2a2e3d-39d5-4a49-920d-940c87594045

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2024-08-21 10:08 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (use externalID inside submit artwork flow - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b11512a37bbf1047ff620bfb57ce4250b668c1d7
</p>

2024-08-21 10:41 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/mutations/createConsignSubmissionMutation.ts
> +    externalID: string
both fields are required - `internalID` because it's important for the photos and the `externalID` is for future mutations. I think later we can return the entire submission but I didn't feel that's required now

2024-08-21 10:43 UTC, MounirDhahri commented on src/app/store/migration.ts
> +  RenameSubmissionIDInSubmissionDraft: 46,
No need to add the `externalID` here since it will be automatically set by the user when they save a new submission

2024-08-21 10:47 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkSubmissionStatusDescription.tsx
> +  if (!consignmentSubmission || !consignmentSubmission.externalID) return null
```suggestion
  if (!consignmentSubmission?.externalID) return null
```

2024-08-21 10:47 UTC, olerichter00 commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +  const id = draft?.deprecatedSubmissionID ?? draft?.externalID
Why do we need `deprecatedSubmissionID`? Can't we just use `submissionID`? It should work with both, the internal ID and the external ID, right?

2024-08-21 10:47 UTC, olerichter00 commented on src/app/Scenes/SellWithArtsy/Components/Header.tsx
> +                const id = draft.deprecatedSubmissionID ?? draft.externalID
```suggestion
                const id = draft.deprecatedSubmissionID ?? draft.externalID
```

2024-08-21 11:26 UTC, dariakoko approved these changes

2024-08-21 11:26 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
> +  if (!consignmentSubmission || !consignmentSubmission.externalID) return null
Same as Ole noted above `if (!consignmentSubmission?.externalID) return null`

2024-08-21 14:02 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +  const id = draft?.deprecatedSubmissionID ?? draft?.externalID
Hmm, since both work then I probably don't need the separation 💯

2024-08-21 14:04 UTC, olerichter00 commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +  const id = draft?.deprecatedSubmissionID ?? draft?.externalID
It would be great, if we could remove it and simplify the draft model :)

2024-08-21 14:11 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +  const id = draft?.deprecatedSubmissionID ?? draft?.externalID
done - entirely removed now 💯

2024-08-21 14:43 UTC, olerichter00 requested changes

2024-08-21 14:43 UTC, olerichter00 commented on src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkNewScreenTemplate.tsx
> +        context_screen_owner_id: values.externalId || undefined,
I had a discussion with @daytavares about the tracking, and there was a request to use the internal ID instead of the external ID to be able to join database tables in Redshift (Force PR that updates the IDs: https://github.com/artsy/force/pull/14188).

2024-08-21 15:08 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkNewScreenTemplate.tsx
> +        context_screen_owner_id: values.externalId || undefined,
Nice- thanks for pointing this out. I am on it

2024-08-21 15:11 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkNewScreenTemplate.tsx
> +        context_screen_owner_id: values.externalId || undefined,
it looks like we do the tracking in a different way now, I will remove this tracking mention from the template

2024-08-22 07:57 UTC, olerichter00 commented on src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkNewScreenTemplate.tsx
> +        context_screen_owner_id: values.externalId || undefined,
Thanks, I'd suggest going through all Sell flow (and maybe submission status) related tracking events and make sure none of them use the external ID. That's what I did in Force, where I found a mix of both.

2024-08-30 10:31 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkNewScreenTemplate.tsx
> +        context_screen_owner_id: values.externalId || undefined,
that's currently done

2024-08-30 10:31 UTC, MounirDhahri commented
Merging this to test things out since the beta is already available

2024-08-30 10:31 UTC, merged

2024-08-30 10:50 UTC, dariakoko reviewed
Thanks!
Sorry, forgot to approve