fix: refactor CreditCardForm for auction registration
artsy/eigen pull request #10642
Opened 2024-08-21 16:41 UTC by MrSltun

This PR resolves [] 

### Description

This PR refactors the credit card form in the Auction registration to include the Billing Address, which is needed when creating a token with Stripe

- [ ] demo videos
- [ ] test iOS

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- refactor credit card form in auction registration - mrsltun

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2024-08-21 16:44 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (refactor credit card form in auction registration - mrsltun)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 531504628f5ef3b07820069fca2fc8f423c2b045
</p>

2024-08-21 16:51 UTC, damassi commented on src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
> +        throw new Error("Credit card token not present")
Not sure how helpful it is these days given eigen's overall tooling setup, but have found that including the originating file location for sentry is super nice. like `[ConfirmBid] Credit card token not present`

2024-08-21 16:53 UTC, damassi commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +import { action, computed, Computed, useLocalStore } from "easy-peasy"
nice @MrSltun 👌

2024-08-21 16:56 UTC, gkartalis reviewed
looking great with a first pass! Lemme know if you need any help testing / fixing tests

2024-08-21 16:56 UTC, gkartalis commented on src/app/Components/Bidding/Components/PaymentInfo.tsx
> -        />
👋

2024-08-21 16:56 UTC, gkartalis commented on src/app/Components/Bidding/Components/PaymentInfo.tsx
> -  }
👋

2024-08-21 16:56 UTC, gkartalis commented on src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
> +        throw new Error("Credit card token not present")
Do we actually need that error? If yes why? wandering if it would break the functionality in case there is no token.

2024-08-21 16:56 UTC, gkartalis commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +  console.log({ billingAddressfromform: billingAddress })
👁️

2024-08-21 16:56 UTC, gkartalis commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +      if (!token || token.error || !token.token.id) {
👀 wouldn't checkin for `token.error` work here? Why did we have to check for all the rest?

2024-08-21 16:56 UTC, damassi commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +  const countryRef = useRef<Select<any>>(null)
☝️ Formik

2024-08-21 16:57 UTC, damassi commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +            defaultValue={state.fields.fullName.value ?? ""}
Formik 😄

2024-08-21 17:01 UTC, damassi requested changes
I like the refactor away from state to using easy-peasy (we should lean on easy peasy more!) tho its essential that we always avoid recreating the wheel, especially in regards to anything involving forms. We've got Formik, which the whole team knows well, is batteries included, and more. So we should stick to that 🙏

2024-08-21 17:40 UTC, MrSltun commented on src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
> +        throw new Error("Credit card token not present")
I'm throwing the error here to show to the user that the registration/bidding was not complete hence it will be caught in a try/catch
And yes the flow would be broken since we need the token to register/bid in a auction :)

2024-08-22 06:55 UTC, araujobarret commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +        <Stack spacing={1}>
This `Stack` element shouldn't be used anymore, instead use:
```jsx
<Flex gap={space(1)}>
```

Can you do a favor and mark it there as deprecated, please? (I know it's a bit out of scope here but since you touched we should prevent more people of using it 😅 )

2024-08-22 06:55 UTC, araujobarret commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +  }),
on top of ☝️ , can we have an organization refactor altogether?
A lot of fields' declarations, initial states, and typing make the component verbose, if we can have at in a different file, that would be nice. Suggestion `./creditCardFormFields.ts`

2024-08-22 10:38 UTC, araujobarret approved these changes
Looks good now, thanks for the changes!
left minor comments but can be addressed later if you don't have time 👍

2024-08-22 10:38 UTC, araujobarret commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +  const buildBillingAddress = (values: CreditCardFormValues): Address => {
these 2 fns can be outside of the component(bottom part is better)

2024-08-22 10:38 UTC, araujobarret commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +        contentContainerStyle={{ padding: 20, paddingBottom: 50 }}
nit: `contentContainerStyle={{ padding: space(2), paddingBottom: 50 }}`

2024-08-22 10:38 UTC, araujobarret commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +              onCardChange={(cardDetails) => {
easier to read if we don't use the arrow function, can we lift this up to some `handleOnCardChange`, please?

2024-08-22 10:38 UTC, araujobarret commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +          loading={isSubmitting}
💟

2024-08-22 10:38 UTC, araujobarret commented on src/app/Components/Stack.tsx
> + * @deprecated Please use `<Flex gap={space(1)}>` instead
🙇

2024-08-22 12:32 UTC, MounirDhahri reviewed
Thanks for making this refactor!

2024-08-22 14:03 UTC, gkartalis approved these changes
THANK YOU FOR PUSHING THIS THROUGH 🚀

2024-08-22 14:04 UTC, MrSltun commented
@damassi I'll merge this one to create a new build and carry on with the release :)

2024-08-22 14:05 UTC, merged

2024-08-22 15:08 UTC, damassi commented on src/app/Components/Bidding/Screens/CreditCardForm.tsx
> +        <Stack spacing={1}>
@araujobarret - can't one just do `<Flex gap={1}>` and have it automatically pick up the spacing scale?