build(deps): bump react-native from 0.72.17 to 0.73.9 #WIP #DONOTMERGE
artsy/eigen pull request #10739
Opened 2024-09-10 13:59 UTC by gkartalis

This PR resolves [PHIRE-1181] 

### Description

Bumps react-native version from `0.72.17` to `0.73.9`

#### What changed:

- Debugging improvements
- Console Log history in Hermes
- Updated debugging [docs](https://reactnative.dev/docs/0.73/debugging)
- Experimental New Debugger
- Stable Symlink Support in Metro
- Better Android 14 support
- Java bump from 11 to 17
- Gradle Bump from 7.4.x to 8.1.x

You can read more info on [RN 73 official blogpost](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks)

#### Which Deps were bumped and why:

- `@braze/react-native-sdk`: `5.2.0` ~> `8.4.0`
- `@react-native-async-storage/async-storage`: `1.19.3` ~> `1.19.8`
- `@react-native-clipboard/clipboard`: `1.7.0` ~> `1.14.1`
- `react-native-code-push`: `8.1.0` ~> `8.3.1`
- `react-native-gesture-handler`: `2.13.1` ~> `2.19.0`
- `react-native-webview`: `13.6.2` ~> `13.6.3`

React Native 0.73 will depend on Android Gradle Plugin (AGP) 8.x. This will require all the libraries to specify a namespace in their build.gradle file. RN team added a compatibility layer for libraries that haven't specified a namespace, but please consider updating your libraries nonetheless.

Read more [here](https://github.com/react-native-community/discussions-and-proposals/issues/671)

#### Patches:

Enhanced react native patch with `.mock('../Libraries/Image/Image', () => mockComponent('../Libraries/Image/Image'))` due to [this issue](https://github.com/facebook/react-native/issues/41907#issuecomment-2293385777).

#### DevExperience Before / After:

Metro is way faster when bundling the app (around ~2x faster)

Android builds have an insane boost that is mostly due to java 17 and gradle updates:

On emulator with cleared cache / deleted app:

|Before|After|
|---|---|
|<img width="353" alt="androidBuildBefore" src="https://github.com/user-attachments/assets/b40a7391-05dd-45dd-b2b1-5ff6fee5c219">|<img width="671" alt="Screenshot 2024-09-13 at 12 43 39" src="https://github.com/user-attachments/assets/eb4f7e7f-cbfe-4f82-91b1-66a5d37f44b5">|

on emulator with cached build:

|Before|After|
|---|---|
|<img width="746" alt="Screenshot 2024-09-13 at 13 22 59" src="https://github.com/user-attachments/assets/a07c5185-4c89-4b5a-9b86-f1ef4130b9b9">|<img width="686" alt="Screenshot 2024-09-13 at 12 44 32" src="https://github.com/user-attachments/assets/74d38b21-de28-4d5e-bcca-aba7a108c0d1">|

#### Steps To Upgrade on your machine after this gets merged:

```sh
# Delete node modules and caches:
rm -rf node_modules && rm -rf .cache && rm -rf "$TMPDIR/metro*" && rm -rf "$TMPDIR/haste-map-*"

# install all the dependencies needed
yarn install:all

# you will most likely have to run also the following to bump hermes-engine:
cd ios && bundle exec pod update hermes-engine --no-repo-update & cd ..
```

Afterwards in order to bump JAVA:

For asdf users:

```sh
asdf install
```

For non-asdf users:

```sh
brew install --cask zulu@17

# Get path to where cask was installed to double-click installer
brew info --cask zulu@17
```

> [!IMPORTANT]  
> For all (asdf/ non asdf users). After you install the JDK, update your JAVA_HOME environment variable in your `.zshrc` file. Afterwards run `source ~/.zshrc` to make it effective and restart your terminal.
>If you used above steps, JDK will likely be at /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home.
> You can try out in the terminal by typing $JAVA_HOME to make sure that it was updated properly.

 
### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- bumps react-native to 0.73.9 - gkartalis

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-1181]: https://artsyproduct.atlassian.net/browse/PHIRE-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-10 14:07 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (bumps react-native to 0.73.9 - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 21b596ed069429947aa76b84d2d02a3e835a035c
</p>

2024-09-10 14:15 UTC, gkartalis commented on .tool-versions
> +java zulu-17.50.19
Java bump to 17

2024-09-10 14:15 UTC, gkartalis commented on android/app/src/main/java/net/artsy/app/MainActivity.kt
> +package net.artsy.app
we had to re-write this with Kotlin 🙈

2024-09-10 14:15 UTC, gkartalis commented on android/app/src/main/java/net/artsy/app/MainApplication.kt
> +
we had to re-write this with Kotlin 🙈

2024-09-10 14:15 UTC, gkartalis commented on metro.config.js
> +    },
Big GOTCHA, `images/` path stopped being recognised after the rn bump and we had to let metro config know where they are

2024-09-10 14:15 UTC, gkartalis commented on package.json
> +    "@react-native-clipboard/clipboard": "1.14.1",
Had to bump these in order for them to be rn 73 compliant

2024-09-10 14:15 UTC, gkartalis commented on package.json
> +    "react-native-code-push": "8.3.1",
Had to bump in order for them to be rn 73 compliant

2024-09-10 14:15 UTC, gkartalis commented on package.json
> +    "react-native-webview": "13.6.3",
Had to bump in order for them to be rn 73 compliant

2024-09-10 14:15 UTC, gkartalis commented on package.json
> +    "react-native-gesture-handler": "2.19.0",
Had to bump in order for them to be rn 73 compliant

2024-09-12 17:05 UTC, brainbicycle requested changes
This looks great! 
Two small ones:
- the braze push handling in MainActivity is commented out, I think it is still necessary? 🤔 
- I think the react native patch may have gotten some generated code carried along

2024-09-12 17:11 UTC, brainbicycle commented on scripts/ci/build-for-tests-ios
> +xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug -sdk iphonesimulator build -destination platform="$DEVICE_HOST_PLAT",OS="$DEVICE_HOST_OS",name="$DEVICE_HOST_NAME" -derivedDa
here

2024-09-13 08:47 UTC, gkartalis commented on HACKS.md
> +in order to also make targetCompatibility and sourceCompatibility compatible with the JAVA 17 which is the standard for newer rn versions starting 0.73.
💯

2024-09-13 10:11 UTC, gkartalis commented on src/app/Components/PopoverMessage/PopoverMessageProvider.tsx
> -  const timer = useRef<number | null>(null)
it is weird indeed 🤷

2024-09-13 10:12 UTC, gkartalis commented on android/app/src/main/java/net/artsy/app/MainApplication.kt
> +            // Braze.getInstance(applicationContext).setRegisteredPushToken(token)
I was getting an error here when trying to build ~ I think that in the end we will need to bump braze to be compliant 🫨 .

Seems like they moved this function to JS side ~ will trigger betas after I address that to test if it works

2024-09-13 10:25 UTC, gkartalis commented on HACKS.md
> +in order to also make targetCompatibility and sourceCompatibility compatible with the JAVA 17 which is the standard for newer rn versions starting 0.73.
we will probably need to test out both android & iOS thoroughly, had to bump to 8.4.0 in the end - will remove the hack entry

2024-09-13 15:16 UTC, gkartalis commented
Bumped braze to 8.4.0 in the end ~ moved the registration of the token to the JS side since I was getting build errors from a depracated method from `setRegisteredPushToken` tried some others and no luck thus I moved the token to the JS side.

Let me know if you have any concerns ~ but I Was thinking to open a separate PR for braze 🤷‍♂️

2024-09-13 16:23 UTC, gkartalis commented
FreshBetas:

`android-8.51.0-1674645836`
`ios - 8.51.0 - 2024.9.13.15`

2024-09-13 16:49 UTC, gkartalis commented
Braze works! Received notifications in both android / ios betas above

2024-09-16 08:52 UTC, MrSltun submitted a review, later dismissed
Thank you for pushing through this!! 💪 ⚡ 📈

2024-09-16 14:19 UTC, brainbicycle commented on src/app/utils/PushNotification.ts
> +        registerPushToken(token.token)
nice

2024-09-16 14:19 UTC, brainbicycle approved these changes

2024-09-19 15:56 UTC, merged