feat(DIA-896): add an auth model method to identify email addresses
artsy/eigen pull request #10861
Opened 2024-09-27 18:54 UTC by iskounen

This PR resolves [DIA-896] by adding a new `verifyUser` method to the `AuthModel` that can be used to check whether an email address belongs to an existing user or not.

It is a companion to artsy/gravity#18193

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Dev changes

- Added more device information to user agent - iskounen

</details>

2024-09-27 18:56 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (Added more device information to user agent - iskounen)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5b61929035a1a112af147273b3b21a967cf5aa82
</p>

2024-09-30 14:23 UTC, brainbicycle requested changes
minor change request to wrap the gravity call in try catch

2024-09-30 14:23 UTC, brainbicycle commented on src/app/Components/ArtsyWebView.tests.tsx
> -        }`
👍

2024-09-30 14:23 UTC, brainbicycle commented on src/app/store/AuthModel.ts
> +    const result = await actions.gravityUnauthenticatedRequest({
i don't think we are doing this correctly elsewhere but I believe this should be wrapped in a try-catch and return your "something_went_wrong" error in case of a throw

2024-09-30 16:50 UTC, brainbicycle approved these changes
looking good!

2024-10-01 08:39 UTC, araujobarret approved these changes

2024-10-01 16:27 UTC, merged