feat(DIA-882): add explore by categories to the home view
artsy/eigen pull request #10914
Opened 2024-10-09 08:27 UTC by araujobarret

This PR resolves [DIA-882] 

### Description

Add the Explore By Categories to the home view

iPhone

https://github.com/user-attachments/assets/428264a2-4b79-4edd-82e3-106bd8b98430

iPad

https://github.com/user-attachments/assets/568609bd-24f4-4289-af2e-d8eab964c37b

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- feat: add explore by section in the homeview - araujobarret

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2024-10-09 08:29 UTC, araujobarret commented on src/app/routes.ts
> +    addRoute("/collections", "Collections"),
@anandaroop any thoughts on this route? I made it in a more REST way so we can navigate with `/collections?category=Medium"`

2024-10-09 08:29 UTC, araujobarret commented on src/app/Scenes/Collections/Collections.tsx
> +export const Collections: FC = () => {
This is just a temporary placeholder, will be worked properly in upcoming tickets

2024-10-09 08:30 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (feat: add explore by section in the homeview - araujobarret)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 933f6501f1e8f00ea724c0b649afd5828bf419ff
</p>

2024-10-09 11:31 UTC, dblandin reviewed
Looking good! Left a few comments.

2024-10-09 11:31 UTC, dblandin commented on src/app/Scenes/HomeView/Sections/HomeViewSectionExploreBy.tsx
> +    const isEnabled = useFeatureFlag("AREnableMarketingCollectionsCategories")
**question**: This is something we should align on best practices for as the __section instance__ definition [already specifies a feature flag](https://github.com/artsy/metaphysics/blob/fc6a57aa2d25cb157b68e5620665714a80324b18/src/schema/v2/homeView/sections/ExploreByCategory.ts#L42) and inclusion can be controlled via the Unleash dashboard across different environments.

Seems potentially confusing to coordinate between and understand the differences across these two different feature flags although it does seem useful to continue to have a way within Eigen to signal that section type support is ready to release to end users.

2024-10-09 11:31 UTC, dblandin commented on src/app/routes.ts
> +    addRoute("/collections", "Collections"),
We already have a [/collections](https://artsy.net/collections) route on web and as this route is doing something a bit different and doesn't yet have any web equivalent or deep-linking expectations, maybe something a bit more explicit would make sense?

```ts
addRoute("/collections-by-category/:category", "CollectionsByCategory")
// or
addRoute("/explore-by-category/:category", "ExploreByCategory")
```

2024-10-09 11:31 UTC, dblandin commented on src/app/Scenes/HomeView/Sections/HomeViewSectionExploreBy.tests.tsx
> +          section(id: "home-view-section-explore-by-category") @required(action: NONE) {
**question**: I don't have much familiarity with this `@required` directive but based on the [documentation](https://relay.dev/docs/guides/required-directive/#none-expected), it states that by using `action: NONE` we expect this field to be null sometimes.

The root level `homeView` field is currently [non-nullable](https://github.com/artsy/metaphysics/blob/afb5f5512a520b1021165e482028b1c7155d1600/src/schema/v2/homeView/index.ts#L82).

This isn't the case now but it looks like we should be able tighten up the types for [homeView/section and homeView/sectionsConnection](https://github.com/artsy/metaphysics/blob/afb5f5512a520b1021165e482028b1c7155d1600/src/schema/v2/homeView/index.ts#L76-L77) to also be non-nullable.

When we can't find a section by ID, we currently throw an error rather than responding with a null section value.

2024-10-09 11:52 UTC, araujobarret commented on src/app/Scenes/HomeView/Sections/HomeViewSectionExploreBy.tests.tsx
> +          section(id: "home-view-section-explore-by-category") @required(action: NONE) {
That's just the mocked query on the test, in this scenario will never be null 👍 
(I did not use this directive in the normal file, just here in the test)

2024-10-09 11:54 UTC, dblandin commented on src/app/Scenes/HomeView/Sections/HomeViewSectionExploreBy.tests.tsx
> +          section(id: "home-view-section-explore-by-category") @required(action: NONE) {
Ahh, gotcha 👍🏼

2024-10-09 11:59 UTC, araujobarret commented on src/app/Scenes/HomeView/Sections/HomeViewSectionExploreBy.tsx
> +    const isEnabled = useFeatureFlag("AREnableMarketingCollectionsCategories")
That's indeed confusing, but there's a conflict because unleash doesn't control the app versions.

The architecture of the home view with ongoing work we might start enabling new elements when you don't even have the entire flow ready, example: in version 8.53.0 it had no collection by category screen whereas in version 8.54.0 that was delivered, so we enable the ff and will have the flow broken on the 8.53.0 and ok in the 8.54.0. 
There's no way to avoid the feature flag combo here to only deliver when all the feature work is done.
More discussions [here](https://artsy.slack.com/archives/C05EEBNEF71/p1727445772237339?thread_ts=1727336233.733129&cid=C05EEBNEF71)

2024-10-09 12:01 UTC, araujobarret commented on src/app/routes.ts
> +    addRoute("/collections", "Collections"),
Then yeah, it makes sense to have something more specific in this case. I think I'll go with `/collections-by-category/:category` because it was something that we previously talked with @anandaroop too, thanks!

2024-10-09 12:33 UTC, dblandin commented on src/app/Scenes/HomeView/Sections/HomeViewSectionExploreBy.tsx
> +    const isEnabled = useFeatureFlag("AREnableMarketingCollectionsCategories")
Yeah, I totally understand the need. Made we can add some guidance re: feature flags in our [home view docs page in MP](https://github.com/artsy/metaphysics/blob/main/docs/adding_a_new_home_view_section.md).

2024-10-09 12:40 UTC, araujobarret commented on src/app/Scenes/HomeView/Sections/HomeViewSectionExploreBy.tsx
> +    const isEnabled = useFeatureFlag("AREnableMarketingCollectionsCategories")
I think it'll be better, if it's a feature that renders something in a new shape but redirects to older screens/has behaviors supported by past versions we can rely solely on MP ff, however when it adds more stuff on Eigen we cannot avoid, maybe this distinction will be also necessary

2024-10-09 13:32 UTC, damassi commented on src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
> +  console.log(params)
🦑

2024-10-09 17:41 UTC, anandaroop requested changes
Looking great, just one suggestion to keep naming conventions consistent with the patterns we've established.

2024-10-09 17:41 UTC, anandaroop commented on src/app/Scenes/HomeView/Sections/Section.tsx
> +      return <HomeViewSectionExploreByQueryRenderer sectionID={section.internalID} {...rest} />
**suggestion:** We should make the component name here match the section type:

```suggestion
    case "HomeViewSectionCards":
      return < HomeViewSectionCards QueryRenderer sectionID={section.internalID} {...rest} />
```

That reinforces the expectation that `HomeViewSectionCards` has a default presentation style, the one you are adding here. 

(And then some future section may declare it is also a `HomeViewSectionCards` but has a different presentation, as discussed in [the thread](https://artsy.slack.com/archives/C05EEBNEF71/p1728404106250269?thread_ts=1728401640.597839&cid=C05EEBNEF71) — but the _default_ style should be clearer here from the component naming)

2024-10-10 13:58 UTC, araujobarret commented
I've addressed all the requested changes, need just a 👍 in order to merge it.

2024-10-10 14:39 UTC, anandaroop commented on src/app/Scenes/HomeView/Sections/Section.tsx
> +      return <HomeViewSectionExploreByQueryRenderer sectionID={section.internalID} {...rest} />
Thank you! I noticed a very similar issue [over here](https://github.com/artsy/eigen/pull/10927/files#diff-980cb0bae6931064b4372248200cf0c852e8b8d0565ac6393ce60a6e8bfd55ccR46-R52), but I will comment on that separately

2024-10-10 14:39 UTC, anandaroop submitted a review, later dismissed

2024-10-11 06:42 UTC, araujobarret commented on src/app/Scenes/HomeView/Sections/Section.tsx
> +      return <HomeViewSectionExploreByQueryRenderer sectionID={section.internalID} {...rest} />
I have to touch again on the discovery by implementing missing features and gonna pack this change there, didn't want to ship here bc it was out of the scope of this PR 👍

2024-10-11 07:24 UTC, merged