fix: avoid prefetching when following deeplinks
artsy/eigen pull request #11097
Opened 2024-11-14 22:42 UTC by anandaroop

This PR resolves [ONYX-1392] 

Co-authored-by: @brainbicycle 

### Description

The goal here is to avoid prefetching when following a deep link, in order to avoid an unnecessary [stampede](https://artsy.slack.com/archives/CA8SANW3W/p1731532192977049?thread_ts=1731531969.773739&cid=CA8SANW3W) that results in API latency.

We observe that prefetching happens in a few ways:

1. A home view prefetch is initiated from the splash screen — but can be avoided by checking If we are following a deep link
2. Content for other tabs is initiated from the home view — but can be similarly avoided
3. A heavier prefetch for a subset of home view sections’ content — still TBD how to avoid these in the case of a deep link

This WIP so far addresses 1 and 2.

But I suspect 2 and especially 3 are the ones that will make the most difference.

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2024-11-15 10:19 UTC, MounirDhahri approved these changes
Nice! thanks for the fix

2024-11-15 17:03 UTC, MounirDhahri commented
| Scenario | Vide |
|--------|--------|
| Opened App w/o deep link | <Video src="https://github.com/user-attachments/assets/1875e3f7-afe4-46df-9205-7b749449f7ac" /> |
| Opened App from deep link | <Video src="https://github.com/user-attachments/assets/2ccbe4be-a25c-4951-aa94-dbb538453909" /> |

2024-11-15 18:00 UTC, brainbicycle commented on src/app/Scenes/Home/HomeContainer.tsx
> +  if (isDeepLink !== false) {
I wonder if we need a check if the deeplinks destination is the homeview? Otherwise this might lead to home view not rendering in this case?

2024-11-18 08:52 UTC, olerichter00 commented on src/app/utils/hooks/useIsDeepLink.tests.ts
> +// Start of the new test case
👀

2024-11-18 08:52 UTC, olerichter00 commented on src/app/utils/hooks/useIsDeepLink.tests.ts
> +// Existing mocks
👀

2024-11-18 08:52 UTC, olerichter00 commented on src/app/Scenes/Home/HomeContainer.tsx
> +  if (isDeepLink !== false) {
`useIsDeepLink` could be renamed to `useDeepLinkURL` and return the URL of the deep link or `null` to make this check possible.

2024-11-18 09:25 UTC, MounirDhahri commented on src/app/Scenes/Home/HomeContainer.tsx
> +  if (isDeepLink !== false) {
good thought! that makes sense

2024-11-18 11:03 UTC, olerichter00 commented on src/app/Scenes/Home/HomeContainer.tsx
> +  if (isDeepLink !== false) {
Instead of `null`, the hook could return `undefined` when waiting for the async call to get the deep link URL (`undefined`: declared but has not yet been assigned a value). This way, we can use `null` when there is no deep link URL (`null`: as a representation of no value) and a string to represent the URL when it exists.

2024-11-19 18:05 UTC, anandaroop commented on src/app/Scenes/Home/HomeContainer.tsx
> +  if (isDeepLink !== false) {
Mobbed on this in Onyx KS today and settled on https://github.com/artsy/eigen/pull/11097/commits/d151919e6ce130302e90f466c329c134d7219421

2024-11-19 18:54 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (Avoids prefetching home view content when opening a deep link - anandaroop)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d151919e6ce130302e90f466c329c134d7219421
</p>

2024-11-19 21:01 UTC, brainbicycle commented on src/app/utils/hooks/useIsDeepLink.ts
> +        const isDeepLink = targetURL !== "/"
I think this is on the right track but the check is a little too naive still, because we handle universal links the link will not always start with `artsy://`. For example if you tap a link on your mobile device from any of our associated domains: 
```
 https://www.artsy.net
- https://artsy.net
- https://click.artsy.net
- https://m.artsy.net
- https://link.artsy.net
- https://email-link.artsy.net
```
This will open the app, the initial url will be `https://artsy.net` and will still resolve to the home view and then not render. 

One approach might be to reuse the matchRoute function in routes.ts we use for handling deeplinks and see what the route resolves to rather than trying to figure it out here.

2024-11-19 21:03 UTC, brainbicycle requested changes
i think we need a little more nuance in our home deeplink detection, happy to pair tomorrow if it would be helpful!

2024-11-19 22:32 UTC, anandaroop commented on src/app/utils/hooks/useIsDeepLink.ts
> +        const isDeepLink = targetURL !== "/"
Great feedback. When we discussed today, there was some concern about coupling this to a specific module e.g. `HomeView`, but sounds like maybe that _is_ actually what's necessary here. 

Yes, happy to pair!

2024-11-20 23:34 UTC, anandaroop commented
Brian and I paired on switching the detection back to `matchRoute` in https://github.com/artsy/eigen/pull/11097/commits/4bf5896a78a27a51f85964ae7503cecbb9fcd720 since it will be more reliable in the edge cases noted above. (h/t @MounirDhahri for suggesting that originally)

I confirmed that the screengrabs above still work the same after these changes, and we also ran through the various cases in this gist, which may also come in handy at Mobile QA time:
- https://gist.github.com/anandaroop/8903e16ced8f962ff1fea60e13266584

2024-11-21 01:27 UTC, brainbicycle submitted a review, later dismissed
thank you!

2024-11-21 11:23 UTC, olerichter00 commented on src/app/utils/hooks/useIsDeepLink.ts
> + * @returns {isDeepLink: boolean | null} isDeepLink is true if the user came from a deep link
I'd add something like this to the description to make sure the hook is used correctly. (`null` vs `false` value).

```suggestion
 * @returns {isDeepLink: boolean | null}` isDeepLink` is true if the user came from a deep link. Initially, it is set to `null` while retrieving the deep link URL asynchronously and will be set to `false` if retrieving the `URL` fails.
```

2024-11-21 11:23 UTC, olerichter00 commented on src/app/utils/hooks/useIsDeepLink.ts
> +  const [isDeepLink, setIsDeepLink] = useState<boolean | null>(null)
**very minor:** Shouldn't the initial value be `undefined` instead of `null` because it's not yet defined ([null vs undefined](https://dev.to/sduduzog/null-vs-undefined-what-to-choose-what-to-use-11g))?

2024-11-21 11:23 UTC, olerichter00 commented on src/app/utils/hooks/useIsDeepLink.ts
> +        setIsDeepLink(false)
**also very minor:** Setting the value to `false` when retrieving the URL fails does not seem 100% correct. However, setting it to another value (`undefined` or `null`) or adding an error state will probably make this hook very complicated. 🤷

2024-11-21 11:23 UTC, olerichter00 commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
Couldn't we use the new hook `useIsDeepLink` here as well?

2024-11-21 15:21 UTC, anandaroop commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
I had the same thought and tried this out briefly, but got some errors that suggested this wouldn't work. Do you want to give it a try @olerichter00?

2024-11-21 16:45 UTC, MounirDhahri commented on src/app/utils/hooks/useIsDeepLink.ts
> +        }
```suggestion
        setIsDeepLink(shouldTreatAsDeepLink)
```

2024-11-21 19:21 UTC, olerichter00 commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
It looks like `useIsFocused` (which is used by `useIsDeepLink`) is causing the error because it cannot be used outside of a `NavigationContainer`.

But I wonder whether we need the deep link check here at all. Even when following a deep link, prefetching the home view query would make sense because it's likely that the user will navigate to the home screen within the same session. Removing the check could have performance implications, but I don't think they are significant (which we should check :)).

![simulator_screenshot_525B6452-2BB9-4C58-8F34-47B09C50ACD0](https://github.com/user-attachments/assets/016ce4b0-5c22-4442-a2ba-1188404439e1)

2024-11-21 19:34 UTC, brainbicycle commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
the motivation here is that eigen is very chatty when first launched and this has led to incidents in the past: https://artsy.slack.com/archives/CA8SANW3W/p1731531969773739

It does occur to me though that the concern is more around push notifications and in app messages specifically as these will result in large groups of users launching the app in a small time frame and causing spikes on our servers

2024-11-21 19:36 UTC, brainbicycle commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
we could possibly distinguish that case specifically 🤔

2024-11-21 22:56 UTC, anandaroop commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
+1 to that case being our exact motivation here.

How might we distinguish the push/in-app case vs others such as email?

2024-11-22 14:46 UTC, brainbicycle commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
we have 2 different ways of handling pushes right now for iOS and Android 🙃 but I think the basic idea would be similar to what you have done here, try to find push handling early enough in the lifecycle, set a flag `isNonHomePush` or hopefully a better name, if that flag is true don't do the prefetching, if it is false do it.

2024-11-22 14:48 UTC, brainbicycle commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
first place I would look is `handleReceivedNotification` in PushNotification.ts, check if that is early enough in lifecycle and works across platforms, if so good to go if not might need to dig in more.

2024-11-22 14:48 UTC, brainbicycle commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
in app messages I would need to look at, there should be some braze callbacks we can get hopefully in js land.

2024-11-22 15:41 UTC, anandaroop commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
I'll timebox an attempt at this^ (happy to pair also) — but if that doesn't pan out quickly how would we feel about merging this as-is, and then following up with this further refinement? 

If I'm understanding correctly, the only risk right now is a non-optimized home screen load for people who following an email deeplink, then navigate back to home. 

If that's right I think we stand to gain more than we lose with this current version, since we are still open to this stampede problem, even as we speak.

2024-11-22 15:46 UTC, brainbicycle commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
I am fine with that personally, I think the more risky thing is the check in the HomeContainer, if we get that wrong we get dead home screens. I will create a ticket to follow up so if you want to timebox fine but fine also to leave it for the time being.

2024-11-25 09:04 UTC, olerichter00 commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
+1 merging this PR as is 👍

2024-11-25 19:00 UTC, anandaroop commented on src/app/utils/useHideSplashScreen.ts
> +        Linking.getInitialURL().then((url) => {
Ok, let's go with that. (My timebox didn't really yield anything).

One more rebase and I'll merge this.

2024-11-25 22:59 UTC, merged