[MX-523] Feat: add auction info
artsy/eigen pull request #3923
Opened 2020-09-25 14:11 UTC by MounirDhahri

The type of this PR is: **Feature**

This PR resolves [MX-523]

### Description
Add auction info page

![Screen_Recording_2020-09-25_at_16 06 59](https://user-images.githubusercontent.com/11945712/94277009-41cef880-ff49-11ea-8c4a-3cbb97c344e6.gif)

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))

2020-09-29 10:51 UTC, pvinis commented on Artsy/App/ARSwitchBoard.m
> +#import "ARSwitchBoard.h"
I think that file here might have been accidentally committed? 😬

2020-09-29 10:53 UTC, pvinis commented on src/lib/Scenes/Sale/Components/SaleHeader.tsx
> +              SwitchBoard.presentNavigationViewController(navRef.current!, `auction/${props.sale.internalID}/info`)
Do you mind changing this to use the new `navigate` without the ref? 🙏

2020-09-29 10:55 UTC, pvinis commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> +  contextType: string
I wonder if we should make this like `contextType: "sale" | "sale information"`, to make it easier to reason with the tracking code 🤔. What do you think?

2020-09-29 10:55 UTC, pvinis commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> -    // TODO: `context_type` should be something like
YES!! Thanks for doing this 🙌

2020-09-29 10:58 UTC, pvinis commented on src/lib/utils/__tests__/saleTime-tests.ts
> +describe("#saleTime.absoluteConcatenated", () => {
Seems `absolute` got renamed to `absoluteConcatenated`. Could you please add some tests for the old `absolute` so we can see the difference of the two, and make sure we don't break it in the future?

2020-09-29 11:01 UTC, pvinis commented on src/lib/utils/saleTime.ts
> +    absoluteConcatenated: `${absoluteSaleTime.headline} ${absoluteSaleTime.date}`,
Could you write like a sentence or two about what this change means? 😬 Like what is `absolute` now and what is `absoluteConcatenated` and why we needed this? Very high-level. I just wanna get why this was needed.

2020-09-29 11:01 UTC, pvinis requested changes
I left some comments. A couple of them are questions and a couple are for changes. Nice stuff!

2020-09-29 13:49 UTC, MounirDhahri commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> +  contextType: string
I agree with that

2020-09-30 09:01 UTC, admbtlr commented
Maybe remove the Jira reference from the PR title? 😬

2020-09-30 13:35 UTC, MounirDhahri commented on src/lib/utils/saleTime.ts
> +    absoluteConcatenated: `${absoluteSaleTime.headline} ${absoluteSaleTime.date}`,
yes sure, I added a description to the absolute and the absoluteConcatenated is trivial I guess

2020-09-30 13:35 UTC, MounirDhahri commented on src/lib/utils/__tests__/saleTime-tests.ts
> +describe("#saleTime.absoluteConcatenated", () => {
Done

2020-10-01 09:21 UTC, pvinis commented on src/lib/utils/__tests__/saleTime-tests.ts
> +      headline: "Live bidding begins",
aaaa gotcha. cool.

2020-10-01 09:22 UTC, pvinis commented
Thanks for adding the comments for `absolute` etc!

2020-10-01 09:57 UTC, pvinis approved these changes
Cool! I left a couple of comments again but non-blocking, so I'll assign this to you and merge whenever you want.

One is about the buyer's premium, one about the faq button, and I have one last one about the text that we can just ask @samchieng. I guess the text "Live bidding begins" is not a strict text, or is it? In this PR the text is "Live bidding opens on".

2020-10-01 09:57 UTC, pvinis commented on src/lib/Scenes/SaleInfo/SaleInfo.tsx
> +          console.log("navigate to auctions FAQ")
Maybe we could navigate to `/auction-faq`? I see that the info in there is kinda the same?

Otherwise we just make sure to connect it when we make the FAQ screen in tsx as well.

2020-10-01 09:57 UTC, pvinis commented on src/lib/Scenes/SaleInfo/SaleInfo.tsx
> +
Shouldn't there be a section for "Buyer's premium" here? I see this on the design, but I don't see it here.

2020-10-01 09:58 UTC, pvinis commented
Ah forgot to say that I added a subject line in the email form from the button, just because I saw it on the swift old file :)

2020-10-01 17:32 UTC, samchieng commented on src/lib/Scenes/SaleInfo/SaleInfo.tsx
> +          console.log("navigate to auctions FAQ")
oh yeah, we can keep the current PR copy: "Live bidding opens on"!

2020-10-23 10:05 UTC, MounirDhahri commented
@pvinis I finished adding the link to the auctions faq and also added some padding to it since it was getting covered (only available when the `react-native-webview` flag is set to true). About the Buyer’s premium section, since Sam commented on the designs to add it only if possible (and I didn't know how to add it), I did not add it and created a jira ticket for it (https://artsyproduct.atlassian.net/browse/CX-745).

2020-10-26 14:25 UTC, merged