fix(auctions): Closed auctions fixes
artsy/eigen pull request #4041
Opened 2020-10-21 11:08 UTC by pvinis

The type of this PR is: **Bugfix**

This PR resolves [CX-725]

### Description

This includes two fixes:
- when a closed auction is accessed, it doesn't try to go live anymore.
- when a closed auction is accessed, the register button is not displayed.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2020-10-21 12:54 UTC, MounirDhahri commented on src/lib/Scenes/Sale/Sale.tsx
> +      sale.liveStartAt !== null && now.isAfter(sale.liveStartAt) && sale.endAt !== null && now.isBefore(sale.endAt)
I think we should also make this check if the sale `endAt` is null and we're after the `liveStartAt`

2020-10-21 12:54 UTC, MounirDhahri commented on src/lib/utils/usePrevious.ts
> +  }, [value])
Since we have value in the dependencies array I guess it's no longer the previous value right? it will be updated once the isLive value is updated and the screen is mounted

2020-10-21 12:54 UTC, MounirDhahri commented on src/lib/utils/usePrevious.ts
> +  }, [value])
**thought:** I guess you are trying to get the new `isLive` value before the screen is mounted, if that's the case I think you should move the reference and the the `useEffect`to the sale screen

2020-10-21 12:56 UTC, MounirDhahri commented
Thanks for fixing these fast 🙏, I left few minor **non-blocking** comments. But I think we should also add a test for `when a closed auction is accessed, it doesn't try to go live anymore.` to avoid this regression in the future

2020-10-21 12:56 UTC, MounirDhahri commented
Thanks for fixing these fast 🙏 good job. I left few minor non-blocking comments. But I think we should also add a test for _when a closed auction is accessed, it doesn't try to go live anymore._ to avoid this regression in the future

2020-10-21 13:12 UTC, pvinis commented on src/lib/Scenes/Sale/Sale.tsx
> +      sale.liveStartAt !== null && now.isAfter(sale.liveStartAt) && sale.endAt !== null && now.isBefore(sale.endAt)
🤔 makes sense.

2020-10-21 13:13 UTC, pvinis commented
Yup, I'll add that too.

2020-10-21 13:56 UTC, brainbicycle commented on src/lib/Scenes/Sale/__tests__/Sale-tests.tsx
> +    expect(tree.findAllByType(RegisterToBidButton)).toHaveLength(0)
🎉

2020-10-21 14:00 UTC, brainbicycle commented on src/lib/Scenes/Sale/Sale.tsx
> +  }, 500)
nice new useInterval is cleaner ✨

2020-10-21 14:01 UTC, brainbicycle approved these changes

2020-10-21 18:40 UTC, pvinis commented on src/lib/utils/usePrevious.ts
> +  }, [value])
Mm I'm not sure what you mean. I used https://usehooks.com/usePrevious/ and modified it to have an initial value. The return is happening before the useEffect, so the usePrevious hook always gives us the previous value. What I use it for is to know when `isLive` is `true` and `prevIsLive` is `false`. That's the only case where we should navigate to the live screen. In any other case we do nothing.

2020-10-21 18:45 UTC, pvinis commented
This should be ready. I'll add @admbtlr as a reviewer because I changed stuff in the `saleTime`. I tried to make types strict, and ended up with a couple of edge cases that were missing. I talked with Sam for how to handle these, changed the tests to reflect that, and then changed the code to make them all pass.

2020-10-22 09:28 UTC, admbtlr requested changes

2020-10-22 09:28 UTC, admbtlr commented on src/lib/Scenes/Sale/Sale.tsx
> +import _ from "lodash"
Shouldn't this rather be 
```
import compact from 'lodash/compact'
```
in order to avoid importing the whole caboodle?

2020-10-22 09:28 UTC, admbtlr commented on src/lib/Scenes/Sale/Sale.tsx
> +    if (sale.liveStartAt === null) {
If it's null, then we don't need to do the `useInterval` in the first place, do we? Unless we're expecting that value to change from null at some point?

2020-10-22 09:28 UTC, admbtlr commented on src/lib/Scenes/Sale/helpers/__tests__/auctionTime-tests.ts
> +const timezones = {
Nice work on these tests!

2020-10-22 09:28 UTC, admbtlr commented on src/lib/Scenes/Sale/helpers/saleTime.ts
> +  // if we have both start and end and we in the middle
```suggestion
  // if we have both start and end and we're in between them
```

2020-10-22 09:28 UTC, admbtlr commented on src/lib/utils/usePrevious.ts
> +import { useEffect, useRef } from "react"
Do we need this util? This is a known pattern, and hiding it in a 6 line library function is kinda obfuscating

2020-10-22 09:42 UTC, pvinis commented on src/lib/Scenes/Sale/Sale.tsx
> +import _ from "lodash"
Nothing really changes in RN. We are not web (thankfully, in this case 😅). In most files we import like that, and since there is no change in perf or whatever, why not keep it consistent and simple. 👍

2020-10-22 09:43 UTC, pvinis commented on src/lib/Scenes/Sale/helpers/saleTime.ts
> +  // if we have both start and end and we in the middle
🇬🇧

2020-10-22 09:45 UTC, pvinis commented on src/lib/utils/usePrevious.ts
> +import { useEffect, useRef } from "react"
🤔 I'm not sure I understand 😬. What do you mean?

The `usePrevious` is kind of a nice and helpful hook. Apparently we are not using it anywhere in eigen already, so I thought I'll add this here.

2020-10-22 09:51 UTC, pvinis commented on src/lib/Scenes/Sale/Sale.tsx
> +    if (sale.liveStartAt === null) {
Indeed. That was one of my thoughts against using useInterval. But then again when I saw the useEffect with an if and an interval and cleanup return func inside that if, I felt confused and a bit uncertain of how that works, and worse, if/how that could break.
So I decided to flip that and run the interval outside the if, and have the if check inside.

This means the interval now will run even if it's not a live auction and the code is simpler. I felt I'm ok with that tradeoff.

2020-10-22 09:52 UTC, pvinis commented on src/lib/Scenes/Sale/Sale.tsx
> +    if (sale.liveStartAt === null) {
```suggestion
    if (sale.liveStartAt === null) {
      const now = moment()
```
I'll quickly do this. This feels slightly nicer.

2020-10-22 09:54 UTC, pvinis commented on src/lib/Scenes/Sale/Sale.tsx
>      }
```suggestion
    if (sale.liveStartAt === null) {
      setIsLive(false)
      return
    }
    const now = moment()
```
I'll do this. This feels slightly nicer.

2020-10-22 10:02 UTC, MounirDhahri commented on src/lib/utils/usePrevious.ts
> +  }, [value])
Sorry, I must have misunderstood the effect then 😬

2020-10-22 10:30 UTC, admbtlr commented on src/lib/utils/usePrevious.ts
> +import { useEffect, useRef } from "react"
Actually, you're right, creating a named hook to do this is a nice approach 👍 . (I was just thinking that it was unnecessary to create a separate hook in order to abstract away 6 lines of code)

2020-10-22 10:37 UTC, pvinis commented on src/lib/utils/usePrevious.ts
> +import { useEffect, useRef } from "react"
Aaah gotcha. Thanks for explaining. Yes, I think it's nice to have, and convenient to have it as a reusable hook.

2020-10-22 11:05 UTC, MounirDhahri commented
Thanks for adding the tests and the quick fixes 🌷

2020-10-22 11:05 UTC, MounirDhahri approved these changes

2020-10-22 12:20 UTC, admbtlr approved these changes

2020-10-22 13:05 UTC, merged