fix: register to bid button tracking
artsy/eigen pull request #4123
Opened 2020-11-09 19:26 UTC by MounirDhahri

The type of this PR is: **Bugfix**

This PR resolves [CX-804]

### Description
Use cohesion for register to bid button tracking

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [X] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2020-11-09 20:47 UTC, pepopowitz requested changes
Thank you!!! I added a couple suggestions but only one of them is blocking, marked accordingly.

2020-11-09 20:47 UTC, pepopowitz commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> +      contextModule: contextType === "sale" ? ContextModule.auctionHome : ContextModule.auctionsInfo,
[blocking] 2 suggestions in this line: (1) compare to the enum value instead of the string to avoid hardcoded strings, and (2) per @mikehrom we should use `ContextModule.aboutThisAuction` for the "about this auction" screen.

```suggestion
      contextModule: contextType === OwnerType.sale ? ContextModule.auctionHome : ContextModule.aboutThisAuction,
```

2020-11-09 20:47 UTC, pepopowitz commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> +      contextModule: contextType === "sale" ? ContextModule.auctionHome : ContextModule.auctionsInfo,
[non-blocking] I also prefer to pass in an additional argument for the `contextModule` than to make a decision here based on `contextType`, but that's only a preference. If the caller is already making a decision about what to pass for `contextType`, it seems reasonable to me that it can also make a decision about what to pass for `contextModule`.

2020-11-09 20:47 UTC, pepopowitz commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> +import { ContextModule, ScreenOwnerType, tappedRegisterToBid, TappedRegisterToBidArgs } from "@artsy/cohesion"
```suggestion
import { ContextModule, OwnerType, ScreenOwnerType, tappedRegisterToBid, TappedRegisterToBidArgs } from "@artsy/cohesion"
```

This suggestion goes along with my suggestion below.

2020-11-10 10:51 UTC, MounirDhahri commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> +      contextModule: contextType === "sale" ? ContextModule.auctionHome : ContextModule.auctionsInfo,
you're absolutely true 🙏

2020-11-10 10:54 UTC, MounirDhahri commented on src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
> +      contextModule: contextType === "sale" ? ContextModule.auctionHome : ContextModule.auctionsInfo,
Submitting PRs after 8pm is never a good idea 🙈

2020-11-10 14:55 UTC, merged