feat: add artist about shows rail
artsy/eigen pull request #4174
Opened 2020-11-25 11:50 UTC by MounirDhahri

The type of this PR is: **Feature**

This PR resolves [CX-743]

### Description
- Move shows entry point to about tab

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2020-11-30 16:32 UTC, pvinis commented on src/lib/Scenes/Artist/Artist.tsx
> +      initial: false, // TODO: revert
whats up with this one? Should it be reverted in this PR?

2020-12-07 13:36 UTC, MounirDhahri commented on src/lib/Scenes/Artist/Artist.tsx
> +      initial: false, // TODO: revert
oh yes sure

2020-12-09 11:38 UTC, pvinis requested changes
A couple of cleanup things, then good to go!

2020-12-09 11:38 UTC, pvinis commented on CHANGELOG.yml
> +    - Move shows entry point to about tab - mounir
```suggestion
    - Move shows entry point to about tab - mounir
```
I think only this is needed?

2020-12-09 12:02 UTC, MounirDhahri commented on src/setupJest.ts
> +// mockedModule("./lib/Components/Artist/ArtistAbout/ArtistAbout.tsx", "ArtistAboutContainer")
I implemented the test so i will delete it 🙌

2020-12-09 12:35 UTC, merged