chore: Add p1 haptics for selection actions
artsy/eigen pull request #4294
Opened 2020-12-23 18:05 UTC by annacarey

The type of this PR is: **chore**

This PR resolves [CX-550]

### Description

Added haptic props to `<Touchable>` and `Button` components in various parts of app according to [this doc](https://www.notion.so/artsy/Haptic-Opportunities-26eb8dfed6c94d9da80929496f8b32d1). (This PR covers only the priority P1 elements.) This follows the @pvinis' work in setup in the PR [here](https://github.com/artsy/eigen/pull/3835/files#diff-837e4859f1c1fabdbcc7aef271fc3b07cefe768572b18ed80aed10cd407dfa92R125).

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-01-05 22:02 UTC, pvinis requested changes
Very nice!

I added one tiny suggestion, and as an extra thing, since we replace TouchableWithoutFeedback with our Touchable, I have a [commit here](https://github.com/artsy/eigen/pull/4137/commits/ec84bf6b1d8960ded7c846f996ce60dca48489cc) that you could cherry-pick, that would make the change in the tests not needed (keeping them with Touchable is fine too though), and most importantly it would keep the no feedback feel in on the buttons which would be nice.

2021-01-07 09:27 UTC, pvinis commented on src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
> +      <Touchable onPress={() => this.handleFollowArtist()} haptic="selection">
I think this and the other file that got TouchableWithoutFeedback replaced need `noFeedback`, and this PR is good to go!

2021-01-07 15:01 UTC, annacarey commented on src/lib/Components/AnimatedBottomButton.tsx
> +      <Touchable haptic="selection" activeOpacity={0.8} onPress={onPress} style={buttonStyles}>
@pvinis thanks for taking a look! I made this small change and pulled in your changes to `Touchable.ts` so then kept the tests as is (to check for `TouchableWithoutFeedback`.) Is there anything I need to do regarding your other PR now that some of the changes are in here?

2021-01-07 15:18 UTC, pvinis commented on src/lib/Components/AnimatedBottomButton.tsx
> +      <Touchable haptic="selection" activeOpacity={0.8} onPress={onPress} style={buttonStyles}>
no no, nothing to do. I'll rebase it later.

only add the noFeedback prop in the two components in this PR here that changed to Touchable and good to go 👍

2021-01-07 17:48 UTC, annacarey commented on src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
> +      <Touchable onPress={() => this.handleFollowArtist()} haptic="selection">
I thought this button and the one in `ArtistSeriesMeta` are now supposed to have the selection feedback according to [our doc](https://www.notion.so/artsy/Haptic-Opportunities-26eb8dfed6c94d9da80929496f8b32d1). But maybe I'm misunderstanding?

2021-01-07 18:06 UTC, pvinis commented on src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
> +      <Touchable onPress={() => this.handleFollowArtist()} haptic="selection">
ah. the noFeedback from the commit you cherry picker is no *visual* feedback. Touchable by default has highlight, but here we don't want it.

2021-01-08 13:14 UTC, annacarey commented on src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
> +      <Touchable onPress={() => this.handleFollowArtist()} haptic="selection">
Got it! Updated those components with `noFeedback` and this passed in CI so should be good to go! Thanks @pvinis!

2021-01-08 13:28 UTC, pvinis approved these changes
noice! can't wait to feel the haptics on the next nightly.

2021-01-08 13:29 UTC, merged