Add lab flag in eigen to enable inquiry checkout
artsy/eigen pull request #4317
Opened 2021-01-11 18:36 UTC by lilyfromseattle

[PURCHASE-2332]

Pretty straightforward - just adding a lab flag so work can begin on inquiry checkout

2021-01-11 18:45 UTC, zephraph approved these changes
Looks good, thanks @lilyfromseattle!

2021-01-11 18:45 UTC, erikdstock approved these changes

2021-01-11 23:44 UTC, zephraph commented on Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
>          @"AROptionsNewFirstInquiry": @(NO)
```suggestion
        @"AROptionsNewFirstInquiry": @(NO),
```

2021-01-11 23:45 UTC, zephraph commented on Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
>        @"AROptionsNewFirstInquiry": @(NO)
```suggestion
      @"AROptionsNewFirstInquiry": @(NO),
```

2021-01-11 23:45 UTC, zephraph requested changes
Missed some commas that caused the build to fail

2021-01-13 17:49 UTC, lilyfromseattle commented on Artsy/App/AROptions.m
> +         AROptionsInquiryCheckout: @"AROptionsInquiryCheckout",
```suggestion
         AROptionsInquiryCheckout: @"Enable inquiry checkout",
```

2021-01-14 13:46 UTC, zephraph approved these changes

2021-01-14 13:46 UTC, merged