feat: migrate LoadFailureView to typescript
artsy/eigen pull request #4452
Opened 2021-02-17 09:59 UTC by MounirDhahri

The type of this PR is: **Feature**

This PR resolves [CX-1055]

### Description
- Migrate LoadFailureView to typescript
- Remove old native `LoadFailureView`

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-02-17 12:06 UTC, pvinis commented on Artsy.xcodeproj/project.pbxproj
> -				"${PODS_ROOT}/Extraction/Extraction/Assets/ARLoadFailureRetryIcon@2x.png",
Even though I love removing these, I see now that this comes back once we run `bundle e pod install`. This is normal, since these come from https://github.com/artsy/extraction. I see that we need this pod for other things like the onboarding for now. I wouldn't bother making a change there and making a new pod version etc, since this pod dependency will go away soon with the android rework.

I would suggest we revert the changes in this file (or just run `bundle e pod install`), so that they don't unexpectedly come back in the next PR that needs to pod install. I guess one extra image in the bundle is not too bad for now, until we ditch the pod altogether.

2021-02-17 12:08 UTC, pvinis commented on Gemfile.lock
> +  ruby
Not sure where this came from. I don't think it's a problem, but I also don't see it added when I run stuff like `bundle install` 🤔.

2021-02-17 12:17 UTC, pvinis requested changes
Just a change for the xcodeproj file that I think is important, otherwise this seems to work well 👍.

2021-02-17 13:22 UTC, MounirDhahri commented on Gemfile.lock
> +  ruby
yes, this came using bundle install

2021-02-17 13:27 UTC, MounirDhahri commented on Gemfile.lock
> +  ruby
pardon -- I meant bundle exec pod install

2021-02-17 13:27 UTC, MounirDhahri commented on Artsy.xcodeproj/project.pbxproj
> -				"${PODS_ROOT}/Extraction/Extraction/Assets/ARLoadFailureRetryIcon@2x.png",
thanks for noticing this. I will update it now

2021-02-17 13:29 UTC, pvinis commented on Gemfile.lock
> +  ruby
🤷 All good then. Thanks.

2021-02-17 13:30 UTC, pvinis approved these changes

2021-02-17 13:46 UTC, MounirDhahri commented on Gemfile.lock
> +  ruby
you're welcome

2021-02-17 13:57 UTC, MounirDhahri commented
Please hold on merging this until we release

2021-02-18 11:35 UTC, MounirDhahri commented
@pvinis  since we submitted the app for release already, I will merge this now

2021-02-18 11:36 UTC, merged