cleanup(old echo): removed some methods and code that were not used
artsy/eigen pull request #4785
Opened 2021-05-17 12:21 UTC by pvinis

The type of this PR is: **Cleanup**

This PR resolves [CX-]

### Description

In order to remove aerodramus completely, I started by removing some code that was not used anywhere in the app. It was an easy quick step. The rest is now used in a few places. Once the old admin menu is migrated, we could probably do another step of cleanup.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-05-17 12:21 UTC, pvinis commented on Artsy/App/ArtsyEcho.h
> -- (NSDictionary *)featuresMap;
not used anywhere

2021-05-17 12:21 UTC, pvinis commented on Artsy/App/ArtsyEcho.h
> -- (NSArray *)legacyFairProfileSlugs;
not used anywhere

2021-05-17 12:22 UTC, pvinis commented on src/lib/store/config/EchoModel.tsx
> -  }),
I will follow up with an echo PR to mark these as deprecated, and we can remove them in the future.

2021-05-17 12:24 UTC, pvinis commented on Artsy/App/ARScreenPresenterModule.m
> -    if ([[[ARAppDelegate sharedInstance] echo] isFeatureEnabled:@"DisableNativeAuctions"] == YES) {
this is the only usage of `isFeatureEnabled`. The string `DisableNativeAuctions` was not found anywhere else in the codebase or echo, and `isFeatureEnabled` is defaulting to `NO`, so I went ahead and removed the if part and kept the else part, since I guess that's the flow the app uses right now.

2021-05-18 12:37 UTC, brainbicycle requested changes
I am a little bit paranoid about removing the "DisableNativeAuctions" flag, so would be in favor of keeping and removing the rest.

2021-05-18 12:37 UTC, brainbicycle commented on Artsy/App/ARScreenPresenterModule.m
> -    if ([[[ARAppDelegate sharedInstance] echo] isFeatureEnabled:@"DisableNativeAuctions"] == YES) {
I believe the reason this was kept so long is that Eigen's native auctions feature needs to stay in lockstep with causality's version because it uses web sockets. This way if we have a breaking change we can always fall back to the webview. I am not 100% on how versioning in causality works so I could be wrong but think we probably want to do some investigation before we remove this and might want to keep for now that there are changes on horizon for bidding engine.

2021-05-18 13:19 UTC, pvinis commented
Makes sense. Ok I will only remove the smaller chunk and keep that auctions part. I didn't see the string anywhere so I thought we don't even have a way to change it. Well, I guess we could add it in echo, but I thought if we didn't have it already there, then probably it's fine to remove.

2021-05-18 13:53 UTC, pvinis commented
This shoudl be fine now I think.

2021-05-18 16:11 UTC, brainbicycle approved these changes

2021-05-18 16:11 UTC, merged