Alexj105/feat order history
artsy/eigen pull request #4803
Opened 2021-05-19 13:50 UTC by alexj105

1.Please, don't merge this branch. It's a common branch for Order History screen. If I understand our flow correctly we will merge it when this screen will be done. We will merge into this branch others branches with order details and etc.
2. Please,  check my tests especially the mocking data request. If I'm wrong, please give me a hint about it!

The type of this PR is Feature

This PR resolves PX-4062

https://user-images.githubusercontent.com/37010996/118822921-3d34c700-b8c1-11eb-8274-a3e45ad9f985.mov
### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-05-20 13:32 UTC, brainbicycle requested changes
Code looks great, excited to get order history in the app! I think we will need to add a feature flag for this to hide it until it is ready to ship, there are docs here but let me know if anything is unclear!
https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md

2021-05-20 13:39 UTC, alexj105 commented
> Code looks great, excited to get order history in the app! I think we will need to add a feature flag for this to hide it until it is ready to ship, there are docs here but let me know if anything is unclear!
> https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md

https://artsyproduct.atlassian.net/browse/PX-4061
It's already done and merged. See https://github.com/artsy/eigen/pull/4795

2021-05-20 16:26 UTC, brainbicycle commented
> > Code looks great, excited to get order history in the app! I think we will need to add a feature flag for this to hide it until it is ready to ship, there are docs here but let me know if anything is unclear!
> > https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md
> 
> https://artsyproduct.atlassian.net/browse/PX-4061
> It's already done and merged. See #4795

Great! but it doesn't like this code is behind the flag unless I am missing it somewhere? For example I would expect the MenuItem in the profile to be only present if the feature is turned on.

2021-05-20 19:07 UTC, sweir27 commented on src/lib/Scenes/MyProfile/MyProfile.tsx
> +      <MenuItem title="Order History" onPress={() => navigate("/orders")} />
@alexj105 this is where we need to make sure we're checking the value on the feature flag.

It'll be something like this--
```
const showOrderHistory = useFeatureFlag("AREnableOrderHistoryOption")
....
{ showOrderHistory && <MenuItem title="Order History" onPress={() => navigate("/orders")} /> }
```

(cc @brainbicycle in case I messed up!)

2021-05-21 07:45 UTC, alexj105 commented on src/lib/Scenes/MyProfile/MyProfile.tsx
> +      <MenuItem title="Order History" onPress={() => navigate("/orders")} />
Good point! It's clear now!

2021-05-21 13:27 UTC, brainbicycle approved these changes
Thanks for adding the feature flag, nice work!

2021-05-21 13:37 UTC, brainbicycle commented on src/lib/store/config/features.ts
> +    echoFlagKey: "AREnableOrderHistoryOption",
You can leave out the echoFlagKey until this is ready for release and the tests should pass! Echo is our config server so if we have the key set here it is expected to be in echo as well!
```suggestion
```

2021-05-21 14:35 UTC, kiryl-zubarau approved these changes

2021-05-21 20:22 UTC, brainbicycle commented
> Thanks for adding the feature flag, nice work! One last request, could you add an entry to CHANGELOG.yml for this?

Went ahead and added an entry here: https://github.com/artsy/eigen/pull/4803/commits/19458c98951f2de8b9cdcf78f18c1aae516e865e

2021-05-24 06:44 UTC, merged