WIP feat: implement UI AuctionResults section with mock data for home screen
artsy/eigen pull request #4808
Opened 2021-05-19 16:14 UTC by JenqaaaBY

The type of this PR is: feature

This PR resolves [CX-922]

### Description

At the moment, I have implemented the auctionResults section with mock data to the home screen
![Screen Shot 2021-05-19 at 7 12 07 PM](https://user-images.githubusercontent.com/30176348/118847174-20ef5500-b8d6-11eb-9650-b0726ccc70eb.png)

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-06-01 09:02 UTC, pvinis requested changes
Nice! I had a couple of questions, which the answer might be "we fix it after the mocks are removed", but I was curious.

Also a small typo and its usages. After that, let's merge 👍.

2021-06-02 13:13 UTC, JenqaaaBY commented on src/lib/Scenes/Home/Home.tsx
> +  const auctionResultsModule = {} // !!! FIX TYPE
I added this in order to preserve the current data composition structure for the render. It will be necessary to add real data here. The comment is no longer relevant

2021-06-02 13:16 UTC, JenqaaaBY commented on src/lib/Scenes/AuctionResultForYou/AuctionResultForYouListItem.tsx
> +  auctionResult: any // add correct type after implementing actionResult query
At the moment, any is here. Since I dont know what datatype it will be. I added a comment so we don't forget to put the correct type here

2021-06-02 13:18 UTC, JenqaaaBY commented on src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
> +export const ActionResultsRailFragmentContainer = createFragmentContainer(AuctionResultsRail, {
Yes, you are right, this is a typo
Thank you

2021-06-02 14:16 UTC, JenqaaaBY commented on src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
> +        <SectionTitle title="Auction Results for You" />
Yes you are right
Thank you for your comment

2021-06-02 14:22 UTC, pvinis approved these changes
Awesome, good stuff! Thanks!

2021-06-02 15:48 UTC, merged