[WIP]feature(CX-1552): facebook auth
artsy/eigen pull request #4923
Opened 2021-06-03 12:51 UTC by edez1t

The type of this PR is: **Feature**

This PR resolves [CX-1552]

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-06-03 15:31 UTC, edez1t commented on android/app/src/main/res/values/strings.xml
> +    <string name="fb_login_protocol_scheme">fb414450748567864</string>
need to do smth with staging/production values (currently staging)

2021-06-10 08:15 UTC, olerichter00 commented on src/lib/store/AuthModel.ts
> +      Alert.alert("Error", "Allow the use of email to continue", [{ text: "Ok" }])
```suggestion
      Alert.alert("Error", "Please allow the use of email to continue", [{ text: "Ok" }])
```

Do we have a guide for this kind of copy?

2021-06-10 08:45 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +      Alert.alert("Error", "Allow the use of email to continue", [{ text: "Ok" }])
no i guess

2021-06-11 11:33 UTC, edez1t commented on src/lib/store/__tests__/AuthModel-tests.ts
> +        ) as any
jest doesn't seem to work second time it gravityUnauthenticatedRequest called

2021-06-14 12:40 UTC, olerichter00 commented on src/lib/store/AuthModel.ts
> +    if (accessToken) {
(non-blocking) Maybe we can use the early return pattern here to make the code more readable.

```
if (!accessToken) {
  return ....
}
```

2021-06-14 12:52 UTC, olerichter00 reviewed
Looking good so far! 

I tested it on iOS and I could log in with Facebook for the first time but I got the error "Couldn't link Facebook account." when I tried to log in again after logging out.

2021-06-14 12:52 UTC, olerichter00 commented on src/lib/store/AuthModel.ts
> +                  "User already exists with this email. Please log in with your email and password",
```suggestion
                  "User already exists with this email. Please log in with your email and password.",
```

2021-06-14 12:52 UTC, olerichter00 commented on src/lib/store/AuthModel.ts
> +                Alert.alert("Error", "Couldn't link Facebook account", [{ text: "Ok" }])
```suggestion
                Alert.alert("Error", "Couldn't link Facebook account.", [{ text: "Ok" }])
```

2021-06-14 13:31 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +    if (accessToken) {
done

2021-06-14 13:37 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +                  "User already exists with this email. Please log in with your email and password",
done

2021-06-14 13:37 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +                Alert.alert("Error", "Couldn't link Facebook account", [{ text: "Ok" }])
done

2021-06-14 16:02 UTC, MounirDhahri requested changes

2021-06-14 16:02 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +            case "Another Account Already Linked":
**issue:** I think it's really nice that you covered this case and you are trying to get the user to Login if they already have an account but I think we should not do that since it's not what we are showing them (sign up and not sign in). This can also potentially break if gravity error message changes

2021-06-14 16:02 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +            case "Another Account Already Linked":
I think what we can do though, is returning the error message as it is if it's human readable

2021-06-14 16:02 UTC, MounirDhahri commented on src/lib/store/GlobalStoreModel.ts
> +    LoginManager.logOut()
**praise:** 👏

2021-06-14 16:06 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +            case "Another Account Already Linked":
this is just how it works on ios

2021-06-14 16:08 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +            case "Another Account Already Linked":
![Screenshot 2021-06-14 at 19 07 51](https://user-images.githubusercontent.com/73339470/121923680-d7aeeb80-cd43-11eb-93f0-a3761d7196c4.png)

2021-06-14 16:08 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +        Alert.alert("Error", "Error fetching data.", [{ text: "Ok" }])
also tried to do it like on ios

2021-06-15 12:46 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +            case "Another Account Already Linked":
done

2021-06-15 12:46 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +        Alert.alert("Error", "Error fetching data.", [{ text: "Ok" }])
done

2021-06-15 12:46 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +      Alert.alert("Error", "Please allow the use of email to continue.", [{ text: "Ok" }])
done

2021-06-16 08:52 UTC, MounirDhahri requested changes

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +        resolve("Please allow the use of email to continue.")
**issue(blocker):** I guess this should be `reject("Please allow the use of email to continue.")`

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +          resolve("Error fetching data.")
same here, probably it would be also worth returning the error as well

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +              resolve(signUpError)
same here

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +                resolve(signInError)
here as well, let's also add some text to make sure we can easily track this back on sentry if something goes wrong

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +              resolve(xAccessTokenError)
I think this as well need to be reject(`failed to get gravity token from gravity`, xAccessTokenError)

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +              const { error_description: xAccessTokenError } = await resultGravityAccessToken.json() // error_description look better than error
**issue(blocker):** To make our code more future proof, I think this would better be
```suggestion
              const res = await resultGravityAccessToken.json()
              if (res.error_description) {
                 console.log(res) // This will get us the error on sentry because we capture console.logs there
                 reject("failed to get gravity token from gravity")
              }
 ```

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
> +            if (res !== true) {
**issue(blocker):** I don't think we should change our current API, we better leave this as it was and instead adjust the new code. res should be returning either `true` or `false` to have a deterministic way of checking if the user signed up or not

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +    return result
**thought:** I don't see a reason why we need to return the result instead of true/false here if the user just finished signing in

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/__tests__/AuthModel-tests.ts
> +      expect(result).not.toBe(true)
if we change back the `signIn` to return `true` or `false`, we won't need to be changing this

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/__tests__/AuthModel-tests.ts
> +      ) as any
**issue(blocker):** In the previous two examples, it's fine to be mocking `signUp` but in this example we should not, instead we should be mocking the API responses as for the other existing tests. Mocking it would mean that we are not really testing the `signUp`

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/__tests__/AuthModel-tests.ts
> +        ) as any
**issue(blocker):** same here, you would have to use `mockFetchResponseOnce` to mock the API response instead of mocking the action

2021-06-16 08:52 UTC, MounirDhahri commented on src/lib/store/__tests__/AuthModel-tests.ts
> +      ) as any
**issue(non-blocking):** same comment applies here, but this is not blocking

2021-06-16 08:53 UTC, MounirDhahri commented on src/lib/store/AuthModel.ts
> +            case "Another Account Already Linked":
I understand, this code is actually few years old. I hope we remove it soon

2021-06-16 09:32 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +    return result
![Screenshot 2021-06-16 at 12 32 22](https://user-images.githubusercontent.com/73339470/122195312-ebbb3000-ce9e-11eb-8649-d01bff16aff1.png)

2021-06-16 09:42 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +    return result
same here

![Screenshot 2021-06-16 at 12 42 24](https://user-images.githubusercontent.com/73339470/122196894-528d1900-cea0-11eb-8081-d6d5cd6c38e7.png)

2021-06-16 13:09 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +        resolve("Please allow the use of email to continue.")
done

2021-06-16 13:09 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +          resolve("Error fetching data.")
done

2021-06-16 13:09 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +              resolve(signUpError)
done

2021-06-16 13:09 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +                resolve(signInError)
done

2021-06-16 13:09 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +              resolve(xAccessTokenError)
done

2021-06-16 13:09 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +              const { error_description: xAccessTokenError } = await resultGravityAccessToken.json() // error_description look better than error
done

2021-06-16 13:09 UTC, edez1t commented on src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
> +            if (res !== true) {
done

2021-06-16 13:09 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +    return result
done, now it'll be no server error message

2021-06-16 13:10 UTC, edez1t commented on src/lib/store/__tests__/AuthModel-tests.ts
> +      expect(result).not.toBe(true)
done

2021-06-16 13:10 UTC, edez1t commented on src/lib/store/__tests__/AuthModel-tests.ts
> +      ) as any
done

2021-06-16 13:10 UTC, edez1t commented on src/lib/store/__tests__/AuthModel-tests.ts
> +        ) as any
done

2021-06-16 13:11 UTC, edez1t commented on src/lib/store/__tests__/AuthModel-tests.ts
> +      ) as any
done

2021-06-16 13:18 UTC, MounirDhahri approved these changes

2021-06-16 13:18 UTC, MounirDhahri commented
This is good to go, Thanks for the changes ⭐️

2021-06-16 13:25 UTC, edez1t commented
#squshongreen

2021-06-16 14:06 UTC, merged