feat: articles screen
artsy/eigen pull request #4935
Opened 2021-06-07 10:27 UTC by olerichter00

The type of this PR is: Feature

This PR resolves [CX-1550]

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-06-09 13:59 UTC, pvinis requested changes

2021-06-09 13:59 UTC, pvinis commented on src/lib/utils/track/schema.ts
> +  Articles = "Articles",
Is this used anywhere? If not, let's remove it. We should not add anything new in this file. We should only get rid of things here, and use cohesion things.

2021-06-09 14:25 UTC, olerichter00 commented on src/lib/Scenes/Articles/ArticlesList.tsx
> +        context_screen: PageNames.Articles,
Amazing, that's what we need! I changed to `ProvideScreenTrackingWithCohesionSchema` and got rid of the `schema.ts` change.

2021-06-09 14:27 UTC, olerichter00 commented on src/lib/Scenes/Articles/ArticlesList.tsx
> +                <ArticleCardContainer article={item as any} isFluid />
Good point. `isFlud` (100% width of container) is just used on this screen. It's used two times without `isFluid` in article rails (home screen, artist screen).

2021-06-09 17:01 UTC, pvinis commented on src/lib/Scenes/Articles/ArticlesList.tsx
> +                <ArticleCardContainer article={item as any} isFluid />
cool then. I was thinking if it's needed or not, and it seems it is needed. thanks :)

2021-06-10 08:16 UTC, olerichter00 commented on src/lib/utils/track/schema.ts
> +  Articles = "Articles",
I removed it.

2021-06-10 13:01 UTC, leamotta approved these changes
Looks good!

2021-06-10 13:02 UTC, olerichter00 commented
#squashongreen

2021-06-10 13:29 UTC, merged