implement share button for articles
artsy/eigen pull request #4971
Opened 2021-06-15 13:11 UTC by kalshannikava

The type of this PR is: Feature

This PR resolves [CX-1590]

### Description

Share button added to article pages. 

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

https://user-images.githubusercontent.com/27921300/122058130-9d008e00-cdeb-11eb-9436-ccee1665726e.mov

2021-06-15 13:35 UTC, olerichter00 commented on CHANGELOG.yml
> +      - Improve admin menu - dzmitry
👀 Is this intended?

2021-06-15 13:35 UTC, olerichter00 commented on src/lib/Components/ArtsyReactWebView.tsx
> +  console.log("showShareButton", showShareButton)
I guess we can remove this `console.log`.

2021-06-15 13:35 UTC, olerichter00 commented on src/lib/navigation/routes.tsx
> +    webViewRoute("/artist/:artistID/articles", { showShareButton: true }),
I'm not sure if we want to show the share button here as well. Isn't this a route for a list of articles (actually I haven't seen this one yet)?

2021-06-15 13:35 UTC, olerichter00 commented on src/lib/navigation/routes.tsx
> +    webViewRoute("/*", { showShareButton: true }),
I don't think we need a share button here as well.

2021-06-15 13:46 UTC, kalshannikava commented on src/lib/navigation/routes.tsx
> +    webViewRoute("/artist/:artistID/articles", { showShareButton: true }),
which route is for it then? I can't find another one

2021-06-15 13:54 UTC, kalshannikava commented on src/lib/navigation/routes.tsx
> +    webViewRoute("/artist/:artistID/articles", { showShareButton: true }),
we need to use a route for a single article page. actually, when I pass showShareButton here it doesn't appear which makes me think that you're right. but I still can't find another route for an article

2021-06-15 16:07 UTC, kalshannikava commented on CHANGELOG.yml
> +      - Improve admin menu - dzmitry
@olerichter00 well vscode adds these spaces automatically on save action - I thought it's part of project linting configuration

2021-06-15 16:19 UTC, olerichter00 commented on CHANGELOG.yml
> +      - Improve admin menu - dzmitry
Interestingly, I had two conflicting formatter in vscode that prevented the file from being automatically formated. When I set a default it's doing the same formatting :)

2021-06-15 16:21 UTC, olerichter00 commented
#squashongreen

2021-06-16 07:43 UTC, kalshannikava commented on CHANGELOG.yml
> +      - Improve admin menu - dzmitry
@olerichter00 so, does it require fixing?

2021-06-16 07:53 UTC, olerichter00 commented on CHANGELOG.yml
> +      - Improve admin menu - dzmitry
@kalshannikava sorry, I should have marked my comment as non-blocking. It doesn't require fixing and is probably intended :)

2021-06-16 07:56 UTC, kalshannikava commented on src/lib/navigation/routes.tsx
> +    webViewRoute("/*", { showShareButton: true }),
fixed

2021-06-16 07:56 UTC, kalshannikava commented on src/lib/Components/ArtsyReactWebView.tsx
> +  console.log("showShareButton", showShareButton)
fixed

2021-06-16 07:58 UTC, kalshannikava commented on CHANGELOG.yml
> +      - Improve admin menu - dzmitry
@olerichter00 thank you! :)
could this PR be merged then?

2021-06-16 08:25 UTC, olerichter00 approved these changes
Looks great!

I just added one question. When we resolve this, we can merge this PR 🚀

2021-06-16 08:25 UTC, olerichter00 commented on src/lib/Components/FancyModal/FancyModalHeader.tsx
> +      return <ArrowRightIcon fill="black100" />
Hmm, do we really need an `ArrowRightIcon` here?

2021-06-16 08:34 UTC, kalshannikava commented on src/lib/Components/FancyModal/FancyModalHeader.tsx
> +      return <ArrowRightIcon fill="black100" />
It was the initial implementation of the header component which I didn't want to remove. But taking a look now, I can't find any place in the code where this arrow would be expected. So I guess it can be removed?

2021-06-16 08:43 UTC, olerichter00 approved these changes

2021-06-16 08:43 UTC, olerichter00 commented on src/lib/Components/FancyModal/FancyModalHeader.tsx
> +      return <ArrowRightIcon fill="black100" />
Ah yes, now I see it as well. I guess we can leave the `ArrowRightIcon` then and merge it 🚀

2021-06-16 10:42 UTC, MounirDhahri requested changes

2021-06-16 10:42 UTC, MounirDhahri commented on CHANGELOG.yml
> +      - Specified a more specific error for logging in with Apple or Facebook - stas hanchar
**issue:** do you mind removing those changes? on vs code you can save without formatting if you do it through the command menu

2021-06-16 10:42 UTC, MounirDhahri commented on src/lib/Components/ArtsyReactWebView.tsx
> +  }
```suggestion
  const handleArticleShare = async () =>  {
    const uri = url.startsWith("/") ? webURL + url : url
    /*
     * We only set shareTitleUrl if we navigate to a different URL within the same WebView
     */
    const shareUrl = ref.current?.shareTitleUrl || uri
    tracking.trackEvent(tracks.share(shareUrl))
    try {
      await Share.share({
        url: shareUrl,
      })
    } catch (error) {
      console.error("ArtsyReactWebView.tsx", error)
    }
  }
```

2021-06-16 10:42 UTC, MounirDhahri commented on src/lib/Components/ArtsyReactWebView.tsx
> +          onRightButtonPress={() => handleArticleShare()}
```suggestion
          onRightButtonPress={handleArticleShare}
```

2021-06-16 10:42 UTC, MounirDhahri commented on src/lib/Components/ArtsyReactWebView.tsx
> +    context_screen_owner_slug: slug,
@mikehrom we had to not pass the article id here because it wasn't possible with our current infra and it would may be take days to implement it if even possible. So for now we decided to only send the slug. Please let me know if you can manage to get the tracking to work properly with the article slug only.

2021-06-16 10:42 UTC, MounirDhahri commented on src/lib/Components/FancyModal/FancyModalHeader.tsx
> +  }
**issue(blocker):** Since the share button is the exception and not the rule, I think this would better be
```suggestion
    if (useShareButton) {
      return <ShareIcon fill="black100" height="25px" width="25px" />
    } else {
      return <ArrowRightIcon fill="black100" />
    }
  }
```

2021-06-16 10:42 UTC, MounirDhahri commented on src/lib/navigation/routes.tsx
> +    webViewRoute("/article/:articleID", { showShareButton: true }),
issue(blocker): Would you mind adding a test for this to make sure we get the right param

2021-06-16 10:42 UTC, MounirDhahri commented on src/lib/Components/ArtsyReactWebView.tsx
>  export const ArtsyReactWebViewPage: React.FC<
**issue(blocker):** Do you mind adding some tests for the new behaviour you added

2021-06-16 14:05 UTC, kalshannikava commented on CHANGELOG.yml
> +      - Specified a more specific error for logging in with Apple or Facebook - stas hanchar
@MounirDhahri I've checked - this was already merged to master as part of adcc799 commit so I think there is no need to remove it?

2021-06-16 15:17 UTC, olerichter00 commented on src/lib/Components/ArtsyReactWebView.tsx
> +  }
@MounirDhahri Shall we include this in `preferred_practices.md`?

2021-06-16 15:20 UTC, MounirDhahri commented on src/lib/Components/ArtsyReactWebView.tsx
> +  }
Yes we can definitely!

2021-06-16 15:50 UTC, mikehrom commented on src/lib/Components/ArtsyReactWebView.tsx
> +    context_screen_owner_slug: slug,
this is fine for now! it's most important that we have the 'share' event implemented and we know an article was the object shared, plus the slug tells us which article it is. `id` is only preferable because sometimes the slug changes, plus the `id` matches the `root_id` in our pageviews/sessions transforms.

2021-06-17 08:31 UTC, MounirDhahri commented on src/lib/Components/ArtsyReactWebView.tsx
> +    context_screen_owner_slug: slug,
Great, thank you Mike

2021-06-25 13:48 UTC, olerichter00 commented
#squashongreen

2021-06-25 14:19 UTC, merged