Anastasiapyzhik/sticky header on show screen
artsy/eigen pull request #4995
Opened 2021-06-21 10:34 UTC by anastasiapyzhik

The type of this PR is: **Enhancement**

[FX-2908]

This PR resolves []

### Description

I incapsulated logic of sticky header from [here](https://github.com/artsy/eigen/pull/4932) and applied for Show screen

**Before**
![Simulator Screen Shot - iPhone 8 - 2021-06-21 at 13 20 03](https://user-images.githubusercontent.com/44819355/122747233-7e8b0e80-d293-11eb-9444-87419b656349.png)

**After**
![after](https://user-images.githubusercontent.com/44819355/122747253-877be000-d293-11eb-9bed-cbf50eb69e32.gif)

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-06-21 14:05 UTC, dimatretyak commented on src/lib/Scenes/Collection/Components/CollectionArtworksFilter.tsx
> +    </>
👍

2021-06-21 15:44 UTC, lordkiz commented on src/lib/Components/HeaderArtworksFilter.tsx
> +                Showing {total} works
Nice work @anastasiapyzhik . Do you want to show "Showing 0 artworks" and the entire header alongside the empty state when artworks total is 0?

2021-06-21 15:45 UTC, mdole requested changes
Nice work @anastasiapyzhik ! Couple comments to resolve and then I think this is good to go :)

2021-06-21 15:45 UTC, mdole commented on src/lib/Scenes/Show/Components/ShowArtworksFilter.tsx
> +export const ShowArtworksFilter: React.FC<any> = (props) => {
We should avoid using `any` if possible! Based on how this is used, I would expect the props to look something like:
```typescript
interface ShowArtworksFilterProps {
  animationValue: Animated.Value
  onPress: () => void
}
```
How does that sound to you @anastasiapyzhik ?

2021-06-21 15:45 UTC, mdole commented on src/lib/Scenes/Show/Show.tsx
> +      ? [{ key: "viewing-room", element: <ShowViewingRoom show={show} mx={2} /> }]
I believe this displays an additional element if the show is associated with a viewing room - we should make sure to look at one as a test to make sure there are no weird UI interactions between the artworks filter and the `<ShowViewingRoom>` component. Here's an example of a VR with a show associated: https://staging.artsy.net/show/xavier-hufkens-cathy-wilkes-2

2021-06-21 15:52 UTC, lordkiz commented on src/lib/Scenes/Show/Components/ShowArtworks.tsx
> +    setFiltersCountAction({
Looks good. However, are we certain we always want to reset the store's `followedArtists` to null? Especially since this PR did not change that property. If we use another component at the the same level with this component and nested within the same StoreProvider, if that component makes a change to followedArtist, this component will overwrite it. 
In CollectionArtworks we did something like:
```
const counts = ArtworksFiltersStore.useStoreState((state) => state.counts)
useEffect(() => {
    // for use by CollectionArtworksFilter to keep count
    const filterCount = { ...counts, ...artworks?.counts }
    setFiltersCountAction(filterCount)
  }, [artworksTotal])
```

2021-06-22 07:34 UTC, anastasiapyzhik commented on src/lib/Scenes/Show/Components/ShowArtworksFilter.tsx
> +export const ShowArtworksFilter: React.FC<any> = (props) => {
Ahh I just put `any` temporarily and forgot about it. Thanks for the note!

2021-06-22 07:46 UTC, anastasiapyzhik commented on src/lib/Components/HeaderArtworksFilter.tsx
> +                Showing {total} works
In case artworks total is 0 the component returns separator only https://github.com/artsy/eigen/blob/320ed16f6085c596514547344077417ae9065437/src/lib/Components/HeaderArtworksFilter.tsx#L88-L90

2021-06-22 09:02 UTC, anastasiapyzhik commented on src/lib/Scenes/Show/Show.tsx
> +      ? [{ key: "viewing-room", element: <ShowViewingRoom show={show} mx={2} /> }]
There are no any works so I added the header with 0 works in order to show you what it looks like

![for](https://user-images.githubusercontent.com/44819355/122895245-9b394c00-d350-11eb-9717-5e946df6b37e.gif)

Please don't mind the UI freezing, I just have a slow mac and can't help it. It happens on demo only, not in simulator

2021-06-22 09:04 UTC, lordkiz commented on src/lib/Components/HeaderArtworksFilter.tsx
> +                Showing {total} works
Oh. I totally missed that line. 👍🏾👍🏾👍🏾

2021-06-22 09:22 UTC, anastasiapyzhik commented on src/lib/Scenes/Show/Components/ShowArtworks.tsx
> +    setFiltersCountAction({
That's a good point, thanks!

2021-06-22 12:39 UTC, anastasiapyzhik commented
Please don't merge yet, I have to add a small update

2021-06-23 10:29 UTC, mdole approved these changes
Nice work! Let's ship it!

2021-06-23 14:36 UTC, merged