[WIP]feat(CX-1603): Add new onboarding feature flag
artsy/eigen pull request #5015
Opened 2021-06-23 08:49 UTC by edez1t

The type of this PR is: **Feature**

This PR resolves [CX-1603]

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

2021-06-23 08:53 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +        "User-Agent": getCurrentEmissionState().userAgent,
context.getStoreState().native.sessionState.userAgent returned undefined for android and wasn't used on ios

2021-06-23 08:58 UTC, edez1t commented on src/lib/store/AuthModel.ts
> +        "User-Agent": getCurrentEmissionState().userAgent,
same here

2021-06-23 08:58 UTC, edez1t commented on src/lib/store/AuthModel.ts
>      return null
these logic wasn't used on ios, so we don't need feat flag

2021-06-23 11:44 UTC, pvinis reviewed
Just some comments :)

2021-06-23 11:44 UTC, pvinis commented on src/lib/store/config/features.ts
> +    showInAdminMenu: Platform.OS === "ios",
👨‍🍳👌

2021-06-23 11:44 UTC, pvinis commented on src/lib/store/GlobalStore.tsx
> +  if (Platform.OS === "ios" && !unsafe_getFeatureFlag("AREnableNewOnboardingFlow")) {
I think it makes it cleaner to have clear ifs (only with the flag check) that wrap code, so we can easily get rid of them when we remove the flag too.

Something like
```
if (!flag(AREnable) {
  if(Platform === "ios") {
    ..
  }
}
```

What do you think?

2021-06-23 11:44 UTC, pvinis commented on src/lib/store/AuthModel.ts
>        return store.auth.androidUserEmail
Could you rename this from `androidUserEmail` to just `userEmail`? It was named `android*` so it's clear it's only used there. Now we are slowly going for both platforms, we can use a better name :)

2021-06-23 11:44 UTC, pvinis commented on src/lib/store/config/features.ts
> +    readyForRelease: false,
Just a thought: I wonder if instead of true, something like `Platform.OS === "android"` would be helpful here. So basically to be `on` by default.

Actually, while I'm writing this, I kinda answered myself.. It would be a problem if we turn that flag to `false` in echo, and it just overrides the check here 😅.

2021-06-23 11:44 UTC, pvinis commented on src/lib/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
> +    Platform.OS === "android" || showNewOnboarding
Just curious, but why didn't you go for `Platform.OS === "ios" && !showNewOnboarding`?

2021-06-23 12:39 UTC, edez1t commented on src/lib/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
> +    Platform.OS === "android" || showNewOnboarding
i'll do it, just thought that maybe it will be more readable

2021-06-23 12:57 UTC, pvinis commented on src/lib/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
> +    Platform.OS === "android" || showNewOnboarding
Both work. I was just curious. For me both read kinda the same, so if you prefer one over the other, do the one you prefer.

2021-06-23 13:55 UTC, edez1t commented on src/lib/store/GlobalStore.tsx
> +  if (Platform.OS === "ios" && !unsafe_getFeatureFlag("AREnableNewOnboardingFlow")) {
done

2021-06-23 14:06 UTC, edez1t commented on src/lib/store/AuthModel.ts
>        return store.auth.androidUserEmail
done

2021-06-24 09:03 UTC, pvinis requested changes
We should not merge this yet!

Maybe I was unclear with the migration instructions. We need to make a new migration in order to rename.

Also we should check if it works if we turn the flag off again 🤔.

Let's do it together maybe?

2021-06-24 15:54 UTC, edez1t commented on src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
> -        onBlur={() => validateForm()}
We don't need this here. We only validate the form when pressing "next" button. (CX-1629) I guess creating a ticket wan't necessary

2021-06-25 10:05 UTC, edez1t commented
> We should not merge this yet!
> 
> Maybe I was unclear with the migration instructions. We need to make a new migration in order to rename.
> 
> Also we should check if it works if we turn the flag off again 🤔.
> 
> Let's do it together maybe?

2021-06-25 10:08 UTC, edez1t commented
![Screenshot 2021-06-25 at 13 04 39](https://user-images.githubusercontent.com/73339470/123408843-25ceb500-d5b6-11eb-90d7-babcea890b97.png)

the only place where we use userEmail. is it good this way? if no it would be better to pair

2021-06-28 12:27 UTC, edez1t commented on src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
> +    <Flex flex={1} style={{ paddingBottom: useScreenDimensions().safeAreaInsets.bottom }}>
Yauheni'es changes fixing white bottom padding [CX-1651]

2021-07-02 10:00 UTC, pvinis commented on src/lib/store/AuthModel.ts
> -  userEmail: computed([(_, store) => store], (store) => {
This here is an important change. the `userEmail` is no longer computed. For android its basically what `androidUserEmail` was a bit further up the file, so just a regular state thing. For ios, we make sure to manually update it from native state, whenever it changes, while the flag is `false`. When the flag is done and `true` and/or when we remove it, we can also remove the `getUserEmail` function and function call as well, as it will no longer use the native state for auth. We will go through the new TS way, like android. That's what ios does in this PR when the flag is `true`.

2021-07-02 10:03 UTC, pvinis commented
I think we can merge this now and get it ready for QA.

2021-07-02 10:03 UTC, pvinis approved these changes
Let's go :D

2021-07-02 11:22 UTC, merged