feat: saved search notification
artsy/eigen pull request #5034
Opened 2021-06-24 18:19 UTC by dimatretyak

The type of this PR is: **Feature**

This PR resolves []

### Description
Initial development start: #5000 

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

2021-06-25 11:28 UTC, mdole requested changes
Awesome work @dimatretyak! There are a couple small adjustments I think we should make. And because https://github.com/artsy/eigen/pull/5032 is now merged in, this PR should be rebased and updated (we changed the format of the props object we were passing from notifications into React Native).

Let me know if you want to pair or have questions!

2021-06-25 11:28 UTC, mdole commented on src/lib/Scenes/Artist/SearchCriteria.tsx
> +export const SearchCriteriaQueryRender: React.FC<SearchCriteriaQueryRenderProps> = (props) => {
**Minor:** suggest renaming `SearchCriteriaQueryRender` -> `SearchCriteriaQueryRenderer` (just the extra `er` at the very end) to match our normal naming conventions

2021-06-25 11:31 UTC, dimatretyak commented on src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
> +      setInitialFilterStateAction(params)
Yep, you're right. Now we pass the search criteria immediately at [the first request](https://github.com/artsy/eigen/blob/8d1f80a0d6808439a33a0ef33dc018728f94b58c/src/lib/Scenes/Artist/Artist.tsx#L143-L148)

2021-06-25 11:33 UTC, dimatretyak commented on src/lib/Scenes/Artist/Artist.tsx
> +        message: "Failed to get saved search criteria",
We [discussed](https://artsy.slack.com/archives/C9SATFLUU/p1624542547280100?thread_ts=1624440986.218100&cid=C9SATFLUU) this with @dblandin yesterday

2021-06-25 11:39 UTC, dimatretyak commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
I don't think there will be an impact on performance since we will never have a query/render query render if the [following conditions](https://github.com/artsy/eigen/blob/8d1f80a0d6808439a33a0ef33dc018728f94b58c/src/lib/Scenes/Artist/SearchCriteria.tsx#L28) are not met

2021-06-25 12:51 UTC, mdole commented on src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
> +      setInitialFilterStateAction(params)
ah right! thanks for clarifying

2021-06-25 13:03 UTC, mdole commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
Ah yes, good point. Makes sense to me!

2021-06-25 13:55 UTC, mdole approved these changes

2021-06-29 09:59 UTC, MounirDhahri commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
**issue:** I am not sure if it's a good idea to be nesting QueryRenderers here. We did some optimisations recently to the Artist screen to improve its TTI and the changes here break those optimizations since we will only be rendering the artist screen after we get the search criteria related fields. I also believe that if any updates to the search criteria, will lead to 2 additional unnecessary queries at the `AboveTheFoldQueryRenderer` in line 151.

Did you maybe considered having the `SearchCriteriaQuery` as part of the below the fold Query and if this is not possible to have the nested QueryRenderer (which we should avoid) only at the Artworks tab

2021-06-29 11:14 UTC, dimatretyak commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
@MounirDhahri  I'll see what I can do. But, unfortunately, this is the best solution to the problem that I managed to come up with. With this solution, we can immediately get filtered works according to the saved criteria in one request. Otherwise, we would first have to make [a request without any criteria](https://github.com/artsy/eigen/blob/f07a71eae224cda84298c56480a27cd2396a50f2/src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx#L226-L239), after we receive the saved search criteria, we need to send another request for receiving artworks, but with the specified filters (there is an example of [such an implementation](https://github.com/artsy/eigen/pull/5000/files), but it complicates the code)

The main idea of `SearchCriteriaQueryRenderer` is that it will execute only when the `searchCriteriaId` was passed (in our case, this is when the user clicked on the PUSH notification about the saved search) and it will not change (respectively, the two queries below will also not be re-executed)

2021-06-29 12:13 UTC, MounirDhahri commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
Thanks for the explanation @dimatretyak. I have a better understanding now of what's happening. I think it's fine this way then and you or @mdole please feel free to merge this.
I do however want to suggest a possible solution for the future. Maybe instead of getting the search criteria on Eigen then querying for artworks using those criteria, we can do that query on metaphysics and even better probably on gravity.
Using sequence diagrams, what I mean is, instead of the following (may not be too accurate and it's definitely very simplified):
![diagram](https://user-images.githubusercontent.com/11945712/123795009-ca693380-d8e3-11eb-8813-7a5ebc4e741e.png)
I would suggest that we try to do something like this:
![Untitled (3)](https://user-images.githubusercontent.com/11945712/123795078-e66cd500-d8e3-11eb-9990-1acb7800b5c4.png)
_What's in the red rectangle is not necessary for now because we can also just move stuff to metaphysics._

2021-06-29 12:33 UTC, dimatretyak commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
@MounirDhahri Thank you for the diagrams and detailed discussion! Yes, this option was also discussed with the team. I think that in the future this is exactly the solution that will be added

2021-06-29 14:19 UTC, mdole commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
+1 thanks for the thoughts and diagrams! we just chatted as a team and we agreed to move forward with this version and make the change to filter artworks by search criteria ID as you suggested in the future.

2021-06-29 14:20 UTC, merged

2021-06-29 17:22 UTC, MounirDhahri commented on src/lib/Scenes/Artist/Artist.tsx
> +      environment={environment}
sure 🙇‍♂️