refactor: category and refine logic
artsy/eigen pull request #5054
Opened 2021-06-28 17:50 UTC by dimatretyak

The type of this PR is: **Refactor**

This PR resolves [FX-3044]

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

2021-07-01 13:44 UTC, brainbicycle commented on src/lib/Components/Gene/GeneArtworks.tsx
> +export const GeneArtwors: React.FC<GeneArtworsProps> = (props) => {
```suggestion
export const GeneArtworks: React.FC<GeneArtworsProps> = (props) => {
```
small typo here!

2021-07-01 13:44 UTC, brainbicycle commented on src/lib/Components/Gene/GeneArtworks.tsx
> +interface GeneArtworsProps extends GeneArtworksContainerProps {
```suggestion
interface GeneArtworksProps extends GeneArtworksContainerProps {
```
small typo here!

2021-07-01 19:16 UTC, dimatretyak commented on src/lib/Components/Gene/GeneArtworks.tsx
> +export const GeneArtwors: React.FC<GeneArtworsProps> = (props) => {
Solved 👍

2021-07-01 19:16 UTC, dimatretyak commented on src/lib/Components/Gene/GeneArtworks.tsx
> +interface GeneArtworsProps extends GeneArtworksContainerProps {
Solved 👍

2021-07-01 22:21 UTC, brainbicycle commented on src/lib/Components/Gene/GeneArtworks.tsx
> +      <Message>There aren’t any works available by the category at this time.</Message>
Not sure about copy here, can you ask @thomasmeerschwam if this is correct?

2021-07-01 22:22 UTC, brainbicycle requested changes
Fantastic work! Code looks great and thank you for removing the old Objective-C code, I have one question about empty state copy I think we should address but otherwise looks great to me 🙇

2021-07-02 14:00 UTC, MounirDhahri commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  }, [appliedFilters])
**thought:** shouldn't this be `applyFilters` ?

2021-07-02 14:02 UTC, MounirDhahri commented on src/lib/Components/Gene/GeneArtworks.tsx
> +      )
**issue(blocker):** I think in the case we have no artworks available for a gene (with no filters enabled) this would show `FilteredArtworkGridZeroState` instead of `no artworks available for this gene`

2021-07-02 14:04 UTC, MounirDhahri commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  }
**issue:** same comment here about analyics as above

2021-07-02 14:07 UTC, MounirDhahri commented on src/lib/Components/Gene/GeneArtworks.tsx
> +      )
I just saw the test you made, so the assumption you have I guess is that `gene.artworks` is null when no artworks are available but I think we actually return an empty array and not null from metaphysics.

2021-07-02 14:18 UTC, dimatretyak commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  }, [appliedFilters])
@MounirDhahri Can you please clarify?

2021-07-02 14:32 UTC, dimatretyak commented on src/lib/Components/Gene/GeneArtworks.tsx
> +      )
Yes, you're right. I don't think there is a possible case where `gene` is `null`

2021-07-02 15:04 UTC, dimatretyak commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  }
If I understood you correctly, then this is solved

2021-07-06 08:53 UTC, MounirDhahri commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  if (artworksTotal === 0) {
**issue:** unfortunately here the artworks total will be changing whenever the filters change and it's hard to tell later if there are no artworks at all or just with the applied filter. I think you can solve that by saving the initial value as a reference or in the state (I prefer as a reference since it won't be changing)
We did something like that here (but probably with a reference) https://github.com/artsy/eigen/blob/7d6e9ca3eecce96eaf4534b07aa53bf56cdf8d78/src/lib/Scenes/Sale/Components/SaleLotsList.tsx#L85-L88

2021-07-06 10:52 UTC, dimatretyak commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  if (artworksTotal === 0) {
@MounirDhahri done

2021-07-06 13:08 UTC, MounirDhahri commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  }, [appliedFilters])
Usually we should be applying the filters only when the applyFitlers boolean is set to true but I think it's fine to have it this way as well

2021-07-06 13:09 UTC, MounirDhahri approved these changes
🙌

2021-07-06 13:22 UTC, dimatretyak commented on src/lib/Components/Gene/GeneArtworks.tsx
> +  }, [appliedFilters])
In our case, filters will also be applied when `applyFilters` is `true`. I looked at how it is implemented in other places and did it by analogy ([ArtistArtworks](https://github.com/artsy/eigen/blob/master/src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx#L113-L125), [ArtistInsightsAuctionResults](https://github.com/artsy/eigen/blob/master/src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx#L41-L54), [ArtistSeriesArtworks](https://github.com/artsy/eigen/blob/master/src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx#L47-L59), etc)

2021-07-06 13:45 UTC, dimatretyak commented
@brainbicycle The text of the empty message is agreed with Thomas

2021-07-06 21:52 UTC, brainbicycle approved these changes

2021-07-06 21:52 UTC, merged