fix: use palette touchable /w bg
artsy/eigen pull request #5057
Opened 2021-06-29 07:32 UTC by gkartalis

The type of this PR is: **Enhancement**

This PR resolves [FX-2254]

### Description

ArtistSeriesListItem was using `TouchableOpacity` from `react-native` and not `Touchable` from palette.

Furthermore the `underlayColor` wasn't the same as other parts of the app so added "black5" to match the other Touchables.

The screenshots below show the touchable behaviour when the user is pressing the button.

|Android|iOS|
|---|---|
|![android](https://user-images.githubusercontent.com/21178754/123755168-f07add80-d8bb-11eb-9d73-f881bc9aca61.png)|![ios](https://user-images.githubusercontent.com/21178754/123755177-f2dd3780-d8bb-11eb-9d27-f372e4d88714.png)|

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### Changelog updates

#### Cross-platform user-facing changes

- Fix add touchable underlay color in ArtistSeriesListItem

2021-06-29 09:20 UTC, mdole requested changes
Nice! Did notice one thing from the screenshots: it looks like the bottom padding between each item also has the opacity on tap. @gkartalis would you be up for tweaking it so that only the item and not the padding has the background color on tap?
![123755168-f07add80-d8bb-11eb-9d73-f881bc9aca61](https://user-images.githubusercontent.com/5361806/123772185-ef51ac80-d8cb-11eb-9148-8a5cce0b4287.png)

2021-06-29 13:31 UTC, gkartalis commented
Good observation. Sure thing!

I also noticed another inconsistency that was discussed on [this slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1624960749370100) with Johnathan as well and will address everything from the reply in this pr.

2021-06-30 08:07 UTC, gkartalis commented on src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
> +      style={{ marginHorizontal: -20 }}
Not sure this is the best approach here. The reason I used this negative margin is because in all instances of `<ArtistSeriesListItem />` and `<ArtistSeriesMoreSeries />` we have a parent component padding of 20 and thought that it would be better to change the margin in one spot than in multiple and also mess with the component tree.

Any thoughts or suggestions to change that are welcome ofc!

2021-06-30 08:49 UTC, mdole approved these changes
Nice work! Let's ship it

2021-06-30 08:49 UTC, mdole commented on src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
> +      style={{ marginHorizontal: -20 }}
Yeah, this is a tricky decision! I think your choice here is reasonable. One small thing you could do would be to add a comment noting the purpose of the `marginHorizontal`; while it's not a particularly complex piece of code, sometimes it's helpful to have the intent clearly spelled out.

2021-06-30 09:10 UTC, gkartalis commented
#squashongreen

2021-06-30 09:13 UTC, merged