fix (CX-958): refresh artwork after purchase
artsy/eigen pull request #5064
Opened 2021-06-30 12:25 UTC by kalshannikava

The type of this PR is: **Bugfix**

This PR resolves [CX-958]

### Description

**The issue:**
As a collector, when I buy an artwork, the artwork screen should automatically refresh to show I've purchased it so that I'm sure I bought it.
Without refresh "Buy now" button is still available and we don't display "Sold" status.

**The fix:**

https://user-images.githubusercontent.com/27921300/123959866-f00f3f00-d9ae-11eb-8527-6c626b8d80c1.mov

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a [CHANGELOG.yml](/CHANGELOG.yml) entry or my changes do not require one.

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

2021-06-30 12:28 UTC, kalshannikava commented on src/lib/Scenes/Artwork/Artwork.tsx
> +          <ActivityIndicator />
I'm not sure if ActivityIndicator is the correct component to use here but by a quick look at the project it seems like so. It could be changed if it's needed.

2021-06-30 12:28 UTC, kalshannikava commented on src/lib/Components/ArtsyReactWebView.tsx
> +              dismissModal()
Had to add it becuse for some reason we were using 'goBack' event even for the modal close which doesn't seem to be correct.

2021-06-30 13:14 UTC, JenqaaaBY commented on src/lib/Scenes/Artwork/Artwork.tsx
> +          <ActivityIndicator />
I think you should use a spinner from palette
`import { Spinner } from "palette"`

2021-06-30 13:39 UTC, JenqaaaBY approved these changes
Now it looks good to me

2021-06-30 13:44 UTC, olerichter00 requested changes
The change refreshes the page but it also breaks the RefreshControl UI. I think we can accomplish the same easier by just the logic in `componentDidUpdate`.

2021-06-30 13:44 UTC, olerichter00 commented on src/lib/Scenes/Artwork/Artwork.tsx
> +        {this.state.refreshing ? (
This change actually breaks the RefreshControl UI (scrolling down from top to refresh the page). I'd suggest to use the already existing logic we have in [componentDidUpdate](https://github.com/artsy/eigen/blob/62b1bbe8cf3d4e7e8618d14e4a8c3fce08bf1e38/src/lib/Scenes/Artwork/Artwork.tsx#L106), extract it into a method (e.g. `refresh`) and call it in `componentDidUpdate` and `handleModalDismissed`.

2021-07-01 14:58 UTC, olerichter00 commented on src/lib/Scenes/Artwork/Artwork.tsx
> +    fetchingData: false,
I think we don't even need to add an indicator that we reload the data when we come from the modal.

2021-07-01 14:58 UTC, olerichter00 commented on src/lib/Scenes/Artwork/Artwork.tsx
> +        )}
I'd just remove this change completely and don't indicate when we reload because we come back from the because the spinner we introduce in this block is breaking the UI of the <RefreshControl /> component

2021-07-01 15:05 UTC, kalshannikava commented on src/lib/Scenes/Artwork/Artwork.tsx
> +        )}
@olerichter00 hmmm, but I'd say this switch from 'buy now' to 'sold' doesn't look good
https://user-images.githubusercontent.com/27921300/124146787-6767d000-da8e-11eb-8bc4-de4e24fb107b.mov

2021-07-01 15:19 UTC, olerichter00 approved these changes
Looks good. What do you think of using the placeholder we use when we initially loading the screen (see comment)?

2021-07-01 15:19 UTC, olerichter00 commented on src/lib/Scenes/Artwork/Artwork.tsx
> +        )}
Sorry, I haven't seen that you actually changed the refresh indicator to a spinner. That's actually way better than not showing any loading indicator 👍

2021-07-01 15:19 UTC, olerichter00 commented on src/lib/Scenes/Artwork/Artwork.tsx
> +          </Flex>
```suggestion
          <ProvidePlaceholderContext>
            <AboveTheFoldPlaceholder />
          </ProvidePlaceholderContext>
```

**Suggestion:** Let's use the same placeholder/loading indicator we use when entering the screen.

2021-07-02 08:11 UTC, kalshannikava commented on src/lib/Scenes/Artwork/Artwork.tsx
> +          </Flex>
Good idea to use the placeholder! Done

2021-07-02 08:32 UTC, merged