feat: add delete address functionality
artsy/eigen pull request #5130
Opened 2021-07-14 13:41 UTC by gkartalis

The type of this PR is: **Feature**

This PR resolves [PURCHASE-2787]

### Description

- Allow an address to be deleted when a user selects the delete text link on the card by adding a deleteAddress mutation

https://user-images.githubusercontent.com/21178754/125631970-70c8fe18-44f1-4223-9a1f-91f913da82e7.mp4

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a CHANGELOG.yml entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Enables users to delete saved addresses

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-07-14 13:42 UTC, gkartalis commented
Noticed in the video that when removing address the unmounting of the element is not the smoothest. Maybe we can address that in another ticket after syncing with design?

2021-07-14 13:42 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Enables users to delete saved addresses)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a18a599d8de398a2394c95e5e08c19fb8e6a2ae2
</p>

2021-07-14 17:08 UTC, jo-rs requested changes
It looks great 💯 
Let's move the mutation to its own file, so we can reuse it. And, are there any tests that we can add?

2021-07-14 17:08 UTC, jo-rs commented on src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
> +
I'd say, let's move this guy to it's own file so we can then reuse it on the edit form?

2021-07-14 17:08 UTC, jo-rs commented on src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
> +          first: 3,
Is this `3` trivial? 🤔

2021-07-14 17:09 UTC, jo-rs commented
> Noticed in the video that when removing address the unmounting of the element is not the smoothest. Maybe we can address that in another ticket after syncing with design?

I think once we add the toast in, it will feel a bit nicer 🤞

2021-07-15 11:12 UTC, jo-rs approved these changes
Nice! 🚀

2021-07-15 11:13 UTC, merged