feat(FX-3089): create saved search alert button
artsy/eigen pull request #5149
Opened 2021-07-20 17:23 UTC by dimatretyak

The type of this PR is: **Feature**

This PR resolves [FX-3089]

### Description
As an admin with the saved search M2 feature flag enabled,
If I am viewing an artist artworks grid,
I always see the "create alert" button

#### Acceptance criteria:
* This ticket includes introduction of a feature flag for M2 and hides these changes behind it
* Button is disabled when no filters are applied
* Button is enabled when filters are applied but no search criteria with those filters exists
* Button is disabled when search criteria with existing filters exists

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-07-20 17:24 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dab478bb9d3b6125f5dbed051fad38513a30f2e1
</p>

2021-07-22 11:15 UTC, dimatretyak commented on src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
> +
Maybe we should return the component immediately and not make a request if the criteria were not passed?

```javascript
if (Object.keys(input).length === 0) {
    return <SavedSearchButton loading={false} attributes={input} />
}
```

2021-07-26 13:01 UTC, mdole requested changes
Looking good! Few minor changes and I think we'll be ready.

I also need to look into where we should add the `Button` icon style changes - I'm confused about the relationship between Eigen's version of Palette and the broader Palette [repo](github.com/artsy/palette). I'll investigate and let you know if they belong elsewhere!

2021-07-26 13:04 UTC, dimatretyak commented on src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
> +  const isSavedSearch = !!me?.savedSearch?.internalID ?? false
Oh, I completely agree with you. I missed this moment

2021-07-26 13:06 UTC, dimatretyak commented on src/palette/elements/Button/Button.tsx
> +                  </LongestText>
Yes, we can. Initially, this was the case, but then I found out that one of the tests was falling, because there is a calculation on `Sans` counts. For this reason, I decided to rename `Sans` to `LongestText`

2021-07-26 13:53 UTC, mdole commented on src/palette/elements/Button/Button.tsx
> +                  </LongestText>
Ah, I see! Maybe we could just create a named component in that case instead of a styled component? something like
```js
const LongestText = <Sans>...</Sans>
```

2021-07-26 14:51 UTC, dimatretyak commented on src/palette/elements/Button/Button.tsx
> +                  </LongestText>
Unfortunately, if we make it so that the test will still fall
```javascript
const LongestText = (
    <Sans role="presentation" weight="medium" size={s.size}>
      {longestText ? longestText : children}
    </Sans>
  )
```

or like this

```javascript
const LongestText = Sans
...
<LongestText>...</LongestText>

2021-07-26 14:54 UTC, dimatretyak commented on src/palette/elements/Button/Button.tsx
> +                  </LongestText>
I checked whether this method is used in other places in the code. And yes, there were coincidences

- [ArtistInsightsAuctionResults](https://github.com/artsy/eigen/blob/master/src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx#L189)
- [ArtworkFilter](https://github.com/artsy/eigen/blob/master/src/lib/Components/ArtworkFilter/ArtworkFilter.tsx#L299)
- [ArtworkFilterOptionsScreen](https://github.com/artsy/eigen/blob/master/src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx#L388)

2021-07-26 14:58 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (Saved search banner M2 – dzmitry tratsiak)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4f8db5298fdcde302778d45dc9bafd596d5f7a29
</p>

2021-07-27 11:25 UTC, mdole commented on src/palette/elements/Button/Button.tsx
> +                  </LongestText>
Thanks for looking into it! You've convinced me, let's leave as-is :)

2021-07-27 11:26 UTC, mdole approved these changes
nice! let's ship it

2021-07-27 11:26 UTC, merged