Feature: Palette V3 Button
artsy/eigen pull request #5185
Opened 2021-07-28 09:39 UTC by olerichter00

The type of this PR is: **Feature**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-07-28 09:40 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2635cb5fb8febc9b16013f18803799198c6e9b67
</p>

2021-07-28 10:24 UTC, pvinis commented on src/storybook/storybook-ui.js
> +  onDeviceUI: true,
👍

2021-07-29 12:38 UTC, olerichter00 commented on src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
> +            {!!this.props.autoFetch && <ActivityIndicator color={Platform.OS === "android" ? "black" : undefined} />}
**Note:** Getting rid of `getColorsForVariant` here because of type issus.

2021-07-29 12:39 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
> +              variant="secondaryOutline"
`secondaryOutlineWarning` doesn't exist anymore and I think `secondaryOutline` should be good for an edit button.

2021-07-29 12:40 UTC, olerichter00 commented on src/palette/elements/Button/__tests__/Button-tests.tsx
> +  it("does not invoke the onClick callback if loading is true", () => {
**Note:** Adding this behaviour (it doesn't exist in the V2 button).

2021-07-29 12:40 UTC, olerichter00 commented on src/palette/elements/Button/__tests__/Button-tests.tsx
> +  it("does not invoke the onClick callback if disabled is true", () => {
**Note:** Adding this behaviour (it doesn't exist in the V2 button).

2021-07-30 09:40 UTC, pvinis commented on src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
> -                // @ts-expect-error STRICTNESS_MIGRATION --- 🚨 Unsafe legacy code 🚨 Please delete this and fix any type errors if you have time 🙏
NICE!

2021-07-30 16:44 UTC, pvinis requested changes
Such good work, can't wait for this to be out :D!

I made some comments that I hope should all be small.

2021-07-30 16:44 UTC, pvinis commented on src/palette/elements/Button/ButtonV2.stories.tsx
> +storiesOf("ButtonV2", module)
```suggestion
storiesOf("Theme/ButtonV2", module)
```
By adding this, it makes a little folder. It might be cool to have it that way, and then we can add Screens etc too 😮

2021-07-30 16:44 UTC, pvinis commented on src/palette/elements/Button/Button.stories.tsx
> +storiesOf("ButtonV3", module)
```suggestion
storiesOf("Theme/ButtonV3", module)
```
same

2021-07-30 16:44 UTC, pvinis commented on src/palette/elements/Button/Button.tsx
> +export type ButtonVariant = "primaryBlack" | "primaryWhite" | "secondaryGray" | "secondaryOutline" | "text"
```suggestion
export type ButtonVariant = "primaryDark" | "primaryLight" | "secondaryFill" | "secondaryOutline" | "text"
```

I see in figma these are the names they use. Let's follow the same names, for less confusion in the future?

I'll link to Jonathan too, for confirmation.

2021-07-30 16:44 UTC, pvinis commented on src/palette/elements/Button/Button.tsx
> +        return { height: inline ? 17 : 30, size: "2", px: inline ? 0 : 15 }
I didn't see `inline` style in v3. Is that somewhere I missed? Or maybe we remove it? I'll ask Jonathan about this too.

2021-07-30 16:44 UTC, pvinis commented on src/palette/elements/Button/Button.tsx
> +  <Theme>
This one is not needed. The one below covers it :)

2021-07-30 16:44 UTC, pvinis commented on src/palette/elements/Button/index.tsx
>  export * from "./Button"
I think we should also export `ButtonV2` juuuuuuuust in case we need to use that anywhere. But hopefully we don't need it.

2021-07-30 16:44 UTC, pvinis commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
> +              variant="secondaryOutline"
I think thats a good use of the mapper for now.

2021-07-30 17:09 UTC, pvinis commented on src/palette/elements/Button/Button.tsx
> +        return { height: inline ? 17 : 30, size: "2", px: inline ? 0 : 15 }
Yup, let's remove the `inline` prop. 👋

2021-07-30 17:17 UTC, pvinis commented on src/palette/elements/Button/Button.tsx
> +export type ButtonVariant = "primaryBlack" | "primaryWhite" | "secondaryGray" | "secondaryOutline" | "text"
After talking to Jonathan, it makes sense to do `fillDark`, `fillLight`, `fillGray`, `outline`, `text`.

2021-07-30 17:20 UTC, pvinis commented on src/palette/elements/Button/Button.tsx
> +                  color={loading ? "transparent" : to.textColor}
This `to.textColor` is not actually animated. I think we need to make the `Text` animated in order for that to work. I does seem a bit jarring when the backfill animated and the text going from black to white imediatelly.

2021-08-02 07:43 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
> +              variant="secondaryOutline"
👍

2021-08-02 07:48 UTC, olerichter00 commented on src/palette/Theme.tsx
> +export interface ColorFuncOverload {
I used the type it in `src/palette/elements/Button/Button.tsx#L207` to pass the color function as a parameter. But refactored it to prevent exporting/importing `ColorFuncOverload` 👍

2021-08-02 07:53 UTC, olerichter00 commented on src/palette/elements/Button/ButtonV2.stories.tsx
> +storiesOf("ButtonV2", module)
Seems like nesting is [not yet implemented](https://github.com/storybookjs/react-native/issues/12).

2021-08-02 07:57 UTC, pvinis commented
I just remembered actually that we could totally use the storybook decorator for the merged theme to verify the button v2 asking.

2021-08-02 08:21 UTC, olerichter00 commented on src/palette/elements/Button/Button.tsx
> +export type ButtonVariant = "primaryBlack" | "primaryWhite" | "secondaryGray" | "secondaryOutline" | "text"
Good idea! I mapped all variants in `src/palette/elements/Button/index.tsx` from V2 -> V3.

2021-08-02 08:23 UTC, olerichter00 commented on src/palette/elements/Button/Button.tsx
> +        return { height: inline ? 17 : 30, size: "2", px: inline ? 0 : 15 }
I just took it from V2 but I can't find it being used anywhere in the codebase. Let's say good by to `inline` 👋

2021-08-02 08:25 UTC, olerichter00 commented on src/palette/elements/Button/index.tsx
>  export * from "./Button"
Sure, that's a good idea. I'll export it as well.

2021-08-02 08:38 UTC, pvinis commented on src/palette/elements/Button/ButtonV2.stories.tsx
> +storiesOf("ButtonV2", module)
Ah, on the browser it works, but ondevice UI is not supporting it. I guess it could still be ok, but I'm open to suggestions. We could also keep it as is?

2021-08-02 09:06 UTC, pvinis commented on src/palette/elements/Button/ButtonV2.stories.tsx
> +  .add("Sizes", () => (
> I just remembered actually that we could totally use the storybook decorator for the merged theme to verify the button v2 asking.

that comment is for here, above this line.

2021-08-02 09:06 UTC, pvinis commented on src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
this one here is still `.only`? 🤔

2021-08-02 09:35 UTC, pvinis commented
![](https://media1.giphy.com/media/1fmBvkvmgm86Hw4WhK/giphy.gif)

2021-08-02 10:41 UTC, merged