feat(FX-3109): tag page
artsy/eigen pull request #5195
Opened 2021-07-29 14:05 UTC by tr-ann

The type of this PR is: Feature
Jira ticket: [FX-3109](https://artsyproduct.atlassian.net/browse/FX-3109)

This PR resolves []

### Description

- `tag/:slug` route render Tag page
- Added artworks grid, filters modal and sticky filter bar
- Added tests for the page

### Demo

https://user-images.githubusercontent.com/56556580/127502537-95079861-e624-460f-85cd-20b45009fd87.mov

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Tag scene

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-07-29 14:06 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Tag scene)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 37736c91e11a33bd8a1f94ac467d453d01c6a704
</p>

2021-07-29 14:25 UTC, tr-ann commented on src/lib/Scenes/Tag/Tag.tsx
> +        <StickyTabPage staticHeaderContent={headerContent} stickyHeaderContent={<></>} tabs={tabs} />
Set `stickyHeaderContent={<></>}` to hide the tab title. In this case only filter bar are sticky.

2021-07-29 16:42 UTC, mdole requested changes
Awesome work, @tr-ann! I left several comments but they're all very small. Thanks for taking this on, and welcome to Eigen!

2021-07-29 16:42 UTC, mdole commented on src/lib/Components/Tag/Header.tsx
> +        {tag.name || ""}
**minor:** I don't think we need the `|| ""` here; all tags have names (though looking at our data, many names are things like IDs or URLs, it's definitely not clean data)

2021-07-29 16:42 UTC, mdole commented on src/lib/Components/Tag/Header.tsx
> +      <Sans size="8" numberOfLines={2}>
**minor:** we should use `<Text>` instead of `<Sans>` - both work, but `<Text>` is newer and is our preferred method :)

2021-07-29 16:42 UTC, mdole commented on src/lib/Components/Tag/Header.tsx
> +      id
**minor:** do we need these three? Seems like we only display `name` in this component - does something else break if we don't fetch them?

2021-07-29 16:42 UTC, mdole commented on src/lib/Components/Tag/__tests__/About-tests.tsx
> +// Note: test renderer must be required after react-native.
**very minor:** we probably don't need to keep this one 😄

2021-07-29 16:42 UTC, mdole commented on src/lib/Components/Tag/__tests__/Header-tests.tsx
> +  renderWithWrappers(<Header tag={tag as any} />)
**Curiosity:** why is this `as any` required?

2021-07-29 16:42 UTC, mdole commented on src/lib/Components/Tag/__tests__/TagArtworks-tests.tsx
> +          // },
**Minor:** could get rid of these

2021-07-29 16:42 UTC, mdole commented on src/lib/Scenes/Tag/Tag.tsx
> +  price_range?: string
Maybe we don't need these as well?

2021-07-29 16:42 UTC, mdole commented on src/lib/Scenes/Tag/Tag.tsx
> +  ]
Could we use `<StickyHeaderPage />` instead of `<StickyTabPage />` since we have no tabs for this screen?

2021-07-29 16:42 UTC, mdole commented on src/lib/Scenes/Tag/Tag.tsx
> +})
We generally prefer [styled-components](https://styled-components.com/) over StyleSheet.create these days; this is left over from early code in the app. Suggest refactoring if you have time!

2021-07-29 17:06 UTC, dimatretyak commented on src/lib/Scenes/Tag/Tag.tsx
> +  ) as FilterArtworksInput
I think that passing `medium`, `price_range` and also passing `input` to `QueryRender` is not necessary for `Tag`

2021-07-29 17:19 UTC, dimatretyak commented on src/lib/Components/Tag/TagArtworks.tsx
> +          forSale: true
Do we have to pass the `forSale` parameter?

2021-07-29 17:24 UTC, dimatretyak commented on src/lib/Components/Tag/TagArtworks.tsx
> +          }
Perhaps there is also no need to query `edges` here

2021-07-29 17:27 UTC, dimatretyak commented on src/lib/Components/Tag/About.tsx
> +import { About_tag } from "__generated__/About_tag.graphql"
Is the `About `component used on the `Tag` page?

2021-07-29 17:36 UTC, dimatretyak commented on src/lib/Components/Tag/Header.tsx
> +import { Header_tag } from "__generated__/Header_tag.graphql"
I think it would be better to move the `Header` component to the `src/lib/Scenes/Components` folder

2021-07-30 10:53 UTC, tr-ann commented on src/lib/Components/Tag/About.tsx
> +import { About_tag } from "__generated__/About_tag.graphql"
Hmm, it's seems like description for tags is empty (checked for some tags). I'm not sure description should be displayed for tag. If not I just remove `About` component.

@mdole what do you think?

2021-07-30 11:00 UTC, tr-ann commented on src/lib/Components/Tag/__tests__/Header-tests.tsx
> +  renderWithWrappers(<Header tag={tag as any} />)
The `tag` prop for `Header` has `Header_tag` type which contains `name`, `$fragmentRefs` and other fields received from relay. So to avoid errors like "missing property from type" I just send custom object with `any` type

2021-07-30 12:04 UTC, tr-ann commented on src/lib/Scenes/Tag/Tag.tsx
> +  ]
I think we can use `<StickyHeaderPage />`, but in this case we should move filters tab to `Tag.tsx` and change the structure of the page (I think there will be a lot of changes here). So use  `<StickyTabPage />` is the easiest way to use sticky filter tab it tag page.

Maybe @dimatretyak can add some more description for this

2021-07-30 12:50 UTC, tr-ann commented on src/lib/Components/Tag/About.tsx
> +import { About_tag } from "__generated__/About_tag.graphql"
Update: Tag description is requested for tag page in Force. So I leave `About` component in Tag page

2021-07-30 17:58 UTC, mdole approved these changes
Woohoo, looking good! Let's get it in the beta and see how it feels 😎

2021-07-30 17:58 UTC, merged