feature: Checkbox V3
artsy/eigen pull request #5227
Opened 2021-08-05 15:09 UTC by olerichter00

The type of this PR is: **Feature**

This PR resolves [CX-1701]

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-08-05 15:10 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d3b362352b49cb1234d9b0e56d0c3dcca5a408ae
</p>

2021-08-09 13:59 UTC, olerichter00 commented on src/palette/elements/Checkbox/Checkbox.tsx
> +          {children}
**Note:** Allowing children here for compatibility reasons to V2.

2021-08-16 11:42 UTC, pvinis requested changes
Just one thing, then I think we are good to go!

2021-08-16 11:42 UTC, pvinis commented on src/palette/elements/Checkbox/index.tsx
> +    return <CheckboxV3 {...props} />
could you wrap this in `ThemeV3`? I noticed that this is actually important for cases like this conditional.

2021-08-17 10:05 UTC, olerichter00 commented on src/palette/elements/Checkbox/index.tsx
> +    return <CheckboxV3 {...props} />
Done 👍

2021-08-17 10:27 UTC, pvinis approved these changes

2021-08-17 10:28 UTC, olerichter00 commented
#squashongreen

2021-08-17 10:34 UTC, merged