spec: update tests to use RNTL and add test for delete address
artsy/eigen pull request #5311
Opened 2021-08-20 15:13 UTC by gkartalis

The type of this PR is: **Enhancement**

This PR resolves []

### Description

This PR adds a test to make sure that the delete mutation is called with the correct input after the user presses delete address button.

Also updated the test file to use `@testing-library/react-native`

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- add tests for delete address - gkartalis

</details>

2021-08-20 15:14 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (add tests for delete address - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8710e21d892fdada90405544a2559d77a76689db
</p>

2021-08-20 15:47 UTC, pvinis requested changes

2021-08-20 15:47 UTC, pvinis commented on src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
> +    expect(queryByText("Berlin, 10179")).toBeTruthy()
I think this will always pass?

If this text is not found, query will give `[]`, which is truth, right?

Maybe expect a nonempty array or some other way of testing this.

2021-08-20 15:47 UTC, pvinis commented on src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
> +    expect(createOperation.request.node.operation.name).toEqual("deleteSavedAddressDeleteUserAddressMutation")
nice

2021-08-20 15:52 UTC, gkartalis commented on src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
> +    expect(queryByText("Berlin, 10179")).toBeTruthy()
Just checked it [here](https://callstack.github.io/react-native-testing-library/docs/api-queries/#queryby) `queryByText` returns null and doesn't pass if it doesn't find the result.

`queryAllByText` is the one that returns the array 🤘

2021-08-20 15:53 UTC, pvinis commented on src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
> +    expect(queryByText("Berlin, 10179")).toBeTruthy()
o snap. i misread. sorry!

2021-08-20 15:54 UTC, pvinis approved these changes

2021-08-20 15:54 UTC, merged

2021-08-24 10:18 UTC, gkartalis commented on src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
> +    fireEvent.press(getAllByText("Add New Address")[0])
This was the only weird part of using `testing-library/react-native`.

For some reason (even when I used debug to see the actual component tree) the content of ListEmptyComponent was displayed x2 times and this is why I used  `    fireEvent.press(getAllByText("Add New Address")[0])` to select the first `Add New Address` button.

It looks like it is a bug that I didn't find a related issue on their repo. Maybe it is worth opening an issue for that.