FX-3146 Added All Artists I Follow option counting
artsy/eigen pull request #5372
Opened 2021-09-01 15:47 UTC by anastasiapyzhik

The type of this PR is: **TYPE**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-09-01 15:50 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 334cf2c407ddb973546821e76689db2504abf443
</p>

2021-09-06 11:02 UTC, mdole requested changes
Nice work! We can simplify by getting rid of the code for the filter names in the filter menu, and I left another comment about adjusting the logic for the filter counts. Let me know your thoughts!

2021-09-06 11:02 UTC, mdole commented on src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
> +      }
I think this works OK, but it's also a bit hard to understand at first.

Maybe it would be a bit simpler if we separated the check for `FilterParamName.artistsIFollow`. Something like:

```ts
const allArtistsIFollowSelectedCount = selectedFilters.some(({ paramName }) => paramName === 'artistsIFollow') ? 1 : 0

...

case isArray(paramValue): {
  counts[paramName] = (paramValue as []).length + allArtistsIFollowSelectedCount
}
```

What do you think @anastasiapyzhik? Is that any better?

2021-09-06 12:47 UTC, anastasiapyzhik commented on src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
> +      }
@mdole looking good!

I modified it a bit, seems like there is more code but I think it's easier to read by variables names what's going on.
Do you think it's readable enough?
```
case isArray(paramValue): {
  const isArtistsIFollow = (selectedFilter: FilterData) =>
    selectedFilter.paramName === FilterParamName.artistsIFollow
    
  const allArtistsIFollowSelectedCount = selectedFilters.some(isArtistsIFollow) ? 1 : 0
  
  const countToAdd = paramName === FilterParamName.artistIDs ? allArtistsIFollowSelectedCount : 0

  counts[paramName] = (paramValue as []).length + countToAdd
  break
      }
```

2021-09-06 14:08 UTC, mdole commented on src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
> +      }
@anastasiapyzhik nice, that looks good to me! Thanks for working on it!

2021-09-06 15:25 UTC, anastasiapyzhik commented on src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
> +      }
This logic causes wrong behavior (if both _All Artists I Follow_ and some _artists_ options are selected we get `+1` twice)

So let's only add each entity's _own_ count to current one

```
case paramName === FilterParamName.artistsIFollow: {
  counts.artistIDs = (counts.artistIDs ?? 0) + 1
  break
}
case isArray(paramValue): {
  const isArtistsFilter = paramName === FilterParamName.artistIDs
  const countToAdd = isArtistsFilter ? counts.artistIDs ?? 0 : 0

  counts[paramName] = (paramValue as []).length + countToAdd
  break
}
```

2021-09-08 10:32 UTC, mdole approved these changes
One tiny thing I noticed, otherwise looking great! Assigning back to you to merge when ready @anastasiapyzhik

2021-09-08 10:32 UTC, mdole commented on src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
> +    // expect(extractText(filterScreen.root.findAllByType(OptionListItem)[5])).not.toContain("•")
Any reason this is commented out?

2021-09-08 11:59 UTC, anastasiapyzhik commented on src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
> +    // expect(extractText(filterScreen.root.findAllByType(OptionListItem)[5])).not.toContain("•")
Thank you for the note! Needed to clarify some point about this one and commented it out for a while to continue updating other tests without distraction and successfully forgot to change it

2021-09-08 12:14 UTC, merged