feature: Pill V3
artsy/eigen pull request #5374
Opened 2021-09-01 16:32 UTC by rajsam003

The type of this PR is: Feature

This PR resolves [CX-1695]

### Description

This PR adds the new V3 Pill and uses them depending on the current theme.

![image](https://user-images.githubusercontent.com/17421923/131708921-7594f532-c4d3-4a86-8224-654b305e7b51.png)![image](https://user-images.githubusercontent.com/17421923/131708957-9cf8145a-2077-42e2-a645-b0f7adbb29ae.png)

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Add V3 Pill component (behind feature flag) - rajsam003

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-09-01 16:33 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Add V3 Pill component (behind feature flag) - rajsam003)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 398f5f56f5f66d731155306dee7adef64a37fd12
</p>

2021-09-02 08:46 UTC, gkartalis requested changes

2021-09-02 08:46 UTC, gkartalis commented on src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
> +            <Pill testID="alert-pill" size="xs" rounded m={0.5} key={`filter-label-${index}`}>
Could you remove `rounded` from this Pill? This is supposed to be square according to design. More info can be found on [this slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1630572009268600)
```suggestion
            <Pill testID="alert-pill" size="xs" m={0.5} key={`filter-label-${index}`}>
```

2021-09-02 08:56 UTC, gkartalis commented on src/palette/elements/Pill/Pill.stories.tsx
> +  .add("Text", () => (
🤩

2021-09-02 09:00 UTC, gkartalis commented on src/palette/elements/Pill/Pill.tsx
> +      borderColor={icon || selected ? color("black60") : color("black10")}
According to figma design the inactive color should be "black15"

2021-09-02 09:18 UTC, gkartalis commented on src/palette/elements/Pill/Pill.tsx
> +  selected,
Maybe lets default this to `true` for now in order to have black60 as a borderColor in the case that nothing is passed as selected prop to ensure that it doesn't break the design of `src/lib/Scenes/SavedSearchAlert/Components/Form.tsx`

2021-09-02 09:19 UTC, gkartalis commented on src/palette/elements/Pill/Pill.tsx
> +  const { color, space } = useTheme()
this should be `colorV3` isn't it? 🤔
```suggestion
  const { colorV3, space } = useTheme()
```

2021-09-03 09:53 UTC, olerichter00 requested changes
That looks very good!

Comparing the pills in the app with the Figma design I think the padding on the right and left should be increased.

2021-09-03 10:07 UTC, gkartalis commented
Agree with @olerichter00! after that lets merge it!

2021-09-03 11:42 UTC, gkartalis approved these changes
🚀

2021-09-03 11:44 UTC, gkartalis commented
#squashOnGreen

2021-09-03 12:03 UTC, olerichter00 approved these changes
Thanks for the fix 🙇

2021-09-03 12:03 UTC, merged