fix(PX-4579): show last offer on offer orders page [WIP]
artsy/eigen pull request #5495
Opened 2021-09-22 13:08 UTC by kiryl-zubarau

The type of this PR is: Bugfix

This PR resolves [PX-4579]

### Description

This PR fixes pricing for offer orders. Added last offer and list price values.

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [X] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [X] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [X] I have documented any follow-up work that this PR will require, or it does not require any.
- [X] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [X] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Added last offer and list price on order details page - kirill-zubarau

</details>

2021-09-22 13:10 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Added last offer and list price on order details page - kirill-zubarau)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6071b94572264c85f1946bcad204955bd42b0721
</p>

2021-09-22 16:33 UTC, MounirDhahri approved these changes
LGTM 🎉
Edit: I just noticed the [WIP] at the end of the title after I finished the review 😅

2021-09-23 19:54 UTC, ansor4 requested changes
Sorry for the product requirement change!

2021-09-23 19:54 UTC, ansor4 commented on src/lib/Scenes/OrderHistory/OrderDetails/Components/SummarySection.tsx
> +              List price
Sorry to change up the ticket requirements on you! Per this [slack thread](https://artsy.slack.com/archives/C9ZJYFDNF/p1632406953123800), let's remove the List price line item for offers

2021-09-24 14:38 UTC, ansor4 approved these changes
thanks!

2021-09-24 14:38 UTC, merged