feat: Order History: rename button "View Order" if order is made as "Make offer" [PX-4577]
artsy/eigen pull request #5503
Opened 2021-09-23 12:12 UTC by Serge0n

The type of this PR is: **Feature**

This PR resolves [PX-4577]

### Description

This PR allows changing the `button title` depending on the `order mode`.

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Order History: added "View Offer" title if the order is made as "Make offer"

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

![image](https://user-images.githubusercontent.com/55637696/134504536-f9d198ec-72da-427b-8aea-d637efc0a647.png)

2021-09-23 12:13 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Order History: added "View Offer" title if the order is made as "Make offer")
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ac4dacbb3a4570045fe0f859d3586aef47a75ce1
</p>

2021-09-23 21:59 UTC, ansor4 approved these changes
~Have a question for @jbeyen but otherwise looks good!~

EDIT: Just got an update from joh on slack in this [thread](https://artsy.slack.com/archives/C01QHJSUVU7/p1631721185038100), let's check for the order state as well!

2021-09-23 21:59 UTC, ansor4 commented on src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
> +              {order?.mode === "OFFER" ? "View Offer" : "View Order"}
I think based off of this [message](https://artsy.slack.com/archives/C01QHJSUVU7/p1631883680067600?thread_ts=1631721185.038100&cid=C01QHJSUVU7) we would want to check for `order.state` for accepted offers as well.

2021-09-23 22:06 UTC, ansor4 requested changes
Let's check for `order.state` is `PENDING` to show this, and we're good to go!

2021-09-24 14:41 UTC, ansor4 approved these changes
Ace!

2021-09-24 14:41 UTC, merged