fix(PX-4402): use small buttons
artsy/eigen pull request #5504
Opened 2021-09-23 12:30 UTC by kiryl-zubarau

The type of this PR is: Bugfix

This PR resolves [PX-4402]

### Description

This PR fixes text splitting for action buttons on the order history page

### PR Checklist (tick all before merging)

- [X] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [X] I have tested my changes on **iOS** and **Android**.
- [X] I have added tests for my changes, or my changes don't require testing, or I have included a link to a separate Jira ticket covering the tests.
- [X] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [X] I have documented any follow-up work that this PR will require, or it does not require any.
- [X] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [X] I have added a changelog entry below or my changes do not require one.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- fixes text splitting for action buttons - kirill-zubarau

</details>

Before
![image](https://user-images.githubusercontent.com/79979820/134506672-5349e3fd-440b-4c06-b465-2c8a36279132.png)

Now
![image](https://user-images.githubusercontent.com/79979820/134506530-d0592e13-6075-452a-817c-22aa8f0ed663.png)

2021-09-23 12:31 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (fixes text splitting for action buttons - kirill-zubarau)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eb857f19662fc110b679409ad870dcd656523512
</p>

2021-09-23 20:05 UTC, ansor4 requested changes
Update for different direction in design 🙏 🙏

2021-09-23 20:05 UTC, ansor4 commented on src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
>            <Box width="50%" paddingRight={0.5}>
After consulting with Gideon, we landed on two full width buttons! Thanks for bearing with the back and forth!

https://artsy.slack.com/archives/C9ZJYFDNF/p1632406953123800

2021-09-24 14:40 UTC, ansor4 approved these changes
🎉

2021-09-24 14:40 UTC, ansor4 commented
@kiryl-zubarau looks like there's a merge conflict, otherwise good to go!

2021-09-24 14:41 UTC, MounirDhahri approved these changes
⛴

2021-09-24 15:06 UTC, merged