feat(FX-3521): Disable search pills
artsy/eigen pull request #5752
Opened 2021-11-03 16:40 UTC by anastasiapyzhik

The type of this PR is: **Feature*

This PR resolves [FX-3521]

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- disable search pills when loading and when there is no results - anastasiapyzhik

</details>

2021-11-03 16:43 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (disable search pills when loading and when there is no results - anastasiapyzhik)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9125990b74f3f7a2036fe110ec685cd25f15db24
</p>

2021-11-05 14:37 UTC, gkartalis commented on src/lib/utils/useAlgoliaIndices.ts
> +  const [loading, setLoading] = useState<boolean>(false)
**suggestion:** I think we can avoid explicitly declaring the type here

2021-11-05 14:37 UTC, gkartalis commented on src/lib/Scenes/Search2/Search2.tsx
> +      })
**question:** Won't that result in changing the type of all the pills to `type: "algolia"`?

2021-11-05 14:47 UTC, gkartalis reviewed
First of all great job generally, I have some thoughts though:

 1. From a users prespective I am a bit confused when I have a query like Banksyaw (that doesn't have any results on the TOP and Artworks pill) to see these pills enabled without having results.
 2. I don't really love the experience of disabling the pills while we are querying to see if the pills have results or not (feels a bit flaky imo). Left a comment to hear your opinion [here](https://github.com/artsy/eigen/pull/5752/files#r743728735) in the code

I've included a video of my experience.

https://user-images.githubusercontent.com/21178754/140528472-3b796d25-3fa3-423b-a8f0-71c7e8a016a1.mp4

On the bright side, the pills look amazing like this!

2021-11-05 14:51 UTC, gkartalis commented on src/lib/Scenes/Search2/components/SearchPills.tsx
> +            accessibilityState={{ selected, disabled: disabledWithStyles || selected }}
😍 Thank you so much for adding the a11yState here! 🚀

2021-11-05 14:57 UTC, gkartalis commented on src/palette/elements/Pill/Pill.stories.tsx
> +      <Pill selected>Selected</Pill>
also thanks for removing the redundant `[NEW]` here

2021-11-05 15:18 UTC, anastasiapyzhik commented on src/lib/Scenes/Search2/Search2.tsx
> +      })
Nope. This processes indices gotten from [here](https://github.com/artsy/eigen/blob/9d655114555d00b09ffe1a0a15063ac6c93408fd/src/lib/Scenes/Search2/Search2.tsx#L155)

2021-11-05 15:34 UTC, anastasiapyzhik commented on src/lib/utils/useAlgoliaIndices.ts
> +  return { loading, indicesInfo, updateIndicesInfo }
The point of making pills disabled is to make it not possible for user to land on view and see that there are no results, you won't likely notice that but without disabling pills users with slow connection will have an experience like this 👇🏻

https://user-images.githubusercontent.com/44819355/140536082-64b01004-a5ee-41d2-bf90-9449e5dea75f.mp4

2021-11-05 15:59 UTC, gkartalis commented on src/lib/utils/useAlgoliaIndices.ts
> +  return { loading, indicesInfo, updateIndicesInfo }
I meant something like this:

https://user-images.githubusercontent.com/21178754/140540315-6a420be0-d1d3-4463-8394-af27631ee74e.mov

 but this is not optimal either :thinking: So fine by my side 🤘, let's hear some feedback from design (after merging this)!

2021-11-05 15:59 UTC, gkartalis approved these changes

2021-11-05 16:05 UTC, anastasiapyzhik commented on src/lib/utils/useAlgoliaIndices.ts
> +  return { loading, indicesInfo, updateIndicesInfo }
I've already [asked](https://artsyproduct.atlassian.net/browse/FX-3521?focusedCommentId=43276) Jonathan, and seems like current behavior is OK for him :)

2021-11-08 10:39 UTC, dimatretyak approved these changes

2021-11-08 10:41 UTC, gkartalis approved these changes

2021-11-08 10:41 UTC, gkartalis submitted a review, later dismissed

2021-11-11 10:27 UTC, pvinis requested changes
very nice. i added some comments that i think will make the code nicer. what do you think?

2021-11-11 10:27 UTC, pvinis commented on src/lib/Scenes/Search2/components/SearchPills.tsx
> +  loading: boolean
maybe lets make this optional? seems like a cleaner "api".

2021-11-11 10:27 UTC, pvinis commented on src/palette/elements/Pill/Pill.tsx
> +  Enabled2 = "enabled2",
Maybe something more descriptive like `EnabledImprovedFlag` or something else would be more clear, and it would make it easier to remove the old `Enabled` once the flag is gone.

2021-11-11 10:27 UTC, pvinis commented on src/lib/Scenes/Search2/types.ts
> +  disabled: boolean
optional again?

2021-11-11 10:27 UTC, pvinis commented on src/lib/Scenes/Search2/components/SearchPills.tsx
> +            accessibilityState={{ selected, disabled }}
nice!

2021-11-11 10:27 UTC, pvinis commented on src/lib/Scenes/Search2/components/SearchPills.tsx
> +  loading: boolean
optional?

2021-11-11 14:43 UTC, pvinis approved these changes

2021-11-12 09:10 UTC, dimatretyak approved these changes

2021-11-12 12:48 UTC, merged