feat: Track screen reader status and preferred theme of users
artsy/eigen pull request #5833
Opened 2021-11-26 14:07 UTC by gkartalis

The type of this PR is: **Enhancement**

This PR resolves []

### Description

- introduces tracking for users that have screen readers enabled on their devices.
- replaces tracking theme preferences for iOS only to both iOS and android

|iOS|Android|
|---|---|
|ios|android|

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- track screen reader status and theme status - gkartalis

</details>

2021-11-26 14:08 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (track screen reader status and theme status - gkartalis)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 98f0533fb84e9db92765485552024a5b231f3536
</p>

2021-12-01 15:52 UTC, gkartalis commented on src/lib/utils/track/constants.ts
>    FreshInstall: "first user install",
notice that [here](https://github.com/artsy/eigen/pull/5833/files#diff-dd9db7bec93b7bd1368805ddd7e76e84917db6b0393de2b1661425ec25c40cefL72) we are using the FreshInstall event ONLY in android. Is there a reason for that? Do we want to also track iOS or I am missing some context?

2021-12-02 20:39 UTC, pvinis commented on src/lib/utils/track/constants.ts
>    FreshInstall: "first user install",
if i remember correctly, we had a different one for ios.

yep, here it is https://github.com/artsy/eigen/blob/b78d277f1b6d545d4703eac66bd77b1ddba003c2/Artsy/App/ARAnalyticsConstants.m#L12.

we could totally remove the native one on ios and use the ts one on both platforms.

2021-12-02 20:39 UTC, pvinis commented on src/lib/utils/track/constants.ts
> -  UserInterfaceStyle: {
👋

2021-12-02 20:40 UTC, pvinis commented on src/lib/utils/usePreferredThemeTracking.tests.ts
> +    expect((postEventToProviders as jest.Mock).mock.calls[0]).toMatchInlineSnapshot(`
🙌

2021-12-02 20:45 UTC, pvinis commented on src/lib/utils/usePreferredThemeTracking.ts
> +    postEventToProviders(tracks.getUserPreferredTheme(colorScheme))
we talked about this on our meeting, i still think having `SegmentTrackingProvider.identify?.(` makes more sense than just `postEventToProviders`, because that way this context of `user_preferred_theme` stays with the user.

see here with the old name:
<img width="555" alt="Screenshot 2021-12-02 at 15 43 52" src="https://user-images.githubusercontent.com/100233/144500210-9899c41c-346a-4c57-b918-69e1e71e334a.png">

2021-12-02 20:45 UTC, pvinis commented on src/lib/utils/useScreenReaderTracking.ts
> +    postEventToProviders(tracks.trackScreenReaderStatus(isScreenReaderEnabled))
same here

2021-12-02 20:46 UTC, pvinis requested changes
I commented about the `identify` call. i think it makes more sense to go that way. waht do you think?

2021-12-03 09:39 UTC, MounirDhahri submitted a review, later dismissed
Nice to see PRs coming from the practice 🕺 I left few minor comments and we should be clear to go.

2021-12-03 09:39 UTC, MounirDhahri commented on src/lib/utils/usePreferredThemeTracking.ts
> +    postEventToProviders(tracks.getUserPreferredTheme(colorScheme))
I think we don't necessarily need it since using the anonymous id we will be able to trace it back to the user, unless we need the user id for something

2021-12-03 09:39 UTC, MounirDhahri commented on src/lib/utils/usePreferredThemeTracking.ts
> +    user_interface_style: preferredTheme,
**issue:** would you mind adding an interface for the event in cohesion

2021-12-03 09:39 UTC, MounirDhahri commented on src/lib/utils/usePreferredThemeTracking.ts
> +    user_interface_style: preferredTheme,
**though:** I also believe the platform can be useful here

2021-12-03 09:39 UTC, MounirDhahri commented on src/lib/utils/useScreenReaderTracking.ts
> +      setIsScreenReaderEnabled(isEnabled)
**thought:** I am not sure why we need to use the state here. Can't we maybe do
```suggestion
      postEventToProviders(tracks.trackScreenReaderStatus(isEnabled))
```
and not use a state

2021-12-03 10:25 UTC, gkartalis commented on src/lib/utils/useScreenReaderTracking.ts
> +      setIsScreenReaderEnabled(isEnabled)
Good point. The initial approach was without `useState`. The reason I used state here is because if I don't (and my code being like this):
```suggestion
  export const useScreenReaderTracking = () => {
    useEffect(() => {
      const getScreenReaderStatus = async () => {
        const isEnabled = await AccessibilityInfo.isScreenReaderEnabled()
        return isEnabled
      }

      getScreenReaderStatus()
      postEventToProviders(tracks.trackScreenReaderStatus(getScreenReaderStatus()))
    }, [])
  }
```
I get the following ts error `Argument of type 'Promise<boolean>' is not assignable to parameter of type 'boolean'.ts(2345)`

2021-12-03 10:42 UTC, MounirDhahri commented on src/lib/utils/useScreenReaderTracking.ts
> +      setIsScreenReaderEnabled(isEnabled)
ah yeah. it's ts sense/non-sense  but I guess it's understandable in case the promise fails

2021-12-03 14:09 UTC, gkartalis commented on src/lib/utils/usePreferredThemeTracking.ts
> +    user_interface_style: preferredTheme,
> **issue:** would you mind adding an interface for the event in cohesion

Will do that :) 
> **though:** I also believe the platform can be useful here

I can add that as well although the event in segment gives us the following data that also includes device info like id. manufacturer, model, name and type so not sure if we really need to add the platform �
![Screenshot 2021-12-03 at 15 06 49](https://user-images.githubusercontent.com/21178754/144616096-61ce5c92-460a-469b-84ac-dac9ba6bc931.png)
�

2021-12-03 14:36 UTC, gkartalis commented on src/lib/utils/usePreferredThemeTracking.ts
> +    postEventToProviders(tracks.getUserPreferredTheme(colorScheme))
Hmmm, we will be able to trace it back to the user **for sure** since we have all the data.
The thing that @pvinis says though is that if we track it with `SegmentTrackingProvider.identify?.` we will have it under `traits` property in every event of the app it will "follow" the user under `traits`. 
Not sure which of the two we prefer.

I am thinking that it might be better for consistency with the previous collected data to continue having the `user inteface style` under traits like we had it before and maybe do the same with the `screen_reader_enabled`?

What do you think?

2021-12-03 15:10 UTC, pvinis commented
I think its best if we add a custom thing in cohesion. Something that allows us to send like
```
{
  action: "custom-track",
  key: "screen-reader",
  value: "whatever the value is",
}
```
then we (as devs or teams) we can track things that are not needed in cohesion, and we can freely and easily add or remove these when we want, without needed extra changes in cohesion or bothering the data team.

2021-12-03 15:12 UTC, pvinis commented on src/lib/utils/useFreshInstallTracking.ts
> +    SegmentTrackingProvider.postEvent({ name: AnalyticsConstants.FreshInstall })
better use the `postEventToProviders` here, so it makes suse we send to anything we might use.

2021-12-03 15:14 UTC, MounirDhahri commented on src/lib/utils/usePreferredThemeTracking.ts
> +    postEventToProviders(tracks.getUserPreferredTheme(colorScheme))
I don't oppose this if we were using previous data, but I am not sure if we were using it before. Otherwise, yes that's a good point

2021-12-03 15:16 UTC, MounirDhahri commented on src/lib/utils/usePreferredThemeTracking.ts
> +    user_interface_style: preferredTheme,
aha we have the `os` there already. I didn't know that, in other areas of the app we are tracking the platform, good to know it's avoidable. we usually have it as a separate value for the sake of simplicity, because who knows what the "os" name will be in a browser, will it be "web", "firefox", "ubuntu" etc... but it's not important here since this is not a browser 😄

2021-12-10 10:51 UTC, pvinis commented on src/lib/utils/useScreenReaderTracking.ts
> +      setIsScreenReaderEnabled(isEnabled)
I agree with getting rid of the state.

maybe try to move the thing in a try-catch, so if you get a boolean you postevent, if you get an error you send nothing or send a "N/A" or something.

2021-12-10 10:52 UTC, pvinis approved these changes
I think we could get rid of the state, but I'll approve so I don't block this. we can change it later too.

2021-12-10 14:50 UTC, merged