Chore: Refactor Add My Collection Artwork form from Modal to Individual Pages
artsy/eigen pull request #5851
Opened 2021-12-02 14:04 UTC by lordkiz

The type of this PR is: **TYPE**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-12-02 14:05 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 238ed8fb82b2b815682651700c7cbe50b3faa423
</p>

2021-12-03 20:38 UTC, brainbicycle commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
>  export type ArtworkFormModalScreen = {
**thought:** maybe we should rename if no longer a modal?

2021-12-03 20:39 UTC, brainbicycle commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
> +type MyCollectionArtworkFormModalProps = { onSuccess: () => void } & (
same comment as above

2021-12-03 20:40 UTC, brainbicycle commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
> +        </Stack.Navigator>
✨

2021-12-03 20:42 UTC, brainbicycle commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
> +      <FancyModalHeader
similar, maybe if we are using this for more than just modals we should name it something like `NavigationHeader`?

2021-12-03 20:44 UTC, brainbicycle commented on src/lib/store/PropsStore.tests.ts
> +    it("sets pendingProps", () => {
nitpick: would be nice to be a little more descriptive for people who come to this module and aren't as familiar
```suggestion
    it("stores and retrieves props for a module", () => {
```

2021-12-03 20:44 UTC, brainbicycle commented on src/lib/store/PropsStore.tests.ts
> +    it("overwrites whatever pending props", () => {
```suggestion
    it("overwrites whatever props already exist for a module", () => {
```

2021-12-03 20:45 UTC, brainbicycle commented on src/lib/store/PropsStore.tests.ts
> +    it("callback with updated props", () => {
```suggestion
    it("calls callback with updated props", () => {
```

2021-12-03 20:46 UTC, brainbicycle commented on src/lib/store/PropsStore.tests.ts
> +      const moduleName = "banananana"
🍌

2021-12-03 20:48 UTC, brainbicycle requested changes
🙌 
Overall this looks great to me, some minor requests on naming specifically if things are no longer being used only for modals or aren't modals can we remove that from the name, and then some nitpicks around test descriptions but otherwise looks great! Thanks

2021-12-06 09:18 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
>  export type ArtworkFormModalScreen = {
@brainbicycle I thought to but this will make the PR large and difficult to review. I will do it anyway.

2021-12-07 09:22 UTC, rajsam003 approved these changes
LGTM 👍🏽

2021-12-07 09:25 UTC, olerichter00 reviewed
This is great work! 🙌  I've added a couple of questions and ideas.

2021-12-07 09:25 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
> +                  }, 50)
**(question):** Why do we need a timeout for `onDelete`?

2021-12-07 09:25 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +            }, 500)
**(question)**: Is there any way to remove the form data inside an effect instead? I don't think using a timer with an arbitrary timeout is a good idea.

2021-12-07 09:25 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx
> +                }, 50)
**(question):** Why do we need a timeout here?

2021-12-07 09:25 UTC, olerichter00 commented on src/lib/store/PropsStore.tests.ts
> +      const moduleName = "banananana"
🍌 🍌 🍌

2021-12-07 09:25 UTC, olerichter00 commented on src/palette/elements/Input/Input.tsx
> +      }
I don`t really understand how we exceed the `maxLimit` for listeners in the form. When I look at the form, I see less than 20 inputs. Are you sure that the reason for the warning is not due to an error?

2021-12-07 13:39 UTC, pvinis commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
I like this idea

2021-12-07 13:42 UTC, pvinis commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
> +        onRightButtonPress={isFormDirty() || __TEST__ ? () => route.params.clearForm() : undefined}
this has caused problems in the sticky header too. I agree we should avoid it.

2021-12-07 14:01 UTC, lordkiz commented on src/lib/AppRegistry.tsx
> +      viewProps: { ...this.props.viewProps, ...propsStore.getPropsForModule(this.props.moduleName) },
@olerichter00 I see. However, PropsStore only hold props that'd be passed around in react native. If I name a react native props viewProps, that would imply that these are props meant for only react native Views. Here each module is registered and treated as native views, so it makes sense to name whatever set of props specific to that native view viewProps. If you for example write `propsStore.getViewPropsForModule` outside of `AppRegistry.tsx`, it becomes really really confusing.

2021-12-07 14:06 UTC, lordkiz commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
@olerichter00 Nice idea. Can we have multiple routes match the same module?

2021-12-07 14:20 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
> +                  }, 50)
@olerichter00 I don't want to popToRoot while root (in this case MyCollection.tsx) is still being refreshed. You don't think it is important?

2021-12-07 14:27 UTC, brainbicycle submitted a review, later dismissed

2021-12-07 14:28 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
That should work but why do we need multiple routes for the same module?

2021-12-07 14:28 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
> +                  }, 50)
What happens if we remove the timeout?

2021-12-07 14:29 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +            }, 500)
@olerichter00  Inside an effect? I don't understand. 
Also, reseting the form will trigger a reload if we have not popped this screen yet. Also we want to avoid reseting the form as we are popping the view. Resetting before popping the view will just cause an unnecessary rerender. Why is using a timeout bad in this case?

2021-12-07 14:34 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +    if (!currentRoute?.name || currentRoute?.name === "ArtworkForm") {
@olerichter00 Nein. `MyCollectionArtworkForm` just holds the Navigator, the routes are from the stack screens. ArtworkForm is the first screen of this Navigator. Usually before any navigation, currentRoute will be nil, that's why I did `!currentRoute?.name ...`

2021-12-07 14:37 UTC, lordkiz commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
@olerichter00 for `my-collection/artworks/edit`

2021-12-07 14:39 UTC, lordkiz commented on src/lib/Scenes/Partner/Components/PartnerShows.tests.tsx
> +import { PartnerShowsTestsQuery, PartnerShowsTestsQueryRawResponse } from "__generated__/PartnerShowsTestsQuery.graphql"
Haha. These are from George's test fix. I think my Artsy vscode settings reformatted them or something.

2021-12-07 14:46 UTC, lordkiz commented on src/palette/elements/Input/Input.tsx
> +      }
@olerichter00 EventEmitter will continue to add listeners for a particular event until it gets to 10, then it will start showing warnings even though it will continue to add these events listeners. In forms like add artwork form more than 10 'clear' event listeners will be added so we'd get warnings all over the place. We don't ever need more than 1 clear event at any time.

2021-12-07 14:49 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
> +        onRightButtonPress={isFormDirty() || __TEST__ ? () => route.params.clearForm() : undefined}
@olerichter00 @pvinis thanks. I agree, it doesn't look nice. How do you test clearForm() in this case if it is dependent on isFormDirty() ?

2021-12-07 14:59 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
> +                  }, 50)
@olerichter00 occassionally you might see the artwork that would be deleted when you arrive at the root, followed by a jumpy MyCollection page as it is refreshed. It doesn't look bad though, it animates gracefully. I guess I can remove these timeouts. But I'd rather not see the refresh happening in my opinion.

2021-12-07 15:47 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
This would then probably be `my-collection/artworks/:artworkID/edit` and use the same form, yes 👍

2021-12-07 15:53 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +            }, 500)
I was thinking about using the [useEffect cleanup function](https://blog.logrocket.com/understanding-react-useeffect-cleanup-function/).

2021-12-07 15:56 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
> +        onRightButtonPress={isFormDirty() || __TEST__ ? () => route.params.clearForm() : undefined}
Can you make the form dirty to test it?

2021-12-07 15:59 UTC, olerichter00 commented on src/palette/elements/Input/Input.tsx
> +      }
At which point do we add these events? Isn't this the problem we want to solve instead?

2021-12-07 16:57 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +            }, 500)
Cleanup yeah. Why didn't I think of that? 👍

2021-12-07 17:01 UTC, lordkiz commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
So we'd be passing an id that we'll never use? 🤔

2021-12-07 17:03 UTC, lordkiz commented on src/palette/elements/Input/Input.tsx
> +      }
This ☝️ is the point we add the event listener.

2021-12-08 09:41 UTC, olerichter00 commented on src/palette/elements/Input/Input.tsx
> +      }
Hmm, but looking at the code the event listener is added once the Input is mounted and then it is removed again once the input is unmounted. How can the clear event be added multiple times for one `Input` component?

```
useEffect(() => {
      inputEvents.addListener("clear", localClear)
      return () => {
        inputEvents.removeListener("clear", localClear)
      }
    }, [])
```

2021-12-08 09:43 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +    if (!currentRoute?.name || currentRoute?.name === "ArtworkForm") {
Ok, can you add a comment to explain this in the code (for people like me who don't understand it ;))?

2021-12-08 09:44 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
If we edit an artwork we would need the ID of the artwork to know which to edit, right?

2021-12-08 09:45 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
> +                  }, 50)
I would remove it. Adding these timeouts can always lead to unpredictable behaviour.

2021-12-08 10:53 UTC, lordkiz commented on src/palette/elements/Input/Input.tsx
> +      }
Each Input will add a `clear` event listener when it mounts. That's why in a long form with many Inputs you can end up adding so many. Listeners are not local to the component that added them. That's why you remove them when you unmount. Listeners can continue to exist even after the component that added them is destroyed.

2021-12-08 11:21 UTC, olerichter00 commented on src/palette/elements/Input/Input.tsx
> +      }
> That's why you remove them when you unmount. Listeners can continue to exist even after the component that added them is destroyed.

Doesn't this mean that the listener will be removed when the component is unmounted? Maybe you can create an example that reproduces the issue and we can see how to fix it. Adding `if (!inputEvents.listeners("clear").length)` won't work because it brings back the bug that has been fixed in https://github.com/artsy/eigen/pull/5681 .

2021-12-08 11:23 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +    if (!currentRoute?.name || currentRoute?.name === "ArtworkForm") {
Oh, this is obvious. You are just confusing the Navigator for screens. This page just holds the Navigator that holds the screens. React-navigation by default will use the first screen you defined in the Navigator as the initial screen which in this case is ArtworkForm. Before we navigate within the Navigator, currentRoute can be null (remember our navigation to this Navigator on ios is from Native pushView, while on android this Navigator is nested inside NavStack.tsx)

2021-12-08 11:35 UTC, lordkiz commented on src/lib/Scenes/MyCollection/MyCollection.tsx
> +                  navigate("my-collection/add-my-collection-artwork", {
Not necessarily. We already have the artwork, and can just pass it to the component. No need to refetch it. But there is no harm in adhering to the standards of Restful routes even though we pass the artwork for the sake of convenience. It is much neater.

2021-12-08 12:14 UTC, lordkiz commented on src/palette/elements/Input/Input.tsx
> +      }
@olerichter00 It will not bring back that bug. The Input in Search Page will register a new event listener for clear if the event listener is not already registered. So no issues here.

2021-12-08 12:17 UTC, lordkiz commented on src/palette/elements/Input/Input.tsx
> +      }
> Doesn't this mean that the listener will be removed when the component is unmounted?
Yes, but a 100 Inputs will add 100 listeners for the same event

2021-12-08 13:49 UTC, lordkiz commented on src/palette/elements/Input/Input.tsx
> +      }
@olerichter00 Fixed the bug where unmounted components prevent clear from firing. This is apparently because the event listener was using an anonymous function as a callback. Changing it to a named function should allow any instance of Input to be able to receive clear event and clear without necessarily registering a new event listener.

2021-12-08 15:03 UTC, olerichter00 commented on src/palette/elements/Input/Input.tsx
> +      }
I still get the same bug with your current changes. I created a [code sandbox](https://codesandbox.io/s/js-playground-forked-u2nk4?file=/src/index.js) with a simplified example to explain why we need to add an event listener for every input.

2021-12-09 12:14 UTC, olerichter00 commented on src/palette/elements/Input/Input.tsx
> +      shouldAddListenerForClear = true,
Why not default to `false` since we just need the clear listener in one place in the app (Search Screen)?

```suggestion
      addClearListener = false,
```

2021-12-10 10:34 UTC, lordkiz commented on src/palette/elements/Input/Input.tsx
> +      shouldAddListenerForClear = true,
I didn't know we needed it only in one place. It definitely should default to false. 👍

2021-12-10 10:42 UTC, olerichter00 submitted a review, later dismissed
🚀

2021-12-10 10:57 UTC, olerichter00 approved these changes

2021-12-10 10:57 UTC, olerichter00 commented
#squashongreen

2021-12-10 11:47 UTC, merged