chore: adopt inclusive language
artsy/eigen pull request #5869
Opened 2021-12-08 11:37 UTC by MounirDhahri

The type of this PR is: **chore**

This PR resolves https://github.com/artsy/eigen/issues/5866
cc @kathytafel 

### Description

- [x] update cocoa lumberjack to 3.7.1 
- [x] /.mention-bot
- [x] /tslint.json

___

_Since our last cocoa lumberjack was to fix an issue with the city guide, I tested it again in the simulator and it's working properly. I will have to test that again once we release a new beta._

![Group 3 (2)](https://user-images.githubusercontent.com/11945712/145201782-cceeb9b6-cbc2-4f49-9f80-f028887e792c.png)

_The new renamed tslint-rule is also working properly_

<img width="1507" alt="Screenshot 2021-12-08 at 12 24 13" src="https://user-images.githubusercontent.com/11945712/145201963-45e6b3ba-0072-427e-bd2a-0c261bfcc85c.png">

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Adopt inclusive language - mounir

</details>

2021-12-08 11:38 UTC, MounirDhahri commented on patches/tslint+5.14.0.patch
> ++  apply(sourceFile: ts.SourceFile): Lint.RuleFailure[]
sorry for the big diff here, prettier just removed spaces

2021-12-08 11:41 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (Adopt inclusive language - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8c072c69fa76be57f7409c358a5b33f73ce22d83
</p>

2021-12-08 21:05 UTC, brainbicycle approved these changes

2021-12-09 20:43 UTC, pvinis requested changes
mostly I want to see the unformatted diff, and go from there.

2021-12-09 20:43 UTC, pvinis commented on .mention-bot
> -  "userBlacklist": ["1aurabrown"]
why was this there?

2021-12-09 20:43 UTC, pvinis commented on patches/tslint+5.14.0.patch
> ++  apply(sourceFile: ts.SourceFile): Lint.RuleFailure[]
in vscode you can "save without formatting". definitely do that so the diff becomes manageable.

2021-12-09 20:43 UTC, pvinis commented on HACKS.md
> +Once tslint updates the naming of their `import-blacklist` plugin to be inclusive. But since RIP tslint, this is likely to stay for a while until we adopt eslint
even though I like this PR idea, I think having a patch for taking for their "API" is a a bit too much to maintain. I look forward to the smaller patch diff to see if that is smaller. if it turns out it's still huge, I think we should just keep the tslint out of this PR and just get this to motivate us to move to eslint sooner.

2021-12-10 11:36 UTC, MounirDhahri commented on HACKS.md
> +Once tslint updates the naming of their `import-blacklist` plugin to be inclusive. But since RIP tslint, this is likely to stay for a while until we adopt eslint
I think that makes sense as well. we will probably use an other package once we go with eslint. I will revert this change

2021-12-10 11:45 UTC, pvinis commented on .mention-bot
> -  "userBlacklist": ["1aurabrown"]
googling for mention-bot, j see that it was so that this user is not suggested for reviews.

do we even have mention-bot in eigen? I've never seen a comment suggesting users. maybe let's get rid of this file? something for practice to chat about.

2021-12-10 12:20 UTC, MounirDhahri commented on .mention-bot
> -  "userBlacklist": ["1aurabrown"]
yes this makes sense, I will remove the bot as it's no longer used

2021-12-10 14:24 UTC, kathytafel commented
I'll let the team decide how to proceed here - if changing linters is a big chore, then let's not do that now, but let's do capture that work on the RFC/notion/eigen backlog. Prefer future proofing whenever we can. Let's make sure that linter change happens within 6 months.

2021-12-13 11:42 UTC, pvinis approved these changes

2021-12-13 11:42 UTC, merged