Feat: (cx-2166) my collection image carousel
artsy/eigen pull request #5876
Opened 2021-12-10 10:26 UTC by lordkiz

The type of this PR is: **TYPE**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-12-10 10:27 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 78e75439a795535827a009708a94019b172ae1ab
</p>

2021-12-27 16:13 UTC, lordkiz commented on src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
> +        // TODO:- Handling of './' paths
Is this even a TODO? `./` will never be local image on a user's device 🤔

2021-12-27 16:42 UTC, olerichter00 commented on src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
> +        // Ignore android's assets:// path
Does this work on Android then?

2021-12-27 17:05 UTC, olerichter00 reviewed
The code looks good to me! 

I just wonder if the image carousel isn't supposed to be placed on the [edit artwork screen](https://github.com/artsy/eigen/blob/5705a8be61a60cf6274d301568175f89149cb95d/src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx#L21) (see screenshots in [CX-1866](https://artsyproduct.atlassian.net/browse/CX-1866) )🤔

2021-12-28 09:07 UTC, lordkiz commented on src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
> +        // Ignore android's assets:// path
@olerichter00 assets on android are treated differently. It doesn't include file extensions, doesn't look like url like. Moreover users will never have anything in assets:// as these contain dev and app assets. If devs want to use assets directly in opaqueimageview then they must be deliberate and `require()`. Comment is so devs know we are handling this now and it is not a use case for us.

2021-12-28 10:22 UTC, lordkiz commented
> I just wonder if the image carousel isn't supposed to be placed on the [edit artwork screen](https://github.com/artsy/eigen/blob/5705a8be61a60cf6274d301568175f89149cb95d/src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx#L21) (see screenshots in [CX-1866](https://artsyproduct.atlassian.net/browse/CX-1866) )🤔

We can absolutely use the ImageCarousel for Edit screens. But from the screenshots it appears the next image is expected to be slightly visible from the side as opposed to ImageCarousel where images are visible one at a time. A simple Horizontal Flatlist can be used to achieve this if we cannot reuse ImageCarousel there.

2021-12-28 10:39 UTC, olerichter00 commented
> > I just wonder if the image carousel isn't supposed to be placed on the [edit artwork screen](https://github.com/artsy/eigen/blob/5705a8be61a60cf6274d301568175f89149cb95d/src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx#L21) (see screenshots in [CX-1866](https://artsyproduct.atlassian.net/browse/CX-1866) )🤔
> 
> We can absolutely use the ImageCarousel for Edit screens. But from the screenshots it appears the next image is expected to be slightly visible from the side as opposed to ImageCarousel where images are visible one at a time. A simple Horizontal Flatlist can be used to achieve this if we cannot reuse ImageCarousel there.

Sorry, maybe my comment was not clear. Looking at the Figma design, I cannot see the carousel on the artwork detail screen (like it is implemented in this PR) but on the screen that shows the artwork form. So I was wondering if it is intended that this PR implements the carousel on the artwork detail screen but not on the screen showing the form.

2021-12-28 10:40 UTC, olerichter00 commented on src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
> +        // Ignore android's assets:// path
Maybe it is a good idea to add why we are ignoring android's `assets://` path in the comment then.

2021-12-28 10:46 UTC, lordkiz commented
> Sorry, maybe my comment was not clear. Looking at the Figma design, I cannot see the carousel on the artwork detail screen (like it is implemented in this PR) but on the screen that shows the artwork form. So I was wondering if it is intended that this PR implements the carousel on the artwork detail screen but not on the screen showing the form.

@olerichter00 Oh I see. Sorry we later agreed to use it in the details screen. https://artsy.slack.com/archives/C01B2P6LJUU/p1638978795097900

2021-12-28 10:57 UTC, lordkiz commented on src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
> +        // Ignore android's assets:// path
```suggestion
        // Ignore android's assets:// path (This is because using assets:// in OpaqueImageView is not a use case for us now.)
```

2021-12-28 11:18 UTC, olerichter00 submitted a review, later dismissed

2021-12-30 20:06 UTC, brainbicycle commented on src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
> +  url: string
kind of confused by this type, we are omitting the fields and then redefining below? is that just to make typescript happy?

also `ProcessedImageDescriptor` in this context makes me think of processed by gemini, maybe something like `OmniImageDescriptor` since in can be both local or remote? although maybe I am misunderstanding the point of the type

2021-12-30 20:14 UTC, brainbicycle commented on src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselPaginationIndicator.tsx
> +  )
✨ Nice!

2021-12-30 20:21 UTC, brainbicycle commented on src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
> +  const ImagesToDisplayCarousel = isDisplayingLocalImages ? ImageCarousel : ImageCarouselFragmentContainer
breadcrumb for Brian

2021-12-30 21:17 UTC, brainbicycle commented on src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
> +    if (hasImagesStillProcessing(defaultImage, images)) {
there is a slight problem here with the case where the user edits the artwork and adds an image, we are clearing out local images for simplicity here but the `hasImagesStillProcessing` will return true and there will be no local images so the user is going to see the fallback image even though we have valid processed images.

Think for simplicities sake for the time being we should just check if the main image is still processing and only use local images in that case, but we might want to have more robust logic here eventually, e.g support showing both local and remote images in carousel or showing a placeholder view for processing images in carousel.

```suggestion
   if (!isImage(defaultImage) || imageIsProcessing(defaultImage, "normalized")) {
```

2021-12-30 21:19 UTC, brainbicycle requested changes
minor change request for the add case but otherwise looks great!

2022-01-03 07:21 UTC, lordkiz commented on src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
> +  url: string
@brainbicycle Those fields were optional in ImageDescriptor. Looks like Pick<ImageDescriptor, 'deepzoom'> would be a lot cleaner.

2022-01-03 07:38 UTC, lordkiz commented on src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
> +  url: string
It just describes the Image after they have been mapped. Maybe MappedImageDescriptor is a better name.

2022-01-03 08:51 UTC, lordkiz commented on src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
> +    if (hasImagesStillProcessing(defaultImage, images)) {
Thanks. Super! 👏

2022-01-03 11:35 UTC, olerichter00 approved these changes
Looks good to me 👍  Approved from me after addressing all comments.

2022-01-11 16:08 UTC, brainbicycle commented on src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
> +  url: string
thanks!

2022-01-11 16:10 UTC, brainbicycle approved these changes

2022-01-11 16:10 UTC, merged

2022-01-11 16:10 UTC, brainbicycle commented
Sorry for delay! Great work!