fix(DX): some small but nice things
artsy/eigen pull request #5904
Opened 2021-12-15 17:17 UTC by pvinis

The type of this PR is: **TYPE**

This PR resolves []

### Description

This started as an investigation to solve `RangeError: Maximum call stack exceeded` with @olerichter00 and @MounirDhahri. We failed, but at least I fixed the following on the way.

- moved `setupSentry` in `index.ios.js` so it doesnt get called again
- removed a deprecated `enableOutOfMemoryTracking` from sentry init
- added an `Open RN Dev Menu` menu item in the admin menu, so we can open the RN dev menu on a device!
- reworked the `useScreenReaderTracking` to not use state

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- moved `setupSentry` in `index.ios.js` so it doesnt get called again - pavlos
- removed a deprecated `enableOutOfMemoryTracking` from sentry init - pavlos
- added an `Open RN Dev Menu` menu item in the admin menu, so we can open the RN dev menu on a device! - pavlos
- reworked the `useScreenReaderTracking` to not use state - pavlos

</details>

2021-12-15 17:18 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (moved `setupSentry` in `index.ios.js` so it doesnt get called again - pavlos,removed a deprecated `enableOutOfMemoryTracking` from sentry init - pavlos,added an `Open RN Dev Menu` menu item in the admin menu, so we can open the RN dev menu on a device! - pavlos,reworked the `useScreenReaderTracking` to not use state - pavlos)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e84dae8ee58ef400c1e2b2f3cc2da07d716e1766
</p>

2021-12-16 08:57 UTC, gkartalis commented
Tried to test it locally but it crashes with this error:
![simulator_screenshot_F2DB2F12-EAFB-41F9-8FD3-513F44138C3C](https://user-images.githubusercontent.com/21178754/146339985-8180b6e5-6596-4234-a401-b07e067dfe98.png)

2021-12-16 08:58 UTC, olerichter00 requested changes
I like the title a lot 🥇 

Just left a small comment about renaming `getScreenReaderStatus`.

2021-12-16 08:58 UTC, olerichter00 commented on src/lib/utils/useScreenReaderTracking.ts
> +    const doIt = async () => {
Not sure if renaming it to `doIt` would be any good when someone tries to debug this code. This could be quite confusing.

2021-12-16 09:02 UTC, gkartalis commented on src/lib/ErrorReporting.ts
> +import Sentry from "@sentry/react-native"
When reverted this line to previous changes it stopped crashing

2021-12-16 09:38 UTC, MounirDhahri reviewed
Thanks for the refactoring

2021-12-16 09:38 UTC, MounirDhahri commented on src/lib/utils/useScreenReaderTracking.ts
> -  const [isScreenReaderEnabled, setIsScreenReaderEnabled] = useState(false)
**praise:** nice

2021-12-16 10:35 UTC, pvinis commented
all of you have noticed this PR being broken. ill try to address things or revert things. trying to make PRs after a debugging frustration leads to funky PRs 😆.

2021-12-16 10:39 UTC, pvinis commented on src/lib/utils/useScreenReaderTracking.ts
> +    const doIt = async () => {
i think ill revert this whole file and try again later. i renamed it to `doIt` because i made it so that the useEffect has only one function, an async one, and then just call it. Since thats the "right" way to do async useEffects, and i removed the need for the useState, i thought ill be able to do it this way, and im kinda used to using `doIt` for this specific case.

unfortunately, this didnt work. also, this change broke the test, which btw @gkartalis i think the test might be not actually testing anything, because a mock is missing. maybe we can pair and try to remove the useState and play with the test together?

2021-12-16 10:39 UTC, pvinis commented on src/lib/ErrorReporting.ts
> +import Sentry from "@sentry/react-native"
```suggestion
import * as Sentry from "@sentry/react-native"
```

2021-12-16 10:41 UTC, gkartalis commented on src/lib/utils/useScreenReaderTracking.ts
> +    const doIt = async () => {
Happy to pair on that, with the previous implementation the test was working though 🤔 , which mock is missing?

2021-12-16 10:49 UTC, olerichter00 commented on src/lib/utils/useScreenReaderTracking.ts
> +    const doIt = async () => {
Instead of naming it `doIt` we could also use an IIFE.

```
useEffect(() => {
    (async () => {
      // do it!
    })()
  }, [])
```

2021-12-16 11:00 UTC, pvinis commented
there we go. we should be good now.

2021-12-16 11:02 UTC, MounirDhahri approved these changes
🚀

2021-12-16 11:04 UTC, MounirDhahri commented on index.ios.js
> +  require("./src/lib/ErrorReporting").setupSentry()
**thought:** I just realized that we do this initialization in AppRegistry, maybe we don't even need this actually https://github.com/artsy/eigen/blob/1fe9becf36c0c6420be4491b8653dde616913680/src/lib/AppRegistry.tsx#L420

2021-12-16 11:38 UTC, olerichter00 approved these changes

2021-12-16 12:09 UTC, pvinis commented on src/lib/utils/useScreenReaderTracking.ts
> +    const doIt = async () => {
yea, thats another way, both feel too boilerplate-y. but yea, i think the IIFE suggestion is cleaner.

2021-12-16 12:10 UTC, merged

2021-12-16 18:01 UTC, MounirDhahri commented on index.ios.js
> +  require("./src/lib/ErrorReporting").setupSentry()
I agree