chore: send better formatted errors to sentry
artsy/eigen pull request #5913
Opened 2021-12-16 20:03 UTC by MounirDhahri

The type of this PR is: **Enhancement**

### Description

- The exceptions that we receive in Sentry are either named `<unknown>` or `RRNLRequestError`. This makes it harder to understand them unless we open their particular page. The goal from this PR is to take advantage of the `formatGraphQLErrors()` API in `react-relay-network-modern` to make our dashboard easier to understand.

![Group 14](https://user-images.githubusercontent.com/11945712/146441111-a89eefcc-a8ec-4824-ba41-54407f15452c.png)

![Group 13](https://user-images.githubusercontent.com/11945712/146441129-c02a5ea9-1d08-4848-bc53-71da4ee15a9b.png)

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- send better formatted errors to sentry - mounir

</details>

2021-12-16 20:04 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (send better formatted errors to sentry - mounir)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cba017f3b6186dc564d97233b04a2d577e92b4ca
</p>

2021-12-16 20:16 UTC, MounirDhahri commented on src/lib/utils/AdminMenu.tsx
> +export const FeatureFlagMenuItem: React.FC<{
This is probably not needed and we can use maybe with some effort adjust the `MenuItem`, again (we already adjusted it a few times to support new behaviors), to support multiple lines but I am afraid one day we will break it somewhere else in the app (it's used in 6 screens) and we won't notice it.

2021-12-17 14:57 UTC, admbtlr requested changes

2021-12-17 14:57 UTC, admbtlr commented on src/lib/relay/middlewares/errorMiddleware.ts
> +    Sentry.captureException(sentryFormattedError)
But we're still going to have the problem that we get two Sentry issues for each error, aren't we? Is it possible to add some of the date in `SentryFormattedError` to the `createRequestError()`, or vice versa, and just throw one? Or is it maybe possible to have Sentry ignore the thrown `createRequestError()`?

2021-12-17 15:14 UTC, rajsam003 commented on src/lib/utils/AdminMenu.tsx
> +          title="Log out"
```suggestion
          title="Logout"
```

2021-12-17 15:15 UTC, rajsam003 commented on src/lib/utils/AdminMenu.tsx
> +          title="Log out"
Actually I am not sure. Haha

2021-12-17 15:21 UTC, rajsam003 commented on src/lib/utils/AdminMenu.tsx
> +export const FeatureFlagMenuItem: React.FC<{
**question:** How does it relate to the requirement of the ticket, which is about sentry error format?

2021-12-19 12:36 UTC, MounirDhahri commented on src/lib/utils/AdminMenu.tsx
> +export const FeatureFlagMenuItem: React.FC<{
it was hard to get feature flags that have a long description to be visible on the screen and we needed to always cut them, few people reported that (including you I guess). so I wanted to fix that in order to show a clear description.

2021-12-19 12:37 UTC, MounirDhahri commented on src/lib/utils/AdminMenu.tsx
> +          title="Log out"
I wanted to have a verb here instead of a noun to match the other title for the other feature flags. Enable, show...

2021-12-19 12:41 UTC, MounirDhahri commented on src/lib/utils/AdminMenu.tsx
> +          title="Log out"
I referred to this https://www.quora.com/What-is-the-difference-between-log-out-and-logout

2021-12-19 12:46 UTC, MounirDhahri commented on src/lib/relay/middlewares/errorMiddleware.ts
> +    Sentry.captureException(sentryFormattedError)
I actually checked that inside the clean `Eigen` sentry project (not `eigen-legacy`) and I noticed that the thrown error below does not show up in Sentry.

> Is it possible to add some of the date in `sentryFormattedError`
Yes, that's possible, I think the date is usually available by default but yes I can add it for easier debugging to avoid scrolling to the top of the page every time

2021-12-19 12:51 UTC, MounirDhahri commented on src/lib/ErrorReporting.ts
> +  captureExceptionsInSentryOnDev = !__DEV__
Probably there is no need to add `InSentry` but the reason behind adding `onDev` here is to make sure whoever reads this later knows that this is only related to dev since we are always capturing errors in non-dev builds.
How about we go for `captureExceptionsInDev` ?

2021-12-20 17:26 UTC, merged