chore: Adding tooltip for Select components
artsy/eigen pull request #5928
Opened 2021-12-20 14:45 UTC by rajsam003

The type of this PR is: Enhancement

This PR resolves [CX-2231]

### Description

![image](https://user-images.githubusercontent.com/17421923/146785216-f0e20bea-5778-4aa1-8bd4-601c69fc91bb.png)

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Tooltip for select components on storybooks

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-12-20 14:47 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Tooltip for select components on storybooks)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7eaac22bdbc4c143d71c982b146bfd7f86a2ba50
</p>

2021-12-20 14:51 UTC, olerichter00 reviewed
Is this PR ready for review or still a draft?

2021-12-20 14:51 UTC, rajsam003 commented
@olerichter00 Its ready now

2021-12-20 16:44 UTC, olerichter00 requested changes
This looks pretty good so far! 

I would expect to pass the text ("What is this?") and the content of the tooltip as props to the component.

2021-12-20 16:44 UTC, olerichter00 commented on src/palette/elements/Select/Select.stories.tsx
> +        title="Title"
```suggestion
        title="With Tooltip"
```

2021-12-20 16:44 UTC, olerichter00 commented on src/palette/elements/Select/Select.tsx
> +              What is this?
Maybe we should pass the text that is shown as a prop instead of a boolean as `tooltip`.

2021-12-20 16:44 UTC, olerichter00 commented on src/palette/elements/Select/Select.tsx
> +        {tooltip ? (
```suggestion
        {!!tooltip && (
```

2021-12-20 16:47 UTC, pvinis commented on src/palette/elements/Select/Select.stories.tsx
> +        onPressTooltip={() => null}
I think this story can get more useful with some actual tooltip. Maybe add something here? Then we can see how this thing is supposed to work.

2021-12-20 16:51 UTC, pvinis commented on src/palette/elements/Select/Select.tsx
> +  onPressTooltip?(): void
What do you think about `onTooltipPress` or even `onHelpPress`?

Tooltip feels like the wrong name for this whole thing, since we don't actually show a tooltip, but we will just navigate to a help page.

Also, usually the names go `on*Press`, like `onLongPress`.

2021-12-20 16:54 UTC, pvinis commented
I tried with a subtitle as well, and it gets funky. Could you ask Jonathan about this case? Maybe the "whats this" stays on the same line as the title?
<img width="296" alt="Screenshot 2021-12-20 at 18 53 25" src="https://user-images.githubusercontent.com/100233/146803550-d9cc529d-54a2-4f0f-a13e-e9af077253c0.png">

2021-12-20 16:56 UTC, pvinis commented on src/palette/elements/Select/Select.tsx
> +              What is this?
I wonder if having this text here makes sense, or if its better to replace the `tooltip` prop with something like `tooltipText` or `helpText` so we can customize.

Maybe ask Jonathan about this, and if he sees this changing often, lets to it with the title, if he sees this being the same for a while, then lets keep it as is.

2021-12-20 16:56 UTC, pvinis requested changes
Had some ideas and some comments

2021-12-20 17:11 UTC, olerichter00 commented
I guess this is a `feature` :)

2021-12-28 09:59 UTC, rajsam003 commented on src/palette/elements/Select/Select.stories.tsx
> +        onPressTooltip={() => null}
Yes, it is just for navigation. Lemme try adding a modal.

2021-12-28 10:04 UTC, rajsam003 commented
> I tried with a subtitle as well, and it gets funky. Could you ask Jonathan about this case? Maybe the "whats this" stays on the same line as the title? <img alt="Screenshot 2021-12-20 at 18 53 25" width="296" src="https://user-images.githubusercontent.com/100233/146803550-d9cc529d-54a2-4f0f-a13e-e9af077253c0.png">

This makes sense. But in any case, it will overlap. I mean even if the title text is long. 
Let's see what Jonathan says.

2021-12-28 10:19 UTC, olerichter00 commented
> > I tried with a subtitle as well, and it gets funky. Could you ask Jonathan about this case? Maybe the "whats this" stays on the same line as the title? <img alt="Screenshot 2021-12-20 at 18 53 25" width="296" src="https://user-images.githubusercontent.com/100233/146803550-d9cc529d-54a2-4f0f-a13e-e9af077253c0.png">
> 
> This makes sense. But in any case, it will overlap. I mean even if the title text is long. Let's see what Jonathan says.

You should probably give the `Flex` holding the title and the subtitle give the prop `flex: 1` to prevent the overlap. We then need to decide if restrict the number of lines for the title and the subtitle:

**Without line restriction:**
![Screenshot 2021-12-28 at 11 18 48](https://user-images.githubusercontent.com/4691889/147556170-dcc28643-4ee1-4032-adfd-9315666307a0.png)

**With line restriction:**
![Screenshot 2021-12-28 at 11 19 14](https://user-images.githubusercontent.com/4691889/147556203-abf178de-32b3-46f4-828c-b4fc3b34262d.png)

2021-12-29 10:01 UTC, rajsam003 commented
> > > I tried with a subtitle as well, and it gets funky. Could you ask Jonathan about this case? Maybe the "whats this" stays on the same line as the title? <img alt="Screenshot 2021-12-20 at 18 53 25" width="296" src="https://user-images.githubusercontent.com/100233/146803550-d9cc529d-54a2-4f0f-a13e-e9af077253c0.png">
> > 
> > 
> > This makes sense. But in any case, it will overlap. I mean even if the title text is long. Let's see what Jonathan says.
> 
> You should probably give the `Flex` holding the title and the subtitle the prop `flex: 1` to prevent the overlap. Not sure though whether to restrict the number of lines for the title and the subtitle:
> 
> **Without line restriction:** ![Screenshot 2021-12-28 at 11 18 48](https://user-images.githubusercontent.com/4691889/147556170-dcc28643-4ee1-4032-adfd-9315666307a0.png)
> 
> **With line restriction:** ![Screenshot 2021-12-28 at 11 19 14](https://user-images.githubusercontent.com/4691889/147556203-abf178de-32b3-46f4-828c-b4fc3b34262d.png)

So according to Jonathan, we will want to test this in situ to check on any min-width issues. If the design is done well, probably we should not run into anything quite as sever (or narrow) as the [examples](https://www.figma.com/file/m6gDpKHEWDbYJyrwsVZDBr/Artsy-3.0-Design-System?node-id=5299%3A3124)

But I have added `ml={1}` to the tooltip flexbox to make it look good.
![image](https://user-images.githubusercontent.com/17421923/147650412-e91cd12b-5ef7-409e-94bb-35c1fe755925.png)

2021-12-29 10:05 UTC, olerichter00 commented
It's still overlapping if the title is too long and I think we should address this.

![simulator_screenshot_0DDF0EDF-811E-4A03-ACC8-79E123B5579A](https://user-images.githubusercontent.com/4691889/147650741-c3c13701-ba3d-48f4-8554-7418b7a2b7f5.png)

2021-12-29 13:29 UTC, rajsam003 commented on src/palette/elements/Select/Select.tsx
> +        <Flex flex={1}>
This can help in adjusting the overlapping of texts. But it displays as overlapped only on storybook as storybook needs some adjustment with width.

2021-12-29 16:30 UTC, closed without merging