chore: Adding Rarity field for My Collection Add work form
artsy/eigen pull request #5947
Opened 2021-12-22 16:53 UTC by rajsam003

The type of this PR is: **TYPE**

This PR resolves [CX-2201]

### Description

This PR resolves to add a rarity field with the dropdown menu in my collection artwork form.

![image](https://user-images.githubusercontent.com/17421923/147127266-51115395-c76f-4346-9038-39ae05ba5f48.png)
### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [x] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Added rarity field on My Collection Artwork form - Sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-12-22 16:55 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  We are trying to ...
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  We are trying to migrate away from `react-test-renderer` towards `@testing-library/react-native`, but found Test-Renderer imports in the following new unit test files:

- `src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityPicker.tests.tsx`

See [`Pill.tests.tsx`](https://github.com/artsy/eigen/blob/2f32d462bb3b4ce358c8a14e3ed09b42523de8bd/src/palette/elements/Pill/__tests__/Pill-tests.tsx) as an example, or [the docs](https://callstack.github.io/react-native-testing-library/docs/api-queries).
  
  </td>
    </tr>
  </tbody>
</table>


### This PR contains the following changes:

- Cross-platform user-facing changes (Added rarity field on My Collection Artwork form - Sam)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 31d30f54031c3c9abba930ef9b14c904a1253002
</p>

2021-12-23 10:11 UTC, olerichter00 requested changes
Looks pretty good so far! We just have to find a way to center the inputs correctly when font scaling is activated.

2021-12-23 10:11 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityPicker.tsx
> +          <Flex justifyContent="center" mx={2} mt={1}>
This is not centering the `/` vertically. We should look for another solution that works with font-scaling and centers correctly.

| iPhone 8, maximum font scaling |
| --- | 
| ![Simulator Screen Shot - iPhone 8 - 2021-12-23 at 11 00 01](https://user-images.githubusercontent.com/4691889/147223878-e9637a47-9bfe-4b3f-8a56-9440bc35ff54.png) |

2021-12-23 10:11 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityPicker.tsx
> +      {formik.values.attributionClass === "LIMITED_EDITION" ? (
I wonder if we should clear `editionNumber` and `editionSize` if `attributionClass` is not `LIMITED_EDITION`.

2021-12-23 10:11 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityPicker.tsx
> +export const RarityPicker: React.FC = () => {
Maybe `Rarity` is a better name because this component also includes inputs for `editionNumber` and `editionSize`.

2021-12-23 10:15 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityPicker.tests.tsx
> +import { renderWithWrappers } from "lib/tests/renderWithWrappers"
`renderWithWrappers` is deprecated. We are trying to migrate away from `react-test-renderer` towards `@testing-library/react-native`

2021-12-23 11:08 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityPicker.tsx
> +              title="EDIION SIZE"
Oops. Sorry about that

2021-12-23 11:09 UTC, rajsam003 commented on src/lib/utils/artworkMediumCategories.ts
> +export const artworkRarityClassifications: Medium[] = [
Sorry I didnt notice it. 🤦🏽‍♂️

2021-12-27 11:29 UTC, olerichter00 requested changes

2021-12-27 11:29 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityPicker.tsx
> +              title="EDITION NUMBER"
No need to write the title in uppercase here. If we'd decide to move away from uppercase titles in the future this would make things difficult. [InputTitle](https://github.com/artsy/eigen/blob/a428cff32b191048e577baad1f71982d243841b1/src/palette/elements/Input/InputTitle.tsx#L13) already transforms the title.

2021-12-28 09:51 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +          <Flex flexDirection="row" mt={2}>
I removed the title and put it in a separate flexbox to adjust with any font scaling.

2021-12-28 10:30 UTC, olerichter00 reviewed
This looks good to me. Feel free to merge after addressing these two questions

2021-12-28 10:30 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +    if (value !== "LIMITED_EDITION") {
I wonder if it is good UX if the values are deleted at this point. This might be just a detail but for me it seems to be expected that the values are still there if I switch back to "Limited Edition".

2021-12-28 10:30 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +            <Flex justifyContent="center" mx={2} mt={1}>
Why do we need `mt={1}` here? With the padding, it doesn't seem to be centered and without it's exactly in the middle? 🤔 
```suggestion
            <Flex justifyContent="center" mx={2}>
```

2021-12-29 09:13 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +    if (value !== "LIMITED_EDITION") {
In that case, I have to clear the values while submitting the whole form.

2021-12-29 09:14 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +    if (value !== "LIMITED_EDITION") {
I would think this would be a better user experience. What do you think?

2021-12-29 09:14 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +          <Flex flexDirection="row" mt={2}>
Very good idea 🙌

2021-12-29 09:33 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +    if (value !== "LIMITED_EDITION") {
Yes, you are right :)

2021-12-29 14:19 UTC, olerichter00 requested changes
This PR has more than 900 file changes. Can you have a look to see what's wrong?

2021-12-29 14:52 UTC, closed without merging