Bugfix(cx-2091): fix broken sharing to instagram stories
artsy/eigen pull request #5958
Opened 2021-12-29 11:20 UTC by lordkiz

The type of this PR is: **Bugfix**

This PR resolves [CX-2091]

### Description
- Fixes broken sharing to Instagram stories on android
- Replace sharing small images (because these images are blurry) with viewshot image

<p>
<img src='https://user-images.githubusercontent.com/18648835/147656699-9a6a1277-701a-4429-81a4-4c75ca2d6854.jpg'  width="45%">
</p>

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Fix sharing to Instagram Stories - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-12-29 11:21 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Fix sharing to Instagram Stories - kizito)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5b081d518fca6dc56f8ce86e31709619aff805fc
</p>

2021-12-29 11:40 UTC, pvinis commented
I will take a look at this tomorrow if thats ok. I need to run this.

2021-12-29 11:40 UTC, pvinis commented
would you mind explaining a bit how this PR fixes the android issue?

2021-12-29 16:10 UTC, lordkiz commented
> would you mind explaining a bit how this PR fixes the android issue?

@pvinis 
The issue on android is that we are not using the `shareArtworkOnInstagramStory` function that you had written because `const showInstagramStoriesItem = useCanOpenURL("instagram-stories://test")` wont work for android as this only checks the iOS urlScheme. So it defaults to using the general `shareArtwork` function which gets and attempts to share a plain image that does not meet the image spec as specified here: https://developers.facebook.com/docs/instagram/sharing-to-stories#shareable-content . All I did was replace the image in the `shareArtwork` function with the one we generate from ViewShot.

2022-01-04 06:43 UTC, pvinis requested changes
Sorry it took a while to review.

This is not what we want here. The `shareArtwork` function is only called when we have the custom share flag disabled. It's the old share, and we don't need to change anything there.

To make sure you're testing the right thing, make sure you have the custom sharesheet flag enabled, and that you have instagram installed so that the `useCanOpenURL` returns true.

Only then you will see the actual issue, where the instagram app opens to share, but it's just a black screen.

2022-01-04 10:22 UTC, lordkiz commented
> Sorry it took a while to review.
> 
> This is not what we want here. The `shareArtwork` function is only called when we have the custom share flag disabled. It's the old share, and we don't need to change anything there.
> 
> To make sure you're testing the right thing, make sure you have the custom sharesheet flag enabled, and that you have instagram installed so that the `useCanOpenURL` returns true.
> 
> Only then you will see the actual issue, where the instagram app opens to share, but it's just a black screen.

@pvinis I see. With this approach we will still have the issue if the user opts to use the native android sharesheet. But I will look into it.

2022-01-04 11:02 UTC, pvinis commented
I guess we should enable the custom one by now, its been there for a while. So I'd say if you fix the android issue in this PR, we could just enable the flag by default, and soon after remove the old code 👍. How does that sound?

2022-01-04 11:17 UTC, lordkiz commented
> I guess we should enable the custom one by now, its been there for a while. So I'd say if you fix the android issue in this PR, we could just enable the flag by default, and soon after remove the old code 👍. How does that sound?

@pvinis that can work. How about we use the ViewShot in both the custom share and the default share? I used the default share for sharing to my drive etc and the image was really bad.

2022-01-05 13:51 UTC, pvinis requested changes
looks good, one thing is that we should just use either `whatsapp://test` or `whatsapp://send?phone=+491898`, no need to complicate this code with two if we can make it work with just one of them.

one more question, so does this change make instagram story share work? i dont see anything that would make any difference for the black screen 🤔. were we not rendering maybe.. could we do a quick call/pairing to make sure we are having the right behavior?

2022-01-05 13:51 UTC, pvinis commented on src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
> +  const whatsappUrlScheme = Platform.OS === "android" ? "whatsapp://send?phone=+491898" : "whatsapp://test"
did you try this and it didn't work on android?

if you tried and it didn't work, first of all, weird 🤔. does android need more things than just the protocol part before `://`? if it does, then let's keep that, for both android and ios, since ios only cares for the protocol. if it doesn't, lets keep again one of them, to keep things simple.

same for instagram.

2022-01-10 10:37 UTC, lordkiz commented
> one more question, so does this change make instagram story share work? i dont see anything that would make any difference for the black screen 🤔. were we not rendering maybe.. could we do a quick call/pairing to make sure we are having the right behavior?

@pvinis Absolutely. This fixes the Instagram story share issue on android. The issue was because the previous image does not adhere to required spec.

2022-01-10 10:38 UTC, lordkiz commented on src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
> +  const whatsappUrlScheme = Platform.OS === "android" ? "whatsapp://send?phone=+491898" : "whatsapp://test"
Updated the PR. Yes, they can share the same. Thanks @pvinis

2022-01-11 03:57 UTC, pvinis approved these changes
the code looks good. I haven't run it on a device so I'll trust you have tried that to make sure it works and posts a story.

you wanna remove the flag and use the new share and delete the old code in this PR or a separate one?

2022-01-11 10:22 UTC, lordkiz commented
> you wanna remove the flag and use the new share and delete the old code in this PR or a separate one?

The custom share sheet is enabled by default. By `remove old code`, do you mean remove the default share? If so, we can't because the user can opt to use the default share through the custom share sheet.

2022-01-11 15:14 UTC, pvinis commented
ok lets keep it as is and we can remove the flag later. ill assign you and sam, so if you have tried on android and it shares a story, then awesome, merge when you want.

2022-01-11 15:37 UTC, merged