feat: Rarity classification type explanation modal
artsy/eigen pull request #5966
Opened 2021-12-30 10:22 UTC by rajsam003

The type of this PR is: Feature

This PR resolves [CX-2202]

### Description

This PR helps in displaying a modal having rarity types and their explanations by tapping on `What is this?`

![image](https://user-images.githubusercontent.com/17421923/147742041-1df1bd09-25aa-407f-a92a-3fe501097161.png)

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Rarity classification explanation modal tapping on `What is this?` - sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2021-12-30 10:23 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Rarity classification explanation modal tapping on `What is this?` - sam)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8ff38f126b1460b3be5cd9bde42de2dc13e24261
</p>

2021-12-30 10:35 UTC, olerichter00 requested changes

2021-12-30 10:35 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +      <Flex p="2" pb={15} flexDirection="row" alignItems="center" flexGrow={0}>
```suggestion
      <Flex p={2} pb={15} flexDirection="row" alignItems="center" flexGrow={0}>
```

2021-12-30 10:35 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +        <Flex flex={1} />
👀

2021-12-30 10:35 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +        <Flex flex={2} alignItems="center">
No need for a custom header, you can use the `FancyModalHeader` component.

2021-12-30 10:35 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +            <Text style={{ fontSize: 16, marginBottom: 2 }}>{classification.description}</Text>
Let's try to avoid styling Palette components to keep a consistent look throughout the app.

2021-12-30 10:35 UTC, olerichter00 commented on src/lib/utils/artworkRarityClassifications.ts
> +    description: "The edition run has ended; the number of works produced is known and included in the listing.",
Great idea 👍

2021-12-30 10:35 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +const RarityClassifcationTypesModal: React.FC<{
Maybe we can keep the naming consistent and call it either `RarityInfoModal` or `RarityClassifcationTypesModal`.

2021-12-30 10:35 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +            <Text variant="md" style={{ fontSize: 13, marginBottom: 2, textTransform: "uppercase" }}>
Let's try to avoid styling Palette components to keep a consistent look throughout the app.

2021-12-30 13:43 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +        <Flex flex={1} />
I actually copied it from Select Modal to make it consistent

2021-12-30 13:43 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +        <Flex flex={1} />
I will remove it

2021-12-30 13:45 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +        <Flex flex={2} alignItems="center">
Same as above

2021-12-30 13:47 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +const RarityClassifcationTypesModal: React.FC<{
So no need for any change here.

2021-12-30 13:48 UTC, rajsam003 commented on src/lib/utils/artworkRarityClassifications.ts
> +    description: "The edition run has ended; the number of works produced is known and included in the listing.",
Thanks

2022-01-03 10:51 UTC, olerichter00 requested changes
Just left two comments. Feel free to merge when they are addressed/resolved 🚀

2022-01-03 10:51 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +const RarityClassifcationTypesModal: React.FC<{
What I mean is that it is called `RarityInfoModal` above (in the state `RarityInfoModalVisible`) and `RarityClassifcationTypesModal` in this line. I was wondering if there is a reason to have to different names for the same modal.

2022-01-03 10:51 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +      <FancyModalHeader onLeftButtonPress={onDismiss} useXButton>
Shouldn't the button be on the right (see screenshot in the PR and Figma file)?

2022-01-03 11:04 UTC, rajsam003 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +      <FancyModalHeader onLeftButtonPress={onDismiss} useXButton>
Yes, it should be on the right side. but anyway we will be changing all the modals. So I left it on the left side to match with the current modal layout. However, I can move it to right. Thanks

2022-01-03 11:10 UTC, olerichter00 commented on src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
> +      <FancyModalHeader onLeftButtonPress={onDismiss} useXButton>
If the change was intentionally of course we can keep it on the left side :)

2022-01-03 11:10 UTC, olerichter00 approved these changes
🚀  🚀  🚀

2022-01-03 11:34 UTC, olerichter00 submitted a review, later dismissed

2022-01-03 11:40 UTC, olerichter00 commented
#squashongreen

2022-01-03 14:07 UTC, merged