Sam/cx 1818/change rail v3
artsy/eigen pull request #5980
Opened 2022-01-05 12:51 UTC by rajsam003

The type of this PR is: **TYPE**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-01-05 12:52 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 27d63c442e2fdf389b849a260c57ab4a195910ce
</p>

2022-01-05 14:02 UTC, rajsam003 commented on src/lib/Scenes/Home/Components/ArtworkRail.tsx
> +      <SmallTileRailContainer
I can change the name of this component to a more generic one like `ArtworkTileRail` but it already exists. 
I tried to use it but then it required a big change and a lot of files are getting affected.

2022-01-05 14:27 UTC, rajsam003 commented on src/lib/Scenes/Home/Home.tsx
> +  const imagePlaceHolderAspectRatio = 0.7
Not sure about this. We need to ask Jonathan about this command aspect ratio to use for placeholder box

2022-01-05 15:38 UTC, olerichter00 requested changes
I love this feature and the code looks good to me 🌟 

I added a few comments about the naming and I get layout shifts when I scroll on the rail (iOS simulator iPhone 12 mini). Please also make sure this looks good on Android and on tablets. I guess it will look as expected but we should check (and add screenshots to the PR).

2022-01-05 15:38 UTC, olerichter00 commented on src/lib/Scenes/Home/Home.tsx
> +  const IMAGE_PLACE_HOLDER_SIZES = {
```suggestion
  const IMAGE_PLACEHOLDER_SIZES = {
```

2022-01-05 15:38 UTC, olerichter00 commented on src/lib/Scenes/Home/Home.tsx
> +  const imagePlaceHolderAspectRatio = 0.7
```suggestion
  const imagePlaceholderAspectRatio = 0.7
```

2022-01-05 15:38 UTC, olerichter00 commented on src/lib/Scenes/Home/Home.tsx
> +  const largeImagePlaceHolderWidth = IMAGE_PLACE_HOLDER_SIZES.large.width
```suggestion
  const smallImagePlaceholderWidth = IMAGE_PLACEHOLDER_SIZES.small.width
  const largeImagePlaceholderWidth = IMAGE_PLACEHOLDER_SIZES.large.width
```

2022-01-06 10:33 UTC, pvinis commented on src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
> +    maxHeight: 275, // Calcuated middle number of maxHeight small and large.
```suggestion
    maxHeight: 275, // Calculated middle number of maxHeight small and large.
```

2022-01-06 14:50 UTC, olerichter00 requested changes
I can still see the same layout shifts. This is probably due to the rail loading more artworks when scrolling which then increases the height. I guess, we either need to set the height of the images to a fixed value (setting `height` instead of `maxHeight`) or disable load more on scroll for all artwork rails.

2022-01-07 13:32 UTC, rajsam003 commented on src/lib/Scenes/Home/Home.tsx
> -                    mb={MODULE_SEPARATOR_HEIGHT}
Removed it as it gives extra unwanted space after adding `height={90}` for the text container of rails as per design,

2022-01-07 15:15 UTC, olerichter00 commented on src/lib/Scenes/Home/Home.tsx
> -                    mb={MODULE_SEPARATOR_HEIGHT}
Giving the text below the images in the artwork item a fixed height of 90px would result in different spaces between rails dependent on the content of the text, right? I'd argue it is better to keep this bottom-margin and removing the fixed height of 90px.

2022-01-07 15:16 UTC, olerichter00 requested changes
Code looks good 👍 
I still get a few layout shifts just after the rail renders for the first time.

2022-01-07 17:07 UTC, rajsam003 commented
> I still get a few layout shifts just after the rail renders for the first time (iOS simulator).

@olerichter00 this is not happening on my end. It happens only before the initial render which I think is expected.

2022-01-07 17:17 UTC, olerichter00 commented
> > I still get a few layout shifts just after the rail renders for the first time (iOS simulator).
> 
> @olerichter00 this is not happening on my end. It happens only before the initial render which I think is expected.

I recorded it (iOS 15.2 iPhone 12 mini Simulator):

https://user-images.githubusercontent.com/4691889/148581404-b6e56fb0-ad43-4537-abe2-440b4fde7d52.mp4

2022-01-07 18:18 UTC, rajsam003 commented
> > > I still get a few layout shifts just after the rail renders for the first time (iOS simulator).
> > 
> > 
> > @olerichter00 this is not happening on my end. It happens only before the initial render which I think is expected.
> 
> I recorded it (iOS 15.2 iPhone 12 mini simulator):
> 
>  Simulator.Screen.Recording.-.iPhone.12.mini.-.2022-01-07.at.18.16.21.mp4

Yes, this is what I meant. If this is not expected, I will have to figure out how to avoid this.

2022-01-10 09:54 UTC, olerichter00 commented
> Yes, this is what I meant. If this is not expected, I will have to figure out how to avoid this.

I'd say we should fix the issue before shipping these new rails.

2022-01-24 11:04 UTC, olerichter00 commented
Closing this PR, the new artwork rail was implemented in https://github.com/artsy/eigen/pull/6045.

2022-01-24 11:04 UTC, closed without merging