chore: consolidate env for ci
artsy/eigen pull request #6082
Opened 2022-01-24 19:38 UTC by brainbicycle

The type of this PR is: **chore**

This PR resolves [MOPLAT-70]

### Description

Gets rid of old script to generate ci env file from circle vars and instead uses the same citadel env file for ci.

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-01-24 19:39 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 932c3b1b1b63c88f23c1672303e67eff9af094f0
</p>

2022-01-24 20:33 UTC, pvinis requested changes

2022-01-24 20:33 UTC, pvinis commented on scripts/setup-awscli-linux
> +
could we make these two files, one?

I'm pretty sure we have scripts that do that, and check for Darwin or Linux. then we can have 1 aws script, called the same from outside 🤔

2022-01-24 21:04 UTC, brainbicycle commented on scripts/setup-awscli-linux
> +
I don't actually see us doing that anywhere but it is a nice idea

2022-01-25 10:03 UTC, MounirDhahri commented
LGTM, I will as well trigger some betas from your branch to make sure everything works fine

2022-01-25 11:15 UTC, MounirDhahri submitted a review, later dismissed
Worked like a charm 🚀

2022-01-25 13:48 UTC, brainbicycle commented on scripts/setup-awscli-linux
> +
alright I did this here and in the setup distribute script!

2022-01-25 13:54 UTC, brainbicycle commented on src/lib/ErrorReporting.ts
> +  if (!captureExceptions && Config.SENTRY_DSN) {
this was supposed to be on another branch, although I am still confused how this is working at all

2022-01-26 08:41 UTC, pvinis approved these changes

2022-01-26 08:41 UTC, merged

2022-01-26 08:41 UTC, pvinis commented
lets go!