feat: Add placeholder layout animation
artsy/eigen pull request #6127
Opened 2022-01-31 12:24 UTC by olerichter00

The type of this PR is: **Feature**

This PR resolves []

### Description

Add placeholder layout animation.

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-01-31 12:25 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4c867541c31c0ddca1ed4461810fa872dd9a97a7
</p>

2022-01-31 14:05 UTC, MounirDhahri requested changes
Thanks for adding this, it looks really nice. I added one comment about using the `LayoutAnimation`, apart from animations are always welcome

2022-01-31 15:13 UTC, olerichter00 commented on src/lib/utils/placeholders.tsx
> +    LayoutAnimation.configureNext(LayoutAnimation.Presets.spring)
In the [docs](https://reactnative.dev/docs/performance) it says:

> "... LayoutAnimation leverages Core Animation and is unaffected by JS thread and main thread frame drops."

Doesn't this mean it's not affecting the JS thread? Nevertheless, I would suggest to test the animation on different devices and deactivating it for specific iOS/Android versions in case the animation isn't running smooth or causes performance issues on older devices.

It's probably possible to implement it with Reanimated I can't find a quick and easy enough solution.

2022-02-01 10:33 UTC, MounirDhahri commented on src/lib/utils/placeholders.tsx
> +    LayoutAnimation.configureNext(LayoutAnimation.Presets.spring)
oh I didn't know it got updated, that's great

2022-02-01 10:35 UTC, MounirDhahri approved these changes
This is great, thanks. Let's merge this after the release today

2022-02-02 11:13 UTC, merged