Sam/cx 2237/my profile navigation container
artsy/eigen pull request #6158
Opened 2022-02-03 18:48 UTC by rajsam003

The type of this PR is: **TYPE**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-02-03 18:49 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 29501ae462a341705b3bcfd73fd67d0ee4f2f604
</p>

2022-02-08 11:24 UTC, olerichter00 reviewed
Is this ready for review?

2022-02-08 16:11 UTC, rajsam003 commented
@olerichter00 

> Is this ready for review?

Not yet. Still need some changes on test files

2022-02-08 18:34 UTC, MounirDhahri reviewed
Glad to see this work being wrapped up. Thanks for this huge refactoring, I left some small comments and then I think we are clear to go 🚀

2022-02-08 18:34 UTC, MounirDhahri commented on src/lib/AppRegistry.tsx
> +import { StorybookUIRoot } from "../storybook/storybook-ui"
**thought:** did this work fine? the comment above says that this might cause issues

2022-02-08 18:34 UTC, MounirDhahri commented on src/lib/AppRegistry.tsx
> +  MyProfileEdit: reactModule(MyProfileEditForm, { hidesBackButton: true }),
**issue:** I guess this is no longer needed right, since we have the profile edit screen inside the navigation container

2022-02-08 18:34 UTC, MounirDhahri commented on src/lib/Scenes/MyProfile/MyProfile.tsx
> +          // force it to not use react-native-screens, which is broken inside a react-native Modal for some reason
**thought:** I think this is not required for us since we have no modals

2022-02-08 18:34 UTC, MounirDhahri commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +    <Suspense fallback={null}>
**thought:** maybe we can show a spinner here or even better show a skeleton loader

2022-02-09 04:25 UTC, lordkiz commented on src/lib/AppRegistry.tsx
> +import { StorybookUIRoot } from "../storybook/storybook-ui"
Yes @rajsam003 what is this error?

2022-02-09 04:42 UTC, lordkiz commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +        expect(findByText("Marvel Universe")).toEqual(Promise.resolve())
These tests are confusing. Texts `toEqual(Promise.resolve())`?

2022-02-09 04:44 UTC, lordkiz commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +      expect(findByText("My Bio")).toBeTruthy()
👏 Nice refactoring to use TL

2022-02-09 04:49 UTC, lordkiz commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +      staticHeaderContent={<MyProfileHeader {...props} />}
Why don't you just pass `me`? Easier to understand, I think.

2022-02-09 04:53 UTC, lordkiz commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> -          {normalizeMyProfileBio(me?.bio)}
What about previously submitted bios that were not normalized before submission? If we absolutely need normalizeMyProfileBio then we should keep it and not rely on whether they had been handled before submission because that can change anytime.

2022-02-09 05:03 UTC, lordkiz commented on src/setupJest.ts
> +
Would devs need to `resetModules` to mock `useRoute` in a single test basis?

2022-02-09 05:06 UTC, lordkiz commented on src/setupJest.ts
> +
Never mind, they can always `unmock` and `doMock`.

2022-02-09 08:18 UTC, rajsam003 commented on src/lib/AppRegistry.tsx
> +import { StorybookUIRoot } from "../storybook/storybook-ui"
This is not my change. I just organized the imports. It moved here from line 126

2022-02-09 08:21 UTC, rajsam003 commented on src/lib/AppRegistry.tsx
> +  MyProfileEdit: reactModule(MyProfileEditForm, { hidesBackButton: true }),
Yes you are right. I will remove it

2022-02-09 08:27 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +        expect(findByText("Marvel Universe")).toEqual(Promise.resolve())
Yes, it's returning an empty Promise for those strings. `toBeFalsy()` , `not.toBeTruthy()` and all other methods were failing.

2022-02-09 08:27 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +      staticHeaderContent={<MyProfileHeader {...props} />}
Okay

2022-02-09 08:29 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> -          {normalizeMyProfileBio(me?.bio)}
Oh snap. I didnt see this. Thanks for noticing. I will revert it back.

2022-02-09 08:30 UTC, olerichter00 requested changes
This is great work 🌟 

I've left a few comments and small change requests.

2022-02-09 08:30 UTC, olerichter00 commented on src/lib/AppRegistry.tsx
> +import { StorybookUIRoot } from "../storybook/storybook-ui"
I remember that we had to import `StorybookUIRoot` last to avoid an error.

2022-02-09 08:30 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +      console.error("Failed to upload profile picture ", error)
The arguments will be joined with a whitespace by `console.log`.
```suggestion
      console.error("Failed to upload profile picture", error)
```

2022-02-09 08:30 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +    <Suspense fallback={null}>
Let's move away from spinners to keep the loading states consistent wherever we can.

2022-02-09 08:30 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +        expect(findByText("Marvel Universe")).toEqual(Promise.resolve())
How is it working with `Promise.resolve()`? Would this work as well?

```suggestion
        expect(findByText("Guardian of the Galaxy")).not.toBeTruthy()
        expect(findByText("Atlantis")).not.toBeTruthy()
        expect(findByText("Marvel Universe")).not.toBeTruthy()
```

2022-02-09 08:30 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +          {me?.bio}
Is there a reason to remove `normalizeMyProfileBio` here? You can find the changes and the discussion about why it was added in https://github.com/artsy/eigen/pull/6162 and [CX-2321](https://artsyproduct.atlassian.net/browse/CX-2321).

2022-02-09 08:30 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> -          {normalizeMyProfileBio(me?.bio)}
@lordkiz The discussion about the decision can be found in [CX-2321](https://artsyproduct.atlassian.net/browse/CX-2321)

2022-02-09 08:30 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +      {!!me && (
Why do we need to check for `me`? Wouldn't it be possible to edit the profile even if the query fails and `me` is `null`?

2022-02-09 08:53 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +      console.error("Failed to upload profile picture ", error)
Isn't that what we want, we need whitespace to make it readable right?

2022-02-09 08:58 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +        expect(findByText("Marvel Universe")).toEqual(Promise.resolve())
Yes @olerichter00, its failing 

    ` expect(received).not.toBeTruthy() `

    ` Received: {} `

2022-02-09 08:59 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +      console.error("Failed to upload profile picture ", error)
`console.log("first", "second")` will print `first second`.

2022-02-09 09:10 UTC, rajsam003 commented on src/setupJest.ts
> +
Tests are failing in other files wherever navigation mock is used. So let me remove this and use it in the specific file.

2022-02-09 09:34 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +        expect(findByText("Marvel Universe")).toEqual(Promise.resolve())
Well, `findByText` doesn't seem to be testing anything and always return an object. Let's try to use another way to check if the text is rendered (e.g. with a test ID).

2022-02-09 10:35 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +      console.error("Failed to upload profile picture ", error)
🤔 💭

2022-02-09 10:50 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +      {!!me && (
Sorry, I reverted it back.

2022-02-09 13:32 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +      expect(findByText("My Name")).toBeTruthy()
Actually, `findByText` returns a promise which will always be truthy. I'll create another PR and add an `await` everywhere where we use `findByText` without.

2022-02-09 13:33 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
> +      expect(findByText("My Name")).toBeTruthy()
https://testing-library.com/docs/example-findbytext/

2022-02-09 13:46 UTC, olerichter00 approved these changes

2022-02-09 13:46 UTC, merged

2022-02-09 17:00 UTC, pvinis commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +export const editMyProfileSchema = Yup.object().shape({
same

2022-02-09 17:00 UTC, pvinis commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +export const MyProfileEditForm: React.FC<{ me: MyProfileEditForm_me$key }> = (props) => {
same

2022-02-09 18:05 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +export interface EditMyProfileValuesSchema {
Sure. I will create a small PR to remove it. Thanks

2022-02-09 18:06 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +export const MyProfileEditForm: React.FC<{ me: MyProfileEditForm_me$key }> = (props) => {
We are using this in test file