update folder capitalisation preferred practices
artsy/eigen pull request #6232
Opened 2022-02-15 17:06 UTC by patrinoua

The type of this PR is: **TYPE**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-02-15 17:07 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 556a183c48c0c81807d866fa83bf74e8b6597f61
</p>

2022-02-15 18:56 UTC, pvinis commented on docs/preferred_practices.md
> +For example migrations, routes, state would be folders with small letter while MyComponent.tsx would start with a Capital letter.
```suggestion
For example `mutations`, `routes`, `state` would be **lowercase** folders, while `MyComponent.tsx` would be a **PascalCase** file.
```

2022-02-15 18:58 UTC, pvinis commented on docs/preferred_practices.md
> +If we have a buttons folder which has many ButtonFile.tsx inside we keep a small letter.
```suggestion
If we have a `buttons` folder which has many ButtonFile.tsx inside we keep it **lowercase**. 
```

2022-02-15 18:59 UTC, pvinis commented on docs/preferred_practices.md
> +However, if we have a Button folder which only exports Button.tsx we write that with a capital letter.
```suggestion
However, if we have a `Button` folder which exports only one button component, we write that with in **PascalCase**.
```

2022-02-15 19:00 UTC, pvinis commented on docs/preferred_practices.md
> +│   ├── Button.tests.tsx
```suggestion
│   ├── Button.tests.tsx
│   ├── hooks
│   ├── animations
```

2022-02-15 19:00 UTC, pvinis commented on docs/preferred_practices.md
> +TODO: Add a migration guide?
i dont think we need a migration guide. like you said, lets let past be past :D

2022-02-15 19:01 UTC, pvinis requested changes
made some changes but leaving it for you to commit these in.

Once we have the rules set, lets pair and take a look at the files/folders we have now to make sure we didn't miss anything, and then we can merge.

PS. I made this into a draft, while we are working on it, if you dont mind.

2022-02-16 08:42 UTC, patrinoua commented on docs/preferred_practices.md
> +TODO: Add a migration guide?
For sure. How about the things we touch in the future though? 
Wouldn't it be nice to have a way to bring them to our modern ways?
Perhaps we could use something 

`State -> stateMigration -> state`

2022-02-16 13:00 UTC, pvinis approved these changes

2022-02-16 13:19 UTC, merged