feat: Reimplement opaqueimageview
artsy/eigen pull request #6265
Opened 2022-02-18 17:21 UTC by gkartalis

The type of this PR is: **TYPE**

This PR resolves [CX-882]

### Description

see https://github.com/artsy/eigen/pull/5021/files for more context

TODO: 
- replace `OpaqueImageView` -> `OpaqueImageView2`
- follow 

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-02-18 17:26 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 14bc3217f7cf5ce7ef53b57eb87ff66449923ccd
</p>

2022-03-04 18:18 UTC, gkartalis commented
After a discussion with @MrSltun we decided to approach it like this:
- Keep old OpaqueImageView component (with native code)
- Introduce the new one OpaqueImageView2 with `react-native-fast-image`
- use a feature flag to have control over this
- 🤔 maybe start swapping the places where we use the old one with the new one incrementaly?

2022-03-18 12:23 UTC, gkartalis commented
TODO: add new OpaqueImageView story with all different cases of the image like loading failing etc

2022-04-21 08:34 UTC, MounirDhahri requested changes
What a nice PR 👏 Thanks @gkartalis for making this huge effort. I left some biased comments for some small improvement. Please let me know what you think

2022-04-21 08:34 UTC, MounirDhahri commented on src/app/Components/ArticleCard.tsx
> +                      width={width - 40}
**nitpick:** 
```suggestion
                      width={width - 2 * space(2)}
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/app/Components/ArticleCard.tsx
> +                      imageURL={article.thumbnailImage?.url}
```suggestion
                      imageURL={imageURL}
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/app/Components/ArticleCard.tsx
> +                    <ImageView imageURL={article.thumbnailImage?.url} style={{ flex: 1 }} />
```suggestion
                    <ImageView imageURL={imageURL} style={{ flex: 1 }} />
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/app/Components/ArticleCard.tsx
> +                  <View style={{ width, flexDirection: "row" }}>
```suggestion
                  <View style={{ width }}>
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/app/Components/ArticleCard.tsx
> +                  <View style={{ width: "100%", aspectRatio: 1.33, flexDirection: "row" }}>
```suggestion
                  <View style={{ width: "100%", aspectRatio: 1.33 }}>
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/app/Components/ArtworkGrids/GenericGrid.tsx
> +        const imgHeight = imgWidth / aspectRatio
**thought:** shouldn't this be 
```
        const imgHeight = imgWidth * aspectRatio
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
> +      return (width - sectionMargins - artworkPadding) / this.props.sectionCount!
**question:** was this broken before?

2022-04-21 08:34 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +          { backgroundColor: backgroundColorStyle },
```suggestion
          { position: "absolute", backgroundColor: backgroundColorStyle },
           ...fastImageStyle,

```

2022-04-21 08:34 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +  placeholderBackgroundColor?: string
**suggestion:** we can use `ColorValue` from `react-native` here
```suggestion
  placeholderBackgroundColor?: ColorValue
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +  const [fIHeight, setFIHeight] = useState(0)
**thought:** How about we set those values already before rendering the component?
```suggestion
  const [fIHeight, setFIHeight] = useState(getActualDimensions()[0)
```

would have been great if getActualDimensions was also returning an object instead of an array here

2022-04-21 08:34 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +  const [fIHeight, setFIHeight] = useState(0)
```suggestion
  const [imageHeight, setImageHeight] = useState(0)
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +    setFIWidth(fw as number)
```suggestion
    const dimensions = getActualDimensions()
    setFIHeight(imageDimensions.height)
    setFIWidth(imageDimensions.width)
```

2022-04-21 08:34 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +  }
**praise:** 🙌

2022-04-21 18:06 UTC, dimatretyak reviewed
wow. impressive work 👍

2022-04-21 18:06 UTC, dimatretyak commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +  }, [props.height, props.width, style.width, style.height, aspectRatio, layoutHeight, layoutWidth])
**suggestion**: use `useCallback` and pass dependencies for it. it seems to me that it will be clearer what these dependencies are used for

```javascripti
const getActualDimensions: () => Array<string | number> = useCallback(() => {
  if (props.height && props.width) {
    return [props.width, props.height]
  }
  if (style.height && style.width) {
    return [style.width, style.height]
  }
  const width = props.width ?? style.width
  if (_.isNumber(width)) {
    return [width, width / aspectRatio!]
  }
  if (_.isString(width)) {
    return [layoutWidth, layoutWidth / aspectRatio!]
  }
  const height = props.height ?? style.height
  if (_.isNumber(height)) {
    return [height * aspectRatio!, height]
  }
  if (_.isString(height)) {
    return [layoutHeight * aspectRatio!, layoutHeight]
  }
  return [layoutWidth, layoutHeight]
}, [props.height, props.width, style.width, style.height, aspectRatio, layoutHeight, layoutWidth])

useEffect(() => {
  const [fw, fh] = getActualDimensions()
  setFIHeight(fh as number)
  setFIWidth(fw as number)
}, [getActualDimensions])
```

2022-04-22 09:41 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +    setFIWidth(fw as number)
definitely agree - I think it's a good idea to make this return an object. this would help here as well https://github.com/artsy/eigen/pull/6265#discussion_r854923217

2022-04-22 09:43 UTC, dimatretyak commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +    setFIWidth(fw as number)
Ah, sorry. I didn't notice this comment yesterday and duplicated your message 😅

2022-04-22 09:57 UTC, MounirDhahri commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +    setFIWidth(fw as number)
no worries, I didn't provide enough context. it's my bad 🙏

2022-04-28 14:26 UTC, brainbicycle commented on src/palette/elements/OpaqueImageView/OpaqueImageView2.tsx
> +        "[OpaqueImageView] Either an aspect ratio or specific dimensions or flex should be specified."
thought, non-blocking: is there a way to get the type system to enforce this for us?

2022-04-28 14:38 UTC, brainbicycle approved these changes
Awesome work! 🎉

2022-05-10 09:04 UTC, gkartalis commented on src/app/Components/ArtworkGrids/GenericGrid.tsx
> +        const imgHeight = imgWidth / aspectRatio
According the [aspect ratio formula](https://stackoverflow.com/a/3461958/7785085)

aspectRatio = width / height => height = width / aspectRatio

2022-05-10 09:05 UTC, gkartalis commented on src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
> +      return (width - sectionMargins - artworkPadding) / this.props.sectionCount!
We checked that a while back with @pvinis and we figured out that it was broken and figured out that this was the way to go.

I remember QAing that as well and confirming that it worked properly, but it was loooong long ago

2022-06-14 11:27 UTC, MounirDhahri approved these changes
Niiiice 🎉 Thanks for this big effort George. I look forward to shipping this.

Also, don't forget to set the feature flag to `readyForRelease` once this is merged and tested

2022-06-14 22:45 UTC, pvinis commented
there are so many files changed here, that might have come from old PRs or pre-appshell stuff? would it make sense to rebase or remove some of these extra things?

2022-06-15 08:56 UTC, MrSltun submitted a review, later dismissed
Thank you for this amazing work George 🔥 🔥  
Looking forward to this being merged and shipped!!! 🚀 🚢

2022-06-16 15:49 UTC, MounirDhahri commented
@gkartalis please feel free to merge this

2022-06-16 15:53 UTC, gkartalis commented
@MounirDhahri I was waiting for approval from @pvinis and @brainbicycle first, but sounds good! We can follow up with new tickets if anything is wrong with this, since it is behind a feature flag! 

🔥🔥🔥🔥🔥🔥🔥🔥 Merging 🔥🔥🔥🔥🔥🔥🔥🔥

2022-06-16 15:53 UTC, merged