feat(metaflags): changing storybook.json into metaflags.json
artsy/eigen pull request #6267
Opened 2022-02-18 22:48 UTC by pvinis

The type of this PR is: **Feature**

This PR resolves []

### Description

This PR comes from some changes we did for the new app shell. Trickling down small improvements to main, while we are in a separate branch :)

The idea behind this PR is that the same way we controlled storybook initialization, we can use it for more things. More specifically, a "new app shell" flag. There is also the usecase of the loggers that @patrinoua is working on #6099. I'm sure we will find more uses for this.

The way it works is:
- the first time you pull after this PR is merged, remember to `yarn setup:artsy`, to do some cleanup.
- from there, you can see the `metaflags.json` file that you will have locally. its ignored, local only, but it controls things for you!
- for now its just for storybook, but soon it will be for at least two other useful things (app shell and loggers)
- the `index.ios.js` and `index.android.js` files, both check for this json file, and control things for us. in general, when we use it for other things, like loggers and app shell, we can quickly import that json file and get a boolean that can give us some control on dev things.
- this file will always be restored with `yarn setup:artsy`, in case something is broken or non-normal. it will be restored from the `metaflags.example.json` file.

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- metaflags! - pavlos

</details>

2022-02-18 22:54 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (metaflags! - pavlos)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7903cd72300ed8012817ccde3be44a959f815ee2
</p>

2022-02-21 08:09 UTC, olerichter00 requested changes

2022-02-21 08:09 UTC, olerichter00 commented on index.android.js
> +}
Let's add some documentation to explain what a meta flag is and how we are using it.

2022-02-21 08:09 UTC, olerichter00 commented on scripts/set-storybook-environment.js
> +// Change `metaflags.json` depending on STORYBOOK env variable
```suggestion
// Change `metaflags.json` depending on env variables (e.g. `STORYBOOK`)
```

2022-02-21 08:58 UTC, pvinis commented on index.android.js
> +}
yup yup! adding it now.

2022-02-21 09:16 UTC, pvinis commented on index.android.js
> +}
👍

2022-02-21 09:49 UTC, olerichter00 approved these changes
Thanks for the docs 🥇

2022-02-21 11:04 UTC, pvinis commented
this should be ready too 👍

2022-02-21 14:26 UTC, pvinis commented
lets go

2022-02-21 14:26 UTC, merged