feat: Sending ID verification email
artsy/eigen pull request #6285
Opened 2022-02-22 10:58 UTC by rajsam003

The type of this PR is: **TYPE**

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-02-22 11:00 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  ❌ **An error occu...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  ❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog.**
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7f67ab3f679b88757ee72672caf8694d7bab4201
</p>

2022-02-22 11:03 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +  const [didSuccessfullyVerifyID, setDidSuccessfullyVerifyID] = useState<boolean | null>(null)
I have created two different states for handling two different case. It can make code easier to understand. 

I can also leave it as it is and create a new state which can play as a conditional argument 
`const [isIDOrEmail, setIsIDOrEmail] = useState<"ID" | "Email">("ID")`

2022-02-22 11:12 UTC, rajsam003 commented on src/lib/utils/verifyID.ts
> +      variables: { input: { userID: null } },
Here I am passing null as userID because it is optional for this endpoint. 
Only admin requires it if he wants to send an ID verification email for a specific user. This case is handled in Torque.

2022-02-22 11:13 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +  const [didSuccessfullyVerifyID, setDidSuccessfullyVerifyID] = useState<boolean | null>(null)
To make things easier you could also try to use an [object with useState](https://blog.logrocket.com/using-react-usestate-object/) or use [useReducer](https://reactjs.org/docs/hooks-reference.html#usereducer).

2022-02-22 11:14 UTC, olerichter00 commented on src/lib/utils/verifyID.ts
> +      variables: { input: { userID: null } },
Then I wouldn't send the userID at all. If it is optional (and in this case not need) we shouldn't send it.

2022-02-22 11:18 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +  const [didSuccessfullyVerifyID, setDidSuccessfullyVerifyID] = useState<boolean | null>(null)
I thought It would make it complicated. 😬
Ok let me try that.

2022-02-22 11:19 UTC, rajsam003 commented on src/lib/utils/verifyID.ts
> +      variables: { input: { userID: null } },
Cool. Thanks

2022-02-22 11:20 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +  const [didSuccessfullyVerifyID, setDidSuccessfullyVerifyID] = useState<boolean | null>(null)
Or you could use a string/enum as the state and do something like this. Whatever is the easiest to understand/read :)

```
const [emailVerificationState, setEmailVerificationState] = useState<{"showBanner" | "verified" | "loading"}>(initialState)
```

2022-02-22 11:21 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +  const [didSuccessfullyVerifyID, setDidSuccessfullyVerifyID] = useState<boolean | null>(null)
You can be creative 🧑‍🎨

2022-02-22 12:41 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +        if (state && state in StateToBlockFurtherIDVerification) {
`StateToBlockFurtherIDVerification` is enum of states that should block further id verification attempts

2022-02-22 12:43 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +}
Refer gravity https://github.com/artsy/gravity/blob/40dcfdfc5fbc10e3b21210483b9cb9059d090f0e/app/models/domain/identity_verification.rb#L40

2022-02-23 08:13 UTC, olerichter00 reviewed
This looks good so far. I've added some comments about the code and about the loading state.

2022-02-23 08:13 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/useHandleVerification.tsx
> +export const useHandleVerification = () => {
This hook still has a lot of repetitive code. We could for example do the following to reduce repetition:

```

type verificationStatus = "idle" | "loading" | "failed" | "success"

const MyComponent = () => {
  [handleEmailVerification, emailVerificationState] = useHandleEmailVerification()
  [handleIDVerification, iDVerificationState] = useHandleIDVerification()
}

const useHandleVerification = (verificationMethod) = { ... }

const useHandleEmailVerification = () => {
  return useHandleVerification(verifyEmail)
}

const useHandleEmailVerification = () => {
  return useHandleVerification(verifyID)
}

```

Although I don't think we need a loading state at all and should use an optimistic response (similar to the follow artist buttons in the app).

2022-02-23 08:29 UTC, MounirDhahri commented on src/lib/Scenes/MyProfile/useHandleVerification.tsx
> +export const useHandleVerification = () => {
This is a great API

2022-02-23 10:09 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +                  handleIDVerification={throttleHandledIDVerification}
we have 2 seconds wait time to get the handleVerification function. I dont think any user can tap on both at the same time. 
@MounirDhahri What do you think? Should we remove this function?

2022-02-23 10:19 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +          <Text color={color("white100")}>Sending ID verification email...</Text>
I think we need this to show the user that the email is being sent. 
Dont you think we need it? 🤔

2022-02-23 10:20 UTC, rajsam003 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +          {didSuccessfullyVerifyID ? resultText : "Something went wrong, please try again"}
I have already asked about this on the ticket 
https://artsyproduct.atlassian.net/browse/CX-2239?focusedCommentId=46348
Let's wait for their replies.

2022-02-23 11:21 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +          <Text color={color("white100")}>Sending ID verification email...</Text>
We could just be optimistic and tell the user that the email has been sent (which should in almost all cases happen). normalizeMyProfileBio

2022-02-23 11:22 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
> +                  handleIDVerification={throttleHandledIDVerification}
Can we just disable the butten as soon as the response has been sent? Like this we don't have to handle any timers.

2022-02-23 17:07 UTC, MounirDhahri approved these changes
Looks good to me. I left one small comment that's not launch blocking

2022-02-23 17:07 UTC, MounirDhahri commented on src/lib/Scenes/MyProfile/useHandleVerification.tsx
> +
I don't think is necessary Sam since it's actually making the code more complex instead

2022-02-24 07:47 UTC, olerichter00 requested changes

2022-02-24 07:47 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/useHandleVerification.tsx
> +    }, [])
Isn't this exactly the code above? Feel free to merge like this, but I think there is potential here to extract the code and avoid the duplication.

2022-02-24 17:09 UTC, olerichter00 approved these changes
Looks great!

2022-02-24 17:09 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/useHandleVerification.tsx
> +    return emailToConfirm
```suggestion
    return confirmationOrError?.unconfirmedEmail
```

2022-02-24 17:09 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/useHandleVerification.tsx
> +    return state
```suggestion
    return confirmationOrError?.identityVerificationEmail?.state
```

2022-02-24 17:09 UTC, olerichter00 commented on src/lib/Scenes/MyProfile/useHandleVerification.tsx
> +const SENT_STATE_TIMEOUT = 6000
```suggestion
const VERIFICATION_BANNER_TIMEOUT = 6000
```

2022-02-24 17:10 UTC, olerichter00 approved these changes
I've added a few suggestions. Feel free to merge 🚀

2022-02-24 17:50 UTC, merged

2022-02-25 12:06 UTC, dblandin commented
Love the demo video!! ❤️