WIP feat(CX-2293): explanatory Banner Appears in My Collection after Artwork Submission
artsy/eigen pull request #6345
Opened 2022-02-28 19:42 UTC by dariakoko

The type of this PR is: **Feature**

This PR resolves [CX-2293]

### Description

Show explanatory banner when successfully uploading an Artwork to MyCollection with SWA flow.
The banner is displayed once per session and can be closed
Based on LocalStorage

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Show explanatory banner when successfully uploading an Artwork to MyCollection with SWA flow. The banner is displaued once per session and can be closed -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-02-28 19:44 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Show explanatory banner when successfully uploading an Artwork to MyCollection with SWA flow. The banner is displaued once per session and can be closed -daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f80dcbe290a109abaa30daecf2a0997003617a4d
</p>

2022-03-02 08:54 UTC, MounirDhahri requested changes
Thanks for this effort Daria and using AsyncStorage to solve this. I would however prefer if we use our existing GlobalStore for this. 
Inside the `VisualClueModel` we can add a property indicating during a session if the user saw the banner or not or also make it visible for them. When a property is available in a model inside a `sessionState`, it does not get persisted between sessions. We do that for example inside the `ToastModel`.
https://github.com/artsy/eigen/blob/476c3a280a8126056b1d093b51db3e4eba5dbeb2/src/app/store/ToastModel.ts#L5-L8
We can do something like this inside the `VisualCluesModel` to support session visual clues

2022-03-02 09:14 UTC, rajsam003 approved these changes
LGTM

2022-03-09 16:17 UTC, dariakoko commented
Thank you for the suggestion @MounirDhahri ! Sorry it took that long
I added changes, I hope this is what you meant :)

2022-03-15 22:38 UTC, dariakoko commented
one test is failing after merge with mail, i'll check main for updates later

2022-03-16 09:49 UTC, rajsam003 commented on src/app/store/VisualClueModel.ts
> +    nextId: 0,
```suggestion
    nextClueId: 0,
```

2022-03-16 09:51 UTC, rajsam003 commented on src/app/store/VisualClueModel.ts
> +    clues: Array<Omit<string, "positionIndex">>
👌

2022-03-16 09:54 UTC, rajsam003 commented on src/app/store/config/visualClues.ts
> +    description: "The banner shown after artwork submission with SWA flow",
**question**: Where will this description get displayed?

2022-03-16 13:06 UTC, dariakoko commented on src/app/store/VisualClueModel.ts
> +    nextId: 0,
Thanks for the suggestion Sam. I don't think we need to change `nextId` to  `nextClueId`. `nextId` here refers to the sesionState.

2022-03-16 14:54 UTC, dariakoko commented on src/app/store/config/visualClues.ts
> +    description: "The banner shown after artwork submission with SWA flow",
I guess this is just a description to explain what the certain clue is meant for

2022-03-16 15:02 UTC, rajsam003 commented on src/app/store/config/visualClues.ts
> +    description: "The banner shown after artwork submission with SWA flow",
We can explain that by a comment also. I dont think we need a description property for it. 
@olerichter00 What do you think? Why do we need?

2022-03-16 15:16 UTC, olerichter00 commented on src/app/store/config/visualClues.ts
> +    description: "The banner shown after artwork submission with SWA flow",
I've added it as a property to force people to add it here and maybe at some point this could be useful if we want to show a list of visual clues for example in the admin menu. You're right and it's not necessary but I don't see that it has any downsides.

2022-03-17 12:08 UTC, MounirDhahri approved these changes
nice PR 🙏

2022-03-17 12:09 UTC, merged