[docs] on betas
artsy/eigen pull request #6360
Opened 2022-03-02 17:51 UTC by patrinoua

The type of this PR is: **documentation**
docs on betas

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

ⓘ 'User-facing' changes will be published as release notes.

#### Cross-platform user-facing changes

- Rename modal title - patrinoua

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-03-02 17:52 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Rename modal title - patrinoua)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a3530900011d5080cdc99d7191a1d870a8fe6431
</p>

2022-03-02 17:53 UTC, pvinis commented on docs/test_on_real_device.md
> +To create a beta version, you need to checkout the branch that has the changes (or `main` branch if the changes are already merged) and run
we haven't tested this with other branches, or not much, anyway. could be interesting.. @brainbicycle @MounirDhahri opinions?

2022-03-02 17:54 UTC, pvinis commented on docs/test_on_real_device.md
> +and soon you will have betas on testflight and firebase
```suggestion
and soon you will have betas on testflight and firebase. ask `eigen beta?` on the #practice-mobile channel to get the links if you are not in the betas yet.
```

2022-03-03 09:02 UTC, MounirDhahri requested changes

2022-03-03 09:02 UTC, MounirDhahri commented on docs/deploy_to_beta.md
> +and soon you will have betas on testflight and firebase
**issue:** I understand this makes it easier to learn how to create builds, but Isn't this what we have already in the first line of this file
```
Deployment to TestFlight and Play Store is handled by Circle CI. Nightly betas are release automatically, but if you need to deploy something right away, run `./scripts/deploy-both` (or `./scripts/deploy-ios` or `./scripts/deploy-android` for individual releases) locally to trigger a beta build on CI
```
I feel like this might not be needed

2022-03-03 09:02 UTC, MounirDhahri commented on docs/deploy_to_beta.md
> +Ask `eigen beta?` on the #practice-mobile channel to get the links if you are not in the betas yet.
**praise:** nice, it makes sense to mention this somewhere

2022-03-09 16:24 UTC, patrinoua commented on docs/test_on_real_device.md
> +To create a beta version, you need to checkout the branch that has the changes (or `main` branch if the changes are already merged) and run
I don't see why it wouldn't work on other branches but I can remove it if we are not sure about this.

2022-03-09 16:28 UTC, patrinoua commented on docs/deploy_to_beta.md
> +Ask `eigen beta?` on the #practice-mobile channel to get the links if you are not in the betas yet.
I am not sure I understand what you mean here. something like this?

## Invite testers
Ask `eigen beta?` on the #practice-mobile channel to get the links if you are not in the betas yet.

2022-03-09 16:29 UTC, patrinoua commented on docs/deploy_to_beta.md
> +and soon you will have betas on testflight and firebase
To me this is the TLDR version - just quickly how you can create a beta version, and then we elaborate more. 
If you find this unnecessary I can remove it.

2022-03-11 14:35 UTC, brainbicycle commented on docs/test_on_real_device.md
> +To create a beta version, you need to checkout the branch that has the changes (or `main` branch if the changes are already merged) and run
It should work on other branches but I might discourage creating betas on other branches unless really necessary. Reason being it is confusing when our betas in TestFlight don't represent the latest on main for other teams. I have done it in the past so I am a bit of a hypocrite but if it becomes a regular practice it will be confusing pretty quickly. 
I think it is useful though but would encourage us to think about how we can have distinct betas for non-main branches if we want to do this.

2022-03-14 13:10 UTC, patrinoua commented on docs/test_on_real_device.md
> +To create a beta version, you need to checkout the branch that has the changes (or `main` branch if the changes are already merged) and run
Thanks for elaborating more on that 🙏  I've updated our docs to reflect that.

2022-03-14 13:57 UTC, MounirDhahri commented on docs/deploy_to_beta.md
> +Ask `eigen beta?` on the #practice-mobile channel to get the links if you are not in the betas yet.
(Sorry I was out sick)
yes, that's what I meant.

2022-03-14 13:57 UTC, MounirDhahri commented on docs/deploy_to_beta.md
> +and soon you will have betas on testflight and firebase
I didn't feel it long but I will leave it to you and other reviewers to decide.

2022-03-14 13:58 UTC, MounirDhahri approved these changes
🙌

2022-03-14 13:58 UTC, merged

2022-03-14 13:58 UTC, MounirDhahri commented
Niice, thanks Angela