chore: Update currency and metrics
artsy/eigen pull request #6374
Opened 2022-03-04 10:17 UTC by rajsam003

The type of this PR is: Chore

This PR resolves [CX-2320]

### Description

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Update currency and length unit - sam

</details>

2022-03-04 10:18 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (Update currency and length unit - sam)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 234a9813f0455c7948c699bf61e5cc6b44acda64
</p>

2022-03-04 10:18 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +      await updateMyUserProfile({
Instead of calling the API in the model. I called it here. With this, we dont need any migration.

2022-03-04 10:19 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        GlobalStore.actions.userPrefs.setMetric(metricUnitFromGravity.toLowerCase() as Metric)
I used `lowercase()` because in the API we have uppercase and in Eigen we have lowercase values. `["cm", "in"]`

2022-03-04 10:20 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +              initialParams={{
This is not my change, this is prettier's change.

2022-03-04 10:29 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        GlobalStore.actions.userPrefs.setMetric(metricUnitFromGravity.toLowerCase() as Metric)
If we want to change we have to check in the whole project. We might need a separate ticket for that. 
Also, the naming is different. In the API it is `lengthUnitPreference` and in Eigen it is `Metric`

2022-03-04 10:53 UTC, olerichter00 requested changes
This looks great so far! I would just move some of the code.

Will there be a follow-up PR to update preferences in Gravity if the user changes them on the device?

2022-03-04 10:53 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +      await updateMyUserProfile({
Wouldn't it make more sense to move the logic to [UserPrefsModel](https://github.com/artsy/eigen/blob/ac35bedebfa65d75c373f0f6030208be43816285/src/app/Scenes/Search/UserPrefsModel.tsx#L27)?

We already use this pattern [here](https://github.com/artsy/eigen/blob/ac35bedebfa65d75c373f0f6030208be43816285/src/app/Scenes/BottomTabs/BottomTabsModel.ts#L37)

2022-03-04 10:53 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +  const loadLengthUnitAndCurrency = async () => {
What do you think about hydrating the store with the user's remote preferences when the app starts? The preferences will potentially be used in different places in the app and hydrating the store for every screen is probably not the best idea.

We do something similar with [Echo](https://github.com/artsy/eigen/blob/ac35bedebfa65d75c373f0f6030208be43816285/src/app/store/config/EchoModel.tests.tsx#L45).

2022-03-04 10:53 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        GlobalStore.actions.userPrefs.setMetric(metricUnitFromGravity.toLowerCase() as Metric)
👍

2022-03-04 11:21 UTC, olerichter00 commented
@rajsam003 I'm sure this is a **feature** and not a **chore**. https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

2022-03-04 11:27 UTC, rajsam003 commented
> @rajsam003 I'm sure this is a **feature** and not a **chore**. https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

We are not introducing any new feature. So I thought it should be a chore. 🤔

2022-03-04 11:29 UTC, olerichter00 commented
> We are not introducing any new feature. So I thought it should be a chore. 🤔

Well, the new feature is that the app considers the artsy-wide metric preferences of the user.

2022-03-04 11:52 UTC, olerichter00 commented
Even if we haven't implemented any logic to update the preferences yet, this change will already set the metric preferences to country-specific default values.

2022-03-04 13:48 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +  const loadLengthUnitAndCurrency = async () => {
Thanks for this idea. I just checked [the docs](https://easy-peasy.vercel.app/docs/api/persist.html#rehydrating-your-store). I will try this.

2022-03-04 13:49 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +      await updateMyUserProfile({
Do you mean calling [this query](https://github.com/artsy/eigen/blob/234a9813f0455c7948c699bf61e5cc6b44acda64/src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx#L335)
?

2022-03-04 13:51 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +      await updateMyUserProfile({
Because this line of code is actually updating gravity based on user selection and while saving the artwork.

2022-03-08 19:31 UTC, olerichter00 reviewed
Thanks a lot for the update 🙇  

Just left a comment with a question.

2022-03-09 07:54 UTC, olerichter00 requested changes
Very nice!

Now we just have to make sure to set the metrics when the user logs in or signs up and to prevent setting the metrics in `didRehydrate` when the user is not logged in. 

The current solution will set both metric prefs to `undefined` if the store rehydrates when the user is not logged in.

2022-03-09 08:36 UTC, rajsam003 commented
> 

Thanks @olerichter00 
I just checked this case. When the user is not logged and the store rehydrates,  the preferences gets default values from the modal i.e. `USD` for currency and `cm` for the metric unit. 

Currently, there is [no default value for metirc](https://github.com/artsy/eigen/blob/b1b053f02cd1b13918c10e75d5e08a8ce0c32338/src/app/Scenes/Search/UserPrefsModel.tsx#L22). I am pushing the change in my next commit. 

This can overcome the situation of `undefined` values. Also, I dont think there is a way to use the app without login or signup. 🤔

2022-03-09 08:40 UTC, olerichter00 commented
> Thanks @olerichter00 I just checked this case. When the user is not logged in and the store rehydrates, the preferences gets default values from the modal i.e. `USD` for currency and `cm` for the metric unit.

My idea is that we want to have the default values from Gravity as soon as the user logs in or signs up because these default values are country specific.
> 
> Currently, there is [no default value for metirc](https://github.com/artsy/eigen/blob/b1b053f02cd1b13918c10e75d5e08a8ce0c32338/src/app/Scenes/Search/UserPrefsModel.tsx#L22). I am pushing the change in my next commit.

This is ok, I guess.

> 
> This can overcome the situation of `undefined` values. Also, I dont think there is a way to use the app without login or signup. 🤔

If you're starting the app while being logged I see a warning that the currency is not supported because the query returns `null` in this case.

2022-03-09 08:41 UTC, olerichter00 commented on src/app/Scenes/Search/UserPrefsModel.tsx
> +    actions.setCurrency(me?.currencyPreference as Currency)
We don't want to set the values if the query fails or returns null.

```suggestion
    const me = await fetchMe()

    if(!me) return

    actions.setMetric(me.lengthUnitPreference.toLowerCase() as Metric)
    actions.setCurrency(me.currencyPreference as Currency)
```

2022-03-09 08:48 UTC, rajsam003 commented
> My idea is that we want to have the default values from Gravity as soon as the user logs in or signs up because these default values are country specific.

That makes sense. Gravity should send the country-specific default values. Is it already implemented in Gravity or do we need a ticket?

2022-03-09 08:49 UTC, rajsam003 commented
> If you're starting the app while being logged I see a warning that the currency is not supported because the query returns null in this case.

So we need a ticket to work on Gravity?

2022-03-09 09:07 UTC, olerichter00 commented
> That makes sense. Gravity should send the country-specific default values. Is it already implemented in Gravity or do we need a ticket?

Yes, it is already implemented.

2022-03-09 09:08 UTC, olerichter00 commented
> > If you're starting the app while being logged I see a warning that the currency is not supported because the query returns null in this case.
> 
> So we need a ticket to work on Gravity?

We need to fetch the values from Gravity as well as soon as the user logs in or signs up.

2022-03-09 10:00 UTC, olerichter00 requested changes
Does the metric preferences get fetched when the user signs up/in? I can't find the code.

2022-03-09 10:19 UTC, rajsam003 commented on src/app/Scenes/Search/UserPrefsModel.tsx
> +const DEFAULT_METRIC = "cm"
Should it be `in`?
Because on UI `cm` is the first radio button. So it makes sense to make it default. Just like how `USD` is the first option in Currency select.

2022-03-09 11:02 UTC, olerichter00 commented on src/app/Scenes/Search/UserPrefsModel.tsx
> +const DEFAULT_METRIC = "cm"
Good question. In the backend `in` is the default because most of our customers live in the US.

2022-03-09 11:05 UTC, rajsam003 commented on src/app/store/AuthModel.ts
> +
@olerichter00 What do you think about this? It is setting the preferences after successful login. 
Didnt add the logic for` if (!me) {return}` because I dont want to return it if `me` is undefined.

2022-03-09 11:07 UTC, rajsam003 commented on src/app/store/AuthModel.ts
> +
Sam as above

2022-03-09 13:02 UTC, rajsam003 commented on src/app/Scenes/Search/UserPrefsModel.tsx
> +}
Made this more generic

2022-03-09 13:11 UTC, olerichter00 requested changes

2022-03-09 13:11 UTC, olerichter00 commented on src/app/store/AuthModel.ts
> +      setUserPrefsFromGravity()
Can we just call `fetchRemoteUserPrefs` from the user preference model here?

2022-03-09 13:11 UTC, olerichter00 commented on src/app/Scenes/Search/UserPrefsModel.tsx
> +export const setUserPrefsFromGravity = async () => {
Maybe we could give this a different name. Eigen should be agnostic about which service stores the preferences.

2022-03-09 13:19 UTC, rajsam003 commented on src/app/Scenes/Search/UserPrefsModel.tsx
> +export const setUserPrefsFromGravity = async () => {
Then I will revert it to the previous change. No need of this function.

2022-03-09 14:10 UTC, olerichter00 requested changes

2022-03-09 14:10 UTC, olerichter00 commented on src/app/store/migration.ts
> +    state.userPrefs.metric = "in"
Wouldn't this migration override all existing metric preferences?

2022-03-09 14:10 UTC, olerichter00 commented on src/app/store/AuthModel.ts
> +      GlobalStore.actions.userPrefs.fetchRemoteUserPrefs()
Nice 👍

2022-03-09 14:28 UTC, rajsam003 commented on src/app/store/migration.ts
> +    state.userPrefs.metric = "in"
Yes, but we get the user preference set by the user from Gravity once log in. That will value will be overridden everywhere.

2022-03-09 14:29 UTC, rajsam003 commented on src/app/store/migration.ts
> +    state.userPrefs.metric = "in"
I think it will override even without login.

2022-03-09 14:37 UTC, olerichter00 commented on src/app/store/migration.ts
> +    state.userPrefs.metric = "in"
👍

2022-03-09 14:37 UTC, olerichter00 approved these changes
🙌

2022-03-09 14:38 UTC, merged