[WIP] chore: Rename MyProfile to Profile
artsy/eigen pull request #6395
Opened 2022-03-10 10:58 UTC by rajsam003

The type of this PR is: Chore

This PR resolves [this ticket](https://www.notion.so/artsy/4d6887f022ad4da6bead5db477d2c5fb?v=8b6b479aabea4c9f9403f68ea776370a&p=aec92bf745aa4b14ad2a770a049c1462)

Here is the [discussion](https://artsy.slack.com/archives/C02PE5Q9J1F/p1643907148658409)

### Description

### PR Checklist (tick all before merging)

- [ ] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [ ] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [ ] I have documented any follow-up work that this PR will require, or it does not require any.
- [ ] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [ ] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- Rename MyProfile to Profile everywhere in the app - sam

</details>

2022-03-10 11:00 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Dev changes (Rename MyProfile to CollectorProfile everywhere in the app - sam)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9c95553abb1178f5457be485be5cec8774654350
</p>

2022-03-10 11:03 UTC, pvinis commented
I thought the idea was to remove `My`, not to add `Collector`, right?

2022-03-10 11:05 UTC, pvinis commented on src/app/navigation/routes.tsx
> -    addRoute("/my-profile", "MyProfile"),
if we really are changing these, it might be worth keeping the old route too, and point it also the new component. that's so links etc keep working.

2022-03-10 11:06 UTC, rajsam003 commented
> I thought the idea was to remove `My`, not to add `Collector`, right?

I wanted the same. but then we decided to make it `CollectorProfile` in our retrospective. 
I am happy to make it `Profile` though. Let's what others feel about it.

2022-03-10 11:11 UTC, pvinis commented
I would definitely vote for just `Profile`, even though I don't mind `MyProfile` that much. But definitely `Profile` seems like a better choice. It's a simpler, there is only one profile in the app. that one. no need to give it an extra description. I was not in the discussion so I don't know what the other choices and reasoning were, so I will not block this, but as a reviewer I definitely think this is not an improvement on what we have now 🤔.

2022-03-10 11:51 UTC, rajsam003 commented on src/app/Scenes/CollectorProfile/utils.ts
> +export const normalizeCollectorProfileBio = (bio: string) => bio.replace("\n", "")
This is in 2 places. 
`src/app/Scenes/CollectorProfile/utils.tests.ts`
`src/app/Scenes/CollectorProfile/CollectorProfileHeaderMyCollectionAndSavedWorks.tsx`

2022-03-10 14:53 UTC, MounirDhahri requested changes

2022-03-10 14:53 UTC, MounirDhahri commented on src/app/navigation/routes.tsx
> -    addRoute("/my-profile", "MyProfile"),
+1 
Unfortunately, we should no longer be changing this route. This is because we are using this route for marketing campaigns related to saved alerts "/my-profile/saved-search-alerts"

2022-04-21 08:55 UTC, MounirDhahri commented
Closing PR for inactivity - please feel free to reopen it if needed 👌

2022-04-21 08:55 UTC, closed without merging