feat: Add skip ahead link
artsy/eigen pull request #6402
Opened 2022-03-10 15:54 UTC by rajsam003

The type of this PR is: Feature

This PR resolves [CX-2415]

### Description

This PR adds a link to skip the `Select and Artwork` page below the search artworks textbox.

|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/157700122-e0803d41-c174-45f7-90c9-98855bab1695.png)|![image](https://user-images.githubusercontent.com/17421923/157700031-b4694673-fd8a-4f31-87b4-372b4b154d83.png)|

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Added a link to skip the `Select and Artwork` page below the search artworks textbox - sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[CX-2415]: https://artsyproduct.atlassian.net/browse/CX-2415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-03-14 13:31 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
> +  }, [viewer.artworks?.edges?.length])
Not quite sure if we need this logic at all. When the screen opens artworks get immediately loaded and `showSkipAheadToAddArtworkLink` will be set to true (and it will never get set to false again). Can't we instead just show the link without any condition?

2022-03-14 16:16 UTC, rajsam003 commented
> I'm not quite sure about the requirements and I couldn't find anything about it in the ticket. Will this new link replace the current "Go to Add Artwork Details" button that appears at the bottom of the artwork grid or will we keep both?

@olerichter00 Me and Pierluca discussed this in this ticket. We came to the conclusion that "Go to Add Artwork Details" button will be there no matter what but the skip ahead link will be disabled if there is no artwork.

2022-03-14 16:17 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
> +  }, [viewer.artworks?.edges?.length])
We need this condition to check if there is any artwork then show the link, if the length is 0 then dont show.

2022-03-14 16:19 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
> +  }, [viewer.artworks?.edges?.length])
Ok, I see. Then let's add the logic to hide the link.

2022-03-14 16:51 UTC, MrSltun submitted a review, later dismissed
Awesome solution Sam! 🔥  🚀  just left a small non-blocking comment

2022-03-14 16:51 UTC, MrSltun commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
> +
**suggestion**: maybe we could have the whole line clickable?
In my opinion it is easier to click the whole section instead of a specific text

2022-03-14 18:04 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
> +  }, [viewer.artworks?.edges?.length])
I dont understand what makes the difference. Initailly the link will not be rendered because `showSkipAheadToAddArtworkLink` is `false`. Once we get the artwork from the API we would know the count of artworks(i.e, `viewer.artworks?.edges?.length`. If it is more than 0, we set `showSkipAheadToAddArtworkLink` to `true`.  Does that make sense?

2022-03-15 08:29 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
> +
So as per Pierluca's comment on the ticket, you are suggestion is right. I will push the change. 👍🏽

2022-03-15 08:48 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
> +  }, [viewer.artworks?.edges?.length])
So you just want to hide the link for a few milliseconds when the artworks are loading?

2022-03-15 08:49 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
> +  }, [viewer.artworks?.edges?.length])
https://user-images.githubusercontent.com/4691889/158340277-582af93b-b6ec-425b-9fae-aa10b8cf3a70.mp4

2022-03-15 08:51 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
> +  }, [viewer.artworks?.edges?.length])
Yes I made some updates. I will push it soon. Thanks @olerichter00

2022-03-15 14:28 UTC, olerichter00 requested changes
Thanks for the change 👍 

Just added a suggestion to simplify a bit. Feel free to merge after this is resolved :)

2022-03-15 15:07 UTC, rajsam003 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
> +            showSkipAheadToAddArtworkLinkHandler={showSkipAheadToAddArtworkLinkHandler}
Good idea

2022-03-15 15:11 UTC, olerichter00 approved these changes
Nice work! You can rebase your branch to make the failing test pass. It should already be fixed.

2022-03-15 15:11 UTC, olerichter00 commented
#squashongreen

2022-03-15 15:53 UTC, merged