Update deploy_to_app_store.md
artsy/eigen pull request #6445
Opened 2022-03-17 11:34 UTC by patrinoua

The type of this PR is: **docs**

Adds some missing information to the release documentation

### Description

### PR Checklist (tick all before merging)
- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀
- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>
### Changelog updates

#### Cross-platform user-facing changes
#### iOS user-facing changes
-
#### Android user-facing changes
-
#### Dev changes
-

</details>

2022-03-17 11:35 UTC, ArtsyOpenSource commented
<!--
  1 failure:  Danger failed to ...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.ts`.
  </td>
    </tr>
  </tbody>
</table>



## Error RangeError
```
/home/circleci/project/scripts/changelog/generateChangelogSectionTemplate.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.conf [...]

2022-03-23 13:33 UTC, brainbicycle requested changes
minor change requests, think we still want to update release notes before running promotion script and 2 the idfa info is out of date and can be removed, thanks for updating!

2022-03-23 13:33 UTC, brainbicycle commented on docs/deploy_to_app_store.md
> -1. Update [`release_notes.txt`](https://github.com/artsy/eigen/blob/main/fastlane/metadata/en-US/release_notes.txt) with the **user-facing** release notes for this version.
we still have to update the release notes right? should this stay?

2022-03-23 13:33 UTC, brainbicycle commented on docs/deploy_to_app_store.md
> +### IDFA
this is actually no longer true we removed idfa access a while back, we should be able to delete this section

2022-04-14 14:39 UTC, patrinoua commented on docs/deploy_to_app_store.md
> -1. Update [`release_notes.txt`](https://github.com/artsy/eigen/blob/main/fastlane/metadata/en-US/release_notes.txt) with the **user-facing** release notes for this version.
I removed this from here because we have now added this section in notion on the [Release Captain tasks](https://www.notion.so/artsy/Release-Captain-Tasks-7ca3e6f5d16e41079a1fb1b1706bd018#9b2d913d4a6343f9a90f78b7c9749e33)
![Screen Shot 2022-04-14 at 16 38 17](https://user-images.githubusercontent.com/36475005/163413725-a9136424-a612-4009-ab2a-74d677dd3875.png)

2022-05-03 09:58 UTC, MounirDhahri commented on docs/deploy_to_app_store.md
> +1. Run `./scripts/promote-beta-to-submission-ios`. This will submit the **most recent beta** for App Store review.
@brainbicycle as we are getting more serious with our code freeze policy, this is going to be obsolete kind of. we should soon start thinking of a better way than doing this manually. 

What I am thinking of is updating the script to let you choose a build to promote - not sure how to inject the user choice into ci though 🤷‍♂️

2022-05-03 09:58 UTC, MounirDhahri commented on docs/deploy_to_app_store.md
> +1. Run `./scripts/promote-beta-to-submission-ios`. This will submit the **most recent beta** for App Store review.
as we are getting more serious with our code freeze policy, this is going to be obsolete kind of. we should soon start thinking of a better way than doing this manually.  (cc @brainbicycle )

What I am thinking of is updating the script to let you choose a build to promote - not sure how to inject the user choice into ci though 🤷‍♂️

2022-11-16 11:50 UTC, MounirDhahri commented
Closing this PR for inactivity, please feel free to reopen it if it's still a work in progress.

2022-11-16 11:50 UTC, closed without merging