docs: Deploy to playstore
artsy/eigen pull request #6448
Opened 2022-03-17 12:13 UTC by rajsam003

The type of this PR is: Documentation

This PR resolves []

### Description

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-03-17 12:14 UTC, ArtsyOpenSource commented
<!--
  1 failure:  Danger failed to ...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.ts`.
  </td>
    </tr>
  </tbody>
</table>



## Error RangeError
```
/home/circleci/project/scripts/changelog/generateChangelogSectionTemplate.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.conf [...]

2022-03-23 13:44 UTC, brainbicycle requested changes
Thanks for updating, 2 minor change requests:
1. I think we still want the update release notes step before submitting a final version
2. There is a difference between Android release in that Android builds are released automatically after submitting and going through review, think we should change some of the wording and headings to make that clear

2022-03-23 13:44 UTC, brainbicycle commented on docs/deploy_to_play_store.md
>  ## Preparing to Ship a Final Version
```suggestion
## Ship a Final Version
```

2022-03-23 13:44 UTC, brainbicycle commented on docs/deploy_to_play_store.md
>  ## Release to Play Store
```suggestion
## Check on Play Store Release
```
Since these are released automatically better to rename this section

2022-03-23 13:44 UTC, brainbicycle commented on docs/deploy_to_play_store.md
>  Our Play Store releases are done manually and are available to users **immediately**. Google might review the app later, but it's not a requirement to publish a release. Don't release unless you are
```suggestion
Our Play Store releases are released **automatically** once reviewed. Don't release unless you are available over the next few hours to monitor Sentry for errors.
```

2022-05-02 13:08 UTC, brainbicycle approved these changes

2022-05-02 13:08 UTC, merged