Disable edit artwork coming from SWA
artsy/eigen pull request #6451
Opened 2022-03-17 14:30 UTC by rajsam003

The type of this PR is: Feature

This PR resolves [CX-2348]

### Description

Disable edit option for artwork in my collection coming from SWA

|Artwork not from SWA| Artwork from SWA|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/158828293-022160ad-b46d-4843-8dec-6b10eb13c7be.png)|![image](https://user-images.githubusercontent.com/17421923/158828048-d524bc88-7ce9-472e-aedc-455b83e83b75.png)|

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Disable edit option for artwork in my collection coming from SWA - sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-03-17 14:31 UTC, ArtsyOpenSource commented
<!--
  1 failure:  Danger failed to ...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.ts`.
  </td>
    </tr>
  </tbody>
</table>



## Error RangeError
```
/home/circleci/project/scripts/changelog/generateChangelogSectionTemplate.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.config.js: /home/circleci/project/relay.conf [...]

2022-03-17 15:35 UTC, olerichter00 requested changes
Can we remove the button on the new My Collection artwork screen as well?

2022-03-17 16:38 UTC, rajsam003 commented
> Can we remove the button on the new My Collection artwork screen as well?

We already have that implementation. 
https://github.com/artsy/eigen/blob/3c96f7e1e556656a9c708b5f3be76a5b965d1f8b/src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx#L102

2022-03-17 17:38 UTC, dariakoko submitted a review, later dismissed
Thanks Sam, looks good 👍

2022-03-17 18:07 UTC, MrSltun approved these changes
LGMT! 🚀 🚀

2022-03-18 09:12 UTC, olerichter00 commented
> > Can we remove the button on the new My Collection artwork screen as well?
> 
> We already have that implementation.
> 
> https://github.com/artsy/eigen/blob/3c96f7e1e556656a9c708b5f3be76a5b965d1f8b/src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx#L102

This implementation disables editing the artwork as long as the artwork is in progress (you cand find more information about the purpose in this ticket: https://artsyproduct.atlassian.net/browse/CX-2326).

2022-03-18 10:35 UTC, MounirDhahri submitted a review, later dismissed
LGTM 🎉 I left just a small comment

2022-03-18 10:35 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
> +      it("hides the edit button when the artwork has consignmentSubmission prop", async () => {
```suggestion
      it("hides the edit button when the artwork is coming from a submission", async () => {
```

2022-03-18 10:35 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tests.tsx
> +    it("hide edit button if the artwork has consignmentSubmission prop", () => {
**nitpick:** same comment as above here

2022-03-18 10:35 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx
> +  }, [props.artwork])
**praise:** 👏

2022-03-18 10:55 UTC, MounirDhahri commented
If you rebase main you should have your failed test fixed.

2022-03-18 11:20 UTC, rajsam003 commented
> If you rebase main you should have your failed test fixed.

Thank you

2022-03-18 12:00 UTC, olerichter00 approved these changes
Thanks a lot for the fix 👍

2022-03-18 12:48 UTC, merged