fix(SWA-267): fix visualised lists bug
artsy/eigen pull request #6472
Opened 2022-03-22 12:47 UTC by patrinoua

The type of this PR is: **feat**

This PR resolves [SWA-267]

### Description

#### Artist Auto Suggest
- [x] Move artist auto suggest to app/components so that it can be used from other places as well
- [x] Use a ScrollView instead of a FlatList

#### Location Auto Suggest
- [ ] Move artist auto suggest to app/components so that it can be used from other places as well
- [ ] Use a ScrollView instead of a FlatList

### PR Checklist (tick all before merging)
- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀
- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>
### Changelog updates

#### Cross-platform user-facing changes
#### iOS user-facing changes
-
#### Android user-facing changes
-
#### Dev changes
- resolves "Visualised lists" error 

</details>

2022-03-22 16:19 UTC, MounirDhahri commented on src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
> -  }, [])
**thought:** do we never use this?

2022-03-22 16:19 UTC, MounirDhahri commented
Thanks for quickly working on this Angela 🙏

2022-03-23 12:04 UTC, patrinoua commented on src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
> -  }, [])
These were going into the Flatlist and since we've now removed the Flatlist we probably don't need them.
I've also just updated the query to directly fetch 64 instead of 34 artists to eliminate the need for loadMore()

2022-03-23 12:10 UTC, patrinoua commented
Also I noticed that ArtistAutosuggest is implemented twice. 

Once in src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx (originally implemented under the new submission flow but extracted in this PR)

and once in src/app/Scenes/Search/AutosuggestResults.tsx where we are still using a FlatList so we are probably getting the same error somewhere else as well.

I am not sure this PR is where we should fix this.

However, I think we should seriously consider keeping an up to date toolkit with standard implementations of things in a central location and not implementing components every time from scratch in the file where we use them, so we can easily implement changes and bug fixes.

2022-03-23 12:19 UTC, pvinis commented
feel free to dedup that artistsuggestion component. but this can be a separate work for office hours :)

2022-03-23 12:20 UTC, pvinis commented on src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
> -  }, [])
would you mind adding a video on the PR description of how this works?

2022-03-23 18:20 UTC, patrinoua commented on src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
> -  }, [])
done

2022-03-24 15:30 UTC, patrinoua commented
@MounirDhahri @pvinis can we merge this?

2022-03-24 17:47 UTC, MounirDhahri requested changes
Thanks for revisiting this Angela and making the refactorings. I do think though that the most straightforward way here would be for you to recreate the component only for the consignments flow. It would be a simple view that loads for example a maximum of 5 artists and we won't need to have any logic around the scrollviews/flatlist

2022-03-24 17:47 UTC, MounirDhahri commented on src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
> +      <ScrollView
By using the scroll view here I feel like we are not solving the issue of nested scrollviews but instead only going around it. We will though loose the virtualization benefits by using the scrollview directly and we won't be able to use this in other places since it's now only using a fixed number of artists

2022-03-24 18:18 UTC, pvinis commented
in the video, i see a warning for "same key children", have you handled that?

2022-03-25 10:24 UTC, patrinoua commented
@MounirDhahri @pvinis Thanks for the comments & suggestions! 🙏 
I've updated the PR description and the implementation to be similar to Ole's https://github.com/artsy/eigen/pull/6466/files let me know if it's ok or I should update something. 
I've also noticed that there is some weird behaviour when erasing but this should probably be resolved under a different ticket.

2022-03-25 10:40 UTC, AlicanAkyuz commented
@patrinoua is this the weird behaviour you mentioned about erasing 👇 

https://user-images.githubusercontent.com/42584148/160105509-37db9e51-ba15-4174-88fb-ed758510cf1d.mp4

2022-03-28 11:31 UTC, patrinoua commented
@AlicanAkyuz It seems like this problem also existed and still exists on the main branch before I make any changes.
Can you maybe also check, and if it's so we can make a separate ticket and address this separately? 

https://user-images.githubusercontent.com/36475005/160386896-696cf48f-358f-4baf-81f1-2152ac0b5318.mov

2022-03-28 11:49 UTC, AlicanAkyuz commented
@patrinoua yes it looks like it's on main :( 

let's aim to fix this before the next release as it's BIG imho. let me know if you have time to tackle it, otherwise I'll take care of it.

2022-03-28 15:13 UTC, patrinoua commented
@MounirDhahri can we merge this?

2022-03-28 15:25 UTC, AlicanAkyuz reviewed
I am not entirely familiar with the agreement about what should go into the components folder and be available to the app instead of specific flows. 

My personal opinion is that these location and artist  auto-suggest components should be inside the submission flow instead of /components, since they are quite specific to the submission flow by design and behaviour. However, if there's an agreement that they should go into components folder, I'd be curious to see them used by other sections of the app.

2022-03-28 15:25 UTC, AlicanAkyuz commented on src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
> +      >
with these change, it is not possible for me to scroll down the suggested artists – as soon as I tap on the suggestion box in order to scroll down, the artist is selected.

2022-03-28 20:34 UTC, patrinoua commented on src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
> +      >
Hmm it works for me, can you maybe upload a video and let's maybe have a look together

2022-03-29 10:12 UTC, MounirDhahri commented
Sorry for the late reply here, this sprint has been crazy 😄 
This looks good to me, since @AlicanAkyuz as well did the same PR inspired by your changes and fixed the focusing issue - I will merge [his PR](https://github.com/artsy/eigen/pull/6510/files) 
Thanks a lot for fixing the Angela and addressing all comments

2022-03-29 10:27 UTC, patrinoua commented
Replaced by https://github.com/artsy/eigen/pull/6510

2022-03-29 10:27 UTC, closed without merging