feat(SWA-267) Animated Progress Bar
artsy/eigen pull request #6487
Opened 2022-03-23 14:41 UTC by patrinoua

The type of this PR is: **TYPE**

This PR resolves [SWA-267]

### Description
- Animated Progress Bar
- destructure items when uploading to gemini/S3

https://user-images.githubusercontent.com/36475005/159725551-64ed19c6-11ff-4296-af26-259b48aec529.mov

### PR Checklist (tick all before merging)
- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/master/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/master/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀
- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>
### Changelog updates

#### Cross-platform user-facing changes
#### iOS user-facing changes
-
#### Android user-facing changes
-
#### Dev changes
-

</details>

[SWA-267]: https://artsyproduct.atlassian.net/browse/SWA-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-03-23 14:59 UTC, evaschilken commented
Looks good!

2022-03-23 14:59 UTC, evaschilken submitted a review, later dismissed

2022-03-23 15:44 UTC, kiryl-zubarau reviewed
LGTM! just a few suggestions

2022-03-23 15:44 UTC, kiryl-zubarau commented on src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/addPhotoToConsignment.ts
> +}) => {
Let's create an interface for the type.

2022-03-23 15:44 UTC, kiryl-zubarau commented on src/app/Scenes/Consignments/Submission/geminiUploadToS3.ts
>      request.open("POST", uploadURL, true)
That will be also useful to reject uploading if error happens and show error message, something like that:

```
request.onerror = () => {
      reject(new Error("Network error: Something went wrong"))
      return
}
```

2022-03-24 18:09 UTC, pvinis commented on src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/validation.ts
> +  path: string
👌

2022-03-24 18:11 UTC, pvinis commented on src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
> +    path: image?.url?.replace(":version", "large") || "",
im not sure what this default value is for, so if you can explain it that would be great, but also its better to use `??` rather than `||` for these cases. it makes things a bit more clear that its because of some `undefined` somewhere.

2022-03-24 18:11 UTC, pvinis commented on src/app/utils/getConvertedImageUrlFromS3.tsx
> +    asset: assetCredentials,
should this be named something more clear? I see `asset` and `assetCredentials`, and these feel veeeery different. 🤔

2022-03-24 18:14 UTC, pvinis requested changes
nice! i added a couple of comments, mostly the naming and the `??` one are things that i think should be cleared up before merging.

2022-03-25 10:26 UTC, AlicanAkyuz approved these changes

2022-03-25 10:26 UTC, AlicanAkyuz commented on src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
> +            })
👏

2022-03-25 10:26 UTC, AlicanAkyuz commented on src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
> +    path: image?.url?.replace(":version", "large") || "",
this `photos` const is set to the global store after an artwork is added to myCollection, so that when user presses 'create a submission from this artwork', the submission flow's form and photos are pre-populated. 

since this PR makes `path` a strictly string field on Photo in [UploadPhotos/validation.ts](https://github.com/artsy/eigen/pull/6487/files#diff-28d08c57256312c1ff07d4f5c26df90cbb59149d3ab9c5d20eb87c6fb70da55b), and `artwork.image.url` from collection could potentially be undefined, TS would complain if we didn't default `path` to empty string when we set it to global store below. 

I agree that ?? would read better here.

2022-03-25 10:26 UTC, AlicanAkyuz commented on src/app/utils/getConvertedImageUrlFromS3.tsx
> +    asset: assetCredentials,
we could rename this whole asset things to photo (asset -> photo, assetCredentials -> photoGeminiCredentials), but `asset` makes things easier to find since the backends (MP, Gemini, Convection) uses `asset` to refer to it. if it's confusing, I suggest leaving asset as `asset`, and renaming assetCredentials to `assetGeminiCredentials`.

2022-03-25 10:34 UTC, patrinoua commented on src/app/utils/getConvertedImageUrlFromS3.tsx
> +    asset: assetCredentials,
We could create a different ticket to bring this in shape. 
I agree that assetCredentials is more clear.
"File" is used to describe the filepath and could also be updated. 
And finally "uploadFileToS3" should come from "uploadFileToS3.js" and not "GeminiUploadFileToS3.js"
(maybe we could add a comment that we use gemini there or it's visible from the imports we make in this file)

2022-03-28 09:30 UTC, patrinoua commented
@pvinis can we merge this?

2022-03-28 09:53 UTC, pvinis commented
I think there is a `??` comment still, and maybe the renaming? its better in this PR than another, since it was added here, let's name them less confusingly and merge.

2022-03-28 13:39 UTC, pvinis approved these changes

2022-03-28 13:43 UTC, merged