fix(CX-2433): Fix Newly added MyCollection Artwork's artist not showing in Filters
artsy/eigen pull request #6488
Opened 2022-03-23 16:30 UTC by lordkiz

The type of this PR is: **Bugfix**

This PR resolves [2433]

### Description

- When an artwork is added to MyCollection, the artist does not show in the MyCollection Filters. This is because the filters were initialized with previous artworks and are not updated. This PR fixes that.

https://user-images.githubusercontent.com/18648835/159748677-b1b703ed-ad5a-4d3b-91e3-903f481ed6cb.mp4

### PR Checklist (tick all before merging)

- [x] I have included screenshots or videos to illustrate my changes, or I have not changed anything that impacts the UI.
- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have added tests/stories for my changes, or my changes don't require testing/stories, or I have included a link to a separate Jira ticket covering the tests.
- [x] I have added a feature flag, or my changes don't require a feature flag. ([How do I add one?](https://github.com/artsy/eigen/blob/main/docs/developing_a_feature.md))
- [x] I have documented any follow-up work that this PR will require, or it does not require any.
- [x] I have added an app state migration, or my changes do not require one. ([What are migrations?](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md))
- [x] I have added a changelog entry below or my changes do not require one.

### To the reviewers 👀

- [ ] I would like at least one of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Fix Newly added MyCollection Artwork's artist not showing in Filters - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-03-23 16:37 UTC, MounirDhahri submitted a review, later dismissed
nice 🙌

2022-03-24 07:13 UTC, olerichter00 requested changes
Looks great! I've added a suggestion to simplify the filter reinitialization.

2022-03-24 07:13 UTC, olerichter00 commented on src/app/Scenes/MyCollection/MyCollection.tsx
> +  }, [artworks.length])
Just checking for the number of artworks wouldn't update the filters in a couple of cases. `artworks.length` would stay the same if an artwork gets updated.

```suggestion
  }, [artworks])
```

2022-03-24 07:13 UTC, olerichter00 commented on src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
>    }, [])
I don't think we need to return `reInitializeLocalArtworkFilter`. We could just move the effect from `MyCollection` to `useLocalArtworkFilter`. 

```suggestion
  useEffect(() => {
    if (artworksList) {
      initLocalArtworkFilter(artworksList)
    }
  }, [artworks])
```

2022-03-24 08:41 UTC, lordkiz commented on src/app/Scenes/MyCollection/MyCollection.tsx
> +  }, [artworks.length])
True that! Thanks.

2022-03-24 08:45 UTC, lordkiz commented on src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
>    }, [])
Moving the effect to useLocalArtworkFilter will make debugging / reproducing bugs related to Local Filters really really difficult.

2022-03-24 09:02 UTC, dariakoko approved these changes
Looks good 👍

2022-03-24 15:17 UTC, olerichter00 commented on src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
>    }, [])
I'm not sure if I can follow. Why does it make debugging harder? I only see the benefit from having all logic related to the filters inside of the hook instead of spreading it between the hook and the component.

2022-03-25 07:44 UTC, lordkiz commented on src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
>    }, [])
@olerichter00 Well, I should have said "...really really difficult `for me`". 😂 
1. If we move that effect, the initialization will still be done once and we'd be back to square 1. Because we will need an effect that depends on artwork for the component to rerender for any reinitialization to occur.
2. I'm always for letting components use methods/hooks however they like and whenever they like. I'd rather a component initialize with artworks (or not) or initialize following an arbitrary event or even initialize with extra objects we may not be displaying. Helps me narrow down what is happening when and where.

2022-03-25 07:50 UTC, lordkiz commented on src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
>    }, [])
Oh @olerichter00 I see your point now. Deleting my previous comment....

2022-03-25 08:05 UTC, lordkiz commented on src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
>    }, [])
Well, I think having components able to initialise localArtworkFilter when and how they want would always help narrow down what's happening where, how and when. I'm always against abstracting so much away from components.  Happy to change it if you insist.

2022-03-25 08:46 UTC, olerichter00 commented on src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
>    }, [])
I can't think of another case where the filters need to be updated. They completely depend on the list artworks.

2022-03-25 08:47 UTC, olerichter00 approved these changes

2022-03-25 11:38 UTC, merged