feat: Explanatory banner for empty Collector Profile
artsy/eigen pull request #6568
Opened 2022-04-06 12:53 UTC by rajsam003

This PR resolves [CX-2473]

### Description

![image](https://user-images.githubusercontent.com/17421923/161978978-2ed1a07d-770c-4e16-b22c-9e67b21ce5dc.png)

### PR Checklist (tick all before merging)

- [ ] Feature flag around my changes.
- [ ] App state migration.
- [ ] Screenshots/videos of my changes.
- [ ] Tested on **iOS** and **Android**.
- [ ] Tests/stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Explanatory banner for empty Collector Profile - sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-04-06 14:06 UTC, dariakoko submitted a review, later dismissed
Looks good to me!

I left one comment, not blocking, just a cleanup

2022-04-06 14:06 UTC, dariakoko commented on src/app/store/config/visualClues.ts
> +  },
I think this is redundant

2022-04-06 14:10 UTC, olerichter00 requested changes
Looks good so far! I've added a couple of comments and questions.

2022-04-06 14:10 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +    await AsyncStorage.getItem(HAS_SEEN_COLLECTOR_PROFILE_EXPLANATORY_BANNER)
You can use [useVisualClue](https://github.com/artsy/eigen/blob/3b5868e769c0ab83d02092b82b50bc0738196cb8/src/app/store/GlobalStore.tsx#L170) instead.

2022-04-06 14:10 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +    !me.bio && !me.icon && !me.profession && !me.otherRelevantPositions
Is this intended? I would expect to show the banner always or if at least one of the fields is empty.

2022-04-06 14:10 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +      {showCollectorProfile && showCollectorProfileExplanatoryBanner && (
Can we introduce a new feature flag just for this feature?

2022-04-06 14:10 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +          bodyTextStyle={{ variant: "xs", color: color("black60") }}
Can we get rid of this? I would expect banners to look the same everywhere in the app.

2022-04-06 14:10 UTC, olerichter00 commented on src/app/Scenes/MyCollection/MyCollection.tests.tsx
> +        "Add works from your collection to access price and market insights."
Are these changes intended? 👀

2022-04-06 14:10 UTC, olerichter00 commented on src/app/Components/States/ZeroState.tsx
> +              textAlign={props.alignItems ? "center" : "left"}
Are these changes intended? 👀

2022-04-06 14:34 UTC, rajsam003 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +    await AsyncStorage.getItem(HAS_SEEN_COLLECTOR_PROFILE_EXPLANATORY_BANNER)
It doesn't work for me ☹️. 
Do you have an example?

2022-04-06 14:35 UTC, rajsam003 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +      {showCollectorProfile && showCollectorProfileExplanatoryBanner && (
Sure ok

2022-04-06 14:36 UTC, rajsam003 commented on src/app/Components/States/ZeroState.tsx
> +              textAlign={props.alignItems ? "center" : "left"}
https://www.figma.com/file/l3plkt7gMSg4p1Or0E8SLC/My-Collection-2022?node-id=719%3A7259

2022-04-06 14:36 UTC, rajsam003 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +          bodyTextStyle={{ variant: "xs", color: color("black60") }}
https://www.figma.com/file/l3plkt7gMSg4p1Or0E8SLC/My-Collection-2022?node-id=719%3A7259

2022-04-06 14:39 UTC, rajsam003 commented
@olerichter00 Most of your comment is about the design. Let's bring this to the channel and see what Pierluca says. 
But anyway thanks for the review :)

2022-04-06 14:46 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +    await AsyncStorage.getItem(HAS_SEEN_COLLECTOR_PROFILE_EXPLANATORY_BANNER)
You could search for `useVisualClue` in the code base for examples.

2022-04-06 14:47 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +          bodyTextStyle={{ variant: "xs", color: color("black60") }}
Is there already a conversation about it? I can only find discussions about the copy in the Figma file. 

If you like I can start the discussion about it in Slack :)

2022-04-06 15:03 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +    await AsyncStorage.getItem(HAS_SEEN_COLLECTOR_PROFILE_EXPLANATORY_BANNER)
This solution should work: https://gist.github.com/olerichter00/fa08c32849d873253181a7147847a110

2022-04-06 15:18 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +    !me.bio && !me.icon && !me.profession && !me.otherRelevantPositions
Ideally, we would set the banner as seen at the end of the session or mark the banner in the session and then set it as seen at the beginning of the next session. This current solution is probably working as expected though.

But, even that wouldn't guarantee that the user has noticed the banner in the case the user opens the Profile screen and doesn't stay long enough to check the banner. What do you think? Should we raise that concern?

2022-04-06 15:18 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +    await AsyncStorage.getItem(HAS_SEEN_COLLECTOR_PROFILE_EXPLANATORY_BANNER)
Ideally, we would set the banner as seen at the end of the session or mark the banner in the session and then set it as seen at the beginning of the next session. This current solution is probably working as expected though.

But, even that wouldn't guarantee that the user has noticed the banner in the case the user opens the Profile screen and doesn't stay long enough to check the banner. What do you think? Should we raise that concern?

2022-04-07 09:37 UTC, dariakoko commented on src/app/store/config/visualClues.ts
> +  },
Since Ole is suggesting to use visualClues, we should keep these changes

2022-04-07 15:09 UTC, dariakoko commented
ping

2022-04-11 10:12 UTC, rajsam003 commented
Based on Pierluca's comment. I have updated the code
https://artsy.slack.com/archives/C01B2P6LJUU/p1649431070486749?thread_ts=1649260836.908909&cid=C01B2P6LJUU

2022-04-11 14:47 UTC, olerichter00 reviewed
Looks good. Just two small comments :)

2022-04-11 14:47 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +  const collectorProfileIsEmpty =
```suggestion
  const collectorProfileIsNotComplete =
```

2022-04-11 14:47 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +          bodyTextStyle={{ variant: "xs", color: color("black60") }}
Can we do this in another way? I don't think we want to have banners styled when there are used. Instead I'd expect to pass a `variant` prop or have different versions of `Banner`.

2022-04-11 15:00 UTC, rajsam003 commented
> Can we do this in another way? I don't think we want to have banners styled when there are used. Instead, I'd expect to pass a variant prop or have different versions of Banner.

@olerichter00 I agree but I think we can style the banner however we want based on the design. Thats why we have `containerStyle`, `titleStyle` and `bodyTextStyle` as props. 
And I dont support creating a new banner when we have one already. 
Shall we bring this to the channel and see how others feel about it?

2022-04-11 15:03 UTC, olerichter00 commented
> > Can we do this in another way? I don't think we want to have banners styled when there are used. Instead, I'd expect to pass a variant prop or have different versions of Banner.
> 
> @olerichter00 I agree but I think we can style the banner however we want based on the design. Thats why we have `containerStyle`, `titleStyle` and `bodyTextStyle` as props. And I dont support creating a new banner when we have one already having props passed. Shall we bring this to the channel and see how others feel about it?

Yes, let's bring this discussion to Slack 👍 

Ideally, we should always prevent styling components from `Palette` when possible to have a consistent look throughout the app.

2022-04-11 15:04 UTC, olerichter00 commented
> And I dont support creating a new banner when we have one already having props passed.

I mean to either use variants and pass it as a prop or create wrapper components like `DarkBanner` and `LightBanner`.

2022-04-19 15:32 UTC, olerichter00 commented
@rajsam003 I took over the ticket and will continue the work in this PR.

2022-04-20 10:19 UTC, rajsam003 commented
> @rajsam003 I took over the ticket and will continue the work in this PR.

Thank you @olerichter00

2022-04-21 07:50 UTC, olerichter00 commented on src/app/Scenes/MyCollection/MyCollection.tsx
> +    const shouldShowConsignments = showSessionVisualClue("ArtworkSubmissionMessage")
**(note):** I've renamed `banner` to `message` because of https://github.com/artsy/eigen/pull/6637

2022-04-21 07:53 UTC, olerichter00 commented on src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
> +  }, [])
**(note):** This sets the visual clue as seen as soon as the user opens the screen. Because we store `showCompleteCollectorProfileMessage` in a local state, the banner will be shown until the component unmounts (which should be the whole session).

2022-04-21 07:56 UTC, olerichter00 approved these changes

2022-04-21 08:05 UTC, MounirDhahri approved these changes
🙌

2022-04-21 08:06 UTC, MounirDhahri commented
Good use of the visual clues

2022-04-21 08:35 UTC, merged

2022-04-21 13:58 UTC, dariakoko commented
Hey @olerichter00 
Shouldn't the body text color be grey?
<img width="326" alt="image" src="https://user-images.githubusercontent.com/36167539/164474107-91b4e7ec-3c42-438f-89ac-bc8a68bf36a4.png">