feat(NX-3118): Display edition set selection modal only when the artwork is non-unique
artsy/eigen pull request #6577
Opened 2022-04-08 09:25 UTC by lean8086

This PR resolves [NX-3118]

### Description

- Click on Make Offer in Inquiry button should open a modal window to confirm the artwork ONLY when there is more than one edition set.
- Unique artworks should take the user directly to the checkout flow
- Artworks with only one edition set should take the user directly to the checkout flow

cc @artsy/negotiate-devs 

### PR Checklist (tick all before merging)

- [x] Tested on **iOS** and **Android**
- [ ] Screenshots and videos 
- [x] Added Tests and Stories
- [ ] App state migration
- [ ] Feature flag

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Display edition set selection modal only when the artwork is non-unique - LeandroL

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

[NX-3118]: https://artsyproduct.atlassian.net/browse/NX-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-04-08 09:56 UTC, araujobarret requested changes

2022-04-08 09:56 UTC, araujobarret commented on src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
> -                  replace: true,
are we sure about this change? those who are using this component without passing `replaceModalView` prop will have this replace changed to `false` instead of `true`

2022-04-08 09:56 UTC, araujobarret commented on src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
> +          <InquiryMakeOfferButtonFragmentContainer
what about tracking here? before we tracked both cases, unique and edition sets, with this change here we don't track anymore unique artworks dispatching the event

2022-04-08 10:00 UTC, lean8086 commented on src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
> +          <InquiryMakeOfferButtonFragmentContainer
Good catch! I completely missed that one.

2022-04-08 10:02 UTC, lean8086 commented on src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
> -                  replace: true,
Agreed! I'll define it as `true` as default.

2022-04-08 13:22 UTC, lean8086 commented on src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
> +          <InquiryMakeOfferButtonFragmentContainer
I added tests to make sure we always track `tappedMakeOffer` 👍 
Let me know what you think about [sending an `onPress` property](https://github.com/artsy/eigen/pull/6577/files#diff-b20d881f9613cdd5d80dfb1d14cceb12684176faa444db82c17136aacfc3ce85R68) to track the event. I'm curious to see what's the cleanest way @araujobarret

2022-04-08 13:27 UTC, lean8086 commented on src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
> +            onPress()
This is outside of `this.handleCreateInquiryOfferOrder` because that one is called again if the mutation fails (`onMutationError`) and the user taps Retry

2022-04-11 08:56 UTC, araujobarret submitted a review, later dismissed
Looks good! 

Left a comment something nice in regards that component design and alignment with `ButtonProps` but nothing critical 👍

2022-04-11 08:57 UTC, araujobarret commented on src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
> +            onPress()
sorry wrong reply box, should be in the last one you tagged me 😭

2022-04-11 08:59 UTC, araujobarret commented on src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
> +          <InquiryMakeOfferButtonFragmentContainer
that's great, thanks!
I commented on the other chat thread regarding some minor improvement there 👍

2022-04-11 15:21 UTC, lean8086 commented on src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
> +            onPress()
Perfect! Just to be sure about the first point: By using the right children prop, you mean like in [Force's implementation](https://github.com/artsy/force/blob/main/src/v2/Apps/Conversation/Components/ConfirmArtworkButton.tsx#L87), right?

2022-04-11 15:30 UTC, merged

2022-04-12 08:08 UTC, araujobarret commented on src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
> +            onPress()
Sorry, my connection was broken yesterday, and wasn't able to come back here.

Yes, exactly 👍

2022-04-13 09:38 UTC, lean8086 commented on src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
> +            onPress()
No problem at all! I opened a [follow-up (draft) PR](https://github.com/artsy/eigen/pull/6606/files#diff-c164780d59564bbe0fa13eff2a35f53b3d919c2a88ed72bf8d32b1c7e6e4ead8R145) with some questions re: using children.