feat: Change copy of my collection when no artwork
artsy/eigen pull request #6592
Opened 2022-04-11 12:29 UTC by rajsam003

This PR resolves [CX-2480]

### Description

|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/17421923/162739350-34dd8006-43fd-4a21-8db1-a8f370dea713.png)|![image](https://user-images.githubusercontent.com/17421923/162739263-4719914e-f550-4830-b907-dc8377a2336d.png)|

### PR Checklist (tick all before merging)

- [x] Tested on **iOS** and **Android**
- [x] Screenshots and videos 
- [x] Added Tests and Stories
- [x] App state migration
- [x] Feature flag

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Change copy in my collection when there are no artworks - sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

2022-04-11 14:38 UTC, olerichter00 requested changes
Thanks for the work 🙇 

I don't think we should create two different flavors of `ZeroState`. Could you please check if this is intended?


| Saved Works | My Collection |
| --- | --- |
| ![simulator_screenshot_263B3A43-C0C7-4E77-8790-92EFBA037AC6](https://user-images.githubusercontent.com/4691889/162763346-4b5d87db-cf8c-4149-af86-e06cfde52119.png) |![simulator_screenshot_1342FA5D-F034-4B39-A29F-8C020787DF3F](https://user-images.githubusercontent.com/4691889/162763465-054dcb2d-4a68-4a23-a0c5-5cd20bf1a9c1.png) |

2022-04-11 14:38 UTC, olerichter00 commented on src/app/Components/States/ZeroState.tsx
> +              textAlign={props.alignItems ? "center" : "left"}
**(issue):** This would set `textAlign` to `"center"` whenever the prop `alignItems` is passed. I don't think we want that.

2022-04-11 14:38 UTC, olerichter00 commented on src/app/Components/States/ZeroState.tsx
> +  alignItems?: AlignItemsValue
This prop seems to do a lot more than it should. It sets the padding for the container and `textAlign` which is quite confusing.

2022-04-11 14:38 UTC, olerichter00 commented on src/app/Components/States/ZeroState.tsx
> +      justifyContent="center"
Why is this needed? When removed it looks the same for me.

2022-04-11 14:54 UTC, dariakoko requested changes
Thanks for the work
I left some comments

2022-04-11 14:54 UTC, dariakoko commented on src/app/Components/States/ZeroState.tsx
> +              textAlign={props.alignItems ? "center" : "left"}
Why not doing something like this?
textAlign={props.alignItems ? **_props.alignItems_** : "left"}

2022-04-11 14:54 UTC, dariakoko commented on src/app/Components/States/ZeroState.tsx
> +              textAlign={props.alignItems ? "center" : "left"}
You'd have an issue with types here? 
you use prop alignItems for textAlign

2022-04-11 14:54 UTC, dariakoko commented on src/app/Components/States/ZeroState.tsx
> +              textAlign={props.alignItems ? "center" : "left"}
You can add a new boolean prop and call it "centered" for example
You could use it for both textAlign and alignItems

textAlign={props.centered ? "center" : "left"}
alignItems={props.centered ? "center" : "stretch"}
("stretch" is default value for alignItems)

2022-04-11 14:54 UTC, dariakoko commented on src/app/Components/States/ZeroState.tsx
> +              textAlign={props.alignItems ? "center" : "left"}
const { title, subtitle, callToAction } = props
👀  the code will look cleaner

2022-04-12 09:38 UTC, olerichter00 requested changes
Looks great! 🌟 

Are these changes to [images/lock.webp](https://github.com/artsy/eigen/pull/6592/files#diff-d893ebda77f1af59e03b1e74b25f82d7e7e7ebf5e6dce0e61d0d584779cfbdcc) intentional?

2022-04-12 10:17 UTC, rajsam003 commented
> Looks great! 🌟
> 
> Are these changes to [images/lock.webp](https://github.com/artsy/eigen/pull/6592/files#diff-d893ebda77f1af59e03b1e74b25f82d7e7e7ebf5e6dce0e61d0d584779cfbdcc) intentional?

Yes. As per the design. It seems like we need it.

2022-04-12 12:19 UTC, olerichter00 approved these changes

2022-04-12 12:19 UTC, merged