feat(CX-2518): add recent auction results based on artists you collect screen
artsy/eigen pull request #6728
Opened 2022-05-11 15:48 UTC by dariakoko

This PR resolves [CX-2518]

### Description

Added `AuctionResultsBasedOnArtistsYouCollectList` screen on which display the list of all auction results (`AuctionResultsBasedOnArtistsYouCollectListQuery`)  
The list has pagination and refresh controller

https://user-images.githubusercontent.com/36167539/167875015-b1117865-e3bb-44e0-bc0c-40a821ee3dd6.mp4

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.
- [x] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- add recent auction results based on artists you collect screen -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look on our [docs], or get in touch with us.

[app state migration]: /docs/adding_state_migrations.md
[feature flag]: /docs/developing_a_feature.md
[docs]: /docs/README.md

[CX-2518]: https://artsyproduct.atlassian.net/browse/CX-2518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-05-11 15:49 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  We are trying to ...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  We are trying to migrate away from moment towards `luxon`, but found moment imports in the following new files:

- `src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx`

See [docs](https://moment.github.io/luxon/api-docs/index.html).
  
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7aaab59350a19a5a69889c016e98983ae14f37f6
</p>

2022-05-11 15:53 UTC, olerichter00 requested changes
This looks good! 

I wonder if we can share the logic from the "Auction Results for Artists You Follow" screen.

2022-05-11 15:55 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollect.tsx
> +          navigate("/auction-results-based-on-artists-you-collect")
I don't think this is necessary because we don't know how a route in Force would look like right now. We could change it later.

2022-05-11 15:56 UTC, dariakoko commented on src/app/AppRegistry.tsx
> +  AuctionResultsBasedOnArtistsYouCollectList: reactModule(
Sure! Will rename in a second

2022-05-11 15:56 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollect.tsx
> +          navigate("/auction-results-based-on-artists-you-collect")
```suggestion
          navigate("/my-collection/auction-results-based-on-artists-you-collect")
```

2022-05-11 16:00 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +  >(auctionResultsBasedOnArtistsYouCollectListFragment, queryData.me!)
Are we 100% sure of queryData.me? To prevent the weird errors we have been seeing lately about me being null, consider returning null early if !me or if !data.
Alternatively you can leave this as it is so we can experience more of those errors in order to really find out what is actually happening. Your call.

2022-05-11 16:03 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +  >(auctionResultsBasedOnArtistsYouCollectListFragment, queryData.me!)
I'd just fail, `me` shouldn't be `null` and if so the screen should crash.

2022-05-11 16:03 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +    refetch({ count: articlesQueryVariables.count })
I think refetch prop has a callback. Consider setting refresh false in the callback. You can inadvertently set refresh false before refetch is done refetching.

2022-05-11 16:05 UTC, dariakoko commented on src/app/AppRegistry.tsx
> +  AuctionResultsBasedOnArtistsYouCollectList: reactModule(
I think would make sense only to move some functions to utils 👀 @olerichter00

2022-05-11 16:07 UTC, dariakoko commented on src/app/AppRegistry.tsx
> +  AuctionResultsBasedOnArtistsYouCollectList: reactModule(
Aaand the header component
I'll refactor and push the changes
thanks for suggestions

2022-05-11 16:11 UTC, olerichter00 requested changes
Can we move everything from [AuctionResultsForArtistsYouFollow](https://github.com/artsy/eigen/blob/af4ebe6cc899de6ea9ee293d9a7c5d7a057ff504/src/app/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx#L31) that is not related to data fetching & tracking (which is both screen specific) into a new component `AuctionResultList` and then render this list in `AuctionResultsForArtistsYouFollow` and in the new `AuctionResultsBasedOnArtistsYouCollect` screen? Right now both implementations look different and we should unify them.

2022-05-11 16:22 UTC, lordkiz reviewed
Excellent work @dariakoko . I left a few comments that should be very easy to address. Nice one 👏🏾

2022-05-11 16:33 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +      <FancyModalHeader hideBottomDivider>{!!showHeader && "Auction Results"} </FancyModalHeader>
Alternatively you can do away with FancyModalHeader and instead apply shrink and translateX with animation to the ListHeader by interpolating the contentOffset.y value. Would make a visibly beautiful effect. You can find example of this in Collection (not MyCollection) screen.

2022-05-11 18:44 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollect.tsx
> +          navigate("/auction-results-based-on-artists-you-collect")
Hm, good point. I'm not sure we need to do this now. I've used the same pattern as we use for the "`auction-results-for-artists-you-follow`" route, to stay consistent. Maybe we need to change both. But we need to check whether it was already used for deeplining or not first

I'll just rename mine to 'auction-results-for-artists-you-collect'

2022-05-12 07:53 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +    }
@lordkiz Looking into this 👍

2022-05-12 08:01 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +    refetch({ count: articlesQueryVariables.count })
I don't think so. In fact, it should be `refetch({})`
https://relay.dev/docs/api-reference/use-pagination-fragment/#return-value

2022-05-12 08:04 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +      <FancyModalHeader hideBottomDivider>{!!showHeader && "Auction Results"} </FancyModalHeader>
Looking into this 👍

2022-05-12 08:14 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +    refetch({ count: articlesQueryVariables.count })
@dariakoko  you can pass an onComplete callback in the options. Like this: `refetch({ count: articlesQueryVariables.count }, { onComplete: () => setRefreshing(false) })`

2022-05-12 08:18 UTC, dariakoko commented
> Can we move everything from [AuctionResultsForArtistsYouFollow](https://github.com/artsy/eigen/blob/af4ebe6cc899de6ea9ee293d9a7c5d7a057ff504/src/app/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx#L31) that is not related to data fetching & tracking (which is both screen specific) into a new component `AuctionResultList` and then render this list in `AuctionResultsForArtistsYouFollow` and in the new `AuctionResultsBasedOnArtistsYouCollect` screen? Right now both implementations look different and we should unify them.

Hi @olerichter00, refactoring is done + your recommendations, I've added the changes you suggested

2022-05-12 09:10 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectList.tsx
> +    <ProvidePlaceholderContextStatic>
Can we move this inside of `LoadingSkeleton`?

2022-05-12 09:10 UTC, olerichter00 commented on src/app/utils/placeholders.tsx
> +}
Interesting, what is this additional context doing?

2022-05-12 09:21 UTC, dariakoko commented on src/app/utils/placeholders.tsx
> +}
Removed it, probably yesterday had a bad light and didn't notice the animation 😵‍💫

2022-05-12 09:28 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
**(suggestion):** What do you think about renaming it to be consistent with our other auction results screen and rail ([AuctionResultsRail](https://github.com/artsy/eigen/blob/af4ebe6cc899de6ea9ee293d9a7c5d7a057ff504/src/app/Scenes/Home/Components/AuctionResultsRail.tsx#L18), [AuctionResultsForArtistsYouFollow](https://github.com/artsy/eigen/blob/af4ebe6cc899de6ea9ee293d9a7c5d7a057ff504/src/app/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx#L31))?

`AuctionResultsForArtistsYouCollect` -> `AuctionResultsForArtistsYouCollectRail`
`AuctionResultsForArtistsYouCollectList` -> `AuctionResultsForArtistsYouCollect`

Open to other ideas, just think it would be great to get some consistency.

2022-05-12 09:34 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
What 'Rail' stands for here?

2022-05-12 09:47 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
Actually, I have no idea, but we use it for this kind of components everywhere in the app 🤔

2022-05-12 09:50 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
Ahah, okay, let's stick to this rule then
Renaming

2022-05-12 09:50 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
All of the rails except the auction results are horizontally scrollabe. We could also give it a new name.

2022-05-12 10:08 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
All rails are on the home screen, I think
Let's rename `AuctionResultsForArtistsYouCollect` to `AuctionResultsForArtistsYouCollectFragmentContainer`?
As it is done for ComparableWorks

2022-05-12 10:12 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
Hmm, we actually don't use `FragmentContainer`s anymore (we could rename `ComparableWorks` as well).

2022-05-12 10:18 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
Ohhhh nooo
How about reaming it to AuctionResultsForArtistsYouCollectRail for now and review the names of these types of components in a separate ticket? And may be documenting it for the future

2022-05-12 10:20 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
> +export const AuctionResultsForArtistsYouCollect: React.FC<
I like the idea! We could start a debate about it in the #practice-mobile Slack channel and find a better naming.

2022-05-12 12:06 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollectList.tsx
> +      <FancyModalHeader hideBottomDivider>{!!showHeader && "Auction Results"} </FancyModalHeader>
@lordkiz We've [decided to use the old design](https://artsy.slack.com/archives/C01B2P6LJUU/p1652352493910109) with a static header for now :/
Resolving conversations about the header

2022-05-12 13:24 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollect.tsx
> +          navigate("/auction-results-based-on-artists-you-collect")
sounds good to me. We can rename it whenever we need to.

2022-05-12 13:26 UTC, olerichter00 approved these changes
Looks great 💯

2022-05-12 13:26 UTC, olerichter00 commented on src/app/Components/AuctionResultsList.tsx
> +type ItemT = any // TODO: ><'
👀

2022-05-12 13:27 UTC, merged