feat [CX-2566]: Add new Generating Market Data loader for My Collection Insights
artsy/eigen pull request #6772
Opened 2022-05-18 19:43 UTC by MrSltun

This PR resolves [CX-2566]

### Description

This PR adds a new loading state for fetching my collection insights after adding new artworks in My Collection

TODO: add video for loader showing "saving artwork & generating market data"

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- adding Generating Market Data loading state for My Collection - mrsltun

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-05-19 14:28 UTC, MrSltun commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> -  props.onSuccess?.()
moved this one to `handleSubmit` to stop changing the `artworkSaved` state after unmounting the artwork from

2022-05-19 15:37 UTC, olerichter00 reviewed
Great work 🌟

2022-05-19 15:37 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        )}
I wonder if we should show the same spinner after editing as well 🤔

2022-05-19 15:37 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +      await Promise.all([
👍

2022-05-19 15:37 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        await new Promise((resolve) => setTimeout(resolve, 1000))
This will add another second to the time the modal is visible. Could we change this logic to reduce the loading time?

2022-05-19 15:50 UTC, MounirDhahri requested changes
Thanks for working on this huge PR. I left some comments, please let me know if something wasn't clear. 

One thing I forgot to mention, it would be great if you also add some tests here to make sure we don't break something in the future by introducing changes here

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/InsightsLoadingModal.tsx
> +export const InsightsLoadingModal: React.FC<InsightsLoadingModalProps & ModalProps> = ({
**suggestion:** I would suggest renaming this to be something more context related `SavingArtworkModal`
```suggestion
export const SavingArtworkModal: React.FC<InsightsLoadingModalProps & ModalProps> = ({
```

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/InsightsLoadingModal.tsx
> +      </View>
**suggestion:** I would instead use [ImageBackground](https://reactnative.dev/docs/imagebackground). If you need it to fill the entire screen, I do also recommend using the [predefined filling objects](https://reactnative.dev/docs/stylesheet#absolutefill-vs-absolutefillobject) from `StyleSheet`

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/InsightsLoadingModal.tsx
> +  const { height: screenHeight } = Dimensions.get("screen")
**suggestion:** although we are not going to be supporting the change of the direction of the screen anytime soon, I would recommend using `height` from `useScreenDimensions()` instead to leverage our app dimensions wrapper

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/InsightsLoadingModal.tsx
> +          {artworkSaved ? "Generating market data" : "Saving Artwork"}
**thought:** I feel a more robust API would have been providing the text as a prop instead of `artworkSaved` as a `boolean`. I don't feel like the modal needs to know that

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/InsightsLoadingModal.tsx
> +    <Modal animationType="slide" visible={isVisible} {...rest} statusBarTranslucent>
```suggestion
    <Modal animationType="fade" visible={isVisible} {...rest} statusBarTranslucent>
```
**issue(non-blocker):** for other loading modal, we have been using `fade` as an animation, let me know if that changed recently

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +  const [artworkSaved, setArtworkSaved] = useState<boolean>(false)
**nitpick:**
```suggestion
  const [isArtworkSaved, setIsArtworkSaved] = useState<boolean>(false)
```

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +  const [keepVisible, setVisible] = useState<boolean>(false)
**issue(blocker):** It took me a while to understand what this is referring to, how about we rename this to something like `iSavingModalVisible`

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +            setVisible(false)
**issue:** I think this will result in the modal being dismissed anyway after 2.5 seconds. I do though like the idea of having a promise that runs in parallel, didn't think of that before.

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        // TODO: update to request for market data after saving/updating artworks
**thought:** I am not a big fan of having todos in the code unless they're actionable and with a ticket associated to them, I would recommend removing this.

2022-05-19 15:50 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +          <InsightsLoadingModal isVisible={loading || keepVisible} artworkSaved={artworkSaved} />
**issue:** I think `isVisible` should be only related to `isSavingModalVisible`

2022-05-19 15:51 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +          }, 2500)
```suggestion
          __TEST__ ? setVisible(false) : setTimeout(() => {
            setVisible(false)
            return resolve("")
          }, 2500)
```

2022-05-19 16:11 UTC, MrSltun commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        )}
I asked about it on the [slack channel](https://artsy.slack.com/archives/C01B2P6LJUU/p1652900318768949), for phase 1 we will be using the new loader only for adding new artworks

2022-05-23 17:36 UTC, MrSltun commented on src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
> +        await new Promise((resolve) => setTimeout(resolve, 1000))
this is a simulation to get the insights data, and we should change it once we have an endpoint to get the new data, or maybe remove it later in case we agree on a different way to fetch the insights data

2022-05-23 17:37 UTC, MrSltun commented
Thank you all for the feedback!! I updated the code and the videos in the description, and I also added tests to the code, please take a look at it now :)

2022-05-24 08:47 UTC, dariakoko approved these changes
Great work 🙌 🙌

2022-05-24 09:14 UTC, olerichter00 approved these changes
🟢

2022-05-24 12:17 UTC, dariakoko commented
@MrSltun , let's merge after resolving conflicts?
I think it conflicts with my changes, feel free to dm to resolve it together

2022-05-25 07:54 UTC, MounirDhahri approved these changes
🙌

2022-05-25 08:43 UTC, merged