feat: Add no artworks have insights Message
artsy/eigen pull request #6808
Opened 2022-05-24 15:36 UTC by olerichter00

This PR resolves [CX-2597]

### Description

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-05-30 14:54 UTC, olerichter00 commented on src/app/Scenes/MyCollection/MyCollection.tsx
> +  const showMessages = async () => {
Just refactoring in this file to clean up 🧹

2022-05-30 14:55 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
> +  me: AuctionResultsForArtistsYouCollectRail_me$key
Cleaning up 🧹

2022-05-30 14:56 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
> +      auctionResults: myCollectionAuctionResults(first: 3) {
This didn't work with `1` and always returned `artworksCount: 1`  🤷

2022-05-31 08:13 UTC, MrSltun approved these changes
LGTM! Great work Ole! 👏 🌟

2022-05-31 12:03 UTC, MounirDhahri requested changes

2022-05-31 12:03 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
> +      auctionResults: myCollectionAuctionResults(first: 3) {
interesting, was it also returning 1 when there are no artworks at all? here I just wanted to know that there is at least 1 auction result available

2022-05-31 12:03 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsMessages.tsx
> +      text="Insights are market data on artists you collect. Not all artists in your collection currently have insights available."
**issue:** I think in the case of no insights available, we should return `There are currently no insights available on your collection. Insights will be shown here if they become available.` and as a title it should be `New artwork successfully added`

2022-05-31 12:03 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsMessages.tsx
> +      text="Insights are market data on artists you collect. Not all artists in your collection currently have insights available."
see https://www.figma.com/file/l3plkt7gMSg4p1Or0E8SLC/My-Collection-2022?node-id=4422%3A87507

2022-05-31 13:30 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
> +      auctionResults: myCollectionAuctionResults(first: 3) {
Exactly, this was the problem. TotalCount was returning 1 for some reason. I'll look into Metaphysics as well or even better expose a field to check if there are any insights.

2022-05-31 14:30 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsMessages.tsx
> +      text="Insights are market data on artists you collect. Not all artists in your collection currently have insights available."
This PR is implementing the following message: https://www.figma.com/file/l3plkt7gMSg4p1Or0E8SLC/My-Collection-2022?node-id=4258%3A77527

2022-05-31 14:30 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsMessages.tsx
> +      text="Insights are market data on artists you collect. Not all artists in your collection currently have insights available."
It's displayed if there are artworks uploaded already but none of these artworks have insights.

2022-05-31 15:41 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsMessages.tsx
> +      text="Insights are market data on artists you collect. Not all artists in your collection currently have insights available."
I thought that this message is what we want to show when we have partial insights

2022-06-01 08:02 UTC, merged