feat: Add account preferences screen
artsy/eigen pull request #6934
Opened 2022-06-16 11:18 UTC by MounirDhahri

### Description

This PR adds user preferences to the settings screen.
Creating this now before I forget it again. 

https://user-images.githubusercontent.com/11945712/174058624-3b1059ee-0884-497f-8a27-8090f972c193.mov

**Still to do**:
- Add tests
- Move the mutation to the store maybe 🤷‍♂️

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [ x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Add account preferences screen - mounir
 
#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-06-16 13:03 UTC, olerichter00 reviewed
@MounirDhahri is this PR ready for review? And could you please at a link to the ticket (or anything else) for context?

2022-06-16 13:29 UTC, olerichter00 requested changes
This is a great idea 🌟

2022-06-16 13:29 UTC, olerichter00 commented on src/app/Scenes/MyAccount/MyAccountPreferences.tsx
> +        </Text>
```suggestion
        <SectionTitle
          title="Currency"
        />
```

2022-06-16 13:29 UTC, olerichter00 commented on src/app/Scenes/MyAccount/MyAccountPreferences.tsx
> +        </Text>
<SectionTitle
          title="Length Unit"
        />

2022-06-16 13:29 UTC, olerichter00 commented on src/app/Scenes/MyAccount/MyAccountPreferences.tsx
> +        <Separator my={1} />
To be consistent with other screens (e.g. Push Notification Settings)

```suggestion
        <Separator my={4} />
```

2022-06-16 13:29 UTC, olerichter00 commented on src/app/Scenes/MyAccount/MyAccountPreferences.tsx
> +            style={{ width: 80 }}
Is this really needed? I'd try to avoid setting styles manually.

2022-06-16 13:29 UTC, olerichter00 commented on src/app/Scenes/MyAccount/MyAccountPreferences.tsx
> +            style={{ width: 80 }}
Same here.

2022-06-16 13:29 UTC, olerichter00 commented on src/app/utils/currencies.ts
> +export type Currency = "EUR" | "USD" | "GBP"
We could instead use the generated type from Relay:
 
```
import CurrencyPreference from "src/__generated__/UserPrefsModelQuery.graphql"
```

2022-06-16 13:29 UTC, olerichter00 commented on src/app/utils/withSuspense.tsx
> +  )
Can we introduce this helper in another PR to have an open discussion about this pattern? Also introducing it here will leave us with two different patterns for screens that use `Suspense`.

2022-06-16 13:29 UTC, olerichter00 commented on src/app/utils/withSuspense.tsx
> +  )
And we should discuss if we want the spinner to be the fallback or if we want to enforce creating a dedicated placeholder skeleton per screen.

2022-06-16 13:29 UTC, olerichter00 commented on src/palette/elements/Radio/RadioButton.tsx
> +    <Wrapper
👍

2022-06-16 15:41 UTC, MounirDhahri commented on src/app/utils/withSuspense.tsx
> +  )
yes, makes sense, i will do it

2022-06-16 15:53 UTC, olerichter00 approved these changes

2022-06-22 15:42 UTC, MounirDhahri commented
good question, I am waiting for approval. I will tag you in the thread

2022-06-23 16:14 UTC, MrSltun approved these changes

2022-06-24 08:39 UTC, olerichter00 submitted a review, later dismissed

2022-08-03 15:25 UTC, dimatretyak commented on src/palette/elements/Radio/RadioButton.tsx
> +    <Wrapper
> using the TouchableWithoutFeedback here when it's not a button was resulting on the touch events from the parent component getting lost and no feedback is returned

can we use `TouchableWithoutFeedback` with `disabled` prop for such cases?

2022-11-16 11:54 UTC, MounirDhahri commented
@dimatretyak @dblandin I remember you working on a similar feature. Did you get it rolled out?

2022-11-16 12:27 UTC, olerichter00 approved these changes
Nice 🌟

2022-11-16 12:27 UTC, olerichter00 commented on src/app/Scenes/Search/UserPrefsModel.tsx
> +const currencies = Object.values(CURRENCIES).map((currencyObj) => currencyObj.value)
**suggestion:** You could try using lodash's [mapValues](https://lodash.com/docs/4.17.15#mapValues) here.

```suggestion
const currencies = mapValues(CURRENCIES, 'value')
```

2022-11-17 10:59 UTC, MounirDhahri commented
@dimatretyak so there are no more plans on setting the metric from the preferences screen?

2022-11-17 11:00 UTC, dimatretyak commented
> @dimatretyak so there are no more plans on setting the metric from the preferences screen?

I think yep

2022-11-17 11:56 UTC, MounirDhahri commented
cool - i will close this PR then. thanks @dimatretyak

2022-11-17 11:56 UTC, closed without merging