refactor: palette colors for native code
artsy/eigen pull request #7078
Opened 2022-07-20 22:13 UTC by pvinis

This PR resolves []

### Description

### QA Test Case(s)

| Test Case | Feature | Environment | Acceptance Criteria | Setup Instructions/Link |
| --------- | :-----: | ----------: | ------------------: | ----------------------: |
|           |         |             |                     |                         |

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-07-20 22:16 UTC, pvinis commented on ios/Artsy.xcodeproj/project.pbxproj
> -		CBE3259627E275A200395A93 /* OldAdminView.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = OldAdminView.swift; sourceTree = "<group>"; };
these were duplicated on the xcode sidebar. probably remnants of the appshell work

2022-07-20 22:17 UTC, pvinis commented on ios/Artsy/ArtsyUIButtons/ARButtonSubclasses.m
> +    [self setBackgroundColor:[UIColor artsyColorFor:@"devpurple"] forState:UIControlStateHighlighted animated:NO];
these stayed purple. i changed the colors as little as i could, but it should be very easy to replace these with `blue100` and get a fresh look!

2022-07-20 22:18 UTC, pvinis commented on ios/Artsy/ArtsyUIColors/UIColor+ArtsyColors.h
>  + (UIColor *)artsyGrayBold;
i kept a couple, until we have a better color to replace it with. we had so many grays before.

2022-07-20 22:19 UTC, pvinis commented on ios/Artsy/ArtsyUIColors/UIColor+ArtsyColors.h
> -+ (UIColor *)artsyRedRegular;
gone!

i replaced:
- graylight with black5
- grayregular with black10
- purplelight and purpleregular with devpurple (could be blue100?)
- redregular with red100
- yellowregular with yellow100
- greenregular with just green

2022-07-20 22:20 UTC, pvinis commented on ios/Artsy/ArtsyUIColors/UIColor+ArtsyColors.m
> +    return [[AREmission sharedInstance] artsyColorFor:name];
here's the new code

2022-07-20 22:20 UTC, pvinis commented on ios/Artsy/ArtsyUILabels/UIView+ARDrawing.m
> -+ (UIColor *)defaultBorderColor
random unused color

2022-07-20 22:20 UTC, pvinis commented on ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
> -#if TARGET_OS_SIMULATOR
the only usage of purplelight. not really needed, so its gone.

2022-07-20 22:24 UTC, pvinis commented on src/palette/Theme.tsx
> +export type ThemeVersion = keyof typeof THEMES
this ends up like `"v2" | "v3"` etc

2022-07-20 22:25 UTC, pvinis commented on src/palette/Theme.tsx
> +export const useThemeValues = (version: ThemeVersion) => THEMES[version]
a simple hook to get the values of the theme. not for a lot of use, but good for what we want in this PR.

2022-07-20 22:25 UTC, pvinis commented on src/app/App.tsx
> +const useSendThemeColorsToNative = (version: ThemeVersion) => {
i kept this here since its only for the init of the app. if we think this should live elsewhere, i can move it.

2022-07-20 22:26 UTC, pvinis commented on src/app/App.tsx
> +  useSendThemeColorsToNative("v3")
this should make it easy to switch to another version

2022-07-20 22:53 UTC, pvinis commented
i need to update the screenshots for native

2022-07-21 11:36 UTC, patrinoua approved these changes
Thanks Pavlos!

2022-07-27 16:11 UTC, brainbicycle commented on ios/Artsy/Emission/Core/AREmission.m
> +        NSLog(@"ERROR: color %@ is missing from the native part of the app.", name);
small change request based on our discussion, I think this should crash in dev mode and log in release mode to reduce the chance we accidentally release with a color missing on native side

2022-07-27 16:11 UTC, brainbicycle requested changes
small change request around how we handle missing colors, otherwise looks good to me!

2023-05-24 14:17 UTC, gkartalis commented
closing, more info [here](https://artsy.slack.com/archives/C02NAJ2CGLW/p1684937696862239)

2023-05-24 14:17 UTC, closed without merging