Docs: update pr template
artsy/eigen pull request #7126
Opened 2022-07-29 14:18 UTC by patrinoua

We updated the PR template to include test descriptions as well as a section that we can directly provide to Applause for testing.

Coauthored by @brainbicycle 

### Description

### QA Test Case(s)

| Test Case | Feature | Environment | Acceptance Criteria | Setup Instructions/Link |
| --------- | :-----: | ----------: | ------------------: | ----------------------: |
|           |         |             |                     |                         |

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-07-29 14:57 UTC, MounirDhahri commented on docs/pull_request_template.md
> +### QA Testing
Such a section could make the job of whoever is the release captain easier but I am afraid it will cause everyone else to spend lots of extra time adding details here. I was under the impression such details should be included already in the Jira ticket. Maybe we can update the recent changes notion doc to include the original Jira ticket

2022-07-29 14:57 UTC, MounirDhahri commented on docs/pull_request_template.md
> +- Feature:
```suggestion
- Context:
```

2022-07-29 14:57 UTC, MounirDhahri commented on docs/pull_request_template.md
> +- Environment:
I feel this is not necessary since the environment will be almost always staging

2022-07-29 14:57 UTC, MounirDhahri commented on docs/pull_request_template.md
> +These tests will be run in recent changes QA, they do not have to be extensive, just a high level feature sanity check, you should do your own extensive QA with your team.
**thought:**
Was this uncommented intentionally?

2022-07-29 14:57 UTC, MounirDhahri commented on docs/pull_request_template.md
> +- [ ] We want to have this tested by Applause.
```suggestion
- [ ] We want to have this tested by our external QA vendor. 
```
Should we maybe not mention Applause name here? maybe it's fine

2022-07-29 14:57 UTC, MounirDhahri commented on docs/pull_request_template.md
> +- If your change needs to be tested by Applause please paste here the name of the change as well as how to test it that you already filled up above.
I would suggest instead simply prefixing the previous items with something like `[NEEDS EXTERNAL QA]` or so to avoid adjusting our parser. I mean instead of having something like
```
### Cross-platform user-facing changes
- Updated login - mounir
```
we can do
```
### Cross-platform user-facing changes
- [NEEDS EXTERNAL QA] Updated login - mounir
```

2022-07-29 15:09 UTC, olerichter00 commented on docs/pull_request_template.md
> +These tests will be run in recent changes QA, they do not have to be extensive, just a high level feature sanity check, you should do your own extensive QA with your team.
Good point! I'd like to keep it as a comment as well to reduce the manual work of removing/commenting these lines.

2022-07-29 15:12 UTC, olerichter00 commented on docs/pull_request_template.md
> +### QA Testing
Will this section be parsed automatically like the changelog?

2022-08-01 14:11 UTC, patrinoua commented on docs/pull_request_template.md
> +### QA Testing
> Will this section be parsed automatically like the changelog?

That would be great!

2022-08-01 14:13 UTC, patrinoua commented on docs/pull_request_template.md
> +- Feature:
I have now removed this completely since the description of the pr provides that context. It would be great if we can parse this automatically in the changelog, together with the instructions / acceptance criteria.

2022-08-01 14:16 UTC, patrinoua commented on docs/pull_request_template.md
> +- Environment:
Agreed, I removed this

2022-08-01 14:19 UTC, patrinoua commented on docs/pull_request_template.md
> +- If your change needs to be tested by Applause please paste here the name of the change as well as how to test it that you already filled up above.
I like that idea!

2022-08-01 14:27 UTC, patrinoua commented
@MounirDhahri and @olerichter00  thanks for your comments. I’ve updated the format here, it would be great if we can set up automatic parsing for the changes that need external QA, where we include the sections of "Acceptance Criteria" and "Setup Instructions/Link" . What do you think?

2022-08-01 14:39 UTC, olerichter00 commented
@MounirDhahri do you think it would be easy to adjust the changelog script to include the sections?

2022-08-01 15:39 UTC, MounirDhahri commented
Yes, this should be possible by extending the list of available sections as we do in here https://github.com/artsy/eigen/blob/1fdfba74f74e859ef676de6870fbbf1139892a53/scripts/changelog/generateChangelogSectionTemplate.js#L3 and extending the PR body here https://github.com/artsy/eigen/blob/1fdfba74f74e859ef676de6870fbbf1139892a53/scripts/changelog/generatePlatformChangelog.js#L176

2022-08-01 15:40 UTC, MounirDhahri approved these changes

2022-08-01 15:41 UTC, MounirDhahri commented
@patrinoua what does `Setup Instructions/Link` refer to?

2022-08-01 16:11 UTC, patrinoua commented on docs/pull_request_template.md
> +- [ ] We want to have this tested by Applause.
I don't see why not 🤷🏻‍♀️

2022-08-01 16:14 UTC, patrinoua commented
> @patrinoua what does Setup Instructions/Link refer to?
@MounirDhahri it was like that and I just copied it but I've now changed it to be just "Setup Instructions", which is what you need to do in order to run this PR.

2022-08-01 16:17 UTC, patrinoua commented
@MounirDhahri @olerichter00 the more I think about this, the more it seems to me like we may be repeating information.

Regarding the information we want to be providing for the ticket and the QA, I am guessing that the **Acceptance criteria** should be the same as the **Description** field, so maybe we could rename keep one field and rename it to **"Description, Acceptance Criteria, Setup instructions"**

Then we can keep the flag of [NEEDS EXTERNAL QA] and wherever there is that flag, we also add a link to the **"Description, Acceptance Criteria, Setup instructions"** part. 

What to do you think?

2022-08-03 10:42 UTC, MounirDhahri commented
> 
> @patrinoua what does Setup Instructions/Link refer to?
> 
> @MounirDhahri it was like that and I just copied it but I've now changed it to be just "Setup Instructions", which is what you need to do in order to run this PR.

thanks for explaining but now I am also lost with what Setup instructions mean here. Maybe we can remove it?

> Regarding the information we want to be providing for the ticket and the QA, I am guessing that the Acceptance criteria should be the same as the Description field, so maybe we could rename keep one field and rename it to "Description, Acceptance Criteria, Setup instructions"

I don't think we should nest it in the same field personally. IMO, if we should have an acceptance criteria field, we can have it separately otherwise I feel like we don't even need it since the acceptance criteria should be inside the Jira ticket.

2022-08-03 17:43 UTC, pvinis commented on docs/pull_request_template.md
> +### QA Testing
thats the idea. this table could automatically be added in the notion QA scripts. Also, it is something that should be "formalized" here, because jira tickets tend to be more loose in their wording, and when people from other teams see something, they are not 100% what to test. this table should make it simpler for everyone, and yes it might be a small extra work on the author, but this is for big feature changes, not small changes that can be QA'd within the team that developed them.

2022-08-03 17:44 UTC, pvinis commented on docs/pull_request_template.md
> +### QA Testing
with all that said, i definitely will insist this should remain as a table, that is replicated from notion. we should not have more things like more headers etc.

2022-08-03 17:44 UTC, pvinis requested changes
i dont think we should remove the table.

2022-08-04 09:33 UTC, patrinoua commented
@pvinis I agree with collecting information for QA, but I'd like to examine if our current solution is effective by answering 1) is something that people use and 2) could it be improved? 

I think that the current implementation using a table is hard to fill out, so people may not be using it. 
It looks good when finished but while editing it's not that easy to use. So I'd be in favor of a format that's easier to fill out.
I'm interested to know if formatting is important to you for some reason and why, or if we could simplify this. 

The information, as discussed above, for some things would always be the same (eg staging) so perhaps we can remove it but we can of course encourage people to provide more information if they think it is needed, for example if some time it happens that the environment is not staging.

Test Case:
Acceptance Criteria:
Setup Instructions:

⬆️ The above is easier to fill out than the below ⬇️

Test Case | Feature | Environment | Acceptance Criteria | Setup Instructions/Link
-- | -- | -- | -- | --


And then I'd argue that 

Feature: Should come from the PR title

2022-08-08 06:57 UTC, pvinis approved these changes

2022-08-08 06:58 UTC, merged