feat(CX-2646): add career highlights to graph
artsy/eigen pull request #7291
Opened 2022-08-29 17:04 UTC by lordkiz

### Description
Adds Career Highlight to Median Sales Graph
https://user-images.githubusercontent.com/18648835/187254796-05db4be6-3eb2-4f39-82fa-3d6df045904c.mp4

This PR resolves [CX-2646]

### QA Testing

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Added career highlights to Median sales graph - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-08-30 08:53 UTC, olerichter00 reviewed
Looks good 🌟 

Is it on purpose that the last year doesn't show any highlights? Or is it maybe just the artists that I've tested the graph with that coincidentally don't have highlights for the current year 🤔 

![Simulator Screen Shot - iPhone 13 Pro - 2022-08-30 at 10 53 14](https://user-images.githubusercontent.com/4691889/187393991-7466c958-b57b-48a4-aecd-c6793a3aa363.png)

2022-08-30 08:53 UTC, olerichter00 commented on package.json
> +    "@gorhom/bottom-sheet": "4.4.3",
@MounirDhahri do we have guidelines whether to open an RFC when introducing a new library?

2022-08-30 08:53 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +        const updatedYear = { ...currentYear, [kind]: compact([...currentYear[kind], body.trim()]) }
This line throws the following error when opening the highlights for Gerhard Richter:

```
undefined is not an object (evaluating 'body.trim')
```

2022-08-30 08:53 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +        const updatedYear = { ...currentYear, [kind]: compact([...currentYear[kind], body.trim()]) }
Maybe we can extract the code to parse an event digest into a function to make it easier to test it.

2022-08-30 08:53 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
I can't find it anymore in the docs, but I remember having a discussion to avoid the `renderSomething` pattern and instead create a component outside and render it the React way.

2022-08-30 09:00 UTC, olerichter00 commented
The animation is quite slow on my simulator when clicking on the career highlight star (iPhone 13 Pro).

2022-08-30 09:29 UTC, lordkiz commented on package.json
> +    "@gorhom/bottom-sheet": "4.4.3",
Oh, I thought this lib was already agreed on as it was specifically mentioned in the ticket as the lib of choice.

2022-08-30 10:13 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
Actually, I'm speaking about the `renderSomething` pattern. [Here is some more context about the reasoning](https://github.com/artsy/force/pull/10798#discussion_r951211200).

2022-08-30 10:52 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
I understand. A function that takes args and return a JSX.Element is best used as a separate Component and those args passed as props. What I am saying is in this case, we can do the mapping in the return block or in a separate component, it will still be the same thing because this returns an array of JSX.Elements.

2022-08-30 10:54 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
Exactly, let's create a separate component.

2022-08-30 11:05 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
We will still do the same thing in the separate component. We will still need `renderHighlight` in the separate component

2022-08-30 11:05 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +        const updatedYear = { ...currentYear, [kind]: compact([...currentYear[kind], body.trim()]) }
Done

2022-08-30 11:06 UTC, lordkiz commented
> The animation is quite slow on my simulator when clicking on the career highlight star (iPhone 13 Pro). Not sure if this is a performance issue or if it is just the simulator being slow.

Hmmmm. Seems pretty fast on mine.

2022-08-30 11:17 UTC, lordkiz commented
> Is it on purpose that the last year doesn't show any highlights? Or is it maybe just the artists that I've tested the graph with that coincidentally don't have highlights for the current year 🤔

Nope. There are no highlights in the digest for that year.

2022-08-30 11:19 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
Exactly, but this will have better performance because with your solution the component gets created on every render. If you move `renderHighlight` outside of the component (and rename it to `Highlight` to follow the React naming conversation), the function will only be created once. 

Maybe it's helpful to keep in mind that a functional component is nothing more than a function that returns a component (so `renderHighlight` is a functional component as well).

2022-08-30 12:06 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
The parent will update all its direct children. Where a child uses `renderHighlight`, the child is updated. By this logic, the renderHighlight in the child should also be in a separate component. And it continues all the way down - it never ends. I don't think a separate component is necessary better if you are returning a map of Elements.
This answer here slightly illustrates what I mean: https://stackoverflow.com/a/55321471/5968596

2022-08-30 12:12 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +        const updatedYear = { ...currentYear, [kind]: compact([...currentYear[kind], body.trim()]) }
Thanks, I was using a bad regex previously.

2022-08-30 12:32 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
Here is more context about the previous conversation: https://github.com/artsy/eigen/pull/6768#discussion_r876903937

2022-08-30 12:35 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
One quick win I can mention now that I have been using the Component pattern more often is how easy it became to test components without need to mock any wrappers around it. I also then don't need to think much as well about which methods to add to the dependency array because the optimisiation will be done by react. The only argument against it for me now is that sometimes I have lots of props to send and i hate that prop drilling hell but I don't think it's the case here

2022-08-30 12:52 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
I think if you are just going to render a component that displays stuff, then it makes sense to have a separate component and pass those as props. But if you are going to map the same prop all over in the child, then there is no added advantage because you can do that mapping on the parent and pass well-defined prop to the child. I'm not sure I am explaining this well 😁

2022-08-30 13:03 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
I'm thinking of refactoring to something like this to avoid the pattern :

```
export const CareerHighlightBottomSheetItem = () => {
  // do important things

  return (
    <Flex flex={1} minWidth={dimensions.width} p={2}>
      <Text variant="lg">{year} Career Highlights</Text>
      <Flex mt={2}>
        { highlights.map((highlight) => <Highlight highlight={highlight} /> }
      </Flex>
    </Flex>
  )
}

const Highlight = (highlight) => {
  // do important things

  return (
    <Flex mb={1} key={header} flexDirection="row">
      <Box mr={1} mt={0.5}>
        {highlight.icon}
      </Box>
      <Flex>
        <Text>{highlight.text}</Text>
        {body}
      </Flex>
    </Flex>
  )
}
```

2022-08-30 13:22 UTC, MounirDhahri requested changes
Thanks for this massive PR Kizito, I left some comments, please let me know if something wasn't clear to explain it further

2022-08-30 13:22 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +          year
it looks like only the year is needed, the rest are used in a different way. Let's see what we can improve here

2022-08-30 13:41 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +    const eventDigest = data.analyticsArtistSparklines?.edges?.find(
Yeah, but won't pass tsc. Our rules enforce passing a base.

2022-08-30 13:46 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +      highlights: careerHighlightsMap[parseInt(year, 10)],
It doesn't. Each year contains all the careerhighlights from 1993 to present. And it is the same for each node. The only way to tell which node is included is if the sparkles is not 0.

2022-08-30 13:48 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +  )
Needed because we want white as bgColor and BottomSheet injects props into whatever component you pass.

2022-08-30 13:50 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +    const headers = Object.keys(highlights)
Refers to each year in the parsed digest. - [2014, 2015, 2016]

2022-08-30 13:54 UTC, lordkiz commented on src/palette/elements/LineGraph/ScatterPointsContainers.tsx
> +  }, [x])
Under the hood, d3/Victory will reuse these components. `x` here refers to the Point along the x axis. It is an injected prop and different from `datum.x` which is our own x-value. 
This injected x position will change over time as points move to their right position. This useEffect keeps it updated, else the `x` you might end up using might be the x position that was initially captured not the updated one. This makes clicking the highlights work even after changing the data passed in.

2022-08-30 13:55 UTC, lordkiz commented on src/palette/elements/LineGraph/ScatterPointsContainers.tsx
> +
We do. Same as above d3 is reusing the component and the initial datum prop may have changed when data changes.

2022-08-30 13:58 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +          year
Even for years without data, there can be eventDigest but sparkles will be "0".
Since each year contains the same data, to find the digest, we find the first year that has sparkles greater than 0 and contains digest. That way we don't need to parse digest over and over again.

2022-08-30 13:58 UTC, MounirDhahri commented on package.json
> +    "@gorhom/bottom-sheet": "4.4.3",
Yes, I actually was thinking about that as well but remembered that I did some research about it with Daria before and we're good here. Makes sense though to open an RFC for the sake of following the process but since bottom-sheet is killing it and has no competition almost, it is maybe okay

2022-08-30 14:00 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +  const dataForFlatlist = (): Array<{
Updated.
Using it as: 
```ts
const flatListData = useMemo(
    () => dataForFlatlist(),
    [JSON.stringify(data.analyticsArtistSparklines)]
  )
```

2022-08-30 14:06 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
Highlights look like this:
```ts
{"Solo Show": ["MusuemX", "MuseumY"], "Biennial": ["Documenta"], "Group Show": ["GalleryX"] }
```

2022-08-30 14:09 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +  const makeCareerHighlightMap = (): Record<
done.

2022-08-30 14:53 UTC, olerichter00 commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
Sorry, but I don't see much value in this discussion and will resolve the conversation. 

The code above is meant as an example to explain my comment and is not supposed to be working code. If you'd like to make it work, you could use [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) to transform the data.

2022-08-30 15:26 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +    const eventDigest = data.analyticsArtistSparklines?.edges?.find(
aha thanks for explaining. Clear

2022-08-30 15:26 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +  const makeCareerHighlightMap = (): Record<
thank you

2022-08-30 15:26 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +  const dataForFlatlist = (): Array<{
niiice 🙌

2022-08-30 15:28 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +      highlights: careerHighlightsMap[parseInt(year, 10)],
I got what you mean, what I meant is the following process:
Eigen speaks to metaphysics about career highlights
Metaphsyics sends a payload ready already like this
```
year:
highlights: careerHighlightsMap
```
and Eigen almost does nothing except for showing the data in the graph

2022-08-30 15:29 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +      highlights: careerHighlightsMap[parseInt(year, 10)],
the comes force, Force won't need as well to define all the methods that are defined in Eigen, it will also only use the interface that is already available to show the data as well in the same format

2022-08-30 15:30 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +      highlights: careerHighlightsMap[parseInt(year, 10)],
I understand what you mean then now. If we have the data from 1993 but we are always showing only the past 3-8 years. Why don't we then update the interface to only return the last 3-8 years as we need. What I mean is, we started with the interface before the UI and we can of course adjust the interface to what works for our needs best

2022-08-30 15:31 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +      highlights: careerHighlightsMap[parseInt(year, 10)],
@olerichter00 maybe assumed we will need all the career highlights, but maybe we don't, if it's the case, please feel free to adjust the interface to what suits us best in the long term

2022-08-30 15:33 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +  )
Oki, thanks for explaining. It would have been great to comment here as well

2022-08-30 16:12 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +      highlights: careerHighlightsMap[parseInt(year, 10)],
Oh, I get. Even with that each year will always contain a digest, unless we move this parsing to Metaphysics. It helps but it is likely not to change much.

2022-08-30 16:13 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
> +      highlights: careerHighlightsMap[parseInt(year, 10)],
Here is an example response:
```js
{
  "data": {
    "analyticsArtistSparklines": {
      "edges": [
        {
          "node": {
            "artistName": "Kerry James Marshall",
            "year": "year_2003",
            "eventDigest": "1993 Reviewed Solo Show @ Artforum; 1995 Reviewed Solo Show @ Artforum; 1997 Biennial Inclusion @ documenta; 1997 Biennial Inclusion @ Whitney Biennial; 1998 Reviewed Solo Show @ Artforum; 1999 Solo Show @ SFMOMA; 1999 Biennial Inclusion @ Carnegie International; 2003 Solo Show @ MCA Chicago; 2003 Biennial Inclusion @ Venice Biennale - International Exhibition; 2004 Solo Show @ PAMM; 2004 Reviewed Solo Show @ frieze; 2004 Group Show @ Hammer Museum; 2005 Solo Show @ Studio Museum; 2005 Group Show @ Museum of Modern Art (MoMA); 2005 Group Show @ MCA Chicago; 2006 Reviewed Solo Show @ Flash Art; 2006 Group Show @ Art Institute of Chicago; 2006 Group Show @ MASS MoCA; 2006 Group Show @ MCA Chicago; 2007 Group Show @ MCA Chicago; 2007 Biennial Inclusion @ documenta; 2007 Reviewed Group Show @ Artforum; 2008 Solo Show @ MCA Chicago; 2009 Solo Show @ SFMOMA; 2009 Group Show @ Museum of Modern Art (MoMA); 2009 Group Show @ SFMOMA; 2009 Group Show @ MCA Chicago; 2010 Group Show @ Museum of Modern Art (MoMA); 2011 Reviewed Solo Show @ Artforum; 2011 Group Show @ MCA Chicago; 2012 Solo Show @ Secession; 2012 Group Show @ SFMOMA; 2013 Reviewed Solo Show @ Artforum; 2013 Group Show @ New Museum; 2014 Solo Show @ Museo Reina Sofia; 2014 Biennial Inclusion @ Prospect New Orleans; 2015 Group Show @ Studio Museum; 2015 Group Show @ Studio Museum; 2015 Group Show @ MCA Chicago; 2015 Biennial Inclusion @ Venice Biennale - International Exhibition; 2016 Solo Show @ Met Breuer; 2016 Solo Show @ MCA Chicago; 2016 Reviewed Solo Show @ frieze; 2016 Reviewed Solo Show @ New Yorker; 2016 Reviewed Solo Show @ Flash Art; 2016 Reviewed Solo Show @ 4Columns; 2016 Group Show @ MOCA Los Angeles; 2016 Group Show @ Studio Museum; 2016 Group Show @ MCA Chicago; 2016 Reviewed Group Show @ Artforum; 2017 Solo Show @ MOCA Los Angeles; 2017 Solo Show @ MCA Chicago; 2017 Reviewed Solo Show @ Artforum; 2017 Reviewed Solo Show @ Texte zur Kunst; 2017 Reviewed Solo Show @ Art in America; 2017 Group Show @ Museum of Modern Art (MoMA); 2017 Group Show @ Studio Museum; 2018 Group Show @ SFMOMA; 2018 Group Show @ Fondazione Prada; 2018 Biennial Inclusion @ FRONT International; 2018 Biennial Inclusion @ Carnegie International; 2018 Reviewed Group Show @ frieze; 2018 Reviewed Group Show @ Apollo; 2019 Group Show @ MCA Chicago; 2019 Group Show @ Studio Museum; 2020 Group Show @ MCA Chicago; 2020 Group Show @ MCA Chicago; 2021 Group Show @ Studio Museum; 2021 Group Show @ The Broad; 2021 Group Show @ MCA Chicago; 2021 Reviewed Group Show @ 4Columns; 2021 Reviewed Group Show @ Flash Art; 2021 Reviewed Group Show @ New Yorker; 2021 Group Show @ The Broad; 2021 Group Show @ LACMA; ",
            "sparkles": "12",
            "tier": 1
          }
        },
        {
          "node": {
            "artistName": "Kerry James Marshall",
            "year": "year_2004",
            "eventDigest": "1993 Reviewed Solo Show @ Artforum; 1995 Reviewed Solo Show @ Artforum; 1997 Biennial Inclusion @ documenta; 1997 Biennial Inclusion @ Whitney Biennial; 1998 Reviewed Solo Show @ Artforum; 1999 Solo Show @ SFMOMA; 1999 Biennial Inclusion @ Carnegie International; 2003 Solo Show @ MCA Chicago; 2003 Biennial Inclusion @ Venice Biennale - International Exhibition; 2004 Solo Show @ PAMM; 2004 Reviewed Solo Show @ frieze; 2004 Group Show @ Hammer Museum; 2005 Solo Show @ Studio Museum; 2005 Group Show @ Museum of Modern Art (MoMA); 2005 Group Show @ MCA Chicago; 2006 Reviewed Solo Show @ Flash Art; 2006 Group Show @ Art Institute of Chicago; 2006 Group Show @ MASS MoCA; 2006 Group Show @ MCA Chicago; 2007 Group Show @ MCA Chicago; 2007 Biennial Inclusion @ documenta; 2007 Reviewed Group Show @ Artforum; 2008 Solo Show @ MCA Chicago; 2009 Solo Show @ SFMOMA; 2009 Group Show @ Museum of Modern Art (MoMA); 2009 Group Show @ SFMOMA; 2009 Group Show @ MCA Chicago; 2010 Group Show @ Museum of Modern Art (MoMA); 2011 Reviewed Solo Show @ Artforum; 2011 Group Show @ MCA Chicago; 2012 Solo Show @ Secession; 2012 Group Show @ SFMOMA; 2013 Reviewed Solo Show @ Artforum; 2013 Group Show @ New Museum; 2014 Solo Show @ Museo Reina Sofia; 2014 Biennial Inclusion @ Prospect New Orleans; 2015 Group Show @ Studio Museum; 2015 Group Show @ Studio Museum; 2015 Group Show @ MCA Chicago; 2015 Biennial Inclusion @ Venice Biennale - International Exhibition; 2016 Solo Show @ Met Breuer; 2016 Solo Show @ MCA Chicago; 2016 Reviewed Solo Show @ frieze; 2016 Reviewed Solo Show @ New Yorker; 2016 Reviewed Solo Show @ Flash Art; 2016 Reviewed Solo Show @ 4Columns; 2016 Group Show @ MOCA Los Angeles; 2016 Group Show @ Studio Museum; 2016 Group Show @ MCA Chicago; 2016 Reviewed Group Show @ Artforum; 2017 Solo Show @ MOCA Los Angeles; 2017 Solo Show @ MCA Chicago; 2017 Reviewed Solo Show @ Artforum; 2017 Reviewed Solo Show @ Texte zur Kunst; 2017 Reviewed Solo Show @ Art in America; 2017 Group Show @ Museum of Modern Art (MoMA); 2017 Group Show @ Studio Museum; 2018 Group Show @ SFMOMA; 2018 Group Show @ Fondazione Prada; 2018 Biennial Inclusion @ FRONT International; 2018 Biennial Inclusion @ Carnegie International; 2018 Reviewed Group Show @ frieze; 2018 Reviewed Group Show @ Apollo; 2019 Group Show @ MCA Chicago; 2019 Group Show @ Studio Museum; 2020 Group Show @ MCA Chicago; 2020 Group Show @ MCA Chicago; 2021 Group Show @ Studio Museum; 2021 Group Show @ The Broad; 2021 Group Show @ MCA Chicago; 2021 Reviewed Group Show @ 4Columns; 2021 Reviewed Group Show @ Flash Art; 2021 Reviewed Group Show @ New Yorker; 2021 Group Show @ The Broad; 2021 Group Show @ LACMA; ",
            "sparkles": "17",
            "tier": 1
          }
        },
        {
          "node": {
            "artistName": "Kerry James Marshall",
            "year": "year_2005",
            "eventDigest": "1993 Reviewed Solo Show @ Artforum; 1995 Reviewed Solo Show @ Artforum; 1997 Biennial Inclusion @ documenta; 1997 Biennial Inclusion @ Whitney Biennial; 1998 Reviewed Solo Show @ Artforum; 1999 Solo Show @ SFMOMA; 1999 Biennial Inclusion @ Carnegie International; 2003 Solo Show @ MCA Chicago; 2003 Biennial Inclusion @ Venice Biennale - International Exhibition; 2004 Solo Show @ PAMM; 2004 Reviewed Solo Show @ frieze; 2004 Group Show @ Hammer Museum; 2005 Solo Show @ Studio Museum; 2005 Group Show @ Museum of Modern Art (MoMA); 2005 Group Show @ MCA Chicago; 2006 Reviewed Solo Show @ Flash Art; 2006 Group Show @ Art Institute of Chicago; 2006 Group Show @ MASS MoCA; 2006 Group Show @ MCA Chicago; 2007 Group Show @ MCA Chicago; 2007 Biennial Inclusion @ documenta; 2007 Reviewed Group Show @ Artforum; 2008 Solo Show @ MCA Chicago; 2009 Solo Show @ SFMOMA; 2009 Group Show @ Museum of Modern Art (MoMA); 2009 Group Show @ SFMOMA; 2009 Group Show @ MCA Chicago; 2010 Group Show @ Museum of Modern Art (MoMA); 2011 Reviewed Solo Show @ Artforum; 2011 Group Show @ MCA Chicago; 2012 Solo Show @ Secession; 2012 Group Show @ SFMOMA; 2013 Reviewed Solo Show @ Artforum; 2013 Group Show @ New Museum; 2014 Solo Show @ Museo Reina Sofia; 2014 Biennial Inclusion @ Prospect New Orleans; 2015 Group Show @ Studio Museum; 2015 Group Show @ Studio Museum; 2015 Group Show @ MCA Chicago; 2015 Biennial Inclusion @ Venice Biennale - International Exhibition; 2016 Solo Show @ Met Breuer; 2016 Solo Show @ MCA Chicago; 2016 Reviewed Solo Show @ frieze; 2016 Reviewed Solo Show @ New Yorker; 2016 Reviewed Solo Show @ Flash Art; 2016 Reviewed Solo Show @ 4Columns; 2016 Group Show @ MOCA Los Angeles; 2016 Group Show @ Studio Museum; 2016 Group Show @ MCA Chicago; 2016 Reviewed Group Show @ Artforum; 2017 Solo Show @ MOCA Los Angeles; 2017 Solo Show @ MCA Chicago; 2017 Reviewed Solo Show @ Artforum; 2017 Reviewed Solo Show @ Texte zur Kunst; 2017 Reviewed Solo Show @ A [...]

2022-08-31 06:46 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
> +  const renderHighlight = () => {
@olerichter00 Sorry. I have refactored to the pattern you specified.

2022-08-31 10:33 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx
> +  onXAxisHighlightPressed: noop,
**(just a q out of curiosity)**: never used noop. What else could be used here, if could?

2022-08-31 10:40 UTC, dariakoko approved these changes

2022-08-31 10:43 UTC, lordkiz commented on src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx
> +  onXAxisHighlightPressed: noop,
@dariakoko noop is just a function that always returns undefined no matter the args passed.  `funcName: (arg: argType) => null (or undefined)` can be a substitute

2022-08-31 10:45 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx
> +  onXAxisHighlightPressed: noop,
Got it, thank you!

2022-09-01 14:03 UTC, lordkiz commented
@MounirDhahri Is there still anything holding up this?

2022-09-01 14:06 UTC, lordkiz commented on src/palette/elements/LineGraph/ScatterPointsContainers.tsx
> +  }, [x])
If we no longer need to watch positions and handle gestures, this will become redundant. But while we still do I have found that it is necessary else our functions capture stale values.

2022-09-01 14:37 UTC, MounirDhahri commented on package.json
> +    "@gorhom/bottom-sheet": "4.4.3",
good point - sounds good

2022-09-01 14:39 UTC, MounirDhahri commented on src/palette/elements/LineGraph/ScatterPointsContainers.tsx
> +  }, [x])
aha I understand your point now, thank you for explaining 🙏

2022-09-01 14:40 UTC, MounirDhahri commented on src/palette/elements/LineGraph/ScatterPointsContainers.tsx
> +
true - please disregard my comment

2022-09-01 14:41 UTC, MounirDhahri approved these changes
I am very sorry for the late re-review. thanks for addressing the review comments. this LGTM

2022-09-02 08:51 UTC, merged