feat(CX-2808): request a Price Estimate / App - UX/UI Update 3/3 (Request Sent update) [app]
artsy/eigen pull request #7484
Opened 2022-10-17 14:24 UTC by dariakoko

This PR resolves [CX-2808]

### Description

Removed toast that confirms that the request for a price estimate is sent
When the request is sent, show an icon and text instead of a blue button
Kept two toasts that notify about: 1. error when no user; 2. error when the request for a price estimate failed

https://user-images.githubusercontent.com/36167539/196202132-7a36510d-bd6b-4df9-8a8a-13d3ef0b3e26.mp4

### QA Testing

#### Acceptance Criteria

-

#### Setup Instructions

-

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Adjusted the request for a price estimate section in MyCollection Artwork to match the implementation in Force -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-10-17 15:52 UTC, MounirDhahri requested changes
Nice PR @dariakoko ,  I added a suggestion about avoiding ternaries for big components. I would like also to suggest adding a test for the component to avoid regressions in the future.

Since so far we have no confirmation page and I don't know when we will be releasing it, I would also suggest hiding the changes above behind a feature flag. sorry we didn't mention that at the ticket level

2022-10-18 08:56 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
> +      {priceEstimateRequested ? (
Good suggestion, thank you, Mounir

2022-10-18 08:57 UTC, dariakoko commented on src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
> +      {priceEstimateRequested ? (
I am not sure the feature flag is necessary since it is mostly UI/UX changes that don't affect the main functionality

2022-10-18 09:08 UTC, MounirDhahri commented on src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
> +      {priceEstimateRequested ? (
sounds good

2022-10-18 12:03 UTC, MounirDhahri approved these changes
LGTM, feel free to merge. Thanks for addressing the review comments

2022-10-18 12:39 UTC, merged