feat(FX-4419): #doNotMerge wip Auctions progressbar/timer move to header
artsy/eigen pull request #7577
Opened 2022-11-02 17:01 UTC by gkartalis

This PR resolves [] 

### Description

Wip wip wip

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-11-04 17:24 UTC, dimatretyak commented on src/app/Components/Bidding/Components/Timer.tsx
> +              *Closure times may be extended to accommodate last-minute bids
I think we won't need to render this label here as it will be displayed in the lot details section.

<img width="868" alt="for-george" src="https://user-images.githubusercontent.com/3513494/200034223-1d1fce1f-d3c3-41f6-961d-fe2e8e648213.png">

2022-11-04 17:24 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
> +export const ArtworkTombstone: React.FC<ArtworkTombstoneProps> = ({ artwork, refetchArtwork }) => {
**suggestion**: what do you think about making these changes (refactor from class to functional component) in a separate PR?

2022-11-04 17:24 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
> +          renderArtistName(artwork.culturalMaker, null)}
**question**: maybe we extract put this logic into a separate component?

2022-11-04 17:24 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +      biddingEndAt: initialBiddingEndAt,
**suggestion(not-related/not-blocking)**: the lot details section has [similar logic](https://github.com/artsy/eigen/blob/e501105ddb990ccc5096434d517899d2f94a9cef/src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotEndDateTime.tsx#L16-L19). We will have to think about how we can reuse this (for example, store the single instance of `biddingEndAt`in react context)

2022-11-07 14:52 UTC, gkartalis commented on src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
> +export const ArtworkTombstone: React.FC<ArtworkTombstoneProps> = ({ artwork, refetchArtwork }) => {
Good idea, opening a separate pr today

2022-11-07 14:56 UTC, gkartalis commented on src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
> +export const ArtworkTombstone: React.FC<ArtworkTombstoneProps> = ({ artwork, refetchArtwork }) => {
actually just realized that most of this refactor have been merged on this one https://github.com/artsy/eigen/pull/7551

2022-11-07 15:04 UTC, gkartalis commented on src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
> +export const ArtworkTombstone: React.FC<ArtworkTombstoneProps> = ({ artwork, refetchArtwork }) => {
so rebased and most of the refactor is gone now from the diff

2022-11-29 17:17 UTC, gkartalis commented on src/app/Components/Bidding/Components/Timer.tsx
> +              *Closure times may be extended to accommodate last-minute bids
good point, removing it

2022-11-30 13:23 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  We are trying to ...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  We are trying to migrate away from moment towards `luxon`, but found moment imports in the following new files:

- `src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx`

See [docs](https://moment.github.io/luxon/api-docs/index.html).
  
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a4c256b8a906c85f2f18c278c91a01650bc48417
</p>

2022-12-01 16:59 UTC, dimatretyak requested changes

2022-12-01 16:59 UTC, dimatretyak commented on src/app/Components/Bidding/Components/ArtworkAuctionProgressBar.tsx
> +    </>
**suggestion**:

```javascript
..

if (isWithinExtendedBiddingPeriod || hasBeenExtended) {
  return <ProgressBar height={height} trackColor="red100" progress={percentComplete * 100} />
}

return null
```

2022-12-01 16:59 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +  )
**question**: as far as I can see `AuctionWebsocketContextProvider` is already used on the [Artwork page](https://github.com/artsy/eigen/blob/47703618e33251e869add2a377eb6d8ac4b73a35/src/app/Scenes/Artwork/Artwork.tsx#L442-L448). should we duplicate it again here?

2022-12-01 16:59 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +    isInAuction && sale && timerState !== AuctionTimerState.CLOSED && isForSale
**suggestion**: remove `isInAuction` since it's already checked [here](https://github.com/artsy/eigen/blob/47703618e33251e869add2a377eb6d8ac4b73a35/src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx#L49)

2022-12-01 16:59 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +    artwork.saleArtwork &&
**suggestion**: we can remove `isInAuction`, `saleArtwork` since it's already checked [here](https://github.com/artsy/eigen/blob/47703618e33251e869add2a377eb6d8ac4b73a35/src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx#L49)

2022-12-01 16:59 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +  if (props.artwork.isInAuction && props.artwork.saleArtwork) {
**suggestion**: i think we can also check `props.artwork.sale` here since it used in `displayAuctionLotLabel`, `isBiddableInAuction`, `shouldShowTimer`

```javascript
const { isInAuction, saleArtwork, sale } = props.artwork ?? {}

if (isInAuction && saleArtwork && sale) {
  ...
}

const isBiddableInAuction = timerState !== AuctionTimerState.CLOSED && isForSale
const displayAuctionLotLabel = artwork.saleArtwork.lotLabel && !artwork.sale.isClosed
...
```

2022-12-01 16:59 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +          </Flex>
**suggestion**: specify `textAlign` prop for `Text`.

```javascript
<Text variant="xs" color="black60" textAlign="right">
  {label}
</Text>
```

2022-12-01 16:59 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +const RenderCountdown: React.FC<AuctionWebsocketWrapperProps> = ({
**suggestion (blocking)**: in `RenderCountdown` we have to update the `auctionTimerState` which stored in the `Artwork` component, as some components depend on it ([example 1](https://github.com/artsy/eigen/blob/47703618e33251e869add2a377eb6d8ac4b73a35/src/app/Scenes/Artwork/Artwork.tsx#L264), [example 2](https://github.com/artsy/eigen/blob/47703618e33251e869add2a377eb6d8ac4b73a35/src/app/Scenes/Artwork/Artwork.tsx#L137)). We are doing this now in [CommercialInformation](https://github.com/artsy/eigen/blob/47703618e33251e869add2a377eb6d8ac4b73a35/src/app/Scenes/Artwork/Components/CommercialInformation.tsx#L186-L190)

2022-12-02 10:00 UTC, dimatretyak approved these changes

2022-12-02 10:00 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +  if (artwork.isInAuction && artwork.saleArtwork && artwork.sale) {
**suggestion(non-blocking)**: 

```javascript
if (!(artwork.isInAuction && artwork.saleArtwork && artwork.sale)) {
  return null
}

return (...)
```

2022-12-02 10:12 UTC, dimatretyak commented
> we never display [bidding closed](https://www.figma.com/file/9DMfKOi5RuuBD2f49eB9nV/Artwork-page?node-id=2759%3A27264&t=LYIucGe9JcQK7h12-0) message

oh, good catch

2022-12-02 10:17 UTC, dimatretyak commented
**question**: @gkartalis can we copy some test cases for timer/countdown from `CommercialInformation.tests.tsx` for the new `ArtworkLotTimer` component?

2022-12-02 10:18 UTC, gkartalis commented
@dimatretyak yes! Will do!

2022-12-02 10:19 UTC, dimatretyak commented
thank you!

2022-12-02 12:19 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
**question**: should we show this label only when `timerState` is `AuctionTimerState.CLOSED` (as [we are doing](https://github.com/artsy/eigen/blob/e3a0a41427ffe502e196d059f1964341ed7278fd/src/app/Scenes/Artwork/Components/AuctionPrice.tsx#L51-L53) it now) since the end time can be [extended](https://github.com/artsy/eigen/blob/e3a0a41427ffe502e196d059f1964341ed7278fd/src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx#L65)?

2022-12-02 13:06 UTC, gkartalis commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
I think using the `endedAt` is the best approach for this since it is null and it is changed to an actual value only when the lot is bidding closed 🤔

2022-12-02 13:10 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
as far as I understand, with this approach, the timer will continue to be displayed if the time has expired. For example:
* the user navigated to the page
* 5 seconds left in the timer
* the user has spent 10 seconds on the page
* the timer will continue to be displayed with 0d 0h 0m 0s

Or am I wrong?

2022-12-02 13:13 UTC, gkartalis commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
Let me check 👌

2022-12-02 13:16 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
hmm, for [this artwork](https://staging.artsy.net/artwork/6389f9cb69e9c700060288da) i get the following result

<img width="507" alt="for-george" src="https://user-images.githubusercontent.com/3513494/205301204-1f0709cf-9af3-4306-b9d9-0f1fdf456b16.png">

2022-12-02 13:18 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
ok, the timer was hidden

https://user-images.githubusercontent.com/3513494/205301498-239638ec-3c53-4330-a06d-72f4782da102.mp4

2022-12-02 13:27 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
> I think using the endedAt is the best approach for this since it is null and it is changed to an actual value only when the lot is bidding closed

we have to consider `extendedBiddingEndAt`. in the attached screenshot, you can notice that the lot end time is later than the auction end time

<img width="1297" alt="for-george-2" src="https://user-images.githubusercontent.com/3513494/205303090-f439537e-5762-462a-b061-7bc0fac945d9.png">

2022-12-02 13:56 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
**suggestion**: 

```javascript
...

{shouldShowTimer ? (
  <>
    <Spacer mr={4} />
    <Flex flexDirection="row" alignItems="center">
      {sale?.cascadingEndTimeIntervalMinutes ? (
        <ModernTicker
          duration={duration}
          hasStarted={hasStarted}
          isExtended={hasBeenExtended}
          variant="md"
        />
      ) : (
        <SimpleTicker duration={duration} separator="  " variant="md" />
      )}
      <TimerIcon height={24} width={24} fill={getColor()} ml={1} />
    </Flex>
  </>
) : (
  <Text variant="sm-display" textAlign="right">
    Bidding closed
  </Text>
)}
```

2022-12-02 16:35 UTC, gkartalis commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +        )}
I pushed one change, basically what you suggested but preventing showing the "bidding closed" message when we shouldn't. 

Let me know your thoughts. In the mean time adding some tests ;)

2022-12-02 16:43 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +  const isBiddingClosed = !artwork.saleArtwork?.endedAt && timerState === AuctionTimerState.CLOSED
**question**: as far as I understand we should display "bidding closed" when `endedAt` is **not equal** to `null`? If yes, then in this case there should be such a check

```javascript
const isBiddingClosed = !!artwork.saleArtwork?.endedAt || timerState === AuctionTimerState.CLOSED
```

2022-12-02 16:43 UTC, dimatretyak commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +  const isBiddingClosed = !artwork.saleArtwork?.endedAt && timerState === AuctionTimerState.CLOSED
I think `||` should be used instead of `&&`

2022-12-02 16:46 UTC, gkartalis commented on src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
> +  const isBiddingClosed = !artwork.saleArtwork?.endedAt && timerState === AuctionTimerState.CLOSED
😅 you are totally right!

2022-12-02 18:09 UTC, dimatretyak commented
**question(non-blocking)**: should we hide the timer when the live bidding state started? Now the timer continues to be displayed, but if you go back and navigate the artwork lot page again, the timer will no longer be displayed (this is due to the fact that `moment.duration(duration)` will return the same value until we reload the page [here](https://github.com/artsy/eigen/blob/2f3a39bb6579bb77be7a29543dde10c81f83a294/src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx#L140)

https://user-images.githubusercontent.com/3513494/205356336-0635ddbf-3b6a-448f-a668-f5d7fdb6cab7.mp4

2022-12-05 12:08 UTC, gkartalis commented
> question(non-blocking): should we hide the timer when the live bidding state started? Now the timer continues to be displayed, but if you go back and navigate the artwork lot page again, the timer will no longer be displayed (this is due to the fact that moment.duration(duration) will return the same value until we reload the page [here](https://github.com/artsy/eigen/blob/2f3a39bb6579bb77be7a29543dde10c81f83a294/src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx#L140). See the second attached video)

Let's leave it as is for now and lets discuss during QA

2022-12-05 12:08 UTC, gkartalis commented
@dimatretyak added some simple tests but having a hard time with the duration, even when I pass duration to the rendered component the duration is 0 in my component.

2022-12-05 12:11 UTC, gkartalis commented
I am thinking to merge this and fix the tests on a follow up pr to unblock the work, what do you think

2022-12-05 13:13 UTC, dimatretyak approved these changes
LGTM. Thank you!

2022-12-05 13:27 UTC, merged