feat(CX-3052): Create Embedded Carousel
artsy/eigen pull request #7580
Opened 2022-11-03 13:13 UTC by dariakoko

This PR resolves [CX-3052] 

### Description

Create Embedded Carousel
| iOS | Android |
| --- | --- |
| ![simulator_screenshot_5E5C58EB-8253-4E4A-BDCD-5531B162D86A](https://user-images.githubusercontent.com/36167539/199727481-7c118a61-c6d2-4aab-a9a4-4d9f71a23a3a.png) | ![Screenshot_1667481171](https://user-images.githubusercontent.com/36167539/199729843-0b24455e-7480-4dad-83c0-a40dc39eed8b.png) |
### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [x] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-11-04 10:27 UTC, MounirDhahri reviewed
Thanks for creating this PR Daria, I left few comments and I think we need also some tests here.

2022-11-04 10:27 UTC, MounirDhahri commented on src/app/Scenes/Home/Home.tsx
> +  const enableMyCollectionHFOnboarding = useExperimentFlag("my-collection-hf-onboarding")
**thought:** why are we using an unleash ff here, can we use an echo ff ?

2022-11-04 10:27 UTC, MounirDhahri commented on src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
> +            </Flex>
**issue:** would you mind if you export this component into a separate one?

2022-11-07 14:57 UTC, dariakoko commented on src/app/Scenes/Home/Home.tsx
> +  const enableMyCollectionHFOnboarding = useExperimentFlag("my-collection-hf-onboarding")
Because we use unleash in force
Why can't we use unleash in Eigen too?
@MounirDhahri

2022-11-07 14:58 UTC, dariakoko commented on src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
> +            </Flex>
Sure, it would be better

2022-11-09 10:22 UTC, MounirDhahri commented on src/app/Scenes/Home/Home.tsx
> +  const enableMyCollectionHFOnboarding = useExperimentFlag("my-collection-hf-onboarding")
We spoke about it in [this thread](https://artsy.slack.com/archives/C02BAQ5K7/p1652969802754479?thread_ts=1649955187.001959&cid=C02BAQ5K7) @dariakoko You can take a look at it

2022-11-09 10:53 UTC, MounirDhahri requested changes
Thanks for updating the PR to use the new interface from Metaphysics, I left some comments that I will be happy to explain further if something isn't clear

2022-11-09 10:53 UTC, MounirDhahri commented on src/app/Components/EmbeddedCarousel.tsx
> +// TODO: replace any type
👀

2022-11-09 10:53 UTC, MounirDhahri commented on src/app/Components/EmbeddedCarousel.tsx
> +        style={{ overflow: "visible" }}
**thought:** is this required?

2022-11-09 10:53 UTC, MounirDhahri commented on src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tests.tsx
> +describe("HomeFeedOnboardingCard", () => {
**praise:** nice tests

2022-11-09 10:53 UTC, MounirDhahri commented on src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tests.tsx
> +  const TestRenderer = () => {
**thought:** have you considered using `setupTestWrapperTL` here, it already does this for you and could save you some time

2022-11-09 10:53 UTC, MounirDhahri commented on src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tests.tsx
> +  it("doesn't throw when rendered", () => {
**issue:** I would suggest avoiding similar type of tests ("works, renders properly etc...") and focus instead on testing specific scenarios. For example in this case, we have a HomeFeedOnboarding rail that shows nothing when nothing is specified and shows only cards that are marked as visible from the query, I would assume then that the test will contain the following cases:
- Show nothing when none of the cards are visible
- Show only cards that are marked as visible

2022-11-09 10:53 UTC, MounirDhahri commented on src/app/Scenes/Home/Home.tsx
> +        }
**issue(non-blocker):** would you mind using the `@optionalField` directive here to make sure that the home page doesn't break in case something goes wrong with this query

2022-11-09 13:13 UTC, dariakoko commented on src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tsx
> +  }
I thought bout it too. But in the end, went with the design we use in other rails, to stay consistent
Example: CollectionsRail https://github.com/artsy/eigen/blob/main/src/app/Scenes/Home/Components/CollectionsRail.tsx#L41
I would maybe return null instead of an empty tag

2022-11-09 13:27 UTC, dariakoko commented on src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tsx
> +  }
Actually, I'm working on tests now and I think you're right

2022-11-09 13:37 UTC, MounirDhahri commented on src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tsx
> +  }
I don't feel like both components logic is similar, the other component is supposed to show nothing if the data it's fetching is not there, the one you built though, shows/hides data depending on what the parent component decides instead.

2022-11-09 19:53 UTC, dariakoko commented on src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
> +        data={onboardingData}
Have done that and moved the logic from the rail to the home component

2022-11-09 20:14 UTC, dariakoko commented on src/app/Components/EmbeddedCarousel.tsx
> +        style={{ overflow: "visible" }}
Yes and no :) I removed it and refactored the affected components

2022-11-09 20:16 UTC, dariakoko commented on src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tests.tsx
> +  it("doesn't throw when rendered", () => {
Done that in one test, but in the Home component test. I would spend some time refactoring it btw 🤔 It looks very outdated

2022-11-09 20:34 UTC, dariakoko commented on src/app/Scenes/Home/Home.tsx
> +  const enableMyCollectionHFOnboarding = useExperimentFlag("my-collection-hf-onboarding")
Got it, will use echo ff 👌

2022-11-10 15:28 UTC, MounirDhahri approved these changes
👏
![quality-content-5907a3](https://user-images.githubusercontent.com/11945712/201136259-39b3a352-9a5c-447e-89cb-4791d7adbc05.jpeg)

2022-11-10 15:28 UTC, MounirDhahri commented on src/app/Scenes/Home/Home.tsx
> +      hidden: !enableMyCollectionHFOnboarding || !homePageAbove?.onboardingModule,
**praise:** 👏

2022-11-10 15:29 UTC, dariakoko commented on src/app/Scenes/Home/Home.tsx
> +      hidden: !enableMyCollectionHFOnboarding || !homePageAbove?.onboardingModule,
Hooraaaay 🥳 🥳 🥳 🥳

2022-11-10 16:02 UTC, merged