feat(NX-3318): coditionally display "Bids" or "Inquiries" on the Inbox.
artsy/eigen pull request #7589
Opened 2022-11-03 16:40 UTC by patrinoua

This PR resolves [NX-3318] 

### Description

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-11-08 17:48 UTC, jo-rs requested changes
Nice nice. Happy first NX PR! 🎉 
I left a comment to ensure we're considering "watched lots" other than active bids.
Is there any testing that we could implement?

2022-11-08 17:48 UTC, jo-rs commented on src/app/Containers/Inbox.tsx
> +            }
We should also consider watched lots here:
```    
saleArtworks {
 internalID
}
```

2022-11-09 08:31 UTC, lidimayra commented
So nice to this moving forward!! 🎉 

CCing @MounirDhahri here for awareness

2022-11-09 10:19 UTC, MounirDhahri reviewed
Nice addition. I left few comments but none are blocking.

I noticed something though, the modal showing up has broken top padding. It's not coming from this PR but it would be nice to fix it at some point
<img width="285" alt="Screenshot 2022-11-09 at 10 47 20" src="https://user-images.githubusercontent.com/11945712/200804307-4d07d0e2-3cdf-40c3-bb63-a81d39b8f3be.png">

2022-11-09 10:19 UTC, MounirDhahri commented on src/app/Containers/Inbox.tsx
> +    const userHasBids = (this.props.me.myBids?.active ?? []).length > 0
```suggestion
    const hasActiveBids = (this.props.me.myBids?.active ?? []).length > 0
```

2022-11-09 10:19 UTC, MounirDhahri commented on src/app/Containers/Inbox.tsx
> +    const inquiriesTab = 1
**suggestion:** I would recommend moving this out of the render method and moving them outside of the component maybe.
Something like:
```
BIDS_TAB_INDEX = 0
INQUIRIES_TAB_INDEX = 1
```

2022-11-16 16:57 UTC, patrinoua commented
@jo-rs @lidimayra @MounirDhahri 
Thank you all for reviewing and @gkartalis for coauthoring this.
We have now added tests, feel free to have another look 😊

2022-11-16 17:00 UTC, jo-rs approved these changes
Thank you for the changes, @patrinoua! 💪 
![beautiful](https://user-images.githubusercontent.com/7117670/202245023-0c98f821-a734-41e4-a275-d541aa5cf1e0.gif)

2022-11-16 17:23 UTC, araujobarret commented on src/app/Containers/Inbox.tests.tsx
> +    <QueryRenderer<InboxScreenTestQuery>
We don't need to rewrite the query renderer, you can use setupTestWrapperTL helper that abstracts it, like [here](https://github.com/artsy/eigen/blob/7703aa01103a06b69b650af11bc9903ab37b1c4b/src/app/Scenes/Partner/Components/PartnerLocationSection.tests.tsx#L21)

2022-11-21 13:35 UTC, pvinis commented on src/app/Containers/Inbox.tsx
> +  isActiveTab: boolean
```suggestion
  _test_isActiveTab: boolean
```
since we are only using this for the test, id prefer if we were explicit. we do have this pattern in a couple of places already, so maybe making it clear will make others avoid using it for actual code.

2022-11-21 15:13 UTC, jo-rs commented on src/app/Containers/Inbox.tsx
> +  isActiveTab: boolean
I feel a little icky about this nomenclature, but I'm trusting you as an Eigen context holder, @pvinis 😅

2022-11-21 15:15 UTC, jo-rs approved these changes
Thank you for addressing the comments! 🚀

2022-11-21 15:15 UTC, merged