feat(FX-4305): add ability to hide bottom tabs on specific screen
artsy/eigen pull request #7760
Opened 2022-11-30 18:50 UTC by dimatretyak

This PR resolves [FX-4305] 

### Description

### Demo
#### iOS
https://user-images.githubusercontent.com/3513494/205075962-6e138520-1512-43ee-b33b-6ce760de1e22.mp4

#### Android
https://user-images.githubusercontent.com/3513494/205077788-d45d93b6-cf39-4449-b8df-f309818a7c95.mp4

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

- add ability to hide bottom tabs on specific screen - dimatretyak

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[FX-4305]: https://artsyproduct.atlassian.net/browse/FX-4305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-12-01 14:23 UTC, dimatretyak commented on src/app/Scenes/BottomTabs/BottomTabs.tsx
> +    <Flex position="absolute" left={0} right={0} bottom={0} paddingBottom={bottom} bg="white100">
`position: absolute"` is used here to solve the problem with displaying gray empty space (see attached video). 

https://user-images.githubusercontent.com/3513494/205076919-dca6a5d3-730d-4558-8b7d-5a8f1a311e97.mp4

2022-12-01 14:33 UTC, gkartalis approved these changes
🥇 Can't thank you enough for this fix! 🙏

2022-12-01 14:33 UTC, gkartalis commented on src/app/Scenes/Artwork/Artwork.tsx
> +  }, [])
🔥👌🥇

2022-12-01 14:33 UTC, gkartalis commented on src/app/Scenes/BottomTabs/BottomTabs.tsx
> +    return <></>
**question:** is this intentional? Why not `null`

2022-12-01 14:33 UTC, gkartalis commented on src/app/Scenes/BottomTabs/BottomTabs.tsx
> +    <Flex position="absolute" left={0} right={0} bottom={0} paddingBottom={bottom} bg="white100">
👏

2022-12-01 14:34 UTC, dimatretyak commented on src/app/Scenes/BottomTabs/BottomTabs.tsx
> +    return <></>
nope, we can use `null` also. i'll change it

2022-12-01 14:36 UTC, gkartalis commented
also tested on my device and the previous issue is not reproducible any more!

2022-12-01 14:39 UTC, dimatretyak commented on src/app/Scenes/BottomTabs/BottomTabs.tsx
> +    return <></>
done

2022-12-01 23:54 UTC, pvinis commented on src/app/Scenes/BottomTabs/BottomTabs.tsx
> +    <Flex position="absolute" left={0} right={0} bottom={0} paddingBottom={bottom} bg="white100">
I don't get this. why is the grey bit showing?

2022-12-01 23:57 UTC, pvinis commented on src/app/Scenes/Artwork/Artwork.tsx
> +  }, [])
hm. could we have this in the routes? the boolean for hiding the tabbar?

2022-12-01 23:59 UTC, pvinis requested changes
I don't want to block this, but I do want to understand the grey bit and see if we could move from the hook to the routes before this is merged 🙏

2022-12-01 23:59 UTC, pvinis commented on src/app/Scenes/BottomTabs/setBottomTabVisibilityForCurrentScreen.ts
> +import { __unsafe_mainModalStackRef } from "app/NativeModules/ARScreenPresenterModule"
wow this was a thing already?

2022-12-02 00:09 UTC, dimatretyak commented on src/app/Scenes/BottomTabs/BottomTabs.tsx
> +    <Flex position="absolute" left={0} right={0} bottom={0} paddingBottom={bottom} bg="white100">
This is an iOS-specific bug that does not reproduce in all cases/not always

2022-12-02 00:09 UTC, dimatretyak commented on src/app/Scenes/BottomTabs/setBottomTabVisibilityForCurrentScreen.ts
> +import { __unsafe_mainModalStackRef } from "app/NativeModules/ARScreenPresenterModule"
yep

2022-12-02 00:10 UTC, dimatretyak commented
> if we could move from the hook to the routes

I don't quite understand what you mean. if it's not difficult for you, can you please describe it in a little more detail?

2022-12-02 00:15 UTC, dimatretyak commented
> I don't want to block this, but I do want to understand the grey bit

[Here](https://github.com/react-navigation/react-navigation/issues/10432) you can find a little more context about the problem and [some solutions](https://github.com/react-navigation/react-navigation/issues/10432#issuecomment-1298324534) (only the first proposed solution solved the problem in our case)

2022-12-02 00:20 UTC, dimatretyak commented on src/app/Scenes/Artwork/Artwork.tsx
> +  }, [])
the main problem is that we have to dynamically hide the bottom tab bar depending on the some condition (in our case, the bottom tab bar will be hidden if the `isForSale` of artworks is set to `true` and sticky bottom content will be displayed. [Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4285) for it)

2022-12-05 12:27 UTC, pvinis approved these changes
ah. so its not a problem we created, its a lib thing. cool cool, thanks for the links!

2022-12-05 13:25 UTC, merged