feat(CX-3157): Eigen Add Medium to SWA Form
artsy/eigen pull request #7889
Opened 2022-12-21 12:25 UTC by lordkiz

This PR resolves [CX-3157] 

### Description

Adds the medium field to the SWA Form in Eigen

<p>
<img src="https://user-images.githubusercontent.com/18648835/208904069-1b0a28fe-3501-4743-bde7-74362628abf3.png" width="50%" />
</p>

### PR Checklist

- [x] I tested my changes on **iOS** / **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Add Medium to SWA form

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2022-12-21 13:04 UTC, olerichter00 reviewed
Looks good. 

Have you tried using the already existing [category picker](https://github.com/artsy/eigen/blob/020c2ec3b71dcb4151efd68e9c7202304fc3097e/src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tsx#L6)?

2022-12-21 13:06 UTC, olerichter00 commented on src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
> +      />
Here we could use the already implemented [medium picker](https://github.com/artsy/eigen/blob/main/src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tsx)

2022-12-21 13:33 UTC, MounirDhahri requested changes
Same comment here, I would also recommend using the existing medium picker component if possible

2022-12-21 14:21 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
> +      />
Thanks. Unfortunately, I don't think we can without refactoring that Component. The formik context used there is specifically for myCollection artwork form.
This is something we might want to do later, unless we want to expand the scope of this ticket. And would require quite some refactoring since both submission can be started from both inside mycollection and swa screen - it is not exactly straightforward. We will need to combine `GlobalStore.actions.myCollection.artwork` and `GlobalStore.actions.artworkSubmission.submission` among so many other things.

2022-12-21 14:21 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
> +      />
I am happy to expand the scope of the ticket or add a chore to the backlog.

2022-12-21 14:55 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
> +      />
I would still suggest doing it in this ticket given that it will be hard to prioritize this later and it will be tech debt that we can already avoid. 
Have you considered sending `handleChange` as a prop to the category picker from my collection to avoid having it coupled to it? I don't think it should take much time to do it

2022-12-21 16:17 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
> +      />
Sounds good. Let's do what you said then and link a ticket as a comment in the code.

2022-12-21 16:20 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
> +      />
since this is not going to go anywhere though, I will still prioritize this kind of work for this sprint otherwise we will never do it

2022-12-21 16:37 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
> +      />
Ok. No problem. Will get on it. 🙏🏽

2022-12-22 16:27 UTC, lordkiz commented
@MounirDhahri @olerichter00 My last commit **fully** decouples CategoryPicker from MyCollection and allows us to use it with other ValueTypes as your reviews suggested. Thank you 🙏 . I think that is sufficient for now. Let me know if there are other concerns I may have missed.

2022-12-22 16:47 UTC, MounirDhahri approved these changes

2022-12-22 16:48 UTC, MounirDhahri commented
Thanks Kizito. LGTM

2022-12-22 17:29 UTC, olerichter00 approved these changes
Looks great 🌟

2022-12-22 17:35 UTC, MounirDhahri commented
I will merge this to make sure we can review it tomorrow

2022-12-22 17:35 UTC, merged