feat: Art quiz first screen
artsy/eigen pull request #7982
Opened 2023-01-16 19:07 UTC by rajsam003

This PR resolves [GRO-1264] 

The user sees the first screen of the quiz after onboarding. 

https://user-images.githubusercontent.com/17421923/212750139-d72a0b8e-3ee9-4ab5-854d-c910d1f7dfd1.mov

### PR Checklist

- [ ] I tested my changes on **iOS** / **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
- [ ] I added an [app state migration].
- [ ] I hid my changes behind a [feature flag].
- [ ] I have prefixed changes that need to be tested during a release QA with **[NEEDS EXTERNAL QA]** on the changelog.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-01-16 19:09 UTC, rajsam003 commented on src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
> +          OPTION_THE_ART_TASTE_QUIZ,
I am not sure in which particular case this option should be available. So I added in 2 places for now.

2023-01-16 19:09 UTC, rajsam003 commented on src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
> +          OPTION_THE_ART_TASTE_QUIZ,
👆

2023-01-16 22:15 UTC, damassi commented on src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingArtTasteQuiz.tsx
> +export const OnboardingArtTasteQuiz: React.FC = () => <ArtQuiz />
This might as well be a fully returned component vs an implicit return; things will likely expand here

2023-01-17 15:01 UTC, laurabeth commented on src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
> +          OPTION_THE_ART_TASTE_QUIZ,
It's probably best for us to exclude this piece for now. There is a separate ticket for this work that we are deliberately saving for last, as it's technically our "go live" (reveals the quiz to users).

2023-01-17 15:11 UTC, laurabeth requested changes
Looks good overall. Once the option to access the quiz is removed I'll give it the ✅

2023-01-17 16:23 UTC, rajsam003 commented on src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingArtTasteQuiz.tsx
> +export const OnboardingArtTasteQuiz: React.FC = () => <ArtQuiz />
Yes right, We can expand when it's required :)

2023-01-17 16:47 UTC, damassi commented on src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingArtTasteQuiz.tsx
> +export const OnboardingArtTasteQuiz: React.FC = () => <ArtQuiz />
We should just expand it now, and avoid implicit returns completely. They always, 100% of the time, get unwound later, especially for entrypoints like this. So just save our future selves time.

2023-01-18 15:08 UTC, jonallured commented on src/app/Scenes/Onboarding/OnboardingQuiz/Hooks/useNextOnboardingScreen.tsx
> +  OnboardingTopAuctionLotsCollection: "OnboardingTopAuctionLotsCollection",
Oops, looks like maybe this snuck in after a rebase? I removed these options here: https://github.com/artsy/eigen/pull/7990

2023-01-18 16:24 UTC, rajsam003 commented on src/app/Scenes/Onboarding/OnboardingQuiz/Hooks/useNextOnboardingScreen.tsx
> +  OnboardingTopAuctionLotsCollection: "OnboardingTopAuctionLotsCollection",
Oh yes. Removing

2023-01-19 15:54 UTC, laurabeth approved these changes
:shipit:

2023-01-19 15:54 UTC, merged

2023-01-19 15:54 UTC, TMcMeans approved these changes
I asked one non-blocker question but otherwise LGTM 👍🏾 🥇

2023-01-19 15:54 UTC, TMcMeans commented on src/app/Scenes/ArtQuiz/ArtQuiz.tsx
> +  const { onDone } = useOnboardingContext()
**question [non-blocking]:** 

noticing that we're using `onboardingContext()` functions here, is this because we're gonna eventually connect art quiz to the onboarding flow?? Asking because I'm curious about how things are done in Eigen.

*format via [Conventional Comments](https://conventionalcomments.org/)*

2023-01-19 16:46 UTC, rajsam003 commented on src/app/Scenes/ArtQuiz/ArtQuiz.tsx
> +  const { onDone } = useOnboardingContext()
Yes, I thought Art quiz is a part of the onboarding process. So I used the same context. Should I create a separate context for the quiz? if yes I can do that in the next PR.

2023-01-19 16:48 UTC, rajsam003 commented on src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
> +  // TODO: Remove this feature flag after succussful QAing of Quiz App
Yes true. I will do it on the next PR and remove this comment.

2023-01-19 18:51 UTC, TMcMeans commented on src/app/Scenes/ArtQuiz/ArtQuiz.tsx
> +  const { onDone } = useOnboardingContext()
nope, I think that makes a ton of sense!