Feat(CX-3376): Redesign SWA Landing Page [Part 1]
artsy/eigen pull request #8196
Opened 2023-02-14 20:36 UTC by lordkiz

This PR resolves [CX-3376] 

### Description
Redesign SWA Landing Page [Part 1]

#### iPhone
https://user-images.githubusercontent.com/18648835/218855509-62bfe3ed-9d07-4517-940a-53cd565a47ff.mov

#### Android
[swa-lp-1-android.webm](https://user-images.githubusercontent.com/18648835/218855694-7b78d9d2-c9cd-4ed1-9fa9-2064a5f7cb53.webm)

#### iPad

https://user-images.githubusercontent.com/18648835/218855862-f46eb20a-140c-4dd7-9aa8-73b22712e6b8.mov

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Redesign SWA Landing Page [Part 1] - kizito

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-02-15 10:14 UTC, MounirDhahri requested changes
Niice LGTM. 
I have only one comment about the images size, I feel they're too big for what we need. I would suggest making them as small as possible since they will be part of the carousel, there is no need to have them very clear. I think we can get them to about 1mb maybe for 3x instead of 5mb

2023-02-15 14:54 UTC, dariakoko reviewed
Looks good!
I only left several suggestions

2023-02-15 14:54 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/Components/SWALandingPageHeroImage.tsx
> +export const SWALandingPageHeroImage = () => {
You can import the group of images as one image and use it in the Image component

2023-02-15 14:54 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
> +        contentContainerStyle={{ marginLeft: 20 }}
**Suggestion:** let's use `const space = useSpace()`?

2023-02-15 14:54 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
> +              style={{ maxWidth: width - 60 }}
**Suggestion:** and here as well

2023-02-15 14:54 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +            {enableNewSWALandingPage && <Spacer y={4} />}
**Suggestion:** what do you think about using ff only once and, to avoid using Spacer multiple times, we can wrap it in `<Join /> `

Also, to avoid using Spacer multiple times, we can wrap it in `<Join /> `
```
{enableNewSWALandingPage && (
  <Join separator={<Spacer y={4}  />}>
      <Highlights />
      <WaysWeSell />
  </Join>
)}
```

2023-02-15 15:42 UTC, lordkiz commented
> Niice LGTM.
> I have only one comment about the images size, I feel they're too big for what we need. I would suggest making them as small as possible since they will be part of the carousel, there is no need to have them very clear. I think we can get them to about 1mb maybe for 3x instead of 5mb

@MounirDhahri Ok. Just for the images in the carousel right?
I think we also have to revisit how the header looks on iPads. The design can be better.

2023-02-15 15:44 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +            {enableNewSWALandingPage && <Spacer y={4} />}
Thanks @dariakoko. That is cleaner. But Join will not append spacer below. I think we can fix all this when we are done with part 3

2023-02-15 15:44 UTC, MounirDhahri commented
totally agree

2023-02-15 15:46 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/Components/SWALandingPageHeroImage.tsx
> +export const SWALandingPageHeroImage = () => {
It appeared stretched to me, no matter resizeMode. Is there another way?

2023-02-15 15:47 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
> +        contentContainerStyle={{ marginLeft: 20 }}
We want to avoid useSpace for now until we have a stable palette-mobile.

2023-02-16 16:31 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/Components/SWALandingPageHeroImage.tsx
> +export const SWALandingPageHeroImage = () => {
Have you tried setting height and width and adding resizeMode property?

2023-02-16 16:33 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
> +        contentContainerStyle={{ marginLeft: 20 }}
Why can't we import it from palette?
I'd say it's still better to use useSpace here since it is something very basic and is used in a lot of places already

2023-02-16 16:36 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +            {enableNewSWALandingPage && <Spacer y={4} />}
Okay, as you feel comfortable.
Imo, it's easier to work with components like this, we are automatically avoiding situations when spaces are added to the child components. It's easier to maintain

2023-02-16 16:53 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
> +        contentContainerStyle={{ marginLeft: 20 }}
@dariakoko space is actively being worked on atm. And being replaced in various places in the app. See: https://artsy.slack.com/archives/C02NAJ2CGLW/p1676398423106229
By importing space from `palette` and not mobile-palette, we will end up with merge conflicts. I will replace these soon in later parts of the process.

2023-02-16 17:18 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/Components/SWALandingPageHeroImage.tsx
> +export const SWALandingPageHeroImage = () => {
I did. Another thing with all the images mashed in one image is we will usually need a higher quality single image. When you compress the single image to say 500kb and stretch it across the screen end to end, it begins to look blurry. But we can have each of the images compressed to say 150kb and position them without gaining too much app size and still maintain quality.

2023-02-16 17:22 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
> +            {enableNewSWALandingPage && <Spacer y={4} />}
Absolutely. I agree.

2023-02-16 18:09 UTC, lordkiz commented on src/app/Scenes/SellWithArtsy/Components/SWALandingPageHeroImage.tsx
> +export const SWALandingPageHeroImage = () => {
I just checked again. While using each image differently has better quality, the quality is negligible compared to the size savings of using a single image.
I will update this. 
Thanks @dariakoko

2023-02-17 08:27 UTC, MounirDhahri commented on src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
> +        contentContainerStyle={{ marginLeft: 20 }}
That's a good point, I believe @pvinis is still working on it, I still believe though that we should not optimize for future work and instead we can still use `useSpace` from local `palette` and update the import once `palette-mobile` work is wrapped. I feel like updating the dependency as part of a merge conflict will take less time than keeping an eye on when the work is done, creating a Jira ticket, prioritizing it then following up with a PR (although it's probably one-line of code).

2023-02-17 10:16 UTC, MounirDhahri submitted a review, later dismissed
Thanks for making the updates. LGTM 🙌

2023-02-17 11:03 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
> +        contentContainerStyle={{ marginLeft: 20 }}
Thanks, @MounirDhahri 
Agree!

2023-02-17 11:03 UTC, dariakoko commented on src/app/Scenes/SellWithArtsy/Components/SWALandingPageHeroImage.tsx
> +export const SWALandingPageHeroImage = () => {
Thanks @lordkiz!

2023-02-17 11:04 UTC, dariakoko approved these changes
Thanks for the updates ⭐

2023-02-20 11:12 UTC, merged