chore(NX-3493): replace Zendesk with Salesforce links
artsy/eigen pull request #8542
Opened 2023-04-19 11:17 UTC by tam-kis

This PR resolves [NX-3493] -->](https://artsyproduct.atlassian.net/browse/NX-3493)

### Description

Replaces Zendesk links with Salesforce links.

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-04-19 11:31 UTC, araujobarret approved these changes

2023-04-19 12:02 UTC, lidimayra approved these changes
Thank you for addressing this!! ❤️

2023-04-20 08:23 UTC, lidimayra commented
_same as https://github.com/artsy/force/pull/12274#issuecomment-1515902955_

2 of the links added in this PR are not working as expected. These URLs are matching the ones we have in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Yofy_cExeEgdV1-o8rzMrGnJ6In4c0aotV5dzowhYUU/edit#gid=571260299). I'll share this on [#zendesk-sf-migration](https://artsy.slack.com/archives/C04U9SJ5A0K) channel

- https://support.artsy.net/s/article/What-is-cascade-and-popcorn-bidding-and-how-does-it-work
- https://support.artsy.net/s/article/What-Counts-as-an-Artworks-Proof-of-Authenticity
- https://support.artsy.net/s/topic/s/topic/0TO3b000000UevEGAS/contacting-a-gallery ❌
- https://support.artsy.net/s/article/What-items-do-you-accept
- https://support.artsy.net/s/topic/s/topic/0TO3b000000UevOGAS/sell-with-artsy ❌
- https://support.artsy.net/s/topic/0TO3b000000UesxGAC/sell
- https://support.artsy.net/s/article/Im-an-artist-Can-I-submit-my-own-work-to-sell

2023-04-20 08:55 UTC, lidimayra requested changes

2023-04-20 08:55 UTC, lidimayra commented on src/app/Scenes/Inbox/Components/Conversations/Support.tsx
> +            "https://support.artsy.net/s/topic/s/topic/0TO3b000000UevEGAS/contacting-a-gallery",
```suggestion
            "https://support.artsy.net/s/topic/0TO3b000000UevEGAS/contacting-a-gallery",
```

2023-04-20 08:55 UTC, lidimayra commented on src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx
> +  const article = "https://support.artsy.net/s/topic/s/topic/0TO3b000000UevOGAS/sell-with-artsy"
```suggestion
  const article = "https://support.artsy.net/s/topic/0TO3b000000UevOGAS/sell-with-artsy"
```

2023-04-20 11:14 UTC, tam-kis commented on src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx
> +  const article = "https://support.artsy.net/s/topic/s/topic/0TO3b000000UevOGAS/sell-with-artsy"
Thanks for noting the wrong links from the sheet, I updated it.

2023-04-20 11:45 UTC, lidimayra approved these changes

2023-04-20 12:51 UTC, MrSltun approved these changes
🚀 ✨

2023-04-20 13:14 UTC, merged