feat(progressive onboarding): context
artsy/eigen pull request #8558
Opened 2023-04-21 16:08 UTC by laurabeth

This PR resolves [] 

### Description

Creates the context that will govern progressive onboarding behaviors. No UI created as yet. Up to date w/ latest behaviors in force. 

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-04-21 16:15 UTC, dzucconi commented on src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
> +}
I understand that most of this is copied out of Force and that these steps will almost certainly change. But I would strongly suggest adding some spec coverage to this. [The specs there](https://github.com/artsy/force/blob/main/src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx) should provide a decent starting point.

2023-04-21 16:16 UTC, dzucconi commented on src/app/utils/hooks/useDidMount.ts
> +}
Why add this hook?

2023-04-21 16:16 UTC, dzucconi reviewed
I don't really have a problem with this, but I'd probably approach this the other way around: get a single simple tooltip displaying first before trying to predict what you might need to support it.

2023-04-21 16:20 UTC, damassi commented on src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
> +})
This is non-blocking, but worth noting that in Eigen we use easy-peasy, and there's a much nicer way to manage local contexts should you wish to use it:

https://easy-peasy.vercel.app/docs/api/create-context-store.html

I would suggest going this route, but can also understand not wanting to refactor.

2023-04-24 08:23 UTC, MounirDhahri commented on src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
> +  })
**thought:** I see you are here trying to set a value for the same key (`localStorageKet(id)`) in AsyncStorage many times in sequence. Is it possible to do that only one time when you know the final value?

2023-04-24 15:02 UTC, damassi requested changes
We should be using easy-peasy for the context, per @MounirDhahri's note about out of the box persistence, etc. It will simplify this up and down.

2023-04-25 16:37 UTC, laurabeth commented on src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
> +})
Hey guys! Stepped away from this for future friday, but I'll be back to it shortly. Great feedback and I don't mind the refactor at all now that I've had a little breathing room from the work.

Thanks for taking a look.

2023-04-25 16:38 UTC, closed without merging