feat: Artwork list sorting
artsy/eigen pull request #8672
Opened 2023-05-12 13:02 UTC by rajsam003

This PR resolves [FX-4750] 

This PR implements sorting of Artwork list artworks

https://github.com/artsy/eigen/assets/17421923/7494db99-9a6b-442c-92a7-25518878f5e5

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- Artwork list sorting - sam

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-05-12 13:21 UTC, dimatretyak requested changes

2023-05-12 13:21 UTC, dimatretyak commented on src/app/Scenes/ArtworkList/ArtworkList.tsx
> +  const [modalVisible, setModalVisible] = useState(false)
**suggestion**: rename to `sortModalVisible` and `setSortModalVisible`

2023-05-12 13:21 UTC, dimatretyak commented on src/app/Scenes/ArtworkList/ArtworkList.tsx
>    const RefreshControl = useRefreshControl(refetch)
**blocking**: We need to pass and use currently selected sort value in `useRefreshControl`. Otherwise, pull-to-refresh will always be executed with sort by default (`SAVED_AT_DESC` in our case)


https://github.com/artsy/eigen/assets/3513494/3b6dc4c6-2065-4373-bfe8-f818412952c0

2023-05-12 13:23 UTC, rajsam003 commented on src/app/Scenes/ArtworkList/ArtworkList.tsx
>    const RefreshControl = useRefreshControl(refetch)
Thats true. Thanks

2023-05-12 13:26 UTC, dimatretyak commented on src/app/Scenes/ArtworkList/ArtworkList.tsx
> +  const [selectedSortValue, setSelectedSortValue] = useState("SAVED_AT_DESC")
**suggestion**

```javascript
const SORT_OPTIONS: SortOption[] = [
  { value: "SAVED_AT_DESC", text: "Recently Added" },
  { value: "SAVED_AT_ASC", text: "First Added" },
]

const DEFAULT_SORT_OPTION = SORT_OPTIONS[0].value as CollectionArtworkSorts

...
const [selectedSortValue, setSelectedSortValue] = useState(DEFAULT_SORT_OPTION)
...
const queryData = useLazyLoadQuery<ArtworkListQuery>(
  ...
  {
    ...
    sort: DEFAULT_SORT_OPTION,
  },
  ...
)
...
const handleSelectOption = (option: SortOption) => {
  setSelectedSortValue(option.value as CollectionArtworkSorts)
  ...
}
```

2023-05-12 13:29 UTC, rajsam003 commented
@dimatretyak Shall we move `<SortByModal />` this to `src/app/Components`? Because its inside `src/app/Scenes/SavedSearchAlertsList/Components` and we use it in Artwork List too.

2023-05-12 13:29 UTC, dimatretyak commented
> @dimatretyak Shall we move `<SortByModal />` this to `src/app/Components`? Because its inside `src/app/Scenes/SavedSearchAlertsList/Components` and we use it in Artwork List too.

yeah, i like this idea 👍

2023-05-15 11:42 UTC, dimatretyak approved these changes

2023-05-15 11:42 UTC, dimatretyak commented on src/app/utils/refreshHelpers.tsx
> +  const refetchObj = !!sort ? { count: pageSize, sort: sort } : { count: pageSize }
**suggestion**: I think it would be better if you add the ability to pass `args` argument (this approach will be more flexible)

```javascript
interface RefreshArgs extends Record<string, any> {
  pageSize?: number
}

export const useRefreshControl = (refetch: any, args?: RefreshArgs) => {
  ...

  const handleRefresh = () => {
    setIsRefreshing(true)
    refetch(
      {
        ...args,
        count: args?.pageSize ?? PAGE_SIZE,
      },
      ...
    )
  }

  ...
}
```

2023-05-15 14:42 UTC, merged