[WIP] feat(alerts): add confirmation modal with matching artworks
artsy/eigen pull request #8942
Opened 2023-06-28 22:28 UTC by anandaroop

This PR resolves [FX-4805] 

### Description

Counterpart to https://github.com/artsy/force/pull/12543

Adds a richer confirmation experience when creating an alert — a preview of currently matching artworks, plus CTAs to view all, or manage alerts.

#### TODO

- [ ] Confirm this screen is wired up correctly for all journeys (artwork vs artist & create vs edit)
- [ ] Confirm callbacks (for exiting modal etc) are passed around correctly for all journeys
- [x] Implement the confirmation screen
  - [x] Refactor to use Relay hooks
  - [x] Skeleton placeholders
  - [x] Refactor to use `SavedSearchStore`, to avoid prop drilling and extra querying
  - [x] Restrict to for-sale works
  - [x] Match web experience for scroll behavior
  - [x] CTAs to view all & manage alerts
  - [ ] Handle zero state (no matches)
- [ ] Specs

<video src="https://github.com/artsy/eigen/assets/140521/ca58f583-c1df-4ec2-84d9-44dc0a5bcb85" />

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-07-13 04:21 UTC, anandaroop reviewed
Ready for review finally!

(There's an odd [CI  failure for an Android step](https://app.circleci.com/pipelines/github/artsy/eigen/43844/workflows/5f81fac6-4b90-4d14-8aab-47e433620a68/jobs/145508) currently, but I'm not sure if that's related to these changes.)

2023-07-13 04:21 UTC, anandaroop commented on src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
> +  const total = data?.artworksConnection?.counts?.total // TODO: handle zero state
I don't think the [Figma design](https://www.figma.com/file/JqjoFeLoRX0aXQmbyOyiQG/Alerts%3A-Quick-Wins?type=design&node-id=626-18688&mode=design&t=5I1qyjpBuWDVbbHN-0) specifies a zero-state. 

(Or even a "one-state" for the case where the only matching artwork is the one from which you are starting the alert flow.)

It's tricky to find real-world examples, but here are some that work as of this writing:

- **zero-state**: create an alert starting from this not-for-sale artwork on staging
  - https://staging.artsy.net/artwork/henri-matisse-large-seated-nude-grand-nu-assis

    <details>
    <summary>currently looks like…</summary>
    <img height="500" alt="zero artwork" src="https://github.com/artsy/eigen/assets/140521/2056bdae-c773-49dd-82fa-a94c0b2b00ad">
    <img height="500" alt="zero" src="https://github.com/artsy/eigen/assets/140521/89562c74-a820-4a21-bead-aa529486d4e1">
    </details> 

- **"one-state"**: create an alert starting from this for-sale artwork on staging
  - https://staging.artsy.net/artwork/helen-frankenthaler-untitled-113

    <details>
    <summary>currently looks like…</summary>
    <img height="500" alt="one artwork" src="https://github.com/artsy/eigen/assets/140521/c4f059cd-e614-43ad-b909-f111f502279c">

    <img height="500" alt="one" src="https://github.com/artsy/eigen/assets/140521/db10d316-7ca8-4ff5-bc48-68a9cd627474">

    The artwork screen is basically recapitulated here.
    </details> 

(I think this is also underspecified in the web version.)

2023-07-13 08:45 UTC, nickskalkin commented
Hey @anandaroop what do you think about aligning "no match" state between web and app?

| App | Web |
|---|---|
|  ![Screenshot 2023-07-13 at 10 43 32](https://github.com/artsy/eigen/assets/3934579/c1a47d64-0103-41b3-959c-6bea7f3fa196) |  ![photo1689237827](https://github.com/artsy/eigen/assets/3934579/96bc19b9-c39b-4fd4-81de-2caca62bfabd) |

2023-07-13 08:59 UTC, nickskalkin requested changes
Great PR! Only one tiny remark from me

2023-07-13 08:59 UTC, nickskalkin commented on src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
> +        You might like these {total} works currently on Artsy that match your criteria
**suggestion**: In case of `total == 1` this sense will be wrong, it should be "You might like this 1 work..."

2023-07-13 08:59 UTC, nickskalkin commented on src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
> -  it("should navigate to the saved search alerts list when popover is pressed", async () => {
Not sure that this is what you need, but this is how I tested navigation in my PR recently: https://github.com/artsy/eigen/pull/8954/files#diff-0ef610e8851ceaf122974825563f4cf13024d329d6fa30369f52592dafab55baR109

2023-07-13 09:01 UTC, MounirDhahri commented on src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
> +        You might like these {total} works currently on Artsy that match your criteria
I left a suggestion about this https://github.com/artsy/eigen/pull/8942/files#r1262245061

2023-07-14 20:31 UTC, anandaroop reviewed
Addressed feedback and posted some further clarifications on the [ticket](https://artsyproduct.atlassian.net/browse/ONYX-15)

2023-07-17 13:50 UTC, MounirDhahri submitted a review, later dismissed
Thanks for addressing my comments. LGTM

2023-07-17 22:06 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (Enhances the process of creating alerts, by showing examples of artwork inventory matched by the new alert)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 84a72b75b2db3040a9be91428f56f8e4affd02a9
</p>

2023-07-17 22:10 UTC, anandaroop commented on src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
> -  it("should navigate to the saved search alerts list when popover is pressed", async () => {
Thanks, this situation was somewhat different but ultimately solved in https://github.com/artsy/eigen/pull/8942/commits/84a72b75b2db3040a9be91428f56f8e4affd02a9

2023-07-18 04:14 UTC, merged