feat: send additional Sift events on Android
artsy/eigen pull request #8991
Opened 2023-07-13 15:17 UTC by mdole

### Description

Followup to https://github.com/artsy/eigen/pull/8370.

Sift's React Native package doesn't correctly upload events without manual calls. This means we've had a few Sift events on Android (on app open + user login), but not as many as we'd like. The [recommendation](https://github.com/SiftScience/sift-react-native/pull/23#issuecomment-1630984250) from the folks who worked on it is to add these calls on navigate.

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [x] I hid my changes behind a **[feature flag]**, or they don't need one.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [x] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Dev changes

- Adds additional Sift event calls on Android - mdole

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-07-13 15:18 UTC, mdole commented
@MounirDhahri mind pulling this down and confirming you're still seeing events correctly fired? Would be greatly appreciated 🙂

2023-07-14 08:59 UTC, MounirDhahri reviewed
Nice! I tested this again and it's working well. I left a minor comment then I believe we can merge this

https://github.com/artsy/eigen/assets/11945712/d54f9acb-a3ed-4ec9-9e61-614a8239780d

2023-07-14 08:59 UTC, MounirDhahri commented on src/app/system/navigation/ModalStack.tsx
> +      const initialRouteName = routeNameRef.current
**issue:** I believe you forgot to set the `routeNameRef` value within the `onReady` block inside the navigation container.

2023-07-14 08:59 UTC, MounirDhahri commented on src/app/system/navigation/ModalStack.tsx
> +      // @ts-expect-error
**nitpick:** I suggest patching the package to include this type or even better make a PR at the fork we're using to add it. I see it's already exported here https://github.com/SanoopC/sift-react-native/blob/02aff9c411e26f9303cdc2c6d41584e057754173/android/src/main/java/com/siftreactnative/SiftReactNativeModule.kt#L60

2023-07-14 08:59 UTC, MounirDhahri commented on src/app/store/config/features.ts
> +  AREnableAdditionalSiftAndroidTracking: {
**praise:** 🙌

2023-07-14 14:47 UTC, mdole commented on src/app/system/navigation/ModalStack.tsx
> +      const initialRouteName = routeNameRef.current
ah! thanks @MounirDhahri. updated in https://github.com/artsy/eigen/pull/8991/commits/105f3038a1625b7c1dd3cba6019d2f889af0afc3; that look right? 

Also a bonus question for you - in [their example](https://github.com/SanoopC/sift-react-native/blob/screen_navigation_example/example/root.js) they do a comparison of the last route name and the current route name and only send an event if the route name changed. I don't think that's super necessary (just might mean we're firing a little more often I suppose). Do you agree or do you think I should add that?

2023-07-14 14:47 UTC, mdole commented on src/app/system/navigation/ModalStack.tsx
> +      // @ts-expect-error
Good call, thanks for suggesting! Added a patch in https://github.com/artsy/eigen/pull/8991/commits/70fb134010a5070b63a6ee244b700c54a3e43dae; there's been an [issue open in the repo](https://github.com/SiftScience/sift-react-native/issues/6) for a while and it appears nobody is working on it 😬  but I'll add a comment there

2023-07-14 15:14 UTC, gkartalis commented on patches/sift-react-native+0.1.8.patch
> + };
Hey! Can you also add an entry to [Hacks.md](https://github.com/artsy/eigen/blob/main/HACKS.md) with why this is needed in order to keep track of the patched packages?

2023-07-14 15:41 UTC, MounirDhahri commented on src/app/system/navigation/ModalStack.tsx
> +      const initialRouteName = routeNameRef.current
I agree as well, I don't think we should add it. I believe in their case, it might be that they're trying to restrict the events that are happening within the "same" screen and firing it only once for some reason. In our case, that would be like not sending events when the user is still in the Artwork screen, and that might be most of the user session. Our users will most likely keep jumping from one artwork to another suggested artwork for the duration of their session. That's why I find it useful to still track it.

https://github.com/artsy/eigen/assets/11945712/7541ac2f-d543-432a-8902-bed069454036

2023-07-14 15:44 UTC, MounirDhahri commented on src/app/system/navigation/ModalStack.tsx
> +      const initialRouteName = routeNameRef.current
This will also allow us to follow what docs suggest when setting up Android [[here](https://github.com/SiftScience/sift-android#add-sift-to-your-application-flow)] by tracking unique page views.

2023-07-14 15:44 UTC, MounirDhahri commented on src/app/system/navigation/ModalStack.tsx
> +      // @ts-expect-error
awesome, thanks Matt

2023-07-14 15:48 UTC, mdole commented on patches/sift-react-native+0.1.8.patch
> + };
Yessir! done in https://github.com/artsy/eigen/pull/8991/commits/014c20d780e52bc0d142b78f59b133fe0541cd52

2023-07-14 15:51 UTC, mdole commented on src/app/system/navigation/ModalStack.tsx
> +      const initialRouteName = routeNameRef.current
Ah yeah good thought! That makes sense, thank you :)

2023-07-14 15:54 UTC, MounirDhahri requested changes
Sorry, I missed something before. I added it now

2023-07-14 15:54 UTC, MounirDhahri commented on src/app/system/navigation/ModalStack.tsx
> +  }, [])
**issue(blocker):** I think you need to trigger this only after the navigation is ready, otherwise it will be empty initially in case the navigation is not yet ready.

2023-07-14 15:54 UTC, MounirDhahri commented on src/app/system/navigation/ModalStack.tsx
> +  }, [])
Actually, even better, you might want to move this to be within `onReady` prop in the `NavigationContainer` to avoid watching the `onReady` global state

2023-07-14 16:07 UTC, mdole commented on src/app/system/navigation/ModalStack.tsx
> +  }, [])
Good catch, thank you! Updated in https://github.com/artsy/eigen/pull/8991/commits/3d08ba54b8a9461623d1dd43c68421044699cf0b

2023-07-17 09:22 UTC, MounirDhahri approved these changes

2023-07-17 11:09 UTC, merged