chore(ONYX-13, ONYX-12): remove old saves implementation
artsy/eigen pull request #9164
Opened 2023-08-16 13:26 UTC by dariakoko

This PR resolves [ONYX-13] [ONYX-12]

### Description

Remove old saves implementation

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- remove old saves implementation -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-08-16 13:29 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (remove old saves implementation -daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0f8060448698826a5b235301811f084dac70e929
</p>

2023-08-16 14:09 UTC, dariakoko commented on src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
> -    }
Is it the right move to remove this condition?

2023-08-16 14:09 UTC, dariakoko commented on src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
> -  if (isArtworkListsEnabled) {
And this one too

2023-08-16 14:24 UTC, nickskalkin commented on src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
> -    }
`isArtworkListsEnabled` takes into account `options.saveToDefaultCollectionOnly` (take a look at how the variable is defined [here](https://github.com/artsy/eigen/blob/main/src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts#L18)). We pass `saveToDefaultCollectionOnly` as `true` when we want to user to experience "old" behaviour, when an artwork is being saved only to default collection. You can trigger this behaviour when clicking on "Watch lot", for instance. We still want to have this "old" behaviour, that's why `saveToDefaultCollectionOnly` should be taken into account here.

The easiest change I can imagine is simply to define `isArtworkListsEnabled` like this:

```ts
const isArtworkListsEnabled = !options.saveToDefaultCollectionOnly
```

But personally I would change all places which check `isArtworkListsEnabled` to `!options.saveToDefaultCollectionOnly`

2023-08-16 16:47 UTC, dariakoko commented on src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
> -    }
Yehhh, that's what I thought initially. But the saveArtworkToDefaultArtworkList() opens the modal with the collections anyways. The only difference is that when we like the artwork the default list is already selected, but when we like the lot none of the lists is selected. I thought we don't need to show the modal in case we're saving an auction artwork. Or should we?

2023-08-16 18:25 UTC, anandaroop approved these changes
Looking good!

2023-08-16 18:25 UTC, anandaroop commented on src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
> +    describe("whith lists feature flag enabled", () => {
**question (non-blocking):** Wondering if we even need to wrap the test with this `describe` block?

2023-08-22 09:25 UTC, nickskalkin requested changes

2023-08-22 09:25 UTC, nickskalkin commented on src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
> +      saveArtworkToDefaultArtworkList()
*blocking*: this code has two issue:

- there should be a return statement as well, otherwise the code below will be executed as well
- saveArtworkToDefaultArtworkList always opens the drawer with artwork lists. When `saveToDefaultCollectionOnly` options is passed (when clicking on Watch lot button, for instance), the drawer shouldn't be opened - an artwork just gets added to a default list silently.

This can be achieved by adding the code below to the optimisticUpdater in saveArtworkToDefaultArtworkList:

```ts
      if (options.saveToDefaultCollectionOnly) {
        return
      }
```

2023-08-25 12:10 UTC, dariakoko commented on src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
> +      saveArtworkToDefaultArtworkList()
Right, thank you @nickskalkin

2023-08-25 12:40 UTC, dariakoko commented on src/app/utils/mutations/useSaveArtwork.ts
> +        refreshOnArtworkSave()
I reused `refreshOnArtworkSave()` method we used for the old saves implementation. This method refreshes Saved tab. If we keep Saved tab open, go to Home screen and save the artwork, when we are back to the Saved tab we see the updated lists. Without this method we would need to refresh the Saved tab ourselves.
The only thing is - if we keep the Artwork **list** open the method doesn't update it as it updates only the Saves tab. Would be nice to be able to refresh individual lists as well imo

https://github.com/artsy/eigen/assets/36167539/8c942751-35c6-4970-a63f-a930e9172ed1

2023-08-28 22:11 UTC, anandaroop submitted a review, later dismissed
LGTM 👍🏽 

(though I still think [this](https://github.com/artsy/eigen/pull/9164/files?file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&show-viewed-files=true&show-deleted-files=false#r1296278208) could be cleaned up)

2023-08-29 10:19 UTC, dariakoko commented
Right, @anandaroop, sorry, missed this. Cleaned up now

2023-08-29 11:10 UTC, merged