feat(ONYX-253): create suggested artworks screen
artsy/eigen pull request #9233
Opened 2023-09-08 16:35 UTC by dariakoko

This PR resolves [ONYX-253] 

### Description

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- create suggested artworks screen -daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-09-08 16:38 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (create suggested artworks screen -daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 629dccf713c5758b1405184cf986b2166fae48a0
</p>

2023-09-12 15:44 UTC, dariakoko commented
> @dariakoko - can you 🙏 update the PR with a full description? We shouldn't depend on external JIRA ticket links to provide relevant context in a PR.

Sure. I have just marked it as ready for review. Next time will update the details first and then change the status

2023-09-12 15:46 UTC, damassi commented
ty! didn't realize it wasn't yet ready to review, saw PR comments and so on. All good. And please spread the word 😄

2023-09-13 08:16 UTC, nickskalkin commented on src/app/AppRegistry.tsx
> +  }), // TODO: change the name
also TODO here

2023-09-13 08:23 UTC, nickskalkin commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorksModal/BrowseSimilarWorksModalContent.tsx
> +    <SavedSearchStoreProvider
**question**: I might be wrong, but I don't think we provider here, right?

2023-09-13 08:29 UTC, nickskalkin commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorksModal/BrowseSimilarWorksModalContent.tsx
> +    artworksConnection(first: $first, input: $input) {
**suggestion**: you could use suggestedArtworksConnection here instead, in this case you even don't need to pass criteria attributes as an argument to it:

```graphql
	artwork(id: "banksy-di-faced-tenner-232") {
		savedSearch {
			suggestedArtworksConnection(first: 10) {
				edges {
					node {
						title
					}
				}
			}
		}
	}
```

2023-09-13 08:32 UTC, nickskalkin commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorksModal/BrowseSimilarWorksModalContent.tsx
> +    return null
**question**: am I right that you do not display any fallback message in case there are no suggested artworks? I think this is a common case when there is nothing to suggest, we should definetely show something to users. Force has this logic, for instance ([link to code](https://github.com/artsy/force/blob/main/src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModalGrid.tsx#L39), [link to translation](https://github.com/artsy/force/blob/main/src/System/i18n/locales/en-US/translation.json#L118))

2023-09-13 08:35 UTC, nickskalkin commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorksModal/BrowseSimilarWorksModalContentWrapper.tsx
> +    onClosePress: () => {},
**question**: is there a reason why we pass empty callbacks here?

2023-09-13 09:33 UTC, MounirDhahri commented
Hey @dariakoko, I see you're still pushing to the PR. Is it ready for review? if not would you mind changing it to a draft PR or adding [WIP] to the title.

2023-09-13 09:40 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorksModal/BrowseSimilarWorksModalContent.tsx
> +    <SavedSearchStoreProvider
You're right, we don't need it here - removed  👍

2023-09-13 09:41 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorksModal/BrowseSimilarWorksModalContent.tsx
> +    return null
Thanks for sharing, added an empty state [here](https://github.com/artsy/eigen/pull/9233/commits/5db730da077bef46a167528af771b0a2479607b2)

2023-09-13 09:42 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorksModal/BrowseSimilarWorksModalContentWrapper.tsx
> +    onClosePress: () => {},
Not at all, I just wanted to reuse the types we use for the alert creation flow. After refactoring it doesn't make sense any more - removed, added an interface with only `aggregations`, `attributes`, `entity` to the file

2023-09-13 09:43 UTC, dariakoko commented
@MounirDhahri Ready for review, pushed the latest changes just now

2023-09-13 15:16 UTC, nickskalkin requested changes
All good, I left 1 code related suggestion and 1 thing I think we should fix before merging - hide the button if there are no artworks to suggest

well done! 👍

2023-09-13 15:16 UTC, nickskalkin commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +        <Button
And in this case we probably will not need "empty state" message we were talking about earlier 🤔

2023-09-13 15:16 UTC, nickskalkin commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +    artworksConnection(first: $first, input: $input) {
**suggestion**: there is a a new query you could use instead, which doesn't require attributes (all logic is on metaphysics side):

```
	artwork(id: "banksy-di-faced-tenner-232") {
		savedSearch {	
			suggestedArtworksConnection(first: 10) {
				edges {
					node {
						title
					}
				}
			}
		}
	}
```

2023-09-13 15:16 UTC, nickskalkin commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +const SimilarArtworksContainer: React.FC<{ attributes: any }> = withSuspense(({ attributes }) => {
and you wouldn't need `any` here 😃

2023-09-13 17:52 UTC, MounirDhahri reviewed
Really nice PR! great work Daria

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +        <Button
Good idea 💡  if we won't implement this now, I suggest we ticket this and refine it tomorrow with the team.

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +          haptic
👏 👏 👏

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +          flex={1}
**Q:** was this required 👀

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +          flex={1}
**suggestion:** have you tried using `block` here

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
> +      artworkID: props.artworkID,
**praise:** thanks for making this adjustment! now this screen design is great

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
> +    return <BrowseSimilarWorks artwork={data.artwork!} />
**issue:** I understand that the artwork should theoretically be there since you're in the artwork page right. But this assumes that we are landing on this page from the `Artwork` screen. This screen is exposed via deep linking though so it could be that someone enters a wrong artwork id. I would suggest avoiding using `data.artwork!` here and instead make a small check before and return an error message.
```typescript
if (!data.artwork) {
   return <Flex><Header /><Text>Could not load artwork</Text></Flex>

}
```

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
> +  fragment BrowseSimilarWorks_artwork on Artwork {
**issue:** using the same fields here as in https://github.com/artsy/eigen/blob/0003f6f8c77a0f2067dd5cc9e005828933ac48f2/src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx#L29 makes me think we should consolidate this into one fragment instead of copying it. This way this code is going to be more robust if we introduce future changes

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +      >{`Works by ${entity.artists[0].name}`}</FancyModalHeader>
**Q:** I would have thought we would be showing all artist who made the artwork here instead of only the first one.

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +      }
**issue:** I believe this is not being used anywhere

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +  }
**thought:** do we need to also check if the data is loading here?

2023-09-13 17:52 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +          navigate(`artwork/${slug}`)
```suggestion
          navigate(`artwork/${internalID}`)
```

2023-09-13 20:05 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +    artworksConnection(first: $first, input: $input) {
Good to know, would be nice to use it
I tried it, but it returns an empty array of nodes, so I'd stick only with the totalCount in [this commit](https://github.com/artsy/eigen/pull/9233/commits/4025994634cab4664968e1b9dff29f91ef09c388)
We could look into this together if you're interested

2023-09-13 20:05 UTC, dariakoko commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +        <Button
Agree, done [here](https://github.com/artsy/eigen/pull/9233/commits/4025994634cab4664968e1b9dff29f91ef09c388)

2023-09-13 20:07 UTC, dariakoko commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +          haptic
Already done this @MounirDhahri 😄  Took 5 minutes

2023-09-13 20:08 UTC, dariakoko commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +          flex={1}
`block` works perfectly 🥇 added

2023-09-13 20:08 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
> +      artworkID: props.artworkID,
Thanks for your help! ⭐

2023-09-13 20:16 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
> +    return <BrowseSimilarWorks artwork={data.artwork!} />
Good point, will address

2023-09-13 20:17 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +      >{`Works by ${entity.artists[0].name}`}</FancyModalHeader>
We display the name in the header which makes it difficult to display all artists
I tried - look bad 👀 
Checked how we do this in the rest of the app - rather often we display only the first one :/

2023-09-13 20:27 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +  }
We're using `withSuspense` here and showing the loading skeleton if the data is loading. Is this what you mean?

2023-09-13 20:28 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +  }
I don't think we need anything else - we are loading only 10 artworks max and all of them are loaded in the same request

2023-09-13 20:31 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
> +    return <BrowseSimilarWorks artwork={data.artwork!} />
![image](https://github.com/artsy/eigen/assets/36167539/8edda122-cdb1-4207-970d-191e1c0e0032)

2023-09-13 20:37 UTC, dariakoko commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +const SimilarArtworksContainer: React.FC<{ attributes: any }> = withSuspense(({ attributes }) => {
🥲 true, using `attributes: SearchCriteriaAttributes` now

2023-09-14 07:44 UTC, nickskalkin approved these changes
👍

2023-09-14 08:45 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
> +    return <BrowseSimilarWorks artwork={data.artwork!} />
perfect, that's enough. we will probably have this in less than 1% of the cases but good to be covered when it happens

2023-09-14 08:46 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +      >{`Works by ${entity.artists[0].name}`}</FancyModalHeader>
oki sounds good then

2023-09-14 08:46 UTC, MounirDhahri commented on src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
> +  }
perfect, sounds good then

2023-09-14 08:51 UTC, MounirDhahri approved these changes
LGTM. Just a small suggestion

2023-09-14 08:51 UTC, MounirDhahri commented on src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
> +    artworkData.savedSearch?.suggestedArtworksConnection?.totalCount ?? 0
**suggestion:** since this is a boolean
```suggestion
  const hasArtworksSuggestions =
    (artworkData.savedSearch?.suggestedArtworksConnection?.totalCount ?? 0) > 0
```

2023-09-14 10:53 UTC, merged