fix(ONYX-822): fix broken ArtsyWebView paddings
artsy/eigen pull request #9922
Opened 2024-03-02 01:58 UTC by dariakoko

This PR resolves [ONYX-822] 

### Description

The ArtsyWebView uses SafeAreaView. SafeAreaView adds paddings to the top and bottom of the page to make sure the active area of the screen can be assessed. We do not need this padding if we are not presenting the screen modally. When we do not the screen modally we can use a react-native View instead of SafeAreaView

| Before iOS | After iOS | Before Android | After Android |
| --- | --- | --- | --- |
| ![image](https://github.com/artsy/eigen/assets/36167539/a4dc33e5-74cc-4bf2-b677-08301140edf7) | ![image](https://github.com/artsy/eigen/assets/36167539/3ca4f7eb-0964-41c5-b356-e8e9522615df) | ![Screenshot_1709343815](https://github.com/artsy/eigen/assets/36167539/58ba30f0-4c7d-4499-9c8a-dffc5eb2095d) | ![Screenshot_1709344209](https://github.com/artsy/eigen/assets/36167539/b6e21408-3197-47b8-b10a-8b2b2be0cfae) |

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I hid my changes behind a **[feature flag]**, or they don't need one.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.
- [ ] I have added a **changelog entry** below, or my changes do not require one.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

<details><summary>Changelog updates</summary>

### Changelog updates

#### Cross-platform user-facing changes

- in ArtsyWebView use SafeAreaView only if presented modally - daria

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2024-03-02 02:00 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### This PR contains the following changes:

- Cross-platform user-facing changes (in ArtsyWebView use SafeAreaView only if presented modally - daria)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e791ce5c64a0cc2fb73f29379baa6f1d78fee665
</p>

2024-03-04 10:58 UTC, MounirDhahri requested changes
This is great, I don't think though we should be merging this at its current state since I find this as an opportunity to fix other similar URL routes that we haven't included in `routes.ts` - especially because now we know what is broken

2024-03-04 10:58 UTC, MounirDhahri commented on src/app/routes.ts
> +    addWebViewRoute("/galleries"),
Nice idea on adding the routes here, but this leads me to think the issue affects any route that is not here. I would therefore look into another approach to get the same behaviour that we get from `addWebViewRoute` to all our deep urls.

2024-03-04 10:58 UTC, olerichter00 reviewed
Thanks a lot for the fix 🙏 

Although this fix works with all routes that are added with `addWebViewRoute("/artists")`, routes that are not added like this would be interpreted as vanity URLs (e.g., `/shows`), which results in the Back button being rendered on top of the page title. I've created https://github.com/artsy/eigen/pull/9924 as an attempt to solve this issue as well.

2024-03-04 11:00 UTC, olerichter00 commented on src/app/routes.ts
> +    addWebViewRoute("/galleries"),
https://github.com/artsy/eigen/pull/9924 would fix the issue by using [ArtsyWebViewPage](https://github.com/artsy/eigen/blob/4a10245a845a6059bebf89a295724268d13ec486/src/app/Components/ArtsyWebView.tsx#L51) for all URLs that down't mach a specific route.

2024-03-04 11:10 UTC, MounirDhahri commented
We thought about the same thing @olerichter00 -  Looking into your PR now

2024-03-04 11:58 UTC, olerichter00 commented on src/app/routes.ts
> +    addWebViewRoute("/galleries"),
Please note that my PR would be a fix on top of this PR because this change is still needed: https://github.com/artsy/eigen/pull/9922/files#diff-edc2fa1c2b97a3ddeaf270d241e4054ba768be253b35b4e75e63914b6b1c20cdR257

2024-03-04 14:58 UTC, olerichter00 commented on src/app/routes.ts
> +    addWebViewRoute("/galleries"),
It works without adding the routes but it seems that https://github.com/artsy/eigen/pull/9922/files#diff-edc2fa1c2b97a3ddeaf270d241e4054ba768be253b35b4e75e63914b6b1c20cdR257 is needed, no?

2024-03-05 09:43 UTC, MounirDhahri commented on src/app/routes.ts
> +    addWebViewRoute("/galleries"),
perfect, do. you mind if you don't commit the route changes then and leave that before merging

2024-03-05 09:45 UTC, olerichter00 commented on src/app/routes.ts
> +    addWebViewRoute("/galleries"),
Good idea not to commit the route changes. @dariakoko I'd say, let's merge https://github.com/artsy/eigen/pull/9924 into this PR, then remove the route changes, test again, and then merge into main.

2024-03-05 16:28 UTC, dariakoko commented on src/app/routes.ts
> +    addWebViewRoute("/galleries"),
Good idea, doing it now

2024-03-05 17:05 UTC, dariakoko commented
Addressed your comments @MounirDhahri @olerichter00 and tested - looking good!
![image](https://github.com/artsy/eigen/assets/36167539/0272b34f-89f4-48e0-91c0-8062d0558971)

2024-03-05 17:10 UTC, olerichter00 approved these changes
🌟

2024-03-06 10:54 UTC, MounirDhahri approved these changes
Perfect - our webviews across the app will be much better now!

2024-03-06 10:55 UTC, MounirDhahri commented
Will merge this to get it to the release

2024-03-06 10:55 UTC, merged